### ISSUE TITLE
add silent stream option?

### ISSUE THREAD

**Issue by budtz** [Belphemur/SoundSwitch#100]
Would there be any way to add a silent stream option for fixing audio with hdmi on windows?

I found an old modified version of soundswitch where this was added in. here: https://community.amd.com/thread/185767

sadly i cant run both programs at the same time.

**Comment by Belphemur** [comment]
I see the idea, keep the audio channel open to avoid the bluetooth device to shutdown, is that it ?

**Comment by budtz** [comment]
Thx for the reply and the great software. Well Bluetooth etc. is most likely also affected. But I was thinking of when the pc is connected to a receiver/TV via HDMI. Here is a better description of the problem than what I could come up with:

When Video card manufacturers started including onboard sound devices with their products, for the first time ever it allowed computer users to get Audio and Video to their A/V receiver, through one cable without the need for an seperate sound card. However, with this new technology, came a new problem. A/V receivers have to switch to the appropriate mode every time an audio stream is presented to them. This in itself isn't a problem, but in Windows, the receiver has to switch modes every time Windows plays a system sound, a video in youtube, an movie in Windows Media Player etc. Because it takes the receiver time to switch modes, this leads to the first second or two of the sound being missed, which in the case of system sounds, often means the whole sound is missed.

The solution:
In order to prevent the receiver from switching modes, a Silent Stream must be kept open permanently, even when no audio is playing. Some audio devices/drivers do not do this, which is what causes the bug.

It might also be needed to detect when the user switches inputs or turn off his receiver or tv, and resume the silent stream once they are turned back on to the correct input again.

Thus a permeant silent stream that sort of keeps the audio device/tv/avr alive fixes all issues of Windows HDMI audio. Baffling that NVidia, Microsoft etc. haven’t fixed this as it basically means systems sounds or the start of a song etc. don’t work via HDMI when using a surround receiver and some TVs

Any chance for this?

**Comment by budtz** [comment]
Any chance for this?

**Comment by Belphemur** [comment]
Unfortunatly I don't think it's in the scope of SoundSwitch.

You can try this: 
https://forums.geforce.com/default/topic/476019/silent-stream-bug-windows-audio-disappears-when-not-generating-sounds-/
