### ISSUE TITLE
When switching to Airpods profile, connect to airpods.

### ISSUE THREAD

**Issue by direrFlood** [Belphemur/SoundSwitch#1004]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
When switching to Airpods profile, connect to airpods.
**Describe alternatives you've considered**
using hotkey to connect to airpods. but i want it fully automated.
**Additional context**
When switching to Airpods profile, connect to airpods. maybe give us the option to add commandlines/arguments when switching to profiles.

**Comment by Belphemur** [comment]
Merging this with #1008
