### ISSUE TITLE
Banner or any does not show when app is open in fullscreen

### ISSUE THREAD

**Issue by ghost** [Belphemur/SoundSwitch#1007]
**Describe the bug**
Opening application/game in full screen. Trying to change audio output with hotkey. Not visual banner/indicator to which audio switched.
**Version**
SoundSwitch vX.X.X
lastest
**To Reproduce**
1. play a game in fullscreen
2. Click on hotkey to switch playback device
3. audio device switches but no visual cue.

**Expected behavior**
1. play a game in fullscreen
2. Click on hotkey to switch playback device
3. audio device switches but with visual cue(banner, windowsn otifciation, etc.)
**Screenshots**

**Additional context**

**Comment by Belphemur** [comment]
Hello,
Can you tell me which game ?

I'm not able to reproduce with Cyberpunk 2077 in any fullscreen mode (windows and exclusive).
