### ISSUE TITLE
C++ 2015 x64 redist installed but installer tries and fails to download and install it again

### ISSUE THREAD

**Issue by LeeC2202** [Belphemur/SoundSwitch#101]
I already have the C++ 2015 Redistributable x64 and x86 installed (14.0.23918) but the installer for SoundSwitch insists on trying to download and install what I presume is an older version, because it fails to install.

I am using "SoundSwitch_v3.10.1.26866_Release_Installer.exe" which has a note on saying this bug is fixed but it seems that isn't the case.

**Comment by Belphemur** [comment]
I have difficulty reproducing this bug.
I have the exact same version installed on my computer, it came with the last update of Visual Studio Community.

The version SoundSwitch need as minimum version is the last one available on Microsoft's website, Build 23026.

Can you check that you have this registry key: 
*SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64*

With *Installed* at **1** and the *Bld* at **23918**

If you don't have those keys, it means there has been some problems with your installation of VC Redist.

**Comment by LeeC2202** [comment]
I don't have that key and I also don't seem to have any problems with the VC Redist. Visual Studio Community runs fine as does any other software requiring those redist. I haven't updated Visual Studio to the latest build though as it breaks some settings I use, so maybe that key is tied to the latest version.

That version number is referenced loads of times in my registry though, including in this one:
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\DevDiv\vc\Servicing\14.0\RuntimeAdditional

It is also referenced in some Steam keys:
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam\Apps\CommonRedist\vcredist\2015

So it looks like Visual Studio might not be the only source it being installed. If that's the case and Steam was installed prior to Visual Studio (which it was), VS might not create all the keys it would do if it was the one to install the redist.

In which case, relying on that one key for verification might not be 100% reliable.

**Comment by Belphemur** [comment]
Can you try with this installer and tell me if it resolves the issue for you ?

http://www.mediafire.com/download/cc3ljv3t87bqml2/SoundSwitch_v3.10.1.26866_Testing_Installer.exe

**Comment by Belphemur** [comment]
I meant this one: http://www.mediafire.com/download/abzxt0adjtw8ej2/SoundSwitch_v3.10.1.26866_Testing_Installer.exe

**Comment by LeeC2202** [comment]
That installer worked fine.

**Comment by Belphemur** [comment]
I added a check for the key you sent me and in fact, you're right that is the key also provided in the VC redist documentation on Microsoft.

Thanks for the bug report, I'm doing a release for this.

**Comment by LeeC2202** [comment]
No problem, glad I could help... thanks for the fix.

**Comment by VeNoMouS** [comment]
This is not fixed... i had to install 3.10.1 to get rdist, then install 3.10.2 again, 3.10.2 failed on a clean win10 install.
