### ISSUE TITLE
After Windows restart, profile hotkey conflicts 'with itself'

### ISSUE THREAD

**Issue by JamesAtlloud** [Belphemur/SoundSwitch#1014]
I LOVE this app - thank you!

**Describe the bug**
After a windows restart (which we all love so much) SoundSwitch detects a conflict with one of 3 profiles.  It is always the profile using the motherboard audio device for output and webcam for input.  I have to rebuild this profile and choose a different hotkey combo.  After every restart the hotkey conflict returns so I am regularly rebuilding that profile and alternating the hotkey combo from ctrl-alt-f8 to ctrl-alt-f12.  I have 2 other profiles with USB audio devices and they have had no issues.

**Version**
SoundSwitch v6.4.2.0

**To Reproduce**
1. Restart windows
2. Press hotkey combo for mboard audio
3. See hotkey conflict notification

**Expected behavior**
Expect to see profile switch confirmation in top left of main display.

**Screenshots**
n/a

**Additional context**
Would it make any differences to remove and re-install SoundSwitch as admin?

**Comment by Belphemur** [comment]
Hello,
Can you share the config and logs ?

Folder: `%appdata%/SoundSwitch`

**Comment by JamesAtlloud** [comment]
[soundswitch20220928.log](https://github.com/Belphemur/SoundSwitch/files/9667283/soundswitch20220928.log)
[soundswitch20220926.log](https://github.com/Belphemur/SoundSwitch/files/9667284/soundswitch20220926.log)
[soundswitch20220927.log](https://github.com/Belphemur/SoundSwitch/files/9667285/soundswitch20220927.log)
[SoundSwitchConfiguration.json.txt](https://github.com/Belphemur/SoundSwitch/files/9667290/SoundSwitchConfiguration.json.txt)

**Comment by Belphemur** [comment]
Unfortunately, the logs don't seem to be around the time the issue arise.

Can you keep the log when the problem occur (like just restart SoundSwitch) :)
