### ISSUE TITLE
Soundswitch suddenly stopped working 

### ISSUE THREAD

**Issue by gagehughes4243** [Belphemur/SoundSwitch#1019]
I had the application working perfectly for the past year but Ive purchased a second pair of headphones for monitoring recordings im making, after getting them set up soundswitch is no longer working with hotkeys or showing in my application bar. As well the app its self will not open at all even when ran as admin

**Comment by Belphemur** [comment]
Can you attach the logs and configuration present in:
`%appdata%/SoundSwitch`
