### ISSUE TITLE
Ability to disable auto update checker

### ISSUE THREAD

**Issue by gricey432** [Belphemur/SoundSwitch#102]
It'd be good if there was an option for disabling update checking, it's a pretty standard setting to have.
#63 suggested this, but the thread changed to making the updates stealthy instead.

**Comment by Technetium1** [comment]
I also think that this would be a good addition. Perhaps it should be above "Automatic Update"?

**Comment by FireEmerald** [comment]
![options2](https://cloud.githubusercontent.com/assets/1107939/15899220/553bfea6-2d9b-11e6-8128-d892fc80e371.png)
(Just how it could look like)

**Comment by Belphemur** [comment]
@FireEmerald I like that mockup. I'll see what I can do for this.
