### ISSUE TITLE
Define a default device on Startup

### ISSUE THREAD

**Issue by Skaronator** [Belphemur/SoundSwitch#103]
I recently switch from v1 to v3 and I've noticed the missing option to define a default device on PC boot. Would be nice if you can bring this option back.

**Comment by Belphemur** [comment]
Hello @Skaronator 

I don't think this was present in the version 2.
Usually, Windows do remember the last default device and reuse it automatically.

**Comment by Skaronator** [comment]
I'm talking about a default device which is always set on boot. For example I want my Speakers as default devices. 

device on shutdown | device after next boot
---|---
headset | speakers
speakers | speakers

This features exist in SoundSwitch version 1 or I'm completly drunk and used a other tool with the same name.

**Comment by ThisIsABug** [comment]
As far as I know the the programs code was totally different at V1, Belphemur (thx btw, your program is awesome!) took over at a later point.
