### ISSUE TITLE
Accessing 'help' at any time

### ISSUE THREAD

**Issue by Philip-Sutton** [Belphemur/SoundSwitch#105]
Would it be possible to have a link (labelled 'Help') on the right-click pop-up window to the .html help file? 
C:\Program Files\SoundSwitch\Readme.html

![right-click pop-up](https://cloud.githubusercontent.com/assets/1549449/16361041/0e5a11a8-3bc4-11e6-9745-5fb68ebc37c8.png)

**Comment by Belphemur** [comment]
Sure that would be easy enough to do.
