### ISSUE TITLE
Not switching "default communications device"

### ISSUE THREAD

**Issue by Belatar** [Belphemur/SoundSwitch#106]
Hi again, I`m unsure whether my comment on the closed issue will be noticed, so I repost this as a new issue (old one: https://github.com/Belphemur/SoundSwitch/issues/14 )

I just downloaded and installed Sound Switch on Windows 10 64 Bit German and it doesn`t switch the "Default communication device" anymore. Strangely on my desktop this seems to work with the same drivers and peripheral components.

Thanks for the great tool!

**Comment by Belphemur** [comment]
Hello @Belatar 

I would need more information. Can you check and uncheck the checkbox in the settings for the communication device ?

Can you also try the switching with the control panel to see if this works ?

**Comment by Belatar** [comment]
Hi @Belphemur 

I can manually switch the "default communication device" back and forth via the "playback devices" panel accessed via right clicking on the speaker symbol in the taskbar.

I do not quite understand what you mean by "check and uncheck the checkbox in the settings for the communication device"? which checkbox on which tab?
 
I attached two screenshots showing the two ways I can change the "default communication device".

![soundswitch 1](https://cloud.githubusercontent.com/assets/1206801/16373531/0b8feab2-3c53-11e6-8bdb-100ce7d5c5fe.jpg)

![soundswitch 2](https://cloud.githubusercontent.com/assets/1206801/16373535/153ffbe2-3c53-11e6-9d97-83232f196b2c.jpg)

Addionally I have added my dxdiag, maybe that will help too.

[DxDiag.txt](https://github.com/Belphemur/SoundSwitch/files/334391/DxDiag.txt)

**Comment by Belphemur** [comment]
The checkbox I meant is in the settings of SoundSwitch to activate or disable the switching of communications devices.

Which application did you use for your tests ?

**Comment by Belatar** [comment]
Fml, I'm so stupid. It was the "Communications device" options. Sorry for the hassle. Btw, do you take donations? The tools awesome.

**Comment by Belphemur** [comment]
No problem :) Glad it was that easy to fix.

Not for now, still toying with the idea of how to do it cleanly without having to bother about the currency or not getting the money.
