### ISSUE TITLE
Add option to identify sound devices with an alias

### ISSUE THREAD

**Issue by Izanx** [Belphemur/SoundSwitch#1069]
### What workfow do you want to improve?

On some occasions, when you have several sound devices connected, there are similar names even the same.

### How to make it better?

It would be interesting to be able to assign an alias to any sound device and thus it would be easier to choose the one you want.

### Any alternative?

No.

**Comment by Belphemur** [comment]
Hello,

You can rename audio peripheral in Windows.

See https://github.com/Belphemur/SoundSwitch/discussions/702

Sent from Nine

________________________________
From: Izanx ***@***.***>
Sent: Friday, December 2, 2022 04:04
To: Belphemur/SoundSwitch
Cc: Subscribed
Subject: [Belphemur/SoundSwitch] Add option to identify sound devices with an alias (Issue #1069)

What workfow do you want to improve?
On some occasions, when you have several sound devices connected, there are similar names even the same.
How to make it better?
It would be interesting to be able to assign an alias to any sound device and thus it would be easier to choose the one you want.
Any alternative?
No.
Additional context
No response
