### ISSUE TITLE
Testing SoundSwitch with Skype

### ISSUE THREAD

**Issue by Philip-Sutton** [Belphemur/SoundSwitch#107]
I've set SoundSwitch so that the Communication Devices setting is turned on.  (I rebooted SoundSwitch after making this settings change.)

But when I use the SoundSwitch shortcut keys to switch either sound input or output Skype still uses the input and output devices that are registered in the Skype settings.

Am I doing something wrong or am I misunderstanding how things should work or is SoundSwitch not able to over-ride the audio settings of Skype?

**Comment by Belphemur** [comment]
Hello @Philip-Sutton,

Unfortunately, skype doesn't rely on the selection of Default device to output/input the sound.
It does only work with its own setting menu, which means you need to always go there and switch manually the device. I can't do anything about it.

**Comment by german95n** [comment]
So then, can you please remove the part of skype in:

> Communications

SoundSwitch can also change the communications devices when asked in the Settings. Windows make a differentiation between Multimedia and Communication, it means if an application ask to have access to Communications Audio Device (like Skype), it will receive the default Communications device. By default SoundSwitch only change the Multimedia device, and not the communications. Now if the checkbox is checked in the settings, it will also change the Communications device.

**Comment by Belphemur** [comment]
@german95n You're right, this was only true for older version of skype before they forced the user to choose the output.
