### ISSUE TITLE
Windows 10: Shorter notification duration when 'browsing' with hotkey

### ISSUE THREAD

**Issue by ArmEagle** [Belphemur/SoundSwitch#108]
I have several sound devices and used to use the hotkey to go through them.
In windows 7, when quickly switching from a to b to c, the notification (switching from a to b) would quickly be replaced (by b to c) either because of default short notification duration, or you doing something in code.

In windows 10 the minimum duration one can configure is 5 seconds ( found through: Start -> Settings -> Ease of Access -> Other options ). So, after the first notification is shown any next notification won't show until the first disappears (and will show 5 seconds itself again).

I'd like to have the next notification replace the first immediately.

Hopefully Windows 10 allows you to do that.

**Comment by Belphemur** [comment]
See #73 

It's linked to it. I need to implement my own notification instead of relying on the windows default one, then I'll be able to customize it like you suggest.
