### ISSUE TITLE
Tooltip text

### ISSUE THREAD

**Issue by xcasxcursex** [Belphemur/SoundSwitch#1096]
### What happened?

The tooltip text doesn't seem to fit:

![image](https://user-images.githubusercontent.com/58130821/213844339-6067d8d6-7e0b-443c-8486-8b394eb0ab99.png)
(Note the cut-off '10..' for the recording device)

On a possibly related note, I don't know what those numbers are (the percentages at the end, 100% here) but it doesn't correlate to any of the volume levels set on my devices. 

### Step to reproduce

Mouseover the tray icon

### Version

6.5.0

### What version of Windows are you seeing the problem on?

Windows 10

**Comment by Belphemur** [comment]
Hello,
it's actually representing the volume, but I have an issue where the tooltip doesn't get updated when the volume level change.
For the max length of it, I have no control unfortunaly.

**Comment by Belphemur** [comment]
Next version will have the volume first and updating properly.

**Comment by xcasxcursex** [comment]
Thanks mate :)
