### ISSUE TITLE
Combined hotkey for In+Output device

### ISSUE THREAD

**Issue by Pyrolit** [Belphemur/SoundSwitch#110]
I'd like to use SoundSwitch to more easily toggle between my laptop's built in speakers+mic and my wireless headset (which also has a mic).

Could you make it an option to switch both at once with a single keypress?
Perhaps even add the ability to link an input and output device into a custom device profile (since one particular mic should only ever be used with one particular speaker in this situation)

This feature would make your application perfect for my use.

Thanks

**Comment by Belphemur** [comment]
Hello @Pyrolit 

The single keypress for both toggle should be easily doable, but the linking is a little more tricky, I'll think about it.

Lately I didn't have that much free time to work on the project.

**Comment by MartenF** [comment]
I know this is an old ticket, but a combined hotkey to change playback and recording would still be very nice for people with multiple headsets.
On a sidenote if you set the same hotkey for both (in the json file) only the playback hotkey gets executed. By deleting the "else" in line 410 in AppModel.cs this would be fixed.

**Comment by Belphemur** [comment]
Done with the profile feature.
