### ISSUE TITLE
Add SoundSwitch to microsoft store.

### ISSUE THREAD

**Issue by bigplayer-ai** [Belphemur/SoundSwitch#1101]
### What workfow do you want to improve?

Hey,
Can you Add SoundSwitch to microsoft store.

### How to make it better?

installing via one place all your application.
more convenient.
more contorl.

### Any alternative?

not really

**Comment by Belphemur** [comment]
Hello,
I didn't know they had changed their policy about letter people with their own installer be on the store.

SoundSwitch is now officially published there.

https://apps.microsoft.com/store/detail/soundswitch/XP9K5QHW4KX4H8
