### ISSUE TITLE
Add icon support for profile mode banners.

### ISSUE THREAD

**Issue by bigplayer-ai** [Belphemur/SoundSwitch#1109]
### What workfow do you want to improve?

adding an icon support for profile mode banners.
So when I switch to a profile I can have visual clue what profile am I in.
for example showing the audio output icon.

### How to make it better?

support icons from windows as what happens when switching devices/playbackdevices from sound switch there is an icon showing the icon device.

### Any alternative?

Magicpods

**Comment by Belphemur** [comment]
You can try it with the nightly build if you want.

https://soundswitch.aaflalo.me/nightly
