### ISSUE TITLE
icons shows very small although it is a correct size.

### ISSUE THREAD

**Issue by bigplayer-ai** [Belphemur/SoundSwitch#1111]
### What happened?

when I change audio output/input. The icon size shown is very small, Maybe you can add a way to show it in a clear way or stretch it to fit... As shown in the image below
![image](https://user-images.githubusercontent.com/119108387/216943186-475eec1d-42b0-43ec-8b6b-f4f0b2b96ffe.png)
![Clip_20230206_120506](https://user-images.githubusercontent.com/119108387/216943219-5b752f04-14b7-4102-8ca6-a476c8104ca3.png)

### Step to reproduce

when I change audio output/input. The icon size shown is very small, Maybe you can add a way to show it in a clear way or stretch it to fit... As shown in the image below
![image](https://user-images.githubusercontent.com/119108387/216943186-475eec1d-42b0-43ec-8b6b-f4f0b2b96ffe.png)
![Clip_20230206_120506](https://user-images.githubusercontent.com/119108387/216943219-5b752f04-14b7-4102-8ca6-a476c8104ca3.png)

### Version

6.5.3.0

### What version of Windows are you seeing the problem on?

Windows 11

**Comment by Belphemur** [comment]
Hello,

For the icon as said in the discussion, you should aim for 16x16. I don't plan to change the size of the icon in the banner.

I advise you find proper icons online that are directly made in that size instead of resizing a bigger on.

**Comment by bigplayer-ai** [comment]
The icons still too small, even though they are 16x16. Also they look very blurry. Please make soundswitch more appealing to the eye.
