### ISSUE TITLE
HDMI output "forgotten" after audio hardware powers off.

### ISSUE THREAD

**Issue by dethzord** [Belphemur/SoundSwitch#1113]
### What happened?

SoundSwitch "forgets" my HDMI audio output (via NVIDIA card) after powering off HDMI devices (a soundbar, then out to a display).  Rather than becoming a disconnected device, SoundSwitch no longer sees the HDMI output at all, either as selectable from the icon or as an option in settings.  I would expect the output to move to a "Disconnected" status within SoundSwitch.

Upon powering back up, SoundSwitch continues to not see the output, even though sound is playing through the output.  Also, if I manually change the default output via Sound/Playback, SoundSwitch will pop a notification indicating the HDMI output is selected, but still does not list it as an option.  I would expect the HDMI output to return to a "Selected" status in the SoundSwitch options, as well as become available again when clicking the systray icon.

This issue may have began with 6.5.2, I am uncertain due to how closely they were released.

Do note that restarting the application restores the missing HDMI output, until again turning off the display/soundbar.

### Step to reproduce

To recreate, I simply power off my soundbar and display, then turn them back on.

### Version

v6.5.3

### What version of Windows are you seeing the problem on?

Windows 10

**Comment by tenderling** [comment]
Similar here. HDMI output disappearing at random until restart.  I think it started after gpu driver update.

**Comment by Aridity-hub** [comment]
I have this exact same issue, which has never happened before until a few days ago (I've been using SoundSwitch for a long time--it's fantastic).  It's my monitor (through which I output sound to speakers) that keeps getting forgotten by SoundSwitch every time the monitor turns off.  Restarting SoundSwitch resolves this temporarily.  Thank you for making this fantastic app and I hope this gets fixed soon.

**Comment by dethzord** [comment]
That seems to have done it.

I think there was also a graphics driver update in the mix, so I suspect it was an NVIDIA change, yes?  Just a coincidence in the timing.

Thanks for the good work.  Love your program.
