### ISSUE TITLE
Add support to switch Foreground App in Profile

### ISSUE THREAD

**Issue by bigplayer-ai** [Belphemur/SoundSwitch#1117]
### What happened?

Hey,
I can't force foreground program to change audio output when switching audio output via profile.
When I switch audio outputs regulary using soundswitch it works fine.
When using profile it does not switch.

### Step to reproduce

1) Have a profile for different audio output
2) have a hot key for that profile
3) press that hotkey
4) foreground program does not change its audio output.

### Version

6.5.4

### What version of Windows are you seeing the problem on?

Windows 11

**Comment by Belphemur** [comment]
Not really a bug. This isn't supported for now.
Making this an Enchancement.
