### ISSUE TITLE
Update installer to allow install to a custom location.

### ISSUE THREAD

**Issue by Vilhjalmr26** [Belphemur/SoundSwitch#1118]
### What workfow do you want to improve?

I like to install some tools to a different path than the windows default Program Files location.  Current installer doesn't not appear to have a way to set a different install location.

### How to make it better?

Add an install path variable to the installer.

### Any alternative?

I had just moved the folder after installing, which worked until the next update, at which point I had 2 installs in the system.

**Comment by Belphemur** [comment]
Hello,

This is already possible but only on first install.
If you want to change where the program is installed, you simply need to uninstall it and reinstall it (you won't lose your config).
From that moment on, SoundSwitch will always be updating itself in the new folder.

**Comment by Vilhjalmr26** [comment]
So it is!  I must have done something weird along the way to get it in a bad state.  Uninstall and reinstall worked fine.
Thanks!
