### ISSUE TITLE
Wrong Default Recording audio in Soundswitch

### ISSUE THREAD

**Issue by bigplayer-ai** [Belphemur/SoundSwitch#1123]
### What happened?

Soundswitch is not getting the right default recording audio.
It shows a disabled audio as the default recording audio, Even though the device is disabled and other device is the default. (see image below):
![Clip_20230212_225928](https://user-images.githubusercontent.com/119108387/218336660-c4a1a5f2-972a-4c62-b560-b3547b28e3a3.png)

### Step to reproduce

1) nothing it just shows wrong default recording audio input.

### Version

6.5.4.0

### What version of Windows are you seeing the problem on?

Windows 11

**Comment by Belphemur** [comment]
Good catch !

Thanks for the report.

**Comment by MasterBlastered** [comment]
Ver 6.6.0 and 6.6.5 do not exist here.

**Comment by bigplayer-ai** [comment]
Yes me too I’m using store application On 28 Mar 2023, at 16:44, MasterBlastered ***@***.***> wrote:﻿
Ver 6.6.0 and 6.6.5 do not exist here.
