### ISSUE TITLE
Hover notification shows wrong record device

### ISSUE THREAD

**Issue by Diaolou** [Belphemur/SoundSwitch#1124]
### What happened?

See attached images - the wrong record device is shown in the notification.
![Screenshot_20230216_140844](https://user-images.githubusercontent.com/36163428/219388017-b03f02ae-af29-412a-a831-1891114323a3.png)
![Screenshot_20230216_140903](https://user-images.githubusercontent.com/36163428/219388026-1fea6597-f108-46a1-a381-211f8eeb178e.png)
![Screenshot_20230216_141105](https://user-images.githubusercontent.com/36163428/219388036-b17feaa0-acd0-4027-94d1-b2b1d3eb521c.png)

### Step to reproduce

This has been happening since at least the first 6.5 version, I think.

I don't do anything special, it's just wrong.

### Version

6.5.4.0

### What version of Windows are you seeing the problem on?

Windows 11

**Comment by Belphemur** [comment]
Thanks for the report.
I already have it fixed for the new release.

duplicate of #1123

**Comment by Belphemur** [comment]
Duplicate of #1123

**Comment by Diaolou** [comment]
Sorry for missing the dupe and thank you!!

**Comment by bigplayer-ai** [comment]
I am still experiencing the same issue.
I am using SoundSwitch 6.5.4
![Clip_20230227_233825](https://user-images.githubusercontent.com/119108387/221691711-0e54cc69-bd6c-4baa-8bfc-0c0c1da2ba1a.png)
