### ISSUE TITLE
Error - "Cannot Start Application"

### ISSUE THREAD

**Issue by redmondChris** [Belphemur/SoundSwitch#113]
Each time I do a full start of Windows 10, I get a Windows error that says Cannot Start Application - "Cannot download the application. The application is missing required files. Contact application vendor for assistance."

In the Details, I see this...
`* Activation of C:\Users\Chris\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\SoundSwitch.appref-ms| resulted in exception. Following failure messages were detected:`
`		+ Downloading http://soundswitch.codeplex.com/releases/clickonce/SoundSwitch.application did not succeed.`
`		+ The remote server returned an error: (404) Not Found.`

Is there still an old auto-update reference to Codeplex when SoundSwitch starts? I'm running the latest build of SoundSwitch, v3.10.2.24485.

Despite the error, SoundSwitch does start and run successfully.

**Comment by Belphemur** [comment]
Go to C:\Users\Chris\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\

And delete SoundSwitch.appref-ms or anything that’s named SoundSwitch.
The new version doesn’t use this method anymore to make soundswitch start with the computer.

**Comment by redmondChris** [comment]
Thank you! That took care of it.
