### ISSUE TITLE
Startup problem, the Program file will be ..............

### ISSUE THREAD

**Issue by 1353604736** [Belphemur/SoundSwitch#1138]
### What happened?

Startup problem, the Program file will be generated under the root path of the installed drive letter, and the startup cannot be started automatically, and the startup item name in the startup item of the task manager has changed to Program. I judge that this problem will occur with a high probability when the installation directory name has spaces

### Step to reproduce

![无标题_看图王](https://user-images.githubusercontent.com/12869582/223287169-925f5a5e-480d-49a3-ad12-8eb6f58913a4.png)

### Version

6.5.4

**Comment by Belphemur** [comment]
Hello,

I'm not sure I understand what happened here, what was the path you used to install SoundSwitch ?

**Comment by 1353604736** [comment]
> Hello,
> 
> I'm not sure I understand what happened here, what was the path you used to install SoundSwitch ?

My installation path is in D:\Program Files\SoundSwitch\SoundSwitch.exe
