### ISSUE TITLE
Problem with VC Redist and Win 10 anniversary update

### ISSUE THREAD

**Issue by Vaelek** [Belphemur/SoundSwitch#114]
I'm not sure if it was directly after the Win10 anniversary update or not, but ever since about that time, this tool no longer works. The hotkey does absolutely nothing. Tested both on the latest stable and the beta branch, same results on either.

**Comment by ewakramo** [comment]
LTSBv14393 here; same issue. it starts, binds the key, but nothing happens.

**Comment by mskadu** [comment]
Same here. Am using the latest SoundSwitch beta v3.11.0.32914 on Windows Build 14393.82.

**Comment by ewakramo** [comment]
i just did a clean install (build 14393.82) with proper VClib install, now it is working correctly. i think the issue is related to improper vc install/version/register fault.

**Comment by mskadu** [comment]
So you suggest a full uninstall and re-install?

**Comment by Belphemur** [comment]
I keep this open.

@ewakramo thanks for the troubleshooting
@mskadu thanks for the confirmation.
