### ISSUE TITLE
beta 3.11.0.32914

### ISSUE THREAD

**Issue by sirius1** [Belphemur/SoundSwitch#115]
beta 3.11.0.32914 doesn't retain the playback devices. It show only one. Going back to an earlier version.
windows 10 with the dreaded anniversary update that break just about everything
Thanks for the great work.

**Comment by sirius1** [comment]
earlier version dont work at all, doesn't retain any output devices.  windows 10 anniversary BS

pretty much out of a soundswitch for me.

**Comment by Belphemur** [comment]
Please see #114 

Download and reinstall the VC Redist. The Windows update seems to have fucked it up.
