### ISSUE TITLE
Same hotkey for both "Playback" and "Recording" devices

### ISSUE THREAD

**Issue by CVI89** [Belphemur/SoundSwitch#1154]
### What workfow do you want to improve?

I can't seem to find a way to get SoundSwitch to change both Playback device AND Recording device with same hotkey.

E.g. my son has the following setup:
- Speakers and a table microphone
- Headset with microphone

So when he is browsing or listening to music and still wants to talk to friends online, he can use speakers and table microphone, but when he is gaming, he would like to use headset with microphone.

I can get it to work with to hotkeys - one for Playback device and one for Recording device, but it would be great if one could do it all.

### How to make it better?

I would like one hotkey for changing both recording and playback device at the same time.

### Any alternative?

I have no alternatives in mind.

**Comment by CVI89** [comment]
I do not understand how that fixes it?

I would like the same hot key to switch the profile then, that does not seem to be possible?

**Comment by Belphemur** [comment]
Hello,

Sorry if that wasn't clear.
You can setup 2 profiles in the settings of SoundSwitch with a HotKey trigger.

# Example
* Speakers and a table microphone: Profile 1 with CTRL+ALT+1
* Headset with microphone: Profile 2 with CTRL+ALT+2

That what profile are for, you can select what device (playback/recording) to use for what (normal/communication) and be changed together.

**Comment by CVI89** [comment]
Yes, but I was hoping I could use the same hot key to toggle between the profiles then.

**Comment by Belphemur** [comment]
In that case the article I linked explain how to do that :)

Yes you can have two profile with the same HotKey.
It will iterate between the two.

Sent from Nine
________________________________
