### ISSUE TITLE
Tray icon no longer changes to match output icon

### ISSUE THREAD

**Issue by Turbocat777** [Belphemur/SoundSwitch#1159]
### What happened?

after updating to the latest version 6.6.0.0 the icon in the tray will show the current output icon and will not switch to any other icon when switching to another output with a diff icon.

### Step to reproduce

1. open program
2. change to a different output
3. notice that the tray icon is still the old output and not the new one.

### Version

6.6.0.0

**Comment by Dominiquini** [comment]
+1

**Comment by PureSpider** [comment]
Same issue here!

**Comment by dmeiners88** [comment]
+1

**Comment by markvvaals** [comment]
Same issue here (on Win10 22H2).

To emphasize, the icon matches the output that is active when the program starts (either on boot or by closing the application  and starting it again).
The icon doesn't change when switching outputs, regardless of the change being invoked by a hotkey, left clicking the icon or in Windows playback devices screen.

**Comment by markvvaals** [comment]
From 6.6.0.0 release notes:
> Icon: Don't change icon when communication device is changed. ([84b7b46](https://github.com/Belphemur/SoundSwitch/commit/84b7b4674a53708b9b619ce5d7b0e73aec1c38a0)), closes https://github.com/Belphemur/SoundSwitch/issues/1134

After seeing that, I did some quick testing.

First of all, rolling back to 6.5.4.0 fixes the issue and the icon changes as expected.

Second, after re-installing 6.6.0.0 I noticed the following behavior.
With the setting "Switch Default Communications Device" (see screenshot below) checked, the bug occurs as described before. With this setting unchecked, the icon changes as expected (although there is a little delay in the change).

So it seems there is a fault in the logic which attempts to stop an icon change when the "Default Communication Device" is changed. This is too broad now, as it disregards whether the "Default Device" is changed which it should not.

![20230414_13-55-31_SoundSwitch](https://user-images.githubusercontent.com/16164609/232037711-6d32fcc7-8f21-4561-999d-6f8d3158047c.png)

**Comment by Dominiquini** [comment]
If, in the settings, I change the selection of "Systray Icon" from "Both" to any other option, and soon after I switch back to "Both", the icon in the systray change accordingly to the selected audio device!

**Comment by Turbocat777** [comment]
> From 6.6.0.0 release notes:
> 
> > Icon: Don't change icon when communication device is changed. ([84b7b46](https://github.com/Belphemur/SoundSwitch/commit/84b7b4674a53708b9b619ce5d7b0e73aec1c38a0)), closes #1134
> 
> After seeing that, I did some quick testing.
> 
> First of all, rolling back to 6.5.4.0 fixes the issue and the icon changes as expected.
> 
> Second, after re-installing 6.6.0.0 I noticed the following behavior. With the setting "Switch Default Communications Device" (see screenshot below) checked, the bug occurs as described before. With this setting unchecked, the icon changes as expected (although there is a little delay in the change).
> 
> So it seems there is a fault in the logic which attempts to stop an icon change when the "Default Communication Device" is changed. This is too broad now, as it disregards whether the "Default Device" is changed which it should not.
> 
> ![20230414_13-55-31_SoundSwitch](https://user-images.githubusercontent.com/16164609/232037711-6d32fcc7-8f21-4561-999d-6f8d3158047c.png)

Thanks for the input, this is an acceptable workaround for myself until this can be fixed in future versions.

**Comment by Belphemur** [comment]
Can you try the nightly release and tell me if that fixes it for you ?

http://soundswitch.aaflalo.me/nightly

**Comment by Turbocat777** [comment]
> Can you try the nightly release and tell me if that fixes it for you ?
> 
> http://soundswitch.aaflalo.me/nightly

Seems to be working again with the same settings I had issues with previously. Thanks for the fix.

**Comment by Dominiquini** [comment]
> Can you try the nightly release and tell me if that fixes it for you ?
> 
> http://soundswitch.aaflalo.me/nightly

Seems to be working here too!

**Comment by markvvaals** [comment]
Thanks for the quick fix @Belphemur 🙏
