### ISSUE TITLE
Crashing on Windows 7

### ISSUE THREAD

**Issue by JustinSummerlin** [Belphemur/SoundSwitch#116]
I have a fresh install of Windows 7 x64 and SoundSwitch (both the actual release and the beta) keeps crashing every time I try to launch it.  I pasted the "problem details" below:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	SoundSwitch.exe
  Application Version:	3.11.0.32914
  Application Timestamp:	57ba2865
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7c78c
  Exception Code:	e0434352
  Exception Offset:	000000000000a49d
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	367e
  Additional Information 2:	367e805d0e7c1ec3f63b05bb5ce5c416
  Additional Information 3:	9bf9
  Additional Information 4:	9bf9fc30c9639fb545fa85845e97064f

**Comment by Belphemur** [comment]
Do you have the SP1 ?

Do you have all the dependencies installed like .net and vc_redist 2015 ? (they should have been installed by the installer).

**Comment by JustinSummerlin** [comment]
You know what?  I probably didn't have all windows updates installed (I've been installing them the past few days).  They're installed now, and your post made me try soundswitch again and it's working great now.  Sorry for the false alarm, and thanks for helping anyway!

**Comment by Belphemur** [comment]
Glad to hear.

Usually, this would be caused by having Windows 7 without the SP1. I'll have to check the installer to be sure it would warn the user.
