### ISSUE TITLE
Switching doesn't change audio device between 2 devices (again, PART 2)

### ISSUE THREAD

**Issue by TheRealDjElite** [Belphemur/SoundSwitch#1175]
### What happened?

**_I had this issue in v6.6.0, then it went away for a bit after updating to v6.6.1, and now it's back again._**

Windows 11 Pro, Version 22H2, 22621.1555
SoundSwitch v6.6.1.0

I have 2 sound devices check marked.

Whether I use the shortcut or from within the app, I cannot switch audio devices successfully. The audio device choice changes (even in Windows 11 sound settings), however, the actual sound source itself doesn't.

I have to go into Windows 11 sound settings and disable either audio device to kickstart the other one, then re-enable the disabled one.

Rebooting the system doesn't help either.

### Step to reproduce

Nothing really. Just let the program start up as usual and try to change devices.

### Version

6.6.1

### What version of Windows are you seeing the problem on?

Windows 11

**Comment by Belphemur** [comment]
Hello,

Can you try the new nightly ?
https://soundswitch.aaflalo.me/nightly

Stop SoundSwitch, replace all file by the content of the zip, restart SoundSwitch
