### ISSUE TITLE
Ability to move notification window from the default top left

### ISSUE THREAD

**Issue by choekstr** [Belphemur/SoundSwitch#1176]
### What workfow do you want to improve?

It would be nice to have a way to move the default notification window from top left (overlaying all icons) to somewhere a little more noticeable based on a user's screen layout and wallpaper.  

### How to make it better?

Even if it was a simple config file with X/Y values we could modify it would be helpful.

### Any alternative?

Otherwise a great app and use it daily multiple times to go between speakers and headphones and one of my very important apps right now.

**Comment by alinayg** [comment]
Just wanted to comment on this since this is exactly what I was looking for. Using ultra wide monitors, sometimes its hard to see the banner. I was looking to have an option to center it top middle or bottom. Thank you for the great app!

**Comment by Yashirow** [comment]
Sorry for the bump but even with the latest version there's no settings to change the banner position. Is it not implemented yet or only a config file thing ? Thanks.

**Comment by Yashirow** [comment]
Thanks a lot !
