### ISSUE TITLE
Not switching at all [Win11Pro v22H2 b22621.1778]

### ISSUE THREAD

**Issue by TheRealDjElite** [Belphemur/SoundSwitch#1184]
### What happened?

It's not switching at all between 2 sound sources no matter what I do.

### Step to reproduce

Ctl+Alt+F11 or otherwise.

### Version

6.6.1.0

### What version of Windows are you seeing the problem on?

Windows 11

**Comment by Belphemur** [comment]
Hello,

Can you try the new nightly ?
https://soundswitch.aaflalo.me/nightly

Stop SoundSwitch, replace all file by the content of the zip, restart SoundSwitch

**Comment by TheRealDjElite** [comment]
> Hello,
> 
> Can you try the new nightly ? https://soundswitch.aaflalo.me/nightly
> 
> Stop SoundSwitch, replace all file by the content of the zip, restart SoundSwitch

No change.
