### ISSUE TITLE
Can't launch the program

### ISSUE THREAD

**Issue by ZaDrAx** [Belphemur/SoundSwitch#120]
Hi,

I can't launch the software.

he is installed, but when I click on him, nothing happen ..

W7 Pro 64 Bits.

**Comment by Belphemur** [comment]
Hello @ZaDrAx,

Do you have SP1 installed ?

Without it, SoundSwitch isn't going to work on Windows 7

**Comment by ZaDrAx** [comment]
Yes, he's installed, and I've try to re-install him in the doubt.

I don't know what to do, i've reboot my computer from 0, put the same Windows 7 CD as always, and now nothing want to work on him ..

**Comment by Belphemur** [comment]
Can you try with the last beta ?

**Comment by ZaDrAx** [comment]
Yes, I've tried different version.

I think when I've installed my W7 my ISO got corrupted. I'll try with another one in few hours. 

I keep you up !

**Comment by Belphemur** [comment]
This should be resolved with the last release.

A problem with VCRedist.
