### ISSUE TITLE
notification sounds not working in 6.7.0 and 6.7.1 versions

### ISSUE THREAD

**Issue by Nightbreez** [Belphemur/SoundSwitch#1203]
When i updated from version 6.6.1.0 to 6.7.1 my custom sound for switching devices stopped working when switching devices
Note: None of the other notification options where working either.
I grabbed the 6.7.0 prerelease update as it mentioned fixing this issue and it was still broken.
After downgrading back to 6.6.1.0 it works fine again.

Here's a DXDIAG if that helps
[DxDiag.txt](https://github.com/Belphemur/SoundSwitch/files/11692131/DxDiag.txt)

**Comment by Belphemur** [comment]
Hey,

Can you reinstall 6.7.1, and right click on SoundSwitch -> Reset app audio

See if that fixes it. Because if no notification were working that is the most probable cause.

Also, please, template are here for a reason.

**Comment by devildant** [comment]
Hi, i detect same bug, i try to re install and click on Reset per app audio, but that change anything, currently i downgrade to 6.6

**Comment by Nightbreez** [comment]
> Hey,
> 
> Can you reinstall 6.7.1, and right click on SoundSwitch -> Reset app audio
> 
> See if that fixes it. Because if no notification were working that is the most probable cause.
> 
> Also, please, template are here for a reason.

Sorry for the late reply and not using a template. I am rather new to posting on github XD.
I tried your solution and it still didn't work

**Comment by Belphemur** [comment]
Hello,

Can you try the new nightly ?
https://soundswitch.aaflalo.me/nightly

Stop SoundSwitch, replace all file by the content of the zip, restart SoundSwitch.

**Comment by Nightbreez** [comment]
I just got around to trying the nightly build …4004 and everything is working for me
