### ISSUE TITLE
Remove unnecessary SoundSwitch notification prefix

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#121]
I would suggest to remove the "SoundSwitch: " -Prefix of the notifications like shown here:
![2016-10-29 23_06_24](https://cloud.githubusercontent.com/assets/1107939/19832929/433875e8-9e31-11e6-98da-f3bc3e9f9cf9.png)
Because it's an information which is unnecessary. This is only a suggestion.

How it would look like:
![2016-10-29 23_06_24_new](https://cloud.githubusercontent.com/assets/1107939/19832964/47787760-9e32-11e6-87e6-513f4abd1fa1.png)
See [SoundSwitch/Properties/TrayIconStrings.resx#L151](https://github.com/Belphemur/SoundSwitch/blob/6c8a7e4a0ff444fdfa617821e06dd99669f47b3b/SoundSwitch/Properties/TrayIconStrings.resx#L151)...

**Comment by Belphemur** [comment]
I have another solution for you :)

Try the new beta, and use the Windows 10 toast notification, this one are made to be used from windows 8 -> 10 and don't have the preprended SoundSwitch.

This prefix is necessary for toast notification on WIndows 7.

**Comment by FireEmerald** [comment]
And where do i find the default windows notification sound if i select **Toast Notification** (*.wav;*.mp3)?

**Comment by Belphemur** [comment]
I admit there isn't a way for now to get the same sound as a normal notification.

By default it's silent (personal preference) or the sound you choose.

**Comment by FireEmerald** [comment]
Found the sound file, they are located at **"C:\Windows\Media\"** for example **Windows Notify System Generic.wav**.

@Belphemur But there's an bug: If the file name contains spaces like **Windows Notify System Generic.wav** and you klick **Open** the file isn't accepted.

**Comment by Belphemur** [comment]
@FireEmerald I tried to make the Alert01 or other of the Media file selectable, it seems to be a permission issue.

Those are system file that can only be opened by a system app or the user directly ... I tried multiple way to make the dialog select them but each time it crashed soundswitch.
