### ISSUE TITLE
Disable Systray icon

### ISSUE THREAD

**Issue by fidelako** [Belphemur/SoundSwitch#1219]
### What workfow do you want to improve?

The systray icon is rather unnecesary, you do the setup for the program once, and then just use the shortcuts/profiles for the rest, so having the app cluttering the tray and showing up 24/7 with no option to turn it off bothers me

### How to make it better?

Give the user the option to disable the systray icon.

### Any alternative?

.

### Additional context

The reason I'd love this is first of all I think it'd be simple to make, and the other one is that this program is perfect but it clutters my tray, I love having little to no icons there, and Windows 10 won't let you simply disabling systray icons, it keeps them in this unnecesary sub-menu arrow that you click and shows everything you were hiding (like a child hiding all his stuff under the carpet, rather than properly cleaning it). So the option to disable it by the program itself is necessary.

**Comment by Belphemur** [comment]
Hello,

As this is the only way for users to get back into the settings and that since Windows 10 the systray icon are hidden by default, I consider this as a non issue.
