### ISSUE TITLE
Device-dependent system tray icon

### ISSUE THREAD

**Issue by dimitrisplagiannis** [Belphemur/SoundSwitch#122]
Hi and thank you so much for this useful utility!
 
Could there be an option for the SoundSwitch icon on the system tray to change, depending on the currently active device? 
 
That would be very useful for us that monitor audio through alternative speaker sets.  I constantly need to make sure which speakers are currently active (which is not always evident acoustically, because they sit close to one another) and in order to do that I find myself having to hover my mouse cursor over the system tray icon. If the tray icon was different for each device, then I would know just by looking at it.
 
How about some sort of icon configuration? This could be a number, or a configurable color background, or even replacing the SoundSwitch icon with the device icons of Playback Devices (which are easily configurable).
 
Thanks again.

**Comment by Technetium1** [comment]
I think that this is a great idea! Maybe a dialog to choose the icon that starts at
`%systemroot%\system32\mmres.dll`
which is where all the generic sound device icons that most of us use are.

**Comment by Belphemur** [comment]
SoundSwitch will use the device icon as set in the Playback Device list in Windows.

You'll be able to change the icon there to make SoundSwitch use it if you have multiple device with the same icon.
