### ISSUE TITLE
SoundSwitch forgets nVidia HDMI audio output after handshake

### ISSUE THREAD

**Issue by neogohan324** [Belphemur/SoundSwitch#1224]
### What happened?

This issue appears to have been reintroduced after being fixed in #1113 & #1114.

I am running a fresh reinstall of SoundSwitch 6.7.2.0 on Windows 10 22H2, and the audio output in question is an HDMI audio output from an nVidia RTX 3060 Ti to a Denon AVR-S760H. The latest graphics and audio drivers are installed. I am using a 35ft optical HDMI cable which could be one fly in the ointment here.

See the image below, where Windows sees the output and SoundSwitch's Settings panel sees it but the 'tooltip' from the toolbar does not see it.
![image](https://github.com/Belphemur/SoundSwitch/assets/30501522/f289ca8d-5e06-44ae-af11-8e709c0ee118)

While that in itself wouldn't be a huge issue, it seems like SoundSwitch cannot /actually/ see it, and my profile to switch to the nVidia HDMI output on Steam Big Picture results in an error and audio remaining on the Realtek output.

![image](https://github.com/Belphemur/SoundSwitch/assets/30501522/4fe6901d-e083-4114-8f1c-b2592f346f74)

If I close and reopen SoundSwitch, the nVidia/Denon output will be re-detected and work without issue. Until, as far as I can tell, an HDMI handshake takes too long causing the audio device to drop out and reinit, in which case SoundSwitch will 'forget' about the output until SoundSwitch is restarted.

I've attached my log from today in which this happened 2-3 times as I tried to recreate the issue reliably.
[soundswitch20230718.log](https://github.com/Belphemur/SoundSwitch/files/12089675/soundswitch20230718.log)

### Step to reproduce

Open SoundSwitch while device attached to HDMI audio output is active. HDMI output is detected.

Turn off the device attached to HDMI output. Turn device back on. HDMI will likely be re-detected.

Load up a game on the HDMI output that causes a change in refresh rate/resolution on the HDMI output. After HDMI handshake is established, HDMI audio will likely drop and never be re-detected by SoundSwitch despite being seen by Windows.

### Version

6.7.2.0

### What version of Windows are you seeing the problem on?

Windows 10 22H2

### Relevant log output

[soundswitch20230718.log](https://github.com/Belphemur/SoundSwitch/files/12089675/soundswitch20230718.log)

**Comment by Belphemur** [comment]
Should be fixed in the latest version.
