### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by BrandonWLee** [Belphemur/SoundSwitch#124]
When I try to launch the program, it crashes, leaving me with a Windows error message "SoundSwitch has stopped working"

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	SoundSwitch.exe
  Application Version:	3.12.1.38069
  Application Timestamp:	58379d3a
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.23569
  Fault Module Timestamp:	57f7c0b4
  Exception Code:	e0434352
  Exception Offset:	000000000001a06d
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	367e
  Additional Information 2:	367e805d0e7c1ec3f63b05bb5ce5c416
  Additional Information 3:	fd73
  Additional Information 4:	fd731aee666a0a59d5b1c34140bff37f
```

I've tried v3.12.1 (SoundSwitch_v3.12.1.38069_Beta_Installer.exe) and 3.10.2 (SoundSwitch_v3.10.2.24485_Release_Installer.exe) and a couple others
OS: Windows 7 64-bit Professional w/ SP1

Let me know if you need more info :)

Also, there were no issues with the installation process

**Comment by Belphemur** [comment]
Hello

Can you try this tool and see if it crashed also ?

https://github.com/Belphemur/AudioEndPointLibrary/releases/download/v4.6.2/AudioTester.7z

**Comment by BrandonWLee** [comment]
Yup, it crashes. 
![capture](https://cloud.githubusercontent.com/assets/734576/20653031/ccc25e88-b4ba-11e6-90f0-6af11fe6acbb.PNG)

**Comment by Belphemur** [comment]
Great !
That's error help me a lot.

It seems I'm not packaging the right version of C++ Redist
Try this one: https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by BrandonWLee** [comment]
Nice! I installed the C++ Redist, and now I'm able to start SoundSwitch. 

Thanks!
