### ISSUE TITLE
Setting to keep the normal SoundSwitch TrayIcon

### ISSUE THREAD

**Issue by Ketrel** [Belphemur/SoundSwitch#128]
Could an option be added to always use the soundswitch icon rather than changing to the device icon without having to change Windows settings?

When the icon changes with the device, it makes it quite hard to find the icon in a cluttered system tray, and worse even when the icon doesn't match the one displayed in Playback Devices.

It would be nice to have the option to disable the changing icon all together so I'm always looking for the same thing when I need to change.

**Comment by Belphemur** [comment]
Hello @Ketrel 

I thought this request was going to come, just no so fast.
I'll add a checkbox in the settings for this
