### ISSUE TITLE
Auto-Updater

### ISSUE THREAD

**Issue by CaiB** [Belphemur/SoundSwitch#129]
I just received a UAC prompt out of nowhere to allow "Installer.exe" from an unknown publisher to run. Not knowing what it was, and being rather concerned at this point, I clicked "No". Later I realized it was SoundSwitch trying to update itself.

So I opened SoundSwitch, and let it do its update. The UAC prompt came up again, I clicked Yes, it asked to install some redistributable, and then promptly restarted my computer without warning or approval. **Not cool!**

I suggest that you notify the user that there is an update, and allow them to act upon that, instead of starting an installer out of nowhere, and also please add a notification/question if the computer should be restarted.

Otherwise, a super useful program :)

**Comment by Belphemur** [comment]
Hello @CaiB 

As you can see in #64 this is a feature that has been added some time ago, this is an opt-out feature that you can easily disable in the settings.

This last version of SoundSwitch updated your .NET and VC Redist to avoid any issue.

In other words, you can easily disable the stealth update and just have a notification when there is an update.

**Comment by Belphemur** [comment]
About the UAC I was putting before this information in the release to install my certificate (the one I used to Sign SoundSwitch and it's installer)

## Certificate installation

To resolve some security issue (see #6), the installer/uninstaller and application are now signed with my own certificate. You need to install it by downloading it from here: https://www.aaflalo.me/certs/AaflaloMeCertificates.zip

1. Unpack the zip
1. Run as admin the InstallCA.bat
1. Follow the indication
1. Now windows will recognize SoundSwitch as a valid publisher
