### ISSUE TITLE
Possibility to link application to Audio Device

### ISSUE THREAD

**Issue by Belphemur** [Belphemur/SoundSwitch#13]
Make SoundSwitch change the default audio device to a selected one when a set application is launched.

Like a game X is launched -> SoundSwitch configured to switch to headphones.

**Comment by joshery420** [comment]
I'd totally be on board for this! :D
Specifically, whenever my voice chat application is opened I'd love for it to switch to my headset.

**Comment by Life4YourGames** [comment]
:+1: Mentioning that this should count per application and not the default device in windows, just to make sure ;)

**Comment by Rohaq** [comment]
Suggestion: Allow for application linking during the implementation of #207 - since you could link applications to entire device profiles.

**Comment by pseisam** [comment]
Just a heads up, Windows can do this now. The option is called "App volume and device preferences":

https://lifehacker.com/how-to-customize-whether-windows-uses-speakers-or-headp-1826083404

**Comment by FireEmerald** [comment]
As @pseisam already explained, this feature is available with Windows 10 Version 1803.
A description how, can be found here #282.

**Comment by joshsleeper** [comment]
sorry for the noise, but I'm not seeing why this is a dupe of #268?

**Comment by FireEmerald** [comment]
@joshsleeper I linked the wrong issue, sorry for that. It's 282.
