### ISSUE TITLE
Audio device's selection menu on the systray stopped updating/working

### ISSUE THREAD

**Issue by nukewarrior** [Belphemur/SoundSwitch#131]
Hi,I got a bug after the recent update(3.12.3.37054)
![image](https://cloud.githubusercontent.com/assets/10683831/21014985/1538838e-bd9b-11e6-8b01-9ceba7bdfcd0.png)

I normally change the playback device by left clicking the icon and chose what i want.
But after the update this method no longer available.

The pic above shows I was using "MX279" yet I was using my Headset right then.Whatever I clicked on those two options the default device didn't change,stuck on the Headset.And on notification pop up after clicking.

However I can still change device by Hotkey or double clicking SoundSwitch icon,works just fine(notifications pop up and icons of two devices will change too).

What I did before update:
1.renamed my playback devices(Headset-->USB PnP Sound Device;MX279-->MX279 - 1)
2.reinstalled my headset's driver

What I tried after update:
1.reboot my PC(didn't work)
2.reinstall previous version of SoundSwitch(didn't work,still the same problem)

My OS:
Windows 10 1607
14393.447

And thank you for making this great software,really useful and saved me a lot of time:)

PS:I'm not good at English if you got confused by my broken english please let me know I'll try to make it more accurate.

**Comment by fredgreco** [comment]
I am experiencing the same problem. I would also note that when changing the audio device by hotkey, the green "check" stays with the previous audio device (it does not change to the currently active device).
