### ISSUE TITLE
Icon on Left-Click menu for Capture devices not being set

### ISSUE THREAD

**Issue by BigAal** [Belphemur/SoundSwitch#1332]
### What happened?

it is an easy fix, so in ProfileToolStripMenuItem, you set the icon to the Render device. If the Profile doesn't have a Render device, it just uses the unknown icon. You should check if device == null to check also for Capture Devices and take the icon of that one. Thanks.

### Step to reproduce

explained above 

### Version

latest

**Comment by Belphemur** [comment]
Good catch and easy fix :) 

However this will have to wait the next release, as I just released v6.8.0

**Comment by BigAal** [comment]
oh no, I got lazy yesterday and just posted it. It's ok,  I fixed it on my local ;)

**Comment by Belphemur** [comment]
Technically, you can just use the nightly if you prefer to not build it yourself :)

**Comment by BigAal** [comment]
I did some other changes to cater for my stupid work laptop being so slow refreshing. I don't want to wait 8-12 seconds every time I use the USB switch, so I disabled refresh on device change, and added a manual refresh if I need to. Sloppy but working.
