### ISSUE TITLE
Sort Items in Left-Click menu 

### ISSUE THREAD

**Issue by BigAal** [Belphemur/SoundSwitch#1335]
### What workfow do you want to improve?

When using "add to menu item" , profiles are added randomly I am guessing. Either user should be able to set the sort order of the item, or easier yet, just make them sort alphabetically as they appear in profiles tab.

(I added an Orderby() in the code to do that myself )
`var profiles = _profileTrayIconBuilder.GetMenuItems().OrderBy(t => t.Text).ToArray();`  

### How to make it better?

see above

### Any alternative?

no

**Comment by Belphemur** [comment]
Hey @BigAal,

Don't hesitate to make a PR for that line of code, you can easily do it directly from the GitHub UI.

I'll merge it right away, it's a good QoL change to have the profile listed alphabetically.

**Comment by BigAal** [comment]
I used to be a developer eons ago, I have been away from coding for a long time now. Last time I wrote code before this was in 2018. I am doing my changes in VS code, and I have no real experience in GitHub. I should learn more.
