### ISSUE TITLE
SoundSwitch not launching on Windows 8.1

### ISSUE THREAD

**Issue by littlechiki** [Belphemur/SoundSwitch#136]
This application doesn't appear to launch at all. I've tried different versions and everytime, it's the same result. Is it due to my system (windows 8.1 x64) or is it a known issue ? Would you have a solution ?

**Comment by Belphemur** [comment]
Hello @littlechiki,

Can you try to download the audio tester here: https://github.com/Belphemur/AudioEndPointLibrary/releases/tag/v4.6.2

It's a little tool I created to diagnose a problem with the underlying lib used by SoundSwitch.
Tell me if it crashes when you launch it and if it does, the exact message.

**Comment by littlechiki** [comment]
It does crashes and it tells me the message (my windows is in french so I'll do my best to translate it)
"Windows doesn't manage to access the device, path or specified file. Maybe you don't have appropriate authorizations to access the element."

**Comment by Belphemur** [comment]
Can you screenshot the message? 
French won't be an issue. ⁣

**Comment by littlechiki** [comment]
Ok it's giving me another message today
![image](https://cloud.githubusercontent.com/assets/25010488/21814326/3e63dec0-d759-11e6-92e9-1f6df2beeb93.png)

**Comment by Belphemur** [comment]
It seems the installer didn't detect correctly your version of the C++ redist

Install this: https://www.microsoft.com/en-us/download/details.aspx?id=52685
And everything should work.

**Comment by littlechiki** [comment]
It didn't but after that I updated my windows (this page [https://www.microsoft.com/en-us/download/details.aspx?id=49081](url)) and it does. Your tool was very helpful so thank you !

**Comment by Belphemur** [comment]
Great !

I'm locking and pinning this issue in the case of anybody encountering this also.
