### ISSUE TITLE
Soundswitch not launching on windows 10

### ISSUE THREAD

**Issue by GastonAbe** [Belphemur/SoundSwitch#137]
Hi everyone
This application doesn't appear to launch at all.
I read an other message about windows 8, and i saw
"Can you try to download the audio tester here: https://github.com/Belphemur/AudioEndPointLibrary/releases/tag/v4.6.2"

the message is
![image](https://cloud.githubusercontent.com/assets/25268827/22176270/f00d0e98-e006-11e6-96cc-62e46ad9e028.png)

can you help me ? thanks

**Comment by Belphemur** [comment]
It seems I have to tweak my detection of VC++ Redist

Download and install this: https://www.microsoft.com/en-us/download/details.aspx?id=53587

It should resolve your issue :)

**Comment by GastonAbe** [comment]
Hi
Thank you, it works now :)
