### ISSUE TITLE
Program notification bug when using multiple monitors and closing full-screen applications

### ISSUE THREAD

**Issue by budtz** [Belphemur/SoundSwitch#138]
If I switch to my receiver and open a full screen exclusive program like a movie or a game. I get a notification of my pc having switched devices just as I exit the program. Even thou it has not (why would it). I tried the program audio switch and this program does not have this bug. Furthermore, I only get this bug when audio device is set to my receiver. If I have it set to my other audio device I get no notifications after closing programs.

Edit: The notification is also a bit strange. I actually get two notifications right after each other - one for each device i have connected

Can you reproduce it?

**Comment by Belphemur** [comment]
Hello

I have difficulty to reproduce your problem.
If you see a notification appearing from SoundSwitch, it means for Windows, the default audio device changed. 

You can try this behaviour yourself by going into the sound settings and changing manually the default device, it will do the same thing.
