### ISSUE TITLE
Soundswitch Not Start on Windows Startup

### ISSUE THREAD

**Issue by hhdkshs** [Belphemur/SoundSwitch#139]
Soundswitch did not start when windows starts, it works fine by manual launch. Problem continuing after fresh install.
ps. some user permission issues occured in my system, i tried to change some permission/admin settings, it didn't help. Maybe those related to each other.
specs: win10 x64 build 14393

I don't know if it helps, but here last logs of soundswitch from roaming folder (there are 2 more files look identical to this):
"TracerX: Log file opened at 24.01.2017 11:39:56.  FullFilePolicy = Wrap, Use_00 = False, MaxGrowth = 1 MB, AppendIfSmallerThan = 0 1, initial size = 3."

and the oldest one:
"TracerX: Log file opened at 21.01.2017 14:49:10.  FullFilePolicy = Wrap, Use_00 = False, MaxGrowth = 1 MB, AppendIfSmallerThan = 0 1, initial size = 3.
14:49:11.510 Error WindowsAPIAdapter SoundSwitch+TrayIcon.<SetEventHandlers>b__14_0 TrayIcon.<SetEventHandlers>b__14_0 entered
14:49:11.518 Error WindowsAPIAdapter SoundSwitch+TrayIcon.<SetEventHandlers>b__14_0 TrayIcon.<SetEventHandlers>b__14_0 exiting
14:49:18.718 Error <null> SoundSwitch+TrayIcon.<SetEventHandlers>b__14_0 TrayIcon.<SetEventHandlers>b__14_0 entered
14:49:18.724 Error <null> SoundSwitch+TrayIcon.<SetEventHandlers>b__14_0 TrayIcon.<SetEventHandlers>b__14_0 exiting"

**Comment by Belphemur** [comment]
Hello, 

Can you go in the settings and uncheck /recheck the checkbox about starting with Windows? 

It should do the trick :) ⁣

**Comment by hhdkshs** [comment]
Tried it. Nothing changed :( is there a folder/registry that i can check if soundswitch do the trick?

**Comment by Belphemur** [comment]
Yes.

You should have a registry key: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\SoundSwitch

**Comment by hhdkshs** [comment]
It was there and seems correct, but no effect. Uninstalling, cleaning registry and reinstalling again looks like solved the problem. still dont know the cause. Thanks anyway
