### ISSUE TITLE
Idea: Add function to switch "Default communication device"

### ISSUE THREAD

**Issue by regener** [Belphemur/SoundSwitch#14]
I am using S.W. mainly to change between a headset and speakers when I browse or watch films/videos, but sometimes I would like to put TeamSpeak/Skype on speakers instead of the headset (the audio output).

Currently when I swtich between the outputs it changes the "Default sound device" but not the "Default communication device".

Is there any possibilities that you will add that? :)

**Comment by Belphemur** [comment]
I'm thinking of recoding the underlying library used in SoundSwitch.
This should make this possible.

**Comment by Belatar** [comment]
I just downloaded and installed Sound Switch on Windows 10 64 Bit German and it doesn`t switch the "Default communication device" anymore. Strangely on my desktop this seems to work with the same drivers and peripheral components.
