### ISSUE TITLE
Crashed when Bluetooth headphones conneted

### ISSUE THREAD

**Issue by gonejack** [Belphemur/SoundSwitch#140]
Before last version everything running fine, but after updated to the last stable version, soundswitch would crash when not selected bluetooth headphone connected.

**Comment by Belphemur** [comment]
@CrippleZero
> When I connect my Bluetooth speaker (or any other Bluetooth audio device), SoundSwitch crashes, offering a restart of the application. If the Bluetooth device is already connected and I reboot, then SoundSwitch crashes indefinitely at start-up and I have to relaunch the application.
I am running Windows 7-64bit, fully patched, SoundSwitch version 3.12.5.20099

**Comment by Belphemur** [comment]
I'm able to reproduce it.
Going to work on it

**Comment by gonejack** [comment]
soundswitch still crashes just several minutes ago, when I turn on my Bluetooth headphone with it automatically connected to the PC.

**Comment by Belphemur** [comment]
@gonejack Did you update the the latest version ?

If yes, you should have a full crashlog generated

**Comment by gonejack** [comment]
yes, and here is then content of SoundSwitch.txt after a current crash.

```
TracerX: Log file opened at 2/17/2017 11:34:31 PM.  FullFilePolicy = Wrap, Use_00 = False, MaxGrowth = 1 MB, AppendIfSmallerThan = 0 1, initial size = 3.
23:34:56.188 Error <null> SoundSwitch+ Exception while getting release Exception type: System.Net.WebException
Message: The underlying connection was closed: An unexpected error occurred on a send.
Source: System
StackTrace:
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)

Inner Exception type: System.IO.IOException
Message: Authentication failed because the remote party has closed the transport stream.
Source: System
StackTrace:
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

23:36:43.986 Error <null> SoundSwitch+AppModel.SaveState TracerX: Last line before circular log starts.
23:36:43.986 Error <null> SoundSwitch+AppModel.SaveState TracerX: First line in circular portion of log (never wrapped if you see this whole line).
23:36:43.986 Error <null> SoundSwitch+AppModel.SaveState AppModel.SaveState entered
23:36:43.986 Error <null> SoundSwitch+AppModel.SaveState    Saving application state
23:36:43.986 Error <null> SoundSwitch+AppModel.SaveState    Recovery Success
23:36:43.986 Error <null> SoundSwitch+AppModel.SaveState AppModel.SaveState exiting
```

**Comment by Belphemur** [comment]
Did it generated a zip file ?

If yes, I need that zip file, it contains valuable information when the 
application crashed.

**Comment by gonejack** [comment]
probably no, I can't find zip file, what location should I look for?

**Comment by Belphemur** [comment]
Could you zip me the content of %appdata%/SoundSwitch ?

it contains the logs and your configuration, it will help me understand exactly what happened. For now it seems linked with an interrupted connection to github while checking for new updates ... which is weird.

**Comment by gonejack** [comment]
Here is the folder, https://www.dropbox.com/s/jvykw2cc23v9yhw/SoundSwitch.zip?dl=0

**Comment by CrippleZero** [comment]
Mine is doing the same.  Where may I upload the zip file of the %appdata%\Soundswitch folder?  My company doesn't allow access to 'cloud' sharing sites like Google Drive, DropBox, OneDrive, etc.

I am running SoundSwitch 3.12.8.37187, Windows 7 Enterprise 64-bit, fully patched.

**Comment by Belphemur** [comment]
You can drag/drop it in your github comment: 
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/
