### ISSUE TITLE
Similar to #140 - Crashes when CONNECTING Bluetooth Device/Headphones

### ISSUE THREAD

**Issue by CrippleZero** [Belphemur/SoundSwitch#141]
When I connect my Bluetooth speaker (or any other Bluetooth audio device), SoundSwitch crashes, offering a restart of the application.  If the Bluetooth device is already connected and I reboot, then SoundSwitch crashes indefinitely at start-up and I have to relaunch the application.

I am running Windows 7-64bit, fully patched, SoundSwitch version 3.12.5.20099

**Comment by Belphemur** [comment]
merging with #140
