### ISSUE TITLE
Different notification icons for different devices

### ISSUE THREAD

**Issue by Sopor** [Belphemur/SoundSwitch#1418]
### What workfow do you want to improve?

The icon in the notification area is always the same.
To make it easier to see what sound device i have selected it should be possible to set an icon, so every device has its own icon.

### How to make it better?

.

### Any alternative?

.

### Additional context

It could use the default icon for a device or make me choose a custom
![image](https://github.com/Belphemur/SoundSwitch/assets/5789283/99058aed-0206-4191-b3f2-c5325a6ca830)

**Comment by Belphemur** [comment]
Here is how to do it:
https://github.com/Belphemur/SoundSwitch/discussions/702

**Comment by Sopor** [comment]
I think you misunderstood me.

I want the icon in the notification area (systray) to change icon when i change playback device.

Now it will only show this icon:
![image](https://github.com/Belphemur/SoundSwitch/assets/5789283/d6784be2-6d31-4e69-ae9a-846b690067e3)

**Comment by Sopor** [comment]
I see what i did wrong. It is working.

Thanks!
