### ISSUE TITLE
Voicemeeter doesnt show as playback device

### ISSUE THREAD

**Issue by keld107** [Belphemur/SoundSwitch#1423]
### What happened?

i used to be able to have voicemeeter as a playback device using soundswitch, this doesnt seem to work anymore.

### Step to reproduce

trying to have voicemeeter be a playback device from soundswitch

### Version

6.8.1.0

### What version of Windows are you seeing the problem on?

Windows 10

**Comment by Belphemur** [comment]
Can you check if this does still happen in the latest version ?

**Comment by davidmarshall15** [comment]
This was a concern for me before downloading SoundSwitch to try it out, I actually want to stop windows from automatically changing devices as I control this with voicemeeter.

I can confirm that voicemeeter shows up in both Playback and Recording devices, it all looks good to me.

**Comment by keld107** [comment]
sorry for the late reply, it happens when i run voicemeeter as a service to hide the taskbar icon
