### ISSUE TITLE
strimer

### ISSUE THREAD

**Issue by stranieroxxx** [Belphemur/SoundSwitch#143]
SoundSwitch ciao grazie per favore si potrebbe fare lo stesso lavoro per dispositivi di comunicazione, in modo tale da poterli settare in modo separato, sono un strimer e ho 5 dispositivi di comunicazione sarebbe belo grazie per il lavoro buona giornata.

**Comment by Belphemur** [comment]
If google translate done it's job well, you're asking about the Communication device, right ?

You have a setting in the Setting panel to make SoundSwitch switch the communication device.
