### ISSUE TITLE
Option to configure tray double-click action

### ISSUE THREAD

**Issue by zwsren435** [Belphemur/SoundSwitch#1439]
### What workfow do you want to improve?

In my experience, double-clicking the tray icon typically opens either the main interface or the settings. However, SoundSwitch instead cycles the audio output device. Because I use a hotkey to switch output devices, I would like the option to change what happens on double-click. 

### How to make it better?

An option in settings that allows configuring this

### Any alternative?

a

**Comment by Belphemur** [comment]
Hello,
This has been the behaviour for a long time.

I don't have a plan to change this. Moreover, in new version of Windows the systray is always hidden making this feature rarely used.
