### ISSUE TITLE
Trigger profile when a certain bluetooth audio device is connected

### ISSUE THREAD

**Issue by zwsren435** [Belphemur/SoundSwitch#1440]
### What workfow do you want to improve?

I would like to have the option to trigger a certain profile when a certain bluetooth audio device becomes available (ie. if I connect a certain bluetooth audio device, then I would like SoundSwitch to automatically switch to it).

Of course, the user could manually switch to the new device each time, but I feel that this feature is likely a common wish for many users.

### How to make it better?

a

### Any alternative?

a

**Comment by zwsren435** [comment]
It's similar, but it doesn't seem like a duplicate. I would like the ability to automatically switch to a certain profile when a bluetooth device is connected, not the other way around.

**Comment by t-makaro** [comment]
Yea, the other issue does seem like a slightly different ask. This sounds like it should be easier to implement. I have a bluetooth speaker that automatically conencts to my PC when I turn it on. It would be nice to detect that and automatically switch to the appropriate profile.
