### ISSUE TITLE
Optimization of the tray menu buttons; Option to rearrange/remove menu items

### ISSUE THREAD

**Issue by zwsren435** [Belphemur/SoundSwitch#1442]
### What workfow do you want to improve?

When I first started using SoundSwitch, the most confusing and frustrating part of the program was the tray menu's confusing buttons and mysterious layout. For this reason, I think it would be a big improvement if it had certain items moved around or combined (I have created a mock-up below). 

It would also be nice to be able to add/remove certain items, depending on the user's preferences.

### How to make it better?

Proposed new menu:
![image3](https://github.com/Belphemur/SoundSwitch/assets/121317613/887aafa7-9d71-475b-8696-72be76db1c9a)

- "SoundSwitch 6.0.0": Opens the "About SoundSwitch" window. 
    - Because the tile already says "SoundSwitch" and the version number, I think it would be intuitive to most users that clicking this option would open up application info.
    - The About SoundSwitch window already shows the version number, so it could also show the update channel, and have a manual update button next to/below that.

- (The update tile could appear here when an update is available, to encourage users to update. I would recommend that it normally not be shown, to reduce cluttering)

- "Playback Devices", "Mixer", "Settings": Placed next to each other in the same group, to help the user understand that these buttons are the ones that they will use most often. "Mixer" tile renamed to "Volume Mixer", to make its function more clear and to match the name of what it triggers.

- "Reset per-app audio": Not shown by default, to prevent cluttering (as I can't see most users using this very often).*

- "Exit": Renamed to "Quit SoundSwitch" to make it clearer what this button does (some users might think that this simply closes the menu, then not understand why SoundSwitch is no longer running. 

----------

Of course, you should change this to whatever you feel is correct. I just want to offer my perspective as an end-user who has no involvement in development.

I recommend that current users be asked before their tray menu is suddenly changed, as some would not be happy to see it change without warning. The tray menu configuration tool, whatever it ends up looking like, could have some "preset" buttons like "old default layout" and "new default layout" to allow users to change to the old/new default layouts. (Or, the configurator could be _only_ these preset buttons, if making a full-fledged configurator would be too difficult)

\* I can't see many users wanting to constantly delete their custom audio configuration, so I would recommend that the "Reset per-app audio" button be moved to Settings (or somewhere else that makes more sense). If the 'tray menu configuration tool' is implemented, users would be able to add this option to their custom menu layout, if they choose to. (and if the 'tray menu configuration tool' does not end up being added, they can select the "old default menu layout" button in Settings to get this tile back.

### Any alternative?

a

**Comment by Belphemur** [comment]
Hello,

I've discussed this with @XangelMusic and I like your mockup. We're going to rethink the menu.

However, it won't be configurable.
