### ISSUE TITLE
Add cmd line options for scripts to Soundswitch

### ISSUE THREAD

**Issue by GeAd23** [Belphemur/SoundSwitch#1454]
### What workfow do you want to improve?

I want to make macros for a mechanical tastatur. For that I need a function to ask Soundswitch for informations. 

### How to make it better?

The main function/method must add cmd args and must parse them. For getter commands one arg is enough. The set can be used up to two args.

### Any alternative?

You need to check if the program already started and send this args to the open process (pid). Else it start Soundswitch and initialize before work with the args. Soundswitch would not exit automatically after that.

### Additional context

Cmd params : 
Start Soundswitch (only call the soundswitch.exe)
Exit Soundswitch (call the internal exit function from Soundswitch)

Get profile list (profile names)
Get active profile (profile name)
Set active profile (profile name)

Get audio input devices list (devices names)
Get audio output devices list (devices names)
Get active audio input device (device name)
Get active audio output device (device name)
Set active audio input device (device name)
Set active audio output device (device name)

Force this audio input or output (add --force after Set profile)
Also switch audio for the active application (add --switch_active_application after Set profile)

Export profile (profile name)
Import profile (profile name)

**Comment by Belphemur** [comment]
Hello,

Sorry this a very niche feature that brings a lot of complexity to the code base to be implemented properly. I don't have plan on adding this to SoundSwitch.

There are other tool that can work command line to manage audio devices.
