### ISSUE TITLE
Add a Centered/center screen banner notification location

### ISSUE THREAD

**Issue by choekstr** [Belphemur/SoundSwitch#1466]
### What workfow do you want to improve?

Thank you very much for adding in the ability to change the location of the banner notification, that has helped a lot!  Would you be so kind as to add an option for "center" as well as the current 6 choices?  It would be nice for certain machines (my handicapped brother for instance) to have the notification in the center of the screen for higher visibility. 

Much appreciate your work on this stellar app, really enjoy using it!

### How to make it better?

Additional choice in the current notification dropdown of "center"

### Any alternative?

config file for manual adjustment of banner location using x,y coords

**Comment by Belphemur** [comment]
@XangelMusic Interested in taking that one ?

Shouldn't be too hard with the logic you built.
