### ISSUE TITLE
Ability to adjust notification on-screen timeout

### ISSUE THREAD

**Issue by choekstr** [Belphemur/SoundSwitch#1467]
### What workfow do you want to improve?

It might help if there was an adjustable time field for the on-screen notification before it fades out.  

The current hardcoded time works pretty well but I'm thinking about accessibility and handicapped people might need it to remain longer.

### How to make it better?

A user setting in the settings panel that has an on-screen notification timeout setting so people can adjust it to remain longer or remove quicker. 

### Any alternative?

maybe a config file setting but that's much less usable.

**Comment by Belphemur** [comment]
Hey,

I don't see why not :) 
Not a hard thing to make setting for, surely going to be shown in seconds with a strong minimum of 2.

**Comment by shaund** [comment]
Can you allow any delay rather than imposing a minimum? Two seconds is really long. It would also be great if it applied to the quick menu switcher too.

**Comment by 55ahmedsalah** [comment]
> Hey,
> 
> I don't see why not :) Not a hard thing to make setting for, surely going to be shown in seconds with a strong minimum of 2.

2 seconds is quite a long time and I love to see it instantly like 0 seconds
Can you give us that in the upcoming update?
