### ISSUE TITLE
Icons are hard to see in the notification area if taskbar has a dark color

### ISSUE THREAD

**Issue by kintrupf** [Belphemur/SoundSwitch#1474]
### What happened?

I use dark gray as the taskbar color. As a result, the icons from SoundSwitch are almost impossible to see.
A set of icons for dark mode would be appreciated!

### Step to reproduce

Set the taskbar to a dark gray color and try to find the SoundSwitch icon 😉

![image](https://github.com/Belphemur/SoundSwitch/assets/8496344/82be13a7-1111-4c5e-a04a-cac9b29b2728)

### Version

v6.10.3

### What version of Windows are you seeing the problem on?

Windows 10

**Comment by Belphemur** [comment]
Hello,

SoundSwitch use the icon set on the device in Windows. You can easily change the icon of any device as long as you change it in Windows using an `.ico` file. Suggested dimension: 16x16 and 32x32.

https://github.com/Belphemur/SoundSwitch/discussions/702
