### ISSUE TITLE
Make banners hidden in the alt+tab menu

### ISSUE THREAD

**Issue by Crunchbits** [Belphemur/SoundSwitch#1475]
### What workfow do you want to improve?

Currently the banner notifications show up in the alt+tab menu. This makes it frustrating to alt+tab during the banner's appearance because it will interfere with the program you were actually attempting to go to.

### How to make it better?

Hide notification banners from the alt+tab menu.

### Any alternative?

N/A

### Additional context

SoundSwitch 6.10.3
Windows 10 Home (2009)

**Comment by Belphemur** [comment]
Thanks for reporting this.

This is actually a bug, it shouldn't be visible in the alt+tab menu or even in the task bar. 
I never noticied it ^^'
