### ISSUE TITLE
Can't start SoundSwitch (error with interval)

### ISSUE THREAD

**Issue by Bluscream** [Belphemur/SoundSwitch#1481]
### What happened?

![SoundSwitch_XGUvOpvmVo](https://github.com/Belphemur/SoundSwitch/assets/3318223/949d9a46-ccf1-493a-96e5-395cd8674cb5)

### Step to reproduce

just starting the program 

### Version

latest i guess? cant check cause it doesnt open anymore

### What version of Windows are you seeing the problem on?

Windows 11

### Relevant log output

```sh
it will offer me to open this url https://soundswitch.aaflalo.me/#sentry?eventId=06c31ad6a48945fab6948c278c62b56f which just opens your website
```

**Comment by Bluscream** [comment]
This needs to be fixed. It even happens with a brand new installation with deleted settings. Directly after the update to 

SoundSwitch 6.11.0.0 | Antoine Aflalo | 6.11.0.0 | 15/05/2024 | 179,8 MB

**Comment by Belphemur** [comment]
Hello,

Thanks for reporting this. Happy this only impacts the beta version.

Should be fixed in the new version.
