### ISSUE TITLE
Asking for permission since update

### ISSUE THREAD

**Issue by fredgreco** [Belphemur/SoundSwitch#149]
Since the update to 3.12.7.38751, when I boot up, Soundswitch now asks me for approval to run (like admin setting). Is this intended behavior? Is there a setting to avoid that unnecessary interaction with the program? I just want it to start in the background. Thanks.

**Comment by Belphemur** [comment]
Hello,

Not that shouldn't happen. I can't reproduce your issue, the only moment there is need for the Administrative right, it's when the installer is launched since it needs it to install the application.

**Comment by FireEmerald** [comment]
@fredgreco 
![2017-02-14 20_59_37](https://cloud.githubusercontent.com/assets/1107939/22946770/b1408136-f2f8-11e6-9c92-896ddbd7283a.png)

**Comment by fredgreco** [comment]
I uninstalled and reinstalled. Appears to have solved the problem on reboot.
