### ISSUE TITLE
Unable to bind ScrollLock as a hotkey

### ISSUE THREAD

**Issue by darmach** [Belphemur/SoundSwitch#151]
Hi,
In the old version - not sure how old, probably a lot, the version with smaller interface - I was able to set Scroll Lock as a hotkey, this way scroll lock led was lit when headset was in use.

Could it be brought back in this version? 

Regards,
Darmach

**Comment by Belphemur** [comment]
I cannot reproduce this issue.

The Scroll key in bindable in the latest version
