### ISSUE TITLE
/silent /Silent /VERYSILENT Arguments don't work for silent instalation

### ISSUE THREAD

**Issue by Fanatiikon** [Belphemur/SoundSwitch#1524]
### What happened?

I checked here on github and i found that one of the above are supposed to work for silent installation. I am however prompted whether i want to install on all users or just current. After installing once if I use the /silent argument it works just fine. However I have a script that automatically installs every application I need for a fresh windows installation. Having it prompt me with installation mode blocks my script from automatically completing while I am away.

### Step to reproduce

Run installer with /silent /Silent /VERYSILENT arguments

### Version

6.11.0.0

### What version of Windows are you seeing the problem on?

Windows 10

**Comment by Belphemur** [comment]
Hello,

Not really a bug.
SoundSwitch uses Innosetup for the installer.

The documentation is here:
https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

Depending what you want (all users or current user) you'll have to add the flag for it:
- `/ALLUSERS` for all users
- `/CURRENTUSER` for the current user.
