### ISSUE TITLE
Resolve AppVeyor problems

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#153]
**AppVeyor** is failing all the time - seems like something is wrong.

See https://ci.appveyor.com/project/Belphemur/soundswitch/build/3.12.8.340/job/ahcivmrbbxotx75t from last commit https://github.com/Belphemur/SoundSwitch/commit/67f65716dfb8a8e54ebcfcaaed6982c8940123f2.

**Comment by Belphemur** [comment]
I'm aware of AppVeyor, the problem is quite deep since it doesn't have the required UWP libs.

I'll have to give a try to reconfigure it again.

**Comment by Belphemur** [comment]
Well I removed AppVeyor.

too much hassle for no real usage.
