### ISSUE TITLE
Tray icon doesn't update until switched 

### ISSUE THREAD

**Issue by Technetium1** [Belphemur/SoundSwitch#154]
The tray icon displays the program logo instead of current device. However when the device is switched for the first time, it works correctly. Something to do with #135?

**Comment by Belphemur** [comment]
That would be weird. 

What happen when you change the setting, does the icon also change? 

⁣Sent from BlueMail ​

**Comment by Technetium1** [comment]
It updates exactly as it should, except for the initial launch of the program. For example, if you exit with a headphone icon in the tray, on relaunch you will see the SoundSwitch logo until you switch devices.

**Comment by Belphemur** [comment]
I have a hard time reproducing this. Since #134 is making sure the icon is set correctly at application startup.

Even if the device has no icon, you'd see the basic Speaker icon.

Can you zip the content of %appdata%/SoundSwitch and drag & drop it in your comment ?

**Comment by Technetium1** [comment]
[SoundSwitchAppData.zip](https://github.com/Belphemur/SoundSwitch/files/801643/SoundSwitchAppData.zip)

**Comment by Belphemur** [comment]
@Technetium1 I see you're on the beta channel, and on an old release (3.12.1).

Can you manually update to the 3.12.8, the previous beta aren't updating to the newest release, only to the newest beta.

This should resolve your issue.

**Comment by Technetium1** [comment]
@Belphemur Thank you! It's fixed!
