### ISSUE TITLE
Unable to launch on Windows 7 32bit: Universal C Runtime missing

### ISSUE THREAD

**Issue by nuttaone** [Belphemur/SoundSwitch#155]
Hi,
I am unable launch this on a Windows 7 32bit OS. I get the following error when launching the AudioTester.exe also.

![image](https://cloud.githubusercontent.com/assets/14214341/23308109/efa15fda-faa1-11e6-8a15-a5f97ecb2dd4.png)

Is this known? I've tried checking both open and closed issues.

**Comment by Belphemur** [comment]
Hello,

Do you have the exact same error when launching SoundSwitch ?
If it's the case, it seems the installer installed the 64 bits version instead of the 32 bits.

**Comment by nuttaone** [comment]
Hi @Belphemur 

Thanks for your response.
I've managed to resolve the issue by installing the following windows Universal C Runtime patch.

https://support.microsoft.com/en-gb/help/2999226/update-for-universal-c-runtime-in-windows

**Comment by Belphemur** [comment]
@nuttaone 

Thanks for this, I'll need to find a way to check if it's installed or not and then download the right version since they have a different one per OS.
