### ISSUE TITLE
Localization improvements

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#156]
I was looking inside your code for the localization and thought it would be more or less easy possible to add another language for SoundSwitch. If this is no problem for you @Belphemur i will add **German** as 3rd one.

While adding the new `*.de.resx` files, i'm going to change some names of various controls to get a more consistent naming. This will provide in the future a easier way to implement even more languages.

I'm sure there are also some untranslated strings - like those from the new update settings. I will also add these to the existing resource files as well as some typo fixes ;)

When it's done, I will create a pull request. (next few days)

**Comment by Belphemur** [comment]
Hey

Sure that'd be great. There is couple of issues with the Designer not taking the resource strings (and always a pain in the ass to remove all those "text" by the resource key).

Please don't change the current existing key. To add german, use Zeta Resource Editor: https://www.zeta-resource-editor.com/index.html

It's free and will by default copy the english string in german.

**Comment by FireEmerald** [comment]
Which "existing key" do you mean shouldn't be changed exactly?

**These?**
![2017-02-26 22_56_40-soundswitch - microsoft visual studio](https://cloud.githubusercontent.com/assets/1107939/23344122/11144764-fc77-11e6-8f21-1ebcae337264.png)

**Comment by Belphemur** [comment]
Yup exactly, those keys.

I'm quite used to them by now.

**Comment by FireEmerald** [comment]
I'm going to keep (most) of the key names but some are not named consistent. Theres CamelCase other are lowerCamelCase as well as 'cryptical shorted names'.

**Comment by Belphemur** [comment]
Good point. Some formalization would be needed. 

lowerCamelCase should be the way to go. 

⁣Sent from BlueMail ​

**Comment by FireEmerald** [comment]
Setting all `*.Text = "";` properties inside the `*.Designer.cs` files is a horror, because the `*.Designer.cs` files are overwritten each time you change anything inside the form, like resizing a control and so on.

Wouldn't it a way better just to set all `Text` properties in the constructor of all forms? Seems like the best solution for me.

Ok, we will have to set the Text twice, inside the designer of the form and in the resx files but it's a way easier to sync these files then going through the `*.Designer.cs` files each time and replace all texts...

**Comment by Belphemur** [comment]
In that, case better create a method in the form that would take care of that (because let's be honest, the constructors are quite full already).

Of course, that method will be called in the constructor.
What I don't understand with the Designer, is that before I was able to take the strings directly from the Properties file ... then after one of the VS update, it stopped doing that.

**Comment by FireEmerald** [comment]
I already replaced all strings from the designer and it's a waaay better now ;) As you already proposed i moved the localization in it's own method(s). There are many changes - it would be better to not push any other commits until i set up the pull request - to avoid merge conflicts.

I think it should be done tomorrow.

**Comment by Belphemur** [comment]
No problem, I'll release a beta version once it's done. 

⁣Sent from BlueMail ​
