### ISSUE TITLE
Settings dialog resize issues

### ISSUE THREAD

**Issue by jhakonen** [Belphemur/SoundSwitch#164]
Looks like the Settings dialog have some resizing issues.

When resizing the dialog larger notification label doesn't move with rest of the content:
![settings-resize-1](https://cloud.githubusercontent.com/assets/1950698/23830132/d5016640-070b-11e7-87f5-70f10281051b.png)

When resizing the dialog smaller "Switch Default Communication Device" disappears:
![settings-resize-2](https://cloud.githubusercontent.com/assets/1950698/23830137/f05b347a-070b-11e7-8e19-09193915e048.png)

**Comment by Belphemur** [comment]
Hello, 

Good catch, some element aren't anchored correctly, thanks for spotting it. 

⁣Sent from BlueMail ​

**Comment by FireEmerald** [comment]
I will look into this. There are also some German strings which doesn't fit...
