### ISSUE TITLE
New-Old Issue - Switching to Bluetooth Audio

### ISSUE THREAD

**Issue by CrippleZero** [Belphemur/SoundSwitch#166]
It appears that the new(er) version of Soundswitch is getting better with switching to Bluetooth audio, however still crashes when switching to Bluetooth.  Before, however, I would get a message asking to restart the program after the crash.  Now, it just has the option to close the program.  I have not tested, yet, a reboot while connected to Bluetooth to see if it launches automatically connected or if it crashes upon startup.

One good thing, it finally registered that it is NOT a virus (I knew that, but Symantec didn't for a long time lol).

I am running Windows 7 Enterprise, 64-bit, fully patched/upgraded.  I currently have v3.13.1.19225 of SoundSwitch installed.

Please let me know if i need to archive and upload any log files.

**Comment by FireEmerald** [comment]
> archive and upload any log files.
Directly using github attachments or via a filehoster. The logfiles are located at **%AppData%/SoundSwitch** - the whole folder please.

**Comment by CrippleZero** [comment]
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/841230/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Could you try with the latest version ?

I doubt it would change anything but I'm using VS 2017 to compile it which could help.

**Comment by Belphemur** [comment]
Can you try the latest beta?

https://github.com/Belphemur/SoundSwitch/releases/tag/v4.0
