### ISSUE TITLE
Rename the Installer EXE when autoupdate to something more meaningful

### ISSUE THREAD

**Issue by Belphemur** [Belphemur/SoundSwitch#167]
For now, the file is downloaded as "Installer.exe" which doesn't help the users using automatic update when the UAC popup comes.

**Comment by Skaronator** [comment]
Would be good to make a window, that ask you if you want to update Sound Switch instead of asking for UAC directly.

I was playing a game and it was tab out due to the UAC popup.

**Comment by Belphemur** [comment]
@Skaronator In the settings of SoundSwitch, choose "Notify" in the Update section.

You'll get a Windows notification when a new version is available (and also a little icon in the right click menu on the systray)

**Comment by Skaronator** [comment]
Ah gotcha! Thanks
