### ISSUE TITLE
Improve the notifcation of new update

### ISSUE THREAD

**Issue by Belphemur** [Belphemur/SoundSwitch#168]
Creating a new form and animating it could be the way:

http://stackoverflow.com/questions/461184/toast-style-popup-for-my-application

**Comment by FireEmerald** [comment]
- **Current behavior:** If a new update is available a Windows Notification is shown. If the user clicks onto the notification, the download form is shown.

What would be better if we would use such a custom form? I mean you can't show more information inside such a form so you will still need a other form opened after the popup.

**Comment by Belphemur** [comment]
On Windows 10 (and surely 8) you can disable altogether the notification. In this case, you won't be notified.

The other idea would be to play with the trayIcon to change it to the update icon every X minutes/hours for X seconds (like current icon/update icon/current icon/update icon...).

**Comment by FireEmerald** [comment]
If the user disables these notifications entirely he will indeed miss not only the notification for new updates of SoundSwitch. In this case it would be perhaps better to show directly the download form - that's the easiest way.

**Comment by Belphemur** [comment]
Showing the download form directly is intrusive, it's exactly what the 
users are complaining about when in Stealth update and the UAC popup comes.

I think I'll stick with the idea of the icon changing until the user 
launched the update. (But again, the icon is surely hidden most of the 
time).

**Comment by FireEmerald** [comment]
> Showing the download form directly is intrusive, it's exactly what the
> users are complaining about when in Stealth update and the UAC popup comes.

Moment, do you wan't to show the new form if the "stealth" update option is selected? I was thinking that you will use the new form only if the "Notify" update option is selected.

**Comment by Belphemur** [comment]
Sorry, I'm not clear ; I'm only referring to Notify mode.

# Ideas

  * New notification form with 2 buttons: Update now, Remind me later
  * Make the systray icon "change" to show there is something to do

**Comment by Belphemur** [comment]
I went for simply animating the systray icon
