### ISSUE TITLE
Problem with hotkey since new version

### ISSUE THREAD

**Issue by FitzcairnHS** [Belphemur/SoundSwitch#171]
Hello,

Above all i want to thank you for your work because i'm of the earliest user of Soundwitch and it help me a lot and i use it since a very long time and i could not stop using this wonderfull software.

I have an issue since the last release the hotkey doesn't work anymore. I mean i can still modify the hotkey but it doesnt anything.  The Ctrl + Alt + F11 combination doesnt work. My own combination that i use since the begining was Ctrl + F9 doesnt work anymore too.

For example i don't use Alt + any key because there are used for the Geforce Exerperience hotkey for shadowplay (share) recording and avoid any conflict.

That's why i always used Ctrl + F9 and it always worked fine before now.

I did some test myself before to post there. First thing is to delete appdata%/SoundSwitch folder, check the playback device, check the soundwitch configuration, tried others hotkeys combinations, uninstalled the last version 3.13.1 and tried the old version v3.13.0 and nothing changed.

**But the weirdest thing is soundwitch still works when i change the device manually when i simple click or double click on the systray icon to switch audio devices. I still get the Windows notification.**

For now i'm going to do some others test with more older versions to try to solve the issue.

Edit : I tried also the v3.12.8 version and still the same problem hotkey doesnt work too. I really dont know what to do. Is there an issue with Windows 10 ? I'm on W10 (64 Bits).

I did not change anything neither installed software on my computer. The only thing happen is Windows Update weekly but i don't think it could mess up with soundwitch.

Any idea or help would be welcome thanks !

**Comment by FireEmerald** [comment]
There was another issue which seems like exactly the same see #170. Please upload your logfiles like the other user.

**Comment by FitzcairnHS** [comment]
Thanks for your help.

Log before delete : [http://s000.tinyupload.com/index.php?file_id=52478570461068969094](url)
Log after delete : [http://s000.tinyupload.com/index.php?file_id=08911224972305627982](url)

I always used the same hotkey Ctrl + F9 with soundswitch since the begining and it always worked perfectly since almost a year. I tried the default hotkey without change Ctrl + Alt + F11 is not working. Every others combinations with Crtl or Alt or letters or numbers. Everything. And there is no hotkey who is working at all.

I verified all the other applications which could block my hotkeys and i can't find any conflict at all.

Nothing changed on my configuration and everything was fine for me before the last update so it look very strange to me i really dont understand what's happen.

**Comment by FitzcairnHS** [comment]
I have some news for you. 

Everytime i tested the different versions i was doing this : uninstall soundswitch and after delete the folder in appdata. And everytime i installed a different version (recent/older/betas) it wasnt working.

Tonight for give you the logs i only deleted the appdata folder but without uninstall. So next time i launched soundswitch the software created a new profile in appdata with another SoundSwitchConfiguration.json file.

And guess what he worked for a while. But like i read the other issue you linked with the other guy i was thinking the problem will come back after the next reboot.

I didnt rebooted the whole evening because i was working on the computer. I did just now before going to bed just being curious and guess what it's still work.

I have no fucking clue what is going on but the hotkey is working and i can use my Ctrl+F9 personal hotkey and i didnt do anything else. No software installed or uninstalled so it still cannot be used by another programm.

So my guess it's really a Soundswitch issue because i never changed my hotkey and it didnt worked for days and the whole evening and now it's working so i think there is somewhere a mess with the 
SoundSwitchConfiguration.json files but i can't tell you what is it but it would be good to look about it because i'm sure some others people could have the problem.

So for the moment the problem solved himself and i don't know why or how but i will let you know if it's coming back later.

Goodnight guys :)

**Comment by FitzcairnHS** [comment]
So today the problem is back like for the other person in the other thead i rebooted the computer today and the hotkey doesnt work anymore.

I think i have to delete againthe appdata folder and try to relaunch soundswitch again.

It's really a soundswitch issue the test and facts showed clearly it's not from another application because the hotkey are not used elsewhere.

Any help ?

**Comment by FireEmerald** [comment]
@FitzcairnHS You only uploaded the config files. Please upload the whole **%AppData%\SoundSwitch** folder for both scenarios (before/after delete).

**Comment by GrimArthurius** [comment]
Hi! I have the same problem under Windows 7 Pro SP1 x64. Hotkeys no longer works since 3 last builds I guess. Fresh install (deleting app data etc.) and hotkeys work until first system reboot.

**Comment by FireEmerald** [comment]
@GrimArthurius Do you remember since which version exactly?

**Comment by GrimArthurius** [comment]
I think since 3.13 but what an exact build I don't remember. Two last builds didn't work for sure. I think it started with builds introducing Auto update. The build with Radio mark worked. The next which allowed to turn off Auto Update started to cause problems. Maybe I'm wrong.

**Comment by FireEmerald** [comment]
@GrimArthurius Could you upload your ```%AppData%\SoundSwitch``` folder **after it doesn't** worked?

**Comment by GrimArthurius** [comment]
Yes, sure when I'll get back home later on.

**Comment by Belphemur** [comment]
@FireEmerald seems to be linked with the Enum again that aren't converted correctly.

I guess, the configuration is corrupted when SoundSwitch reload it and can't find the right setting for the Hotkey leading to no hotkey registered. Only happening at boot.

**Comment by FireEmerald** [comment]
I didn't changed any enums which are related to the hotkey system.

**Comment by Belphemur** [comment]
That what I was thinking too.

We didn't rename the configuration either.
Usually it's linked to another app using the same hotkeys, (as said in 
previous issue) but the fact we have 3 reports about this means there is 
a real issue.

I don't see windows changing their HotKey API.
The hardest part is to reproduce this behaviour.

**Comment by GrimArthurius** [comment]
Here's AppData: http://rgho.st/7nRbVwdJX

**Comment by FitzcairnHS** [comment]
Hi, i think GrimArthurius is right if i can remember the hotkey problem since fews versions when the builds introducing Auto update.

I will upload the whole data file soon tonight.

Funny thing today the hotkey is working again but i'm sure next reboot it wont work again.

Weird bug :D

**Comment by FitzcairnHS** [comment]
Guys i think i found the issue !

So today the hotkey was working when i turned on the computer the first time and he was still working after i rebooted the computer for a second time. I immediatly made a copy of the appdata soundswitch folder into a rar. 

I checked the soundswitch option and the hotkey is working when the box Notify me when updates are available is checked.

When i unchecked this box and checked Never check for updates and rebooted then the hotkey was not working anymore ! I'm sure it has something to do with that option update. So i made a copy of the appdata soundwitch folder into a rar file too.

Working appdata SoundSwitch.rar : http://rgho.st/8pLgPdvVj

NOT working appdata SoundSwitch.rar : http://rgho.st/6wbFMcSkq

So for the moment i keep the notify me update checked and i will see if it's working for another day.

Personnaly i prefer uncheck because i don't like to be reminded everyday to update when i don't want to but well for the test and for keep it working i let it checked.

Tell me what you think about it guys :)

**Comment by FireEmerald** [comment]
@FitzcairnHS Really big thanks for all your work - i appreciate that ;)

@Belphemur I would say the source of this error can be found here:
[SoundSwitch/Model/AppModel.cs#L269](https://github.com/Belphemur/SoundSwitch/blob/dev/SoundSwitch/Model/AppModel.cs#L269)

It was my mistake that i missed to evaluate all the code - but i didn't thought that the event hook of the hotkey system is set inside a method called ```void InitUpdateChecker()```... this line of code shouldn't be there. It isn't related to any update related stuff.

**Comment by Belphemur** [comment]
@FireEmerald Holy cow ... 

Well I consider I share most of the blame, bad method naming and I didn't see that in the code review.

Funny thing is ... for users that have the issue they will have to update to resolve it, the ones on the update track don't have it.

I'm correcting it.
Thanks @FitzcairnHS for your patience and help in pinpointing the issue
Thanks @FireEmerald for finding the piece of code triggering this problem/

**Comment by FitzcairnHS** [comment]
Nice ! I'm very glad that i helped you to solve the issue :)
