### ISSUE TITLE
Updates pop UAC

### ISSUE THREAD

**Issue by StingrayNine** [Belphemur/SoundSwitch#174]
Every time soundswitch updates it triggers UAC. That in itself is a good thing, but when I'm on one below default "security" and the command has "/VERYSILENT" doesn't seem very silent. Anything upcoming about this?
![screen 259](https://cloud.githubusercontent.com/assets/1285293/24162886/370e878c-0e69-11e7-848e-0a027b5dfbf9.png)

**Comment by Belphemur** [comment]
Hello

Download the new version manually, run the installer, check the box about Trusting SoundSwitch certificate.

The UAC won't popup anymore.

**Comment by StingrayNine** [comment]
Thanks. I've let it auto-update for so long I hadn't read/re-installed it with the certificate. Probably fixed now. =)
