### ISSUE TITLE
SoundSwitch doesn't start - Windows 8.1

### ISSUE THREAD

**Issue by John-dc** [Belphemur/SoundSwitch#176]
Hi,
Thanks a lot for your tool I use since a long time.

I recently re-install all my pc, with Windows 8.1, and soundswitch doesn't work.
I've tried differents versions and everytime, it's the same result: Nothing happens when I try to start the application.

I've used your "audio test" and this is the error message:
![problem](https://cloud.githubusercontent.com/assets/26770224/24461042/4a0708e0-14a0-11e7-8fa0-dfe34879ddc4.jpg)

Could you please help me please, I ready would like to use your tool ;)
Thanks

**Comment by Belphemur** [comment]
Hello @John-dc 

Can you be sure you're up to date in your Windows updates ?

See #136

**Comment by John-dc** [comment]
Ok, I think it's the probleme, but I've a not really official windows and I do not succed to be OK with all updates ^^

Thank for answering

**Comment by Belphemur** [comment]
You can try to manually install the update that could resolve your issue:
https://www.microsoft.com/en-us/download/details.aspx?id=49081
