### ISSUE TITLE
C++ 64bit Redist Not Able to Install

### ISSUE THREAD

**Issue by KunaniGaming** [Belphemur/SoundSwitch#179]
There is a newer version installed so it won't let the required one install. I'm using Windows 10 Creators update and just ran into this popup during auto update today.

**Comment by Belphemur** [comment]
Can you tell me what do you have in regedit here:

HKLM\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14\VC\Runtimes\x64

The value of Version
![regedit](https://cloud.githubusercontent.com/assets/197810/24830266/730d12f4-1c50-11e7-85b1-632480cff8b1.JPG)
