### ISSUE TITLE
[Question] markdown-html

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#182]
Which tool is used here: [markdown-html](https://github.com/Belphemur/SoundSwitch/blob/dev/Make.bat#L49) ?

**Comment by Belphemur** [comment]
It's a small tool I use to render the change log and the Readme into html file before adding them in the the installer. 

One of the user asked for them to be in html since for non tech/dev the markdown format is a not as readable as an html page. 

⁣Sent from BlueMail ​

**Comment by FireEmerald** [comment]
Could you provide the source of the tool?

I only found https://github.com/pwlmaciejewski/markdown-html and was unable to get it to work in a windows shell...

**Comment by Belphemur** [comment]
You can find all the info here, link to the repo included.
https://www.npmjs.com/package/markdown-html-fixed

I forked it to update it for NodeJS 6.x (should also works on NodeJS 7.x)
