### ISSUE TITLE
[Question] GenerateChangelog script

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#183]
I was evaluating some code. Do you still use the _GenerateChangelog.bat_ file which is mentioned in the gitignore? If so i would say it would be better to include it in the project.

**Comment by Belphemur** [comment]
Yes I use it at every release. 
I won't include it because it contains one of my github API key. 

I'm using a Ruby script to parse the change done between the last and the penultimate tag and generate a comprehensive changelog. 

⁣Sent from BlueMail ​

**Comment by Belphemur** [comment]
When I'm home I can split the key from the file and add the .bat file

**Comment by FireEmerald** [comment]
I thought of the same (splitting) if this isn't any problem for you ;)

**Comment by Belphemur** [comment]
See last commits.

I splitted the key from the file and put the url of the tool.
