### ISSUE TITLE
Switching Spatial sound format in Windows 10 Creator Update

### ISSUE THREAD

**Issue by BrightMedal** [Belphemur/SoundSwitch#184]
Hi there

With the Creator Update, Microsoft has added virtual surround headphone feature. Users can now select either Window Sonic or Dolby Atmos in Speaker Properties to enjoy surround sound with their headphone. I'm a fan of your little tool and it would awesome If I can switch these spatial sound formats with a hotkey.

![untitled](https://cloud.githubusercontent.com/assets/27346903/24954405/5ab9fc86-1fd3-11e7-92e3-25ab01388cd5.png)

**Comment by Belphemur** [comment]
Hello,

The idea sounds good. However I don't have set of skills required to reverse engineer this new feature of windows 10.

As put in the C++ lib I created for SoundSwitch, all the discoveries, reverse engineering and the base code were made by @Eretik. I only built around it with his authorization.

Also I couldn't find this tab in my Windows 10, making it even harder to reproduce.
