### ISSUE TITLE
Error after Creator's Update

### ISSUE THREAD

**Issue by maschwenk** [Belphemur/SoundSwitch#185]
![image](https://cloud.githubusercontent.com/assets/1264305/25562292/fb4d368e-2d36-11e7-843a-33c39c2f712a.png)

**Comment by Belphemur** [comment]
This error is not a good omen.

Depending on what exactly happened, it could mean Creator Update won't be work with SoundSwitch.

**Comment by stecklars** [comment]
I am on the Creators update and Soundswitch is working fine here.

**Comment by maschwenk** [comment]
Hey, I realized I actually wasn't fully on the Creator's Update (went through the process last night where you opt in). Not sure what caused the issue before that but after the Creator's Update went thru, I was able to use it.
