### ISSUE TITLE
Soundswitch crashes on RDP connect

### ISSUE THREAD

**Issue by joszz** [Belphemur/SoundSwitch#187]
Whenever I connect to my desktop with soundswitch running through RDP. Soundswitch crashes on login, see attached file.
[SoundSwitch-crashlog-24_5_2017.zip](https://github.com/Belphemur/SoundSwitch/files/1024972/SoundSwitch-crashlog-24_5_2017.zip)

**Comment by FireEmerald** [comment]
Reference #41, #112.

**Comment by joszz** [comment]
didn't look for closed issues, my bad. Quickly glanced on the open once.
I can assure you this is still a problem with the latest version and Windows 10.

I'm actually using Guacamole as the "client" (webinterface) for RDP connections most of the time. I'll check if it persists when I use the android RDP app from MS (only other valid client I have around at the time).

**Comment by Savemech** [comment]
Also have this very same issue when using freerdp/mstsc(w7x64) at w8.1x64  with 3.14.2

**Comment by Belphemur** [comment]
I made a "possible" fix for this taking into account the crash dump @joszz provided.

It will be in the next beta version.

**Comment by ThisIsABug** [comment]
I'm nearly afraid to ask but ... is this beta already out? Or did this fix ever made it into an release? I created the [original issue](https://github.com/Belphemur/SoundSwitch/issues/112) back in 2016 and I still have this problem. (RDP from Win10 to Win7, everything patched to the latest possible stable).

**Comment by Belphemur** [comment]
@ThisIsABug Did you try with the latest version 4.10 ?
Can you try with a different type of Notification like Banner ?

**Comment by ThisIsABug** [comment]
Yes, it is the latest version (4.10.6899.14921)
I have configured it to show "No Notification"
Where would I find these crashlogs joszz provided?
Maybe they could help you?
