### ISSUE TITLE
Error popup when trying to install latest update

### ISSUE THREAD

**Issue by VeNoMouS** [Belphemur/SoundSwitch#196]
![image](https://cloud.githubusercontent.com/assets/597545/26662041/7fe2a96c-46d5-11e7-9ebd-b4865e65aef3.png)

**Comment by VeNoMouS** [comment]
trying for the 5th time seems to be the charm...

**Comment by Belphemur** [comment]
Github had some issues in the day. 

Since I'm using their server to distribute the updates, it might be linked to it.

⁣Sent from BlueMail ​
