### ISSUE TITLE
Crashes when remote connecting to machine using RDP

### ISSUE THREAD

**Issue by Luckyman79uk** [Belphemur/SoundSwitch#197]
When I connect to the machine running Soundswitch using RDP it crashes. The machine running soundswitch is Windows 10 with Creators Update.  I've pulled out the event log entry and the details are as follows: 

Faulting application name: SoundSwitch.exe, version: 3.15.0.37396, time stamp: 0x592e1268
Faulting module name: ntdll.dll, version: 10.0.15063.0, time stamp: 0xb79b6ddb
Exception code: 0xc0000374
Fault offset: 0x00000000000f775f
Faulting process ID: 0x3668
Faulting application start time: 0x01d2de1f45a6ab84
Faulting application path: C:\Program Files\SoundSwitch\SoundSwitch.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: a6f90f51-aefc-4922-81fc-ea30552a05c3
Faulting package full name: 
Faulting package-relative application ID:

**Comment by FireEmerald** [comment]
Please provide us your logs/configuration folder if you are reporting a crash.
Compress the whole %AppData%\SoundSwitch directory and upload it.

**Comment by Luckyman79uk** [comment]
No probs. I've attached the requested folder.

Many thanks.
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1061795/SoundSwitch.zip)

**Comment by FireEmerald** [comment]
Ref dbe1061f742bb85b0f9b9ba5b2466d9649e87d31
