### ISSUE TITLE
High CPU usage because of "Windows Audio Device Graph Isolation" process

### ISSUE THREAD

**Issue by inascime** [Belphemur/SoundSwitch#198]
Hi there, and thanks for your software.

I was noticing unusual high levels of cpu usage on my PC(specs below). due to a process "Windows Audio Device Graph Isolation"

Upon reading this article:

https://www.howtogeek.com/273764/what-is-windows-audio-device-graph-isolation-and-why-is-it-running-on-my-pc/

I killed SoundSwitch and the problem is no more. I'm not sure if I can say this is 100% indicative of a problem with SoundSwitch or whether and what more info I should provide so let me know. 

Windows 10
CPU: I5 6660k @ 4.4GHZ
Motherboard: Gigabyte LGA 1151 Z170 HDMI 2-Way CrossFire ATX DDR4 Motherboards GA-Z170-HD3
GPU: MSI GTX 1070 GAMING X
Memory: Corsair LPX 16GB 3000MHZ

**Comment by inascime** [comment]
figured out this has nothing to do with soundswitch sorry!

**Comment by FireEmerald** [comment]
What was the reason for the problem? Just if someone else has this problem.

**Comment by Belphemur** [comment]
@inascime and @FireEmerald I had the same issue with the "Sound Enhancements" of my logitech headphone.

I ended up disabling it also.

**Comment by slim-python** [comment]
This is actually a problem of windows 10,(it has lot's of the problem actually), try solving your windows audio device graph isolation problem by looking up online for that

try this guide maybe [Fixed windows audio device graph isolation](https://windowsground.com/windows-audio-device-graph-isolation-high-cpu-usage-fixed/)
