### ISSUE TITLE
SoundSwitch in Homeoffice/Office

### ISSUE THREAD

**Issue by Towi178** [Belphemur/SoundSwitch#199]
I'm a happy user of SoundSwitch. However there seems to be one major feature missing - there is no support for moving the computer from one set of devices to another. 

So I'm working both from a homeoffice space and an office space, and SoundSwitch will always crash when the laptop is plugged into the other envioronment. You have to restart it then.  

Do you think this is on your roadmap, to support such moves?

**Comment by FireEmerald** [comment]
Could you please provide some more information about "_plugged into the other envioronment_"? You add/remove devices? Which one? How many? Version of SoundSwitch? Any crash logs?

**Comment by Towi178** [comment]
Yes, I'm using a docking station at each workplace, they are connected to different devices:
- office docking station: One Jabra Headset
- homeoffice docking station: Another headset and a Jabra speak 410. 
When the laptop moves in between the two locations, I set it to sleep or hibernate. So it awakes all of a sudden with that new configuration, which I assume that it confuses SoundSwitch. 

Version of SoundSwitch: 3.15.0.37396

I think there are no crash logs, because the program just hangs, it does not actually crash. I have to kill it then.

**Comment by Belphemur** [comment]
@Towi178  Okay that makes some sense.

What happens to SoundSwitch when you simply undock the laptop? Is that already enough to make it hang?

**Comment by Towi178** [comment]
In this case it will not hang, it has detected that something has changed. There is a notification saying "SoundSwitch requires configuration [...]"

**Comment by Belphemur** [comment]
Can you right click on it and go into settings and select the devices you want to use?

It seems the configuration got lost of corrupted since it's asking you to set the device list.

**Comment by Towi178** [comment]
Hi Belphemur, 
that was just my reply to the question whether SoundSwitch would hang if the docking station was disconnected. It's not a problem on its own. 

Also the behavior is actually correct that it's asking for devices, as my laptop does have the internal mic and loudspeaker disabled. 

Thanks nevertheless. Now looking forward to a possible solution for the case when SoundSwitch hangs.

**Comment by Towi178** [comment]
Closed this issue due to clumsy fingers. Reopened it now.

**Comment by Belphemur** [comment]
SoundSwitch shouldn't have to ask for anything.

Once you configured it, it will remember the devices you selected even if those are disconnected.

Can you do a screenshot of when you get that specific message ?

**Comment by Towi178** [comment]
I got this message when I disconnected the docking station and no devices were left.

**Comment by Belphemur** [comment]
Okay, that's weird, it sounds like Windows is uninstalling your sound card when undocking, usually it's only deactivating them and reactivating them on "plugging".

If I understand correctly, SoundSwitch crash when a new audio device is added since It happens when you are docking the laptop.

**Comment by Towi178** [comment]
Well I deactivated the soundcard of my laptop, that is maybe a bit special. This may be the reason for the windows popup. 

However this does not explain why SoundSwitch hangs, correct?

**Comment by Belphemur** [comment]
Deactivate shouldn't change anything.

But the crash/freeze you're talking about make me think of #200 

Can you try with an older version of SoundSwtich ?
https://github.com/Belphemur/SoundSwitch/releases/tag/v3.13.2

**Comment by Towi178** [comment]
Hey, for some unknown reason the issue did not occur again. I'm wondering why. Maybe a windows update has changed something for the better. Will come back here if the issue pops up again. 

Thanks anyway for helping!

**Comment by Belphemur** [comment]
Don't hesitate to reopen the issue if it does come back. 

⁣Sent from BlueMail ​
