### ISSUE TITLE
Error: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by HugoDaBosss** [Belphemur/SoundSwitch#20]
I get this error message each time I open the settings. After that it just opens, but without any devices in the list, and thus the shortcut is not doing anything.

**Comment by Belphemur** [comment]
I need more information than this.
When SoundSwitch crash it should give you an error message asking you to provides the content of %appdata%\SoundSwitch

Can you please compress it and use any kind of file hoster to upload it ?
