### ISSUE TITLE
SoundSwitch Freezing randomly.

### ISSUE THREAD

**Issue by Laserman49** [Belphemur/SoundSwitch#200]
Hello all.
I'm on Windows 10 Creators Update Pro x64 (version 1703) with SoundSwitch version 3.15.0.37396.
When I switch to my different sounds output devices with the combination of Alt+Ctrl+F11, Soundswitch is bugging for me, when I try to access it with right clic next to the clock icon in the taskbar, the menu appear, but it is freezed and the banner is freezed too, i can't do anything else to Ctrl+Shift+Esc and kill soundswitch to reload it, to retrieve access of the right clic menu.

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1077463/SoundSwitch.zip)

**Comment by FireEmerald** [comment]
Is this problem present since you installed SoundSwitch or only since a few days/weeks?

**Comment by Laserman49** [comment]
It's only when I installed SoundSwitch, and my installation of Windows is new, less than 1 week, I formated my PC do did it.
With another hotkeys it's the same problem, and with another notification method same problem too.

**Comment by Belphemur** [comment]
@Laserman49 Can you try with an older version?

https://github.com/Belphemur/SoundSwitch/releases/tag/v3.13.2

@FireEmerald I want to check if the problem is related to VS 2017 compiler.

**Comment by Laserman49** [comment]
OK, i will try, and come back with you to say if it work or not.

**Comment by Laserman49** [comment]
Hello, I just tried, and it works with an older version. With the 
latest, it doesn't.

**Comment by Belphemur** [comment]
Okay that helps a lot.

Disable the auto-update the time we resolve this. I want to be sure it's linked to VS 2017.

**Comment by Laserman49** [comment]
Ok, I will do that. Say me when it's solved please.

**Comment by Belphemur** [comment]
I'm keeping the issue open until we're sure it's resolved.

Do you mind trying in the future beta version that should resolve the issue as we're not able to reproduce it on our machines ?

**Comment by Laserman49** [comment]
Yes, I can, if you want, you can send me a link for the beta, and I will 
test it.

**Comment by Laserman49** [comment]
I want to say that, if I quit Soundswitch and reload it, all work like a 
charm, or if I use the left clic on the icon next to the clock it works 
too, if the PC has just been turned on it doesn't work.

**Comment by Laserman49** [comment]
No news about this bug ?

**Comment by Belphemur** [comment]
I'm sorry my main computer is in repair. I'm not able to recompile this for now to give you a beta version easily.

**Comment by Laserman49** [comment]
Ok, no problems, I understand. When you can, send me the Beta, I will 
wait until you can, take your time, I'm not hurry. Lol. ;-).

**Comment by fredgreco** [comment]
I just want to say I have this bug also (I think). Often when I wake the PC from sleep, if I left click or right click on the Soundswitch icon the menu pops up but freezes. A quit from task manager and restart makes it work fine.

**Comment by Laserman49** [comment]
Exactly the same problem like me, except that problem is also at the first use of Soundswitch after PC Turned on. If i kill the app with Task Manager, and relaunch it, no problem, it works fine.

**Comment by hellonearthis** [comment]
I installed the old version which installed the .net framework,  then installed the new version and can now change between devices.

**Comment by Laserman49** [comment]
Hello.

Why did you close this bug ? It isn't solved.

**Comment by fredgreco** [comment]
I think the newest version solves the bug. Is that correct?

**Comment by Laserman49** [comment]
I'm very sorry for you, but it isn't solved. I just installed it, but 
the problem is the same for me.

**Comment by Belphemur** [comment]
@Laserman49  Darn, I hoped this version would solve the issue by forcing to upgrade the VC Redis C++ to 2017.

Can you try this little util for me, do a screenshot of it after running it:
https://github.com/Belphemur/AudioEndPointLibrary/releases/download/v4.7.0/AudioTester_x64.zip

**Comment by Belphemur** [comment]
In fact, use this latest version: 

https://github.com/Belphemur/AudioEndPointLibrary/releases/tag/v4.7.1

Also, tell me what happens when you input the letter "s" and push enter.

Does it crash ?

**Comment by Laserman49** [comment]
Thank you, did the file I sent you will help you to debug the program ?

**Comment by Belphemur** [comment]
@Laserman49 It seems you can't attach file to comment using the email. You need to do it from the web interface.

**Comment by Laserman49** [comment]
I will try.

**Comment by Laserman49** [comment]
Do you receive it now ?

**Comment by Belphemur** [comment]
Okay, no issue with the first one, compiled with VS 2015

Can you try the second one ?

https://github.com/Belphemur/AudioEndPointLibrary/releases/download/v4.7.1/AudioTester_x64.zip

**Comment by Laserman49** [comment]
Tried, and this the file.
![audiotester 2](https://user-images.githubusercontent.com/29454709/27989391-d4b913fc-6437-11e7-9102-fa2c7606fefb.JPG)

**Comment by Belphemur** [comment]
If you do s -> enter

Does it change your audio device ?
Do you get the notification from SoundSwitch in the same time.

From the screenshot, it seems the audio device is changed successfully, I start to think it's a problem with the version of .NET not VC Redist...

**Comment by Laserman49** [comment]
Yes, it change my audio device when I use s and enter, but it switch with devices that I have not selected in Soundswitch.

**Comment by Belphemur** [comment]
@Laserman49 That's normal, it's made as a testing tool to see if the problem lies within the underlying component of SoundSwitch or SoundSwitch itself.

For what I gather from your testing, I need to check the .NET wrapper and SoundSwitch code to understand what is causing that freeze you're observing.

**Comment by Laserman49** [comment]
Do you think you will solve the problem ?

**Comment by Belphemur** [comment]
Can you try to reinstall .NET 4.6.2 manually ?

I was anyway thinking of updating to the next version of .NET.

**Comment by fredgreco** [comment]
Any progress on the bug that causes a freeze when you right click on the status tray icon? You have to manually stop Soundswitch using Task Manager and then restart to get right click options to work.

**Comment by fredgreco** [comment]
Still experiencing the freezing behavior on right-click. Any progress on that bug?

**Comment by Belphemur** [comment]
Unfortunately my free time melt with the summer sun.

I've been able to reproduce the bug.

**Comment by fredgreco** [comment]
Any idea when this might be addressed?

**Comment by synchronos-t** [comment]
I believe I have the same issue as the original poster. SoundSwitch always freezes if I try to use the hotkey to switch audio source (I have changed it to Ctrl+Shift+F12). It _doesn't_ happen if I first open the tray icon menu (either the left-click audio select menu or the right-click settings menu). But it _always_ happen if I use the hotkey first after starting the application.

The tray icon still responds to the menu open clicks (i.e. the left-click or right-click to open the audio select menu or the settings menu), but both menus have an infinite revolving blue wheel (i.e. the "hourglass cursor") and do nothing on further clicks.

I'm using the latest version (3.15.1.15427). Would you like that I provided some other information about my system?

**Comment by Belphemur** [comment]
Hoo okay, this is giving me an idea on what could be causing the issue.

I'll have to rewrite the "caching part" I guess, something is wrong with 
the interface.

**Comment by fredgreco** [comment]
Any word on the bug? Nearly every time I boot up or wake from sleep, the Soundswitch tray menu cannot be clicked with the left or right mouse button. Either just causes it to hang and I have to force quit with Task Manager.

**Comment by Simssmith** [comment]
Unable to switch by using Alt-Ctrl-F11 .  It was working find few weeks ago.  I made no changes beside maybe Windows OS auto update.

**Comment by Belphemur** [comment]
I'm planning to rewrite the whole part of the program that does the 
switching.

I couldn't reproduce the bug, but there is clearly something that 
doesn't works as expected.

**Comment by Belphemur** [comment]
Can you try the latest beta?

https://github.com/Belphemur/SoundSwitch/releases/tag/v4.0

**Comment by ngalluzzo** [comment]
Still having the same issue in latest beta.

**Comment by Belphemur** [comment]
@ngalluzzo Do you have the freezing behavior describe here or simple the hotkeys don't respond ?

if it's the second one, please change the hotkeys to another set of keys.
