### ISSUE TITLE
SoundSwitch Exception: HotKey already registered

### ISSUE THREAD

**Issue by SalvorinFex** [Belphemur/SoundSwitch#201]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
This message pops up when I check the box for the Hotkey:
SoundSwitch Exception:  Impossible to register HotKey: Alt+Control+F11: True

![screenshot 2017-06-22 08 38 31_cr](https://user-images.githubusercontent.com/2433369/27446486-9b7c1d1c-5732-11e7-8831-1e99dd0c3ad0.png)

[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

https://dl.dropboxusercontent.com/u/30598156/SoundSwitch.zip

I have rebooted several times since installing and several updates since then as well.

![screenshot 2017-06-22 10 11 47](https://user-images.githubusercontent.com/2433369/27446662-46d67fea-5733-11e7-8d44-1a5a0d19663a.png)

**Comment by Belphemur** [comment]
Hello

This happens when the set of keys is already used by another program.
SoundSwitch has the least priority to register the hotkeys. 

Please change the hot keys to another desired combination.

**Comment by SalvorinFex** [comment]
Alright, is there a way to see what hotkeys are already assigned and to what?
I just pressed that combo and nothing happened.

**Comment by FireEmerald** [comment]
There is a tool called **Hotkey Commander**. Unfortunately this tool doesn't work with Windows 8 and later - SO DON'T USE IT.

But, there is another tool which can offer you this opportunity for Windows 8 and later. It's called **spyxx** - you can download it [here](http://mdb-blog.blogspot.de/2010/11/microsoft-spy-or-spyxx-for-download.html).

**How to use it:**
![spyxx](https://user-images.githubusercontent.com/1107939/27467187-88628ffa-57e0-11e7-8d59-ba532fb20649.gif)
Any further informations can be found here https://superuser.com/a/1204019/588961.

**Comment by IT6uru** [comment]
That gif is playing in my email. Mind blown.
