### ISSUE TITLE
Crash when not selecting a file for the custom sound notification option

### ISSUE THREAD

**Issue by mgregoireets** [Belphemur/SoundSwitch#202]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

I was looking at the notification options (Because the default notification option by sound is way too loud)
and selected custom sound option. It asked me for the sound file but i Cancelled it. Soundswitch then crashed and I cannot open it anymore
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1100492/SoundSwitch.zip)

**Comment by FireEmerald** [comment]
Update to the latest version of SoundSwitch, Download: https://github.com/Belphemur/SoundSwitch/releases

This issue was already fixed.
