### ISSUE TITLE
Can't install vcredist with the built in installer provided by soundswitch

### ISSUE THREAD

**Issue by edwwie** [Belphemur/SoundSwitch#203]
Hello, I can't install soundswitch since visual c++ 2015 won't install after being downloaded with the soundswitch installer.
I tried to restart my computer or download and install visual c++ without soundswitch (there was no problem with installing visual c++)  but the problem won't go away... here is the error:

![soundswitch_v3 15 0 37396_release_installer tmp_2017-06-27_18-14-08](https://user-images.githubusercontent.com/29735446/27598040-8ce02f10-5b64-11e7-9490-9e2a0ea8032a.png)

I'm on w10.

**Comment by diegose** [comment]
Same error here. This is Windows 10 with Creators Update, using SoundSwitch_v3.15.0.37396_Release_Installer.exe

**Comment by diegose** [comment]
Additional information: I downloaded the redist from Microsoft, and wasn't able to install it because it is already installed.

**Comment by FireEmerald** [comment]
@edwwie and @diegose could you please provide us the following information:

In your registry (open it using `[WIN] + [R]` -> "`regedit`" -> **Ok**):

If your operating system is an 64-bit system search for:
- `SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64` -> Value of keys `Installed` and `Bld`.
- `SOFTWARE\Wow6432Node\Microsoft\DevDiv\vc\Servicing\14.0\RuntimeAdditional` -> Value of keys `Install` and `Version`.

else search for:
- `SOFTWARE\Microsoft\VisualStudio\14.0\VC\VCRedist\x86` -> Value of key `Installed` and `Bld`.
- `SOFTWARE\Microsoft\DevDiv\vc\Servicing\14.0\VC\VCRedist\x86` -> Value of keys `Install` and `Version`.

**Comment by diegose** [comment]
Thanks for your response, @FireEmerald. 64-bit system here:
```
SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64
  Installed: 1
  Bld: 23026
SOFTWARE\Wow6432Node\Microsoft\DevDiv\vc\Servicing\14.0\RuntimeAdditional
  Install: 1
  Version: 14.10.25008
```

**Comment by edwwie** [comment]
64 bit system here too but I don't have the same path...

`SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x86`
 ` Installed: 1`
 ` Bld: 24215`

And I do not have any `14.0` in


`SOFTWARE\Wow6432Node\Microsoft\DevDiv\vc\Servicing\14.0\RuntimeAdditional`
`SOFTWARE\Microsoft\DevDiv\vc\Servicing\14.0\VC\VCRedist\x86`

**Comment by Belphemur** [comment]
@FireEmerald 

To explain everything about the code of the installer.

VC Redist in the registry can be at two different places depending of the version installed.
If it's the release version, we'll find the information into the **SOFTWARE\WOW6432Node\Microsoft\VisualStudio** key if it's the developer version (installed with Visual Studio) it will be in the **SOFTWARE\Wow6432Node\Microsoft\DevDiv\vc\Servicing** key.

The code of the installer (now) check first the default path of the release version, and if it doesn't find it there, fallback to the development path.

# Answer to questions
 * The space isn't needed.
 * Exit is like "break/return", to stop the current processing. In case of a procedure, it returns from it. 
* It doesn't compare the "14" but the build number, it's only used if the normal version of VC redist isn't installed but only the developer one.
