### ISSUE TITLE
SoundSwitch won't launch

### ISSUE THREAD

**Issue by JJKallday** [Belphemur/SoundSwitch#205]
I downloaded SoundSwitch a few weeks ago and had it working perfectly. Recently, I plugged my headphones into a different USB port than I had been using, and SoundSwitch stopped detecting them. I tried to open SoundSwitch to reconfigure things, but it will no longer launch. I can still switch between my desktop speakers and my TV speakers with SoundSwitch, but the program won't launch and my headphones are never switched to. Uninstalling and reinstalling does nothing; my hotkey for playback device switching is still active after reinstall, but my headphones aren't detected. I can get my headphones to work if I set them as the default playback device through Windows.

**Comment by Rohaq** [comment]
Try the following:

1. Close down SoundSwitch.
2. Press Windows key + R.
3. Type "%AppData%" (without the quotes) and press Enter. This should open a Windows Explorer window.
4. Delete or move the SoundSwitch directory in here. This will delete your current SoundSwitch configuration.
5. Try starting SoundSwitch again. You'll need to set it up again, but this should force it to redetect your devices.

Does that resolve it?

**Comment by JaskiratSingh69** [comment]
Thanks bro, that really helped, I created a new account just to thank you
