### ISSUE TITLE
Add ability to link output/recording devices

### ISSUE THREAD

**Issue by Rohaq** [Belphemur/SoundSwitch#206]
Right now you can select devices, and switch with individual hotkeys. There is an option to switch the recording device when you switch your output device, but there's nothing that links certain devices to one another.

For example, I might like to link my headset microphone to my headset, for obvious reasons, or switch to my headset for output whenever I use an external microphone to avoid the microphone picking up audio from speakers.

**Comment by Rohaq** [comment]
As a note, I might actually suggest rejecting this in favour of #207, since a proper profiling system would essentially implement this too.

**Comment by Belphemur** [comment]
@Rohaq That what I was thinking too.
