### ISSUE TITLE
Add device profiles tab, and add new hotkey combo to switch between them

### ISSUE THREAD

**Issue by Rohaq** [Belphemur/SoundSwitch#207]
Another suggestion as an alternative to linking devices: Add a Device Profiles tab which specifies particular device setups, so you could add a profile for switching to your headset for both headset output and recording, another for headset output and dedicated microphone for recording, etc.

You could even specify changes to device volumes, e.g. add a profile for external speakers for output, and mute any recording devices to avoid them picking up the audio.

There could be a hotkey for switching profiles, or hotkey combos could be assigned to individual profiles for specific quick switching.

Device profiles could also be displayed in the systray menu for the purpose of quickly switching between them too.

**Comment by michaelschnyder** [comment]
would also like to add the possibility to change profiles based on system/app state like
* In a conference with (Skype/Skype for Business)
* having a powerpoint presentation
* ...

**Comment by Moinax** [comment]
This feature is very important in my case, because I use a SteelSeries Artic 7 headset and it uses 2 playback devices at the same time, one for games and the other for chats. This enable us to handle volume separately for VOIP during gaming.

**Comment by Cecchellone** [comment]
This feature could be very usefull to me too.
For example you can enable a **"not-always-connected"** audio device without have to go through a dead output everytime _(for example, bluetoorh devices, USB headphones etc)_
So it's very important you can shortcut **even devices not selected** in the cycling menù to skip them in the normal switching.
