### ISSUE TITLE
Possible to make a portable install?

### ISSUE THREAD

**Issue by alystair** [Belphemur/SoundSwitch#208]
Is there a way to make this a portable install? Been using an AHK script until now but this app is a lot more consistent.

**Comment by Belphemur** [comment]
Can you try this version and activate the portable mode?

Tell me if it works as intended.
[SoundSwitch_v3.15.1.15427_Beta_Installer.zip](https://github.com/Belphemur/SoundSwitch/files/1203245/SoundSwitch_v3.15.1.15427_Beta_Installer.zip)

**Comment by alystair** [comment]
Seems to work fine - tried moving folder contents to another location and it also worked. At the very least you need to be able to specify install location in the installer.

Would be cool to simply have an executable that you can place wherever, and it'd run without an installer. You'd have to somehow include all the extra files within the executable itself. The only external file is normally a .ini for config. Unsure of technical scope... Probably not worth your time?

**Comment by Belphemur** [comment]
I'd rather work more on the installer.

The program is not a single executable as some other application. There 
are some dll that are expected to be in the same folder, and also couple 
of other file. The configuration is always stored in your user directory.

I'll need to find a way to let the user choose where to install it and 
also disable the need for admin right ... Mmmh, I guess I'll need to 
split the installer to have a portable version and a normal version.

**Comment by alystair** [comment]
TBH this application is great enough for me to just keep an installer exe in my general tools folder and I'll simply install it wherever needed. Thanks for creating this amazing application.
