### ISSUE TITLE
Show volume slider like the volume system icon

### ISSUE THREAD

**Issue by HekutoruMAC** [Belphemur/SoundSwitch#209]
Activate the volume slider of the system icon, maybe through middle click, to become a full replacement of it by centralizing all sound functions. Thanks.

**Comment by FireEmerald** [comment]
Could you clearify what you exactly mean with "a full replacement of it by centralizing all sound functions."? Give some examples.

**Comment by HekutoruMAC** [comment]
If volume up, down and mute were integrated, there'd be no need for the system icon.

![image](https://user-images.githubusercontent.com/20937237/40231657-4fd1f8c0-5a72-11e8-9480-0bf2dcf54adc.png)

**Comment by FireEmerald** [comment]
SoundSwitch is for switching devices. I don't think it makes much sense to re-invent the wheel and duplicate controls, which already exists and work well (the shown volume sliders).
