### ISSUE TITLE
Invalid sound file make SoundSwitch crash

### ISSUE THREAD

**Issue by ripsky4501** [Belphemur/SoundSwitch#210]
Hello,

Love this program, very useful. Unfortunately, it's started crashing for me. I use the hotkey to switch playback device and it crashes. I've uploaded the crashlog and whole folder. 

[SoundSwitch-crashlog-29_8_2017.zip](https://github.com/Belphemur/SoundSwitch/files/1259488/SoundSwitch-crashlog-29_8_2017.zip)
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1259496/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Hello @ripsky4501 ,

Thank you for the bug report and the full crashlog, it's very helpful.

it seems the SoundFile you chose is not recognized as a valid one by SoundSwitch. Can you try with a different file ?

File used: C:\Users\James\OneDrive\Sounds\silence-1sec.mp3 

If you want to disable the sound, you can simply do cancel when the Sound dialog is open.
