### ISSUE TITLE
Application could not be downloaded

### ISSUE THREAD

**Issue by Techassi** [Belphemur/SoundSwitch#211]
Hi, I recently reinstalled SoundSwitch (version 3.15.1.15427). 
When booting and logging into Windows, SoundSwitch tries to start automatically, but fails. I displays a small window stating `"Application could not be downloaded"` (I can provide a Screenshot aswell as logs [they are in German]). 
Manually starting SoundSwitch works fine. I think there is something worng with an update service searching for new updates.

**Comment by Belphemur** [comment]
Hello @Techassi,

Please see issue #113 

You still have a left-over of the previous version (2.X) of the application. On the other issue I explain how to clean it up.

**Comment by Techassi** [comment]
Thank you. I cleaned it up now.
