### ISSUE TITLE
Soundswitch crash on startup

### ISSUE THREAD

**Issue by Monochr0me** [Belphemur/SoundSwitch#214]
[SoundSwitch-crashlog-6_9_2017.zip](https://github.com/Belphemur/SoundSwitch/files/1282738/SoundSwitch-crashlog-6_9_2017.zip)

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1282739/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Can you describe what you were doing when this happened ?

**Comment by Monochr0me** [comment]
I did literally nothing. It crashed right after I booted into Windows. After restart all was fine. It happend few times.

**Comment by Belphemur** [comment]
Can you try the latest beta?

https://github.com/Belphemur/SoundSwitch/releases/tag/v4.0
