### ISSUE TITLE
Was able to "capture" output device in Firefox until last week

### ISSUE THREAD

**Issue by bcook75** [Belphemur/SoundSwitch#215]
I was using version 3.15.1.15427 on Windows 10 without issue until about a week ago, when I started getting the "Cannot download application" error. I found how to fix that, but in the process I uninstalled and reinstalled Soundswitch.

Prior to starting to see this error, I found that when I started streaming from xFinity in Firefox in its own window on a separate monitor (TV), the sound routing would be "sticky" once the streaming had begun. I could change the routing in Soundswitch to have other things play in my main computer speakers while the xFinity stream would continue on its TV speakers until I stopped the stream. I liked this "feature/bug" a lot.

Now, however, whenever I switch the output, the xFinity stream also switches immediately. I do not like this as much. Has something changed, or is there a setting I've missed that was making this work as I would prefer?

**Comment by Belphemur** [comment]
Hello Bcook75,

This behaviour is directly dependent on the application.

# Example

Most game won't switch the audio once started as they are binding to the device at launch.

# Current case hypothesis
It would seem Firefox was doing the same for the streaming part but changed that behaviour in a later version (or Windows changed something or the new driver of your xFinity has been updated... always possible).

You could try to disable the switch of Communication device, but I doubt this would change it ...
