### ISSUE TITLE
App Crash with MP3 file used for Banner Notification (works fine in Custom Sound Notification)

### ISSUE THREAD

**Issue by snakecase** [Belphemur/SoundSwitch#218]
But it works when it's set to "Customized notification sound" with the same audio file.
Tried running as administrator, placing the audio file to other directories and changing its name.

Thank you for your work anyway!

**Comment by Belphemur** [comment]
Hello,

For what I can see from the dump, the file: 
C:\Users\DELETTHIS\Desktop\123.mp3 isn't a valid MP3 or WAV file. The 
application cannot play it.

**Comment by snakecase** [comment]
Wait but it works fine as I noted in OP. I mean the sound plays when I switch outputs while the notification is set to "Customized notification sound".

**Comment by Belphemur** [comment]
Ho right, I misread, when in Custom sound in work, in Banner mode it 
doesn't.

This is a real bug. The system used to play the sound is different 
between those 2 notifications systems.
