### ISSUE TITLE
Locking up on switch since Fall Creator's Update

### ISSUE THREAD

**Issue by charlesroper** [Belphemur/SoundSwitch#219]
Since updating to Windows 10 Fall Creator's Update (version 1709 / build 16299.64), SoundSwitch locks up when switching. I see the banner, but it doesn't disappear and if I move my mouse over it, I get the spinning busy cursor. If I try and use the tray menu, I also get the busy cursor. I have to end the task in the Task Manager to restart.

It's only the Banner notification that seems to have problems. Other notification methods seem fine.

Here are my logs and config files along with a couple of screenshots to help illustrate the nature of the crash: [SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1490499/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Hello,

Was it already the case with 3.15.1 ?
Or is it only with 3.15.2 ?

**Comment by Schyfis** [comment]
I have the same problem, but I haven't done the Creator's Update yet (downloading it now actually).
I'm on Windows version 1607, build 14393.1198 and have the exact same issue, although it's intermittent. Maybe there's something else in common with our systems?

As @charlesroper describes, sometimes when I switch, the banner will show up and just stay there. The tray context menu also locks up and mousing over either one gives a busy cursor. This happened for me with 3.15.1 and it continues to happen with 3.15.2. Let me know if I can provide any additional info.

**Comment by Belphemur** [comment]
Can you try the latest beta?

https://github.com/Belphemur/SoundSwitch/releases/tag/v4.0

**Comment by charlesroper** [comment]
Hi, so sorry for not responding sooner. It seems Github isn't sending me notification emails, even though I'm subscribed to this thread. They're not anywhere to be found - not even in spam. Weird.

Anyway, I've just tried the beta and it's unstable for me. I uninstalled the old version and installed the new **without** removing the existing settings. This allowed it to start, but on trying to go to settings, it crashes. I'll attach the crash log.

So I tried reinstalling, this time removing the existing settings. Now it just crashes on start and won't load at all.
[SoundSwitch-crashlog-28_11_2017.zip](https://github.com/Belphemur/SoundSwitch/files/1510692/SoundSwitch-crashlog-28_11_2017.zip)

**Comment by Belphemur** [comment]
Hello

Thanks for the crashlog.

Can you attach a screenshot of the Windows menu listing your different 
audio devices ?

That would be really helpful.

**Comment by charlesroper** [comment]
I'm not 100% sure which menu you're after, so I've taken a guess at the following windows. Let me know if that's not what you're after.

![2017-11-28_17h23_02](https://user-images.githubusercontent.com/176/33334210-099479e2-d461-11e7-8978-5af2ee9f54f2.png)

![2017-11-28_17h23_23](https://user-images.githubusercontent.com/176/33334216-0c23a8c2-d461-11e7-803f-769c97ed8acf.png)

**Comment by Schyfis** [comment]
I also installed the beta without removing the existing settings, and no issues for the past two days. I can access the settings just fine too.
I'll continue using it and report back if there are any issues!

**Comment by Belphemur** [comment]
@charlesroper Great, I think I found a fix.

I'll try to build another beta today to give it to you for trying it out.

@Schyfis Glad to hear about that! Seems the rewrite was the right course of action.

**Comment by Belphemur** [comment]
@charlesroper Can you try this version ?

https://github.com/Belphemur/SoundSwitch/releases/download/v4.0/SoundSwitch_v4.0.6542.14100_Beta_Installer.exe

**Comment by charlesroper** [comment]
I've installed it successfully with no crashes. I'll use it and let you know if there are any problems. Looking good so far, though. 👍
