### ISSUE TITLE
KeepAlive feature request

### ISSUE THREAD

**Issue by opus-2** [Belphemur/SoundSwitch#221]
Is it possible to implement a Keep-Alive feature in SoundSwitch, by sending a little signal evey now and then, or even a constant silent signal? It would be very useful for those devices that shut themselves into stand-by mode, when they detect no signal for a while. SPDIF users would surely benefit from that, but I have an analog 5.1 system with this behaviour, so it would be great to see this feature in analog land as well.

**Comment by Belphemur** [comment]
Hello

It has been asked before.

The scope of the application doesn't cover this need as the core feature is about changing audio device, not producing sound.

I heard that there is an old *unofficial* version of SoundSwitch that is doing that, I would advise you to look for it.
