### ISSUE TITLE
Menu shows on the wrong screen with dualscreen and using a vertical taskbar

### ISSUE THREAD

**Issue by jb-boin** [Belphemur/SoundSwitch#222]
I am on Win10, on a dual screen setup with my main screen on the right and the taskbar put in vertical position on the left of the screen.

When i do a right click on the SoundSwitch icon, the menu is displayed on the second screen (which in my case is my TV which is not directly on my desk and not always On) instead of the right one.
It has been happening for quite some time so its not a new bug.

On this example, i did a right click on the icon on the main screen and it shows on the other:
![sondsswitch_menu_bug](https://user-images.githubusercontent.com/4568403/33186689-c0c5111e-d08b-11e7-82eb-5e409f3172f3.jpg)

If i make my taskbar larger than the menu, it will show on the right screen.

**Comment by Belphemur** [comment]
Hello

Unfortunately, it's a known issue. It's hard to resolve it has the displaying of the menu is done by the framework and not our "code".
