### ISSUE TITLE
4.1 crashes on start. Can't inspect log zip before send

### ISSUE THREAD

**Issue by serentilla** [Belphemur/SoundSwitch#227]
Hi, 4.1 crashes every attempt to start. I've reverted to v3.15.0.37396 which works. 

When it crashes it wishes to send a zip of the logs which it claims exists in %appdata% however, there is no zip file there, so I can't inspect it to see what information is being sent. Had a look in %temp% but nothing there either.

The actual logs in %appdata%\SoundSwitch\Logs (neither txt or tx1) do not include any exceptions but do contain some minor identifying information. 

Good practice would be to allow the user to inspect the logs before offering to transmit them. I don't know why the zip file doesn't exist at that point, perhaps it is created once you click the send button.

Thanks
Ian

**Comment by serentilla** [comment]
Regarding the crash, I got the source, had a few issues building so had to change some stuff. Once I eventually got it to build it worked correctly. 

The changes I had to make to build were: 
1) Switch two projects from win32 target to x64 (The c++ ones)
2) switch SoundSwitch project to Any CPU (I think)
3) Retarget C++ projects to Win 10 SDK as I don't have the 8.1 sdk installed

Probably not much help but I thought I'd mention it :)

**Comment by Belphemur** [comment]
Hello Ian,

To answer your questions:
1. SoundSwitch doesn't transmit any information on crash. It only creates the zip file for easy reporting. When you click OK, the program will open an Explorer window where the zip file should be for you to report it to me (if you decide to do so). 
2. The zip file contains the whole %appdata%\SoundSwitch folder, nothing more, nothing less. It's not password protected, which mean you can easily check its content. May you which to open the binary logs, you need to use: [TracerX](https://tracerx.codeplex.com/releases/view/631541) to open them.

About building SoundSwitch:
1. Not needed, you have the different solutions that are setup. Only select Release/x64 in your case. Or use the Make.bat file that will build everything for you, even the installer.
2. As the C++ deps are architecture dependent, there is no point of building SoundSwitch as AnyCPU.
3. After some testing I discovered that using the Win10 SDK mean losing support of Windows 7. Hence the choice to stick with SDK 8.1. Also the SDK 10 doesn't bring any interesting feature for the use I have.

Now about your crash:
I would need to know more about your setup.
Can you download this: https://github.com/Belphemur/AudioEndPointLibrary/releases/tag/v4.7.1 (x64 version) and screenshot the result of the command line ?
This tool will simply list all the audio device (and their ids). Also can you send the full content of your %appdata%\SoundSwitch ?

If you don't want to send the zip publicly, you can use my contact form here:
https://www.aaflalo.me/contact/

**Comment by Belphemur** [comment]
BTW can you try this version for me ?

http://soundswitch.aaflalo.me/beta/SoundSwitch_v4.1.6546.26651_Beta_Installer.exe

I included a possible fix for your issue.

**Comment by serentilla** [comment]
Sure, I'm not around until tomorrow though so I've booked some time after work :) 

On 3 December 2017 19:50:21 GMT+00:00, Antoine Aflalo <notifications@github.com> wrote:
>BTW can you try this version for me ?
>
>http://soundswitch.aaflalo.me/beta/SoundSwitch_v4.1.6546.26651_Beta_Installer.exe
>
>I included a possible fix for your issue.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/227#issuecomment-348809039

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Belphemur** [comment]
I'm going to release 4.2 that has the fix.

Another user has been able to generate a crashlog, I'm pretty sure you have the same issue. (Race condition between 2 threads).
I'll close this issue. May 4.2 not resolve it, please don't hesitate to reopen this :)

**Comment by serentilla** [comment]
Hi Antoine, so sorry I didn't get to send you my logs. Real life issues
unfortunately. 4.2 does appear to have solved the problem, so well done.
Thank you again.
--
  ian bradley
  ianbradley@operamail.com



On Sun, 3 Dec 2017, at 11:54 PM, Antoine Aflalo wrote:
> I'm going to release 4.2 that has the fix.


> Another user has been able to generate a crashlog, I'm pretty sure you
> have the same issue. (Race condition between 2 threads).>  I'll close this issue. May 4.2 not resolve it, please don't hesitate
>  to reopen this :)> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/Belphemur/SoundSwitch/issues/227#issuecomment-348831105
