### ISSUE TITLE
Desktop shortcut is generated on startup

### ISSUE THREAD

**Issue by chris579** [Belphemur/SoundSwitch#228]
Every time SoundSwitch starts it generates a desktop shortcut. When deleting it it will be there again next restart.

**Comment by Belphemur** [comment]
Hello,

When you installed the first time SoundSwitch, you have left the checkbox "Create Desktop shortcut" checked. 

When it updates, it reuse that information.

To resolve the issue, simply install again the latest version, and uncheck the box "Create desktop shortcut". The shortcut won't get created at each update.
