### ISSUE TITLE
crashes on start

### ISSUE THREAD

**Issue by stormssc** [Belphemur/SoundSwitch#23]
The program worked fine upon installation, but the next day it won't start. Error log:

http://speedy.sh/AQv37/Logs.zip

TracerX: Log file opened at 2015-09-02 06:56:48.  FullFilePolicy = Wrap, Use_00 = False, MaxGrowth = 1 MB, AppendIfSmallerThan = 0 1, initial size = 3.
06:56:55.513 Fatal <null> SoundSwitch+Program.HandleException Program.HandleException entered
06:56:55.671 Fatal <null> SoundSwitch+Program.HandleException    Exception OccuredException type: System.IndexOutOfRangeException
Message: Index was outside the bounds of the array.
Source: SoundSwitch
StackTrace:
   at SoundSwitch.Framework.AudioDeviceIconExtractor.ExtractIconFromAudioDevice(AudioDeviceWrapper audioDevice, Boolean largeIcon)
   at SoundSwitch.UI.Forms.Settings.PopulateAudioList()
   at SoundSwitch.Program.Main()

06:57:04.088 Fatal <null> SoundSwitch+Program.HandleException Program.HandleException exiting

**Comment by Belphemur** [comment]
Thanks for the bug report. It's a weird bug that I don't encounter. I'll make a workaround and release a new version.

**Comment by stormssc** [comment]
wow, you do react fast. I'll keep checking for updates :) thanks!

**Comment by Belphemur** [comment]
Can you install the last release 3.4.1 and tell me if it resolve your issue ?

**Comment by stormssc** [comment]
Looks like 3.4.1 works fine - I have also rebooted my PC to see if it starts with windows and it works fine too. Good job :)

**Comment by Belphemur** [comment]
Could you attach a screenshot of your settings menu. 
I'm curious which of the audio device doesn't have a proper icon.

On 2 September 2015 19:08:31 EEST, stormssc <notifications@github.com> wrote:
>Looks like 3.4.1 works fine - I have also rebooted my PC to see if it
>starts with windows and it works fine too. Good job :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/23#issuecomment-137146474

-- 
Best Regards, 
Antoine Aflalo
