### ISSUE TITLE
[Enhancement] Mirror outputs

### ISSUE THREAD

**Issue by evilC** [Belphemur/SoundSwitch#230]
It would be nice to be able to duplicate outputs. Sure, you could use VAC, but it is a bit overkill. Then there is the "Stereo Mix" technique, but this only works if the main output is the onboard audio.  
Associated hotkeys would be nice, and it would also benefit from #207 (ie be able to configure a profile which sets device x as default, and mirrors to device y)

**Comment by FireEmerald** [comment]
First of all thanks for your feature request. As nobody commented until now and mirroring a output has nothing to do with switching output devices, which is what SoundSwitch is intended for, i close this feature request for now.
