### ISSUE TITLE
Windows 10 - Notifications don't seem to be working

### ISSUE THREAD

**Issue by formerghostlyform** [Belphemur/SoundSwitch#231]
I've tried several different options for notifications and they don't seem to be showing at all with the latest update.  Not the biggest of deals because Soundswitch seems to be switching between sources more reliably and FASTER than before, so that's awesome.  Maybe I don't want notifications. :)

**Comment by Belphemur** [comment]
Hello @formerghostlyform,

Which notification are you using?  

If you're coming from an older version, it's possible you have the old default, Windows notification. On windows 10 that mean it will appear in the bar on the right.

I advise to change it to banner. It's a nice little banner that opened on the top left corner of your screen and stays for a couple of second.

**Comment by formerghostlyform** [comment]
PEBKAC error.  Sorry to bother you.  Switched it to banner. I tried it before but didn't notice it in the upper left because I was looking in the bottom right... I'm a moron (4k 32" screen and old eyes). Also figured out that somehow my machine had switched to quiet hours and was stuck there.  Turning -that- off restored the regular Windows toast-style notifications.  Might want to remember that one if you have some other idiot complaining about this in the future (besides this idiot).

Thanks and you're FAST at responding. Wow. :)
