### ISSUE TITLE
SoundSwitch is crashing frequently

### ISSUE THREAD

**Issue by brianazick** [Belphemur/SoundSwitch#232]
SoundSwitch is crashing frequently for me. I have not noticed a pattern in the crashes.
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1537542/SoundSwitch.zip)
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1537544/SoundSwitch.zip)

[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

**Comment by Belphemur** [comment]
Can you give more details?

Does it crash when you're stopping it?

There is nothing really telling in your logs.

**Comment by brianazick** [comment]
It doesn't seem to crash when I am stopping it or switching audio devices. Everytime it has crashed I was using a Bluetooth speaker while also having headphones attached to the computer and registered in SoundSwitch but not in use. I am not sure if there is any causality to this crash that can be found and it's not a big problem, but I figured you might like to be aware of the issue.

**Comment by bobflorian** [comment]
SoundSwitch crashes nearly everytime for me when I log on to my computer remotely via RDP  (Win10)

**Comment by Belphemur** [comment]
Can you open a different issue about RDP ?

This a different issue.

Also, in that new issue, state the version of SoundSwitch you're using.

**Comment by brianazick** [comment]
I have been observing the crashes to see if I could find a pattern or common things that were happening and I noticed that all of my four crashes today occurred an hour and fifty minutes after the previous crash. Does this time interval have any relevance to you?

**Comment by Duckle29** [comment]
I too have very regular crashes. I haven't timed them, but 2h sounds about right. As far as I can tell it's not tied to any actions.

Just as if on a clock, and windows restarts it.

**Comment by VVingnut** [comment]
I'm getting frequent crashes too, after which Windows restarts the APP. Maybe once an hour or so.  Not sure if began when I was experimenting with the EQUALIZER APO app (which I've now uninstalled because it was torpedoing Discord).  

I think it was stable before then.

**Comment by FireEmerald** [comment]
If you break your sound using any 3rd party app this isn't a SoundSwitch issue. If Discord was affected it is obvious that also SoundSwitch may affacted by this 3rd party application.
