### ISSUE TITLE
Error Message when starting SoundSwitch

### ISSUE THREAD

**Issue by randix4** [Belphemur/SoundSwitch#233]
When I start SoundSwitch, I get a dialog box that says:

Impossible to register Hotkey: Alt+Control+F11: True

?????????

**Comment by Belphemur** [comment]
Weird, it shouldn't look like that.

Anyway, it means that the hotkey is already used. Go in setting and choose another set of keys.

**Comment by pkmnct** [comment]
This notification started showing up for me after updating from 4.X to 5.0.1.

![image](https://user-images.githubusercontent.com/8972556/73382966-7ee9ca80-4296-11ea-9366-837d6db42efb.png)

I wasn't using the hotkey shown in the error prior to the update. The tray icon disappears after the notification, so I wasn't able to open settings to change it. Re-installing with the _Remove any existing settings_ option checked got the app working again, and I was able to successfully change my hotkey back to what I had before.
