### ISSUE TITLE
Default device randomly changes

### ISSUE THREAD

**Issue by Technolink** [Belphemur/SoundSwitch#236]
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1619410/SoundSwitch.zip)

Every now and then I see the banner notification that my default device has changed, then immediately I get the notification again, and the default is set back to what it started on. If I am listening to something the audio will cut out for a second.

At first I thought this might be because my headphones are possibly disconnecting/reconnecting sometimes, but after exitingSoundSwitch I do not experience the issue anymore.

Thanks for the software, this is one of my must-installs on all new PCs!

**Comment by Belphemur** [comment]
Hello,
SoundSwitch doesn't automatically change the default device, but
Windows does at boot time.
The notification is directly plugged in the IMMNotificationClient of
Windows.In other words, I'm asking Windows to tell SoundSwitch when the
default device change and then notify the user accordingly.
I have the same behaviour as you when starting the computer or
returning from sleep/hibernation.I would guess Windows is listing the
audio devices at boot time, and re-enable automatically the last
default. 
Nothing I can do about this.
