### ISSUE TITLE
speakers humming on laptop

### ISSUE THREAD

**Issue by pdoig** [Belphemur/SoundSwitch#237]
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1630040/SoundSwitch.zip)

I installed Soundswitch v4.2 to swap between laptop speakers & connected tv . it switches between devices ok but when on speakers if I play any audio I get a bad humming sound coming through speakers which remains even after closing audio file. It only stops when I change sound device to the tv

Hope you can help
Thanks
Phil

**Comment by Belphemur** [comment]
Do you have the power supply connected when you have the humming sound ?

This sound more like a grounding problem of your speaker than an issue with SoundSwitch :)
