### ISSUE TITLE
Different Hotkey per device?

### ISSUE THREAD

**Issue by Shlink** [Belphemur/SoundSwitch#238]
Thanks for this great utility!
Any possibility of setting a different hotkey for each device? I have 4 different speaker setups for different scenarios / locations.
Sometimes I can not see my monitor while I'm switching.
It would be marvelous to set up a different hotkey for each device, to not have to cycle through when I'm switching.
CTRL + ALT + F9 = Desk
CTRL + ALT + F10 = Couch
CTRL + ALT + F11 = Headset
CTRL + ALT + F12 = Bluetooth Headphones
Etc..

**Comment by FireEmerald** [comment]
> Sometimes I can not see my monitor while I'm switching.
If you play anything while switching or use any sound notification of SoundSwitch you don't need to see any notification because you will hear which device is currently outputting something or am i wrong?

**Comment by Shlink** [comment]
> If you play anything while switching or use any sound notification of SoundSwitch you don't need to see any notification because you will hear which device is currently outputting something or am i wrong?

Yes, you are correct that I do not need to see my monitor to know which device it is switching to, but it is still inconvenient. Only some of the devices can be heard from a given location (ie not headphones) and there is a bit of a delay before sound comes out.

I'm not saying that it does not work, but rather asking if there's a possibility of improved usefulness (For my scenario at least)

Thanks

**Comment by Belphemur** [comment]
I understand the idea, but I'd rather implement the idea of profile described in #207 

I consider this request as a duplicate.
