### ISSUE TITLE
SoundSwitch does not automatically start with Windows 10

### ISSUE THREAD

**Issue by Skairkrow** [Belphemur/SoundSwitch#240]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
SoundSwitch runs great but doesn't "Automatically" start when I boot up Windows 10. the Box is checked in the settings. I have  tried un-checking it, restart, then rechecking the box. still no joy. 

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1701247/SoundSwitch.zip)

**Comment by Skaronator** [comment]
Works fine for me. Just installed Windows 10 LTSB like an hour ago and just setted up SoundSwitch with Autostart and it works.

**Comment by FireEmerald** [comment]
As a workaround do the following:

- Press [WIN] + [R].
- Write `shell:startup`, enter.
- A folder should popup. Inside this: Create a shortcut to the SoundSwitch.exe, done.

**Comment by Skairkrow** [comment]
There’s already a shortcut to SoundSwitch in the start up folder. I checked and it does point to the app in the “Program Files” folder. And SoundSwitch still does not start with Windows 10.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by FireEmerald** [comment]
Does SoundSwitch start if you try to start it via a click onto the shortcut?

**Comment by Skairkrow** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Belphemur** [comment]
When you check the checkbox to start with windows, SoundSwitch setup in the registry this key:

`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\SoundSwitch`

Can you check that you have it ?

Do you use any tool to control what start with your computer ?

**Comment by Skairkrow** [comment]
I opened Regedit and made my way along the path you set. Found the Soundswitch folder. Clicked on it and it opens to “(Default)  REG_SZ     (value not set)”

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Skairkrow** [comment]
So did you give up on me?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by FireEmerald** [comment]
Please read the thread via your browser and not via email. You didnt give any answer to my edited questions from above.

**Comment by Skairkrow** [comment]
The only "tool" I used that might have messed things up was Samsungs SSD Magician. But that is no longer installed and hasn't been for some months now. (actually closer to a year ago I uninstalled it) I went into MSconfig and its set on Normal Start-Up, when I look at "startup" with-in System Configuration, It opens Task Manager which shows SoundSwitch as Enabled and under Startup Impact as "Not measured". And yet it is not running. when I right click on the Line that has SoundSwitch in it and go to "Open file location" and click on that it takes me to SoundSwitch.exe. When I click on that SoundSwitch starts. So it is pointing to the proper .exe. Different issue But maybe the same thing is causing both. I uninstalled Samsungs Magicain because after I installed it my Computer would no longer Hybernate. I uninstalled it but my computer still does not hibernate. So it may have made some changes that did not roll back upon Uninstallation.

**Comment by FireEmerald** [comment]
Procedere the following steps to track your issue down:

1. Create a new text file and place it in: `C:\test.bat`
2. Open it with the editor and add:

```
echo hello world!
pause
```

3. Start the `test.bat` file it should open a console window showing "hello world!" (and some more lines, press any key to close the window).
4. Create a shortcut of the `test.bat` file.
5. Move the **shortcut** to `shell:startup` (`WIN` + `R`)
6. Double click onto the shortcut, the same console window must popup.
7. Restart your pc, the same console window must popup again on startup automatically.
8. **Replace** the content of your `test.bat` file with the following lines: (the path may variy)

```
echo "Starting SoundSwitch..."
start /d "C:\Program Files\SoundSwitch" SoundSwitch.exe
pause
```

9. Restart your pc, a console window must popup, showing: "Starting SoundSwitch..." and SoundSwitch must be started.

Tell us what which steps are working and which do not work.

**Comment by Skairkrow** [comment]
ALL the steps worked. SoundSwitch starts with the test.bat. Wonder why I need that work around..  8(
I know its not SoundsSwitch. I know its my system. and I'm betting its that Samsung Magician I ran a year ago.

**Comment by FireEmerald** [comment]
At least now you have a good workaround ;) Remove the line `pause` and edit the properties of your shortcut and set **Run: Minimized** then the snipplet should do what you want.

**Comment by Belphemur** [comment]
I would bet on a optimization tool that disable the autostart of windows.

Like "speed up your system" etc ...

**Comment by Skairkrow** [comment]
I did run "Advanced SystemCare" by IOBIT last year. ran it, uninstalled it last June.
