### ISSUE TITLE
Unable to set shortcut

### ISSUE THREAD

**Issue by Techassi** [Belphemur/SoundSwitch#241]
Hi SoundSwitch Team,

I recently switched to a new PC and installed SoundSwitch. I wanted to use my old shortcut, so I tried to set it.

My preferred shortcut is: `CTRL+ALT+F3`
SoundSwitch turns that into: `CTRL+ALT+`

It won't let me insert the `F3` part.

_Additional information:_

- OS: Win 10 (1079)
- SoundSwitch: 4.2.6546.34142

**Comment by Belphemur** [comment]
Hello @Techassi 

Can you try with a different function key ?

It's possible this shortcut is already used by another application (I know Intel Graphic Utility bind a lot of the CTRL+ALT+FX)

**Comment by Techassi** [comment]
Hey @Belphemur 

I tried many different combinations, e.g.:
- `CTRL+FX`
- `SHIFT+FX`
- `ALT+FX`

I tried` F1`, `F2`, etc for each combination from above. One more thing: the font color turns red (I guess because my shortcut is incomplete)

**Comment by Belphemur** [comment]
Usually it means it couldn't register the hot keys.
Try something like CTRL+ALT+5 (like numlock 5) to see if it lets you do
that.

**Comment by Techassi** [comment]
Ok I will try you suggestion and will report back!

**Comment by Technetium1** [comment]
@Belphemur Why is there `api_key` in your [comment](https://github.com/Belphemur/SoundSwitch/issues/241#issuecomment-369966817) footer above? 😲

**Comment by Belphemur** [comment]
If you check the mails sent by GitHub, you'll see this JSON in all of
them.
It's the inbox markup for having direct action in Gmail/Inbox.
The API_KEY doesn't belong to me.

**Comment by Techassi** [comment]
I now tried to set my shortcut to something like `CTRL+ALT+NUMPAD5` and it worked flawlessly. I then tried to set it to my "old" shortcut and it worked! So I guess it was a weird bug.
Maybe I should have tried rebooting my system :/

Marking this issue as closed.

**Comment by thijsdeschildre** [comment]
Same issue here,  but the PC was put to suspend several times.
A reboot solved the issue.

**Comment by TheLiquidChef** [comment]
Running into the same issue. Any hotkey combination results in a red font and doesn't work.
