### ISSUE TITLE
Hotkey's no longer working on version 4.3.6643.23689

### ISSUE THREAD

**Issue by addrum** [Belphemur/SoundSwitch#247]
Before I updated last night, my hotkeys would switch between 3 playback devices (Ctrl+Alt+H) but this no longer works. I've tried relaunching the application, rebinding the hotkey, binding the hotkey to a different one and nothing works. Logs and config folder attached.
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1802018/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Hello,

Have you tried restarting the computer ?

The latest version of SoundSwitch only added a language, didn't make any change to the rest of the program.

**Comment by addrum** [comment]
Yep I had with no look. I found out that it seemed to be related to the fact my speaker set up has changed slightly recently and one of the "selected" options I was using is no longer connected. Re-selecting the audio devices I wanted solved it.

**Comment by Belphemur** [comment]
This is a problem with some upgrade of Windows, it does recreate the audio device with different IDs making the previous configuration invalid.
