### ISSUE TITLE
Crash observed after restart driven by Windows Update

### ISSUE THREAD

**Issue by sublym0nal** [Belphemur/SoundSwitch#248]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
Currently running the latest version (4.3.6643.23689) on Windows 10.0.16299.309. A crash was observed upon restarting after I had applied KB4088776 and KB4088785:

> TracerX: Log file opened at 3/13/2018 7:18:24 PM.  FullFilePolicy = Wrap, Use_00 = False, MaxGrowth = 1 MB, AppendIfSmallerThan = 0 1, initial size = 3.
19:19:11.992 Fatal <null> SoundSwitch+ Exception Occurred Exception type: System.Threading.ThreadStateException
Message: Instance isn't set even after waiting 750 ms
Source: SoundSwitch
StackTrace:
   at SoundSwitch.Framework.WindowsAPIAdapter.UnRegisterHotKey(HotKeys hotKeys) in D:\VS\SoundSwitch\SoundSwitch\Framework\WindowsAPIAdapter.cs:line 191
   at SoundSwitch.Model.AppModel.SetHotkeyCombination(HotKeys hotkeys, DeviceType deviceType) in D:\VS\SoundSwitch\SoundSwitch\Model\AppModel.cs:line 374
   at SoundSwitch.Model.AppModel.InitializeMain() in D:\VS\SoundSwitch\SoundSwitch\Model\AppModel.cs:line 206
   at SoundSwitch.Program.Main() in D:\VS\SoundSwitch\SoundSwitch\Program.cs:line 130

I haven't been able to reproduce it on subsequent reboot attempts, so it might've been as a result of a one-off slow boot process. Perhaps the timer in question could use a little more wiggle room?
[SoundSwitch-crashlog-13_3_2018.zip](https://github.com/Belphemur/SoundSwitch/files/1809033/SoundSwitch-crashlog-13_3_2018.zip)

**Comment by sublym0nal** [comment]
Given that this was closed, I'm assuming no fix for this is planned? Just seems a bit odd considering it was previously acknowledged as a bug...

**Comment by Belphemur** [comment]
Unfortunately, I have no way of reproducing it. I don't consider it fixed, but more like can't reproduce.

Bug = Just acknowledging an issue arose.
Confirmed = Reproduced.
