### ISSUE TITLE
VLC + SoundSwitch

### ISSUE THREAD

**Issue by habbaz** [Belphemur/SoundSwitch#249]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

VLC last version not working with SoundSwitch
Even if i change the device still the first is working

**Comment by Belphemur** [comment]
Hello,
That's a problem with VLC. I guess VLC bind to the default device when
you launch it.
In that case, you should use VLC settings to manually change the output
device has it doesn't listen to change of default device.
Maybe in the settings you can set VLC to only output to the default
device.
(ps: I'm not using VLC, and never have, I can't help you more than
that).

**Comment by habbaz** [comment]
thanks

**Comment by matma79** [comment]
Interesting.  Having a similar "issue".  Fairly new user and when I installed SoundSwitch VLC worked perfectly in tandem with switching up until the recent update. Since then VLC does not switch with everything else.  I wonder why it was initially synced and how that can be duplicated.
