### ISSUE TITLE
crash on Start: Recording Devices: Call IMMDeviceEnumerator::GetDefaultAudioEndpoint(...) 

### ISSUE THREAD

**Issue by kristianjgs** [Belphemur/SoundSwitch#25]
TracerX: Log file opened at 2/09/2015 7:00:54 p. m..  FullFilePolicy = Wrap, Use_00 = False, MaxGrowth = 1 MB, AppendIfSmallerThan = 0 1, initial size = 3.
19:00:54.310 Fatal <null> SoundSwitch+Program.HandleException Program.HandleException entered
19:00:54.310 Fatal <null> SoundSwitch+Program.HandleException    Exception OccuredException type: AudioEndPoint.DefSoundException
Message: Call IMMDeviceEnumerator::GetDefaultAudioEndpoint(...) failed
Source: Audio.EndPoint.Controller.Wrapper
StackTrace:
   en AudioEndPointControllerWrapper.AudioController.GetRecordingDevices(DeviceState state)
   en SoundSwitch.Model.AppModel.get_AvailableRecordingDevices()
   en SoundSwitch.Util.TrayIcon..ctor()
   en SoundSwitch.Program.Main()

19:00:58.394 Fatal <null> SoundSwitch+Program.HandleException Program.HandleException exiting

**Comment by Belphemur** [comment]
Does this only happen with the 3.4.X ?
You don't have the problem with 3.3.1 ?

**Comment by kristianjgs** [comment]
I don't have problems with 3.3.1, just don't work with 3.4.x

**Comment by Belphemur** [comment]
I have a workaround for this. I'll release a bug fix version for it. For now you can stick with 3.3.1. 

Do you have any recording devices installed? 

On 4 September 2015 03:21:28 EEST, kristianjgs <notifications@github.com> wrote:
>I don't have problems with 3.3.1, just don't work with 3.4.x
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/25#issuecomment-137607068

-- 
Best Regards, 
Antoine Aflalo

**Comment by kristianjgs** [comment]
on, I don't
