### ISSUE TITLE
Identify Re-Connected Displays /w Audio

### ISSUE THREAD

**Issue by ToddAlvord** [Belphemur/SoundSwitch#250]
When my monitors are powered off my PC no longer identifies them unlike most monitors. When I turn them back on SoundSwitch Identifies them as new monitors, and the previous ones as disconnected. It would be nice if SoundSwitch could identify somehow the same monitors when they are powered back on again.

**Comment by FireEmerald** [comment]
A _monitor_ is a pc monitor for me without speaker. But you mean a TV or at least a monitor with boxes, right?

**Comment by ToddAlvord** [comment]
Ah yes. They are both Display Port monitors with speakers and a headphone jack built in.

**Comment by ToddAlvord** [comment]
If anyone else is having the same problem I seem to have found a work around. My displays have an option called DDC/CI. I turned this off and my computer no longer forgets my monitors. If the issue persists I'll re-open the issue. Thanks @FireEmerald

**Comment by FireEmerald** [comment]
It's a driver related issue - nothing to do with sound switch. My headset is also recognized as "new device" each time i dis-/reconnect it.
