### ISSUE TITLE
Add feature: Switch only communications device

### ISSUE THREAD

**Issue by CraigLu** [Belphemur/SoundSwitch#252]
Hey, great application!

I was wondering if it was possible to be able to have an option to switch only communication devices for playback? I currently am using a Steel Series Arctis 7 along with separate microphone and speakers. The issue that I'm running into is that the Arctis 7 uses two different audio channels one for communications and one for the rest. When I'm using my speakers I would like to have my default playback (including communications) as one channel but when I switch to my headset I would like to change only the default  communications.

So the scenario looks something like this

HEADPHONES:
Arctis 7 Game - Default Device
Arctis 7 Chat - Default Communications Device

SPEAKERS:
Arctis 7 Game - Default Device & Default Communications Device (plays through speakers when headphones not connected)

**Comment by mjbrowns** [comment]
I would echo this along with a small expansion to the idea.

It would be great to create profiles that include all three -  Default Output, Default Communications, and Recording devices, then have a mode where double-clicking on the icon rotates through the created profiles.

For example, when using a headset that has separate output and communications mode (Like the Arctis series and many others), you might have two profiles:

Game Profile:
- Default Device: Arctis 7 Game
- Default Communications Device: Arctis 7 Chat
- Recording Device: Arctis 7 Headset Mic
Normal Profile:
Default Device: Realtek Speakers
Default Communications Device: Realtek Speakers
Recording Device: Microphone Input

That will allow you to switch between your headset mode and your desktop mode with full discord and game support.

**Comment by Belphemur** [comment]
Could be added to the profile feature.

**Comment by Belphemur** [comment]
Close this in favour of #348 

Will be part of the profile system.
