### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#254]
The application shall provide logfiles in a format which is readable using Notepad++ e.g. This means no special characters and horrible linebreaks like now:

![example](https://user-images.githubusercontent.com/1107939/38791448-0e88cc24-4148-11e8-914d-8f43990b5511.png)

**Comment by Belphemur** [comment]
I chose to use TraceX to log. It's a binary format for the logs.

You'll find here the client to read the logs: https://github.com/MarkLTX/TracerX

**Comment by FireEmerald** [comment]
I know that you can view the logfiles using TraceX, but the question is: Does a user also knows this, without taking a look at the Wiki? I don't think so. We shouldn't log entries in binary format because the logfile is never that huge that we have to take care of our disk space.

**Comment by Belphemur** [comment]
I see your point, I'd rather put more info in the readme.
But what's is put in the binary logs are mostly for debugging purpose
and doesn't add anything for the End-User.
Moreover, if we would switch to another kind of logging method, I'd
like to keep the idea of scope like this one does, it's quite useful to
pinpoint what has been done in which scope before the issue.
