### ISSUE TITLE
A hotkey to switch audio devices only for specific applications

### ISSUE THREAD

**Issue by Mickimoo2** [Belphemur/SoundSwitch#257]
Hi,

Before I make the new feature suggestion, I just want to say what a great app this is and have been using it for a fairly long time now.

Anyway, with the new Windows 10 version 1803 being rolled out, a new feature in windows allows for the input/output of an application to be individually changed. With this, I thought to myself that this would be a great feature to also add support for in SoundSwitch to enable users to make a hotkey (macro) to switch audio devices for specific applications (as well as global applications as you currently do).

I hope that you take this into consideration,
Many thanks.

**Comment by Belphemur** [comment]
I found the code that is linked to this feature in Windows 10.

When I have time, I'll make a Beta version that will also change the audio device of the current foreground app (the one currently in use) when in Windows 10.

If it works as expected, I'll move into making an interface where you'll be able to manage which app use which audio device.

**Comment by FireEmerald** [comment]
If someone is looking for this feature, here's where to find it in Windows 10 **1803**.
https://www.howtogeek.com/352787/how-to-set-per-app-sound-outputs-in-windows-10/

![ximg_5afdef86d3b71 png pagespeed gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md ic AAhweiNILU](https://user-images.githubusercontent.com/1107939/59163404-141a3200-8b01-11e9-9ddb-16594c9aeb42.png)
