### ISSUE TITLE
New Language: Portuguese (Brazilian) - Pull Request

### ISSUE THREAD

**Issue by aleczk** [Belphemur/SoundSwitch#258]
Olá,

I had some spare time but I'm not familiar to GitHub at all. I added the _PT-BR_ translation to the program but couldn't find out how to make a _'pull request'_ in the GitHub itself. So as recommended in 
[Add or modify another language](https://github.com/Belphemur/SoundSwitch/wiki/Add-or-modify-another-language) I'm sending here a ZIP with the **.zeproj** file and the **Localization** folder.

I hope everything is okay.

cya!

[SoundSwitchPTBR.zip](https://github.com/Belphemur/SoundSwitch/files/1980533/SoundSwitchPTBR.zip)

**Comment by Belphemur** [comment]
That's great !

Thanks for your time, I'm adding this right away.

**Comment by Belphemur** [comment]
In the future, you'll be able to work on the translation here:

https://hosted.weblate.org/projects/soundswitch/

You can create an account with your GitHub account :)

**Comment by aleczk** [comment]
Thank you for adding. There's just a minor typo: you added the language in the settings as Portu**ge**se and not Portu**gue**se. I also used the tool you sent (weblate) and changed a line which I translated to the singular but it's plural, I doubled checked (again) everything else and it seems fine.

Obrigado!

**Comment by Belphemur** [comment]
Good point ...
My bad, I'll make a change as soon as possible.
In fact, I'll change all the language name into their own language.
