### ISSUE TITLE
Add option to disable selected sound on device switch

### ISSUE THREAD

**Issue by stuffedtiger0** [Belphemur/SoundSwitch#261]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
I set a sound to the Banner option for switching devices, but I no longer want to hear anything. Can you include a way to disable the sound from playing?

**Comment by Belphemur** [comment]
Hello,
It already exists, it's counter intuitive though ...
You have to click on the [...] button to select a sound and ... click
on cancel.
This way, the sound will be removed.
I'll have to change this to make it easier to use.
