### ISSUE TITLE
Double Click to switch output device crashes app

### ISSUE THREAD

**Issue by TheClaus** [Belphemur/SoundSwitch#267]
After I upgraded to the latest version via the app I get a crash in the app whenever I double click on the taskbar icon to switch my output device.  It wasn't happening before the update.

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/1997850/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Thanks for the log :)

I see what's the problem is. It'll be corrected in the next version.
