### ISSUE TITLE
App randomly crashes, every 2 hours or so, with latest 4.5 update. 

### ISSUE THREAD

**Issue by yintoza** [Belphemur/SoundSwitch#268]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
Sorry i cant provide logs, because i uninstalled 4.5 and reinstalled 4.4. 
For the time being, I would stay away from 4.5 because the app crashes, and restarts randomly and quite frequently. It has no problems on 4.4 as far i know can tell.

**Comment by WilluXDeluX** [comment]
From what i can see, everytime it closes it calls for an update when it restarts...

**Comment by sidprice** [comment]
Where can I download 4.4 , 4.5 is crashing several times each dat.

**Comment by Belphemur** [comment]
I got some logs for this, it will be corrected in the next version.

**Comment by sidprice** [comment]
Thanks for the quick response, love SoundSwitch and don’t want to get annoyed with it 😝

Sid

 

Sid Price

Desktop Application and Embedded System Design
