### ISSUE TITLE
SoundSwitch isn't working with chrome sometimes

### ISSUE THREAD

**Issue by Psyduck91** [Belphemur/SoundSwitch#269]
When I use my hotkey, everything works except it doesn't register for chrome sometimes. I've tried with Firefox and it works just fine. Any idea why it's not being picked up by chrome sometimes?

There is a similar function in Display Fusion that works with Chrome but it requires a separate function/hotkey to change default communication device.

**Comment by Belphemur** [comment]
Hello,

In that case, it usually means Chrome didn't pickup the change of audio 
device, especially if every other app switched without problem.

There isn't anything I can do here :)

**Comment by Psyduck91** [comment]
I think the issue was fixed with the latest update. I think the issue I was having was what was posted in #256 . Thanks for the commitment to the program, I've been using it for a few years now.
