### ISSUE TITLE
Sound Switch keeps closing

### ISSUE THREAD

**Issue by AnsgarTOdinson** [Belphemur/SoundSwitch#270]
After a few hours of playing games or whatever sound switch will have stopped running.  Not sure what the issue is but it is a bit annoying.  On my old PC it worked flawlessly but on this new one it just keeps getting closed.

**Comment by Belphemur** [comment]
Hello,

Could you attach the content of the folder:
`%appdata%/SoundSwitch/logs`

In a zip file and drag and drop it into the Github issue?

That will give me some context on why it stopped :)
