### ISSUE TITLE
Crashing when mouse over tray icon

### ISSUE THREAD

**Issue by stevenkkim** [Belphemur/SoundSwitch#272]
With version 4.6, SoundSwitch occasionally crashes when I put my mouse over the tray icon. I've never had problems over the last year, but in the last day or so, I get multiple crashes a day – usually when I mouse over the tray icon. Could be related to new Windows 10 update which was just installed a couple days ago. I reverted back to version 4.4, no issues with that version so far. Attached is the crashlog file. 

I love the software. Keep up the great work!

[SoundSwitch-crashlog-14_5_2018.zip](https://github.com/Belphemur/SoundSwitch/files/2003215/SoundSwitch-crashlog-14_5_2018.zip)

**Comment by Belphemur** [comment]
Hello @stevenkkim,

Believe it or not, I just encountered the same issue.
I found the cause and I'll come with a fix in the following minutes.
