### ISSUE TITLE
SoundSwitch not starting after installation finished

### ISSUE THREAD

**Issue by Jensen95** [Belphemur/SoundSwitch#276]
The last couple of times I have installed an update and checked that I want SoundSwitch to start it hasn't started. In the installer, I uncheck everything else than open SoundSwitch.

I don't know if the zip file is necessary but here it is anyways, maybe it will have some useful logs 
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/2008822/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Unfortunately not really. It's a known issue that only occur in very specific condition that are difficult to reproduce.

**Comment by Jensen95** [comment]
Okay, thanks for the look 🙂
