### ISSUE TITLE
Modern Logo for Soundswitch

### ISSUE THREAD

**Issue by linadesteem** [Belphemur/SoundSwitch#277]
Hello, my name is Munzir, I am a logo designer. I am thinking to contribute to this project by making a logo. My main aims are to support open source project like yours, designing a logo to help projects build its identity. here are some concept that you might like, I try to combine sound symbol and switch symbol:

![image](https://user-images.githubusercontent.com/35618068/40135821-75c39500-5970-11e8-98a3-59ba79a7ba39.png)
![image](https://user-images.githubusercontent.com/35618068/40135865-8e2383a8-5970-11e8-8df5-c456adb34945.png)

What do you think? if you like it I will send PR with svg files :)

**Comment by Belphemur** [comment]
Hello @linadesteem,

Wow ! I love it ! :+1: 

It will be perfect for the website.

Could you also add to the PR an .ico file with only the "wave-switch"  to replace the icon of the current application (and be used as favicon).

**Comment by linadesteem** [comment]
Thanks, I am glad that you like it and of course I will add an .ico file to the PR

**Comment by linadesteem** [comment]
Hi, I have sent a pull request #278 can you check if all files are correct?

**Comment by Belphemur** [comment]
Thanks again for your work !

I really love how the wave transform into a switch. I'll also edit the readme to credit you.

**Comment by linadesteem** [comment]
Thanks, glad I can contribute to this project :)
