### ISSUE TITLE
Rarma Radio blocking SoundSwitch

### ISSUE THREAD

**Issue by regener** [Belphemur/SoundSwitch#28]
If Rarma Radio is running SoundSwitch doesn't do it's job, but if the RarmaRadio is closed it is working fine.

Rarma Radio's website: http://www.raimersoft.com/rarmaradio.aspx

**Comment by Belphemur** [comment]
This is a bug in Rarma radio. Usually application are listening for change in default audio enpoint, rarma radio isn't. Which mean, when you are changing the default device Rarma Radio stay stuck to the one that was default when it has been launched.

I can't force the app to change to the audio device you set.

**Comment by Belphemur** [comment]
Everything is explained here: https://msdn.microsoft.com/en-us/library/windows/desktop/dd371417%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
