### ISSUE TITLE
Tie specific application to specific output

### ISSUE THREAD

**Issue by alystair** [Belphemur/SoundSwitch#282]
It'd be great if one could specify outputs on a per-application level for applications that don't have their own output settings.

**Comment by Touchy28** [comment]
Yes! That would be great!

**Comment by FireEmerald** [comment]
This feature is already possible under Windows 10 by default.

- ⚠ **Requires:** _Also switch the foreground program_ must be **DISABLED** in SoundSwitch settings.

Go to your Windows _Settings_ > _Sound_ > _App Volume and device preferences_.
![2019-11-24 11_46_18-Window](https://user-images.githubusercontent.com/1107939/69493557-50bfc700-0eb0-11ea-8b34-64bf407ad084.png)

There you can bind a application to a specific output or input device:
![2019-11-24 11_49_36-Window](https://user-images.githubusercontent.com/1107939/69493582-aeecaa00-0eb0-11ea-94cc-56a0059b06ab.png)
