### ISSUE TITLE
Switching between Audio sources delayed - v4.8

### ISSUE THREAD

**Issue by JP-Xinnam** [Belphemur/SoundSwitch#286]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/2074999/SoundSwitch.zip)

With the new 4.8 update to Sound Switch, there is a noticeable delay in switching from source to source. I reverted to 4.7, and 4.7 does not have this issue.

I am running Windows 10 64 bit, version 1803, build 17134.48. Attached is the AppData folder, if needed.

**Comment by guilhermelawless** [comment]
Same issue, never had it beefore this version.

**Comment by BrightMedal** [comment]
I also have this issue. There is also a delay when right clicking on the the system tray icon to bring up the control panel.

**Comment by oscarhaglund** [comment]
I am also having this issue on windows 10 where it previously was more or less instant it now takes around 5 seconds of having to not move or click your mouse after having pressed the icon to bring up the quick switch

**Comment by Belphemur** [comment]
I dreaded this would happen in some configuration.

I'll work on it asap. I'm downgrading 4.8 from stable to beta.
