### ISSUE TITLE
New logo mostly invisible on white background

### ISSUE THREAD

**Issue by alystair** [Belphemur/SoundSwitch#287]
This is what it looks like in my extended list...
![image](https://user-images.githubusercontent.com/159109/41054851-925e9f66-698d-11e8-8287-229a85044350.png)

Only visible on click 
![image](https://user-images.githubusercontent.com/159109/41054928-d238dfa2-698d-11e8-8bd6-1376d23cd472.png)

Heck not very self-explanatory either... looks more like a spaceship/satellite than anything.. 
![image](https://user-images.githubusercontent.com/159109/41054970-f2df4f98-698d-11e8-8a5c-9e399e3cc2c0.png)

Personally liked old logo more. Give an option to switch ala Notepad++? :+1:

**Comment by alystair** [comment]
Only visible on click 
![image](https://user-images.githubusercontent.com/159109/41054928-d238dfa2-698d-11e8-8bd6-1376d23cd472.png)

**Comment by alystair** [comment]
Heck not very self-explanatory either... looks more like a spaceship/satellite than anything.. 
![image](https://user-images.githubusercontent.com/159109/41054970-f2df4f98-698d-11e8-8a5c-9e399e3cc2c0.png)

**Comment by FireEmerald** [comment]
The blue version should be used instead of the white one. Then it should be always visible.

https://raw.githubusercontent.com/Belphemur/SoundSwitch/dev/img/Logo%20and%20Icon/Ico/Blue%20Icon.ico

**Comment by Belphemur** [comment]
@FireEmerald If we switch to the blue, it's not going to be visible either in Windows 10

I'm trying to see if I can add a visible contour to it.

**Comment by FireEmerald** [comment]
It depends on the color of your taskbar :see_no_evil:

**Comment by alystair** [comment]
I'll put a $10 bounty (via PP or EMT) for an icon switch (for notification area). Allowing minor customization isn't a bad thing. I bet the new logo looks alright under Win 10 but I personally prefer the old one.
