### ISSUE TITLE
Interface slow to respond to click to open

### ISSUE THREAD

**Issue by cabuzzi** [Belphemur/SoundSwitch#288]
Unfortunately, I don't have any logs to upload, as I uninstalled and installed a previous version. The version that prompted for an install last night via automatic update last just was not working right... even after a reboot. If I right-clicked the toolbar icon, I'd get the settings icon within a few seconds (still slow), but left-clicking to bring up the menu would either not bring up the menu at all (though you could see the edges of the window, but couldn't interact with it), or it would bring it up 5-10 seconds later at the location your mouse was at when it finally appeared (middle of screen).

I don't recall the version, but it was different than the one that was on the download site. I uninstalled and reinstalled with the version on the site and it works *almost* as expected (still a little lag when left-clicking the icon).

**Comment by Belphemur** [comment]
see #286
