### ISSUE TITLE
Much slower switching ever since 4.8

### ISSUE THREAD

**Issue by mxr24** [Belphemur/SoundSwitch#291]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
I rolled back my version to v4.7 because v4.8 was hanging for about 10 seconds every time I clicked on the taskbar icon. This never happened with older versions for me, and after reinstalling 4.7, the switch is instant again.

**Comment by etcet54** [comment]
Agree man, I thought I pressed wrong key or something, turned out the switch is delayed. Rolled back also

**Comment by Belphemur** [comment]
See #286
