### ISSUE TITLE
SoundSwitch crashing ... again

### ISSUE THREAD

**Issue by sidprice** [Belphemur/SoundSwitch#292]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

**Comment by Belphemur** [comment]
Hello,
Without providing context or logs, I'm closing this issue.

**Comment by sidprice** [comment]
So where are the logs?

**Comment by FireEmerald** [comment]
Take a look at the wiki: https://github.com/Belphemur/SoundSwitch/wiki

And please provide a description what are you doing before the application crashes.

**Comment by sidprice** [comment]
Thanks. The crash happens one or twice most days without any interaction from me. At this point I do not know what the trigger is, once it happened (because it makes a sound) when I was away from my computer, so doing nothing with it.

 

I have several logs from different days, but I don’t know which one contains the data you need. Is there some identifying text in there for the shutdown/restart of SoundSwitch?

**Comment by Belphemur** [comment]
@sidprice Could you zip the logs/ folder and attach it to a comment on the GitHub issue (drag & drop) ?

I assure you the logs don't contain any information that can't be made public.

**Comment by sidprice** [comment]
I was not concerned about that, just getting you useful logs. Here is a zip of the logs from the last few days.

**Comment by Belphemur** [comment]
Unfortunately GitHub doesn't support email attachments, you have to use the website.

**Comment by sidprice** [comment]
OK, I haven't seen a crash for a while now.
