### ISSUE TITLE
Crashing, unstableness and messed up dialogues.

### ISSUE THREAD

**Issue by thelewiss1** [Belphemur/SoundSwitch#293]
Soundswitch has been very unstable recently. When I try to right click to change sound device or open settings, Soundswitch freezes and/or takes a long time to appear.

I can't really use the program I need!

Thanks a lot.

**Comment by thelewiss1** [comment]
hate to bump, but bump.

**Comment by FireEmerald** [comment]
Try to use any older version and check if your issue persists: https://github.com/Belphemur/SoundSwitch/releases

Tell us which version is working well for you.

Please also provide us your logfiles: https://github.com/Belphemur/SoundSwitch/wiki/SoundSwitch-Configuration-and-Logfiles

**Comment by thelewiss1** [comment]
Even 4.7 seems to buggy context menu wise. The tray icon even just disappeared in 4.7.


[soundswitch20180702.log](https://github.com/Belphemur/SoundSwitch/files/2155910/soundswitch20180702.log)

**Comment by thelewiss1** [comment]
Update: It just crashed without input.

**Comment by FireEmerald** [comment]
So 4.8 doesn't work, 4.7 doesn't work? Please start with the newest version and then go to the older ones.

**Comment by thelewiss1** [comment]
Retrying 4.8, as I did have a installer for it. Currently waiting for 4.8 to download, install, etc. Will update shortly,

**Comment by FireEmerald** [comment]
You can download a installer for each version from: https://github.com/Belphemur/SoundSwitch/releases

**Comment by thelewiss1** [comment]
Alright. Trying 4.8 and I get way better performance, like 4.7, but the right click context menu still freezes and goes black.

**Comment by Belphemur** [comment]
Can you give us a Screenshot of the setting menu.

I'm curious how many audio devices you have.

In 4.9, all the performance issue should have been resolved.

**Comment by thelewiss1** [comment]
https://i.imgur.com/gOk1Wq2.gifv

Only the "connected" devices are selected with the keycombo.

**Comment by Belphemur** [comment]
Mmmh, nothing out of the ordinary.

I might have an idea on what could be impacting your experience.

Can you try something for me ?

1. Reinstall 4.9
2. Configure it as you usally do
3. Restart the program
4. Use the right click menu and time roughly the time it takes to pop-up
5. Do it again

Was the 5. taking less time than the 4. ?

(To not bore you with technicalities, there is a cache that is fired at the first switch, I'm thinking the bootstrapping of the cache is what is causing the delay in the first switch).

**Comment by thelewiss1** [comment]
Right click: 3 - 6 secs
If its longer, a frame will appear, and when the menu loads it just appears where the cursor is and won't go away unless a button is pressed.

**Comment by thelewiss1** [comment]
Just for reference, I’m pretty sure Soundswitch has been loaded at boot for
a while, and it hasn’t crashed. Do you want me to try the latest release
again? Will note down idle (after boot settle) loads when I get chance
tomorrow on whichever older version I have ATM.

**Comment by cjunekim** [comment]
Version 4.9. It takes about 8-9 seconds to show the menu when I right-click the tray icon.

**Comment by Giaki** [comment]
It's so slow on right click, it started few months ago and never got fixed. Old versions worked ok.
