### ISSUE TITLE
4.9 Update will not finish

### ISSUE THREAD

**Issue by Geetop** [Belphemur/SoundSwitch#294]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
![image](https://user-images.githubusercontent.com/40770727/42176747-052a4d46-7df8-11e8-91cd-efa39a5a5b68.png)

**Comment by Belphemur** [comment]
That's weird.

The installer is usually stopping SoundSwitch before doing the update.

Can you close SoundSwitch manually and download the update from https://soundswitch.aaflalo.me ?

Sorry for the inconvenience.

**Comment by Geetop** [comment]
That worked! Thank you for the help. 

And it was not an inconvenience - I appreciate your efforts on the application. : )
