### ISSUE TITLE
Cannot see banner during full-screen application

### ISSUE THREAD

**Issue by AbleOpus** [Belphemur/SoundSwitch#297]
When I am running a full-screen app on my primary monitor (such as a game), I cannot see the banner or the system tray icon. And I use hotkeys to cycle the audio devices the most while gaming. It would be nice to have the banner show on the nearest monitor while using a full-screen app on the primary monitor. Like on the right of the monitor just left of primary or the left of the monitor just right of the primary.

**Comment by Belphemur** [comment]
This is an issue with double monitor.

I've no control on which monitor the banner shows or how it is exactly shown.
