### ISSUE TITLE
Lag opening system tray context menu

### ISSUE THREAD

**Issue by AbleOpus** [Belphemur/SoundSwitch#298]
There is considerable lag specific to this application when opening up the context menu. Anywhere from 500ms to 3 seconds, while all other sys tray context menus open up immediately in my system tray. I suspect this has to do with update checking on the UI thread. I cannot think of any other possible cause.

**Comment by fredgreco** [comment]
I am experiencing this same behavior

**Comment by azeunkn0wn** [comment]
context menu shows but nothing inside, when clicked, it turns black and a "App not responding" prompt appears.

**Comment by AbleOpus** [comment]
The lag is present when right and left clicking the notify icon. I looked over the code and could not find anything conspicuous.

**Comment by azeunkn0wn** [comment]
I noticed this issue after upgrading my windows to latest build.

**Comment by FarewellAngelina** [comment]
I have this problem since i started with SoundSwitch, i kind of get used to it since i use the Hotkey but damn this is annoying, taking 5-seconds to open any context menu (right or left click) is so frustating, i'm talking when my pc is on idle with all of cpu and ram and disk you would need for speed.

**Comment by Xeevis** [comment]
+1

Context menu is unusable for me, had to switch to hotkey.

**Comment by 0vertime** [comment]
This used to work without lag, must be some windows update.

**Comment by ksurl** [comment]
still happening for me as well. just timed it recently and it's about 7-10 seconds on average to open settings. the hotkey works instantly which is fine 90% of the time.

**Comment by Giaki** [comment]
it's a problem so broad that I don't understand why they haven't fixed it yet. It started many months ago

**Comment by izcream** [comment]
its happen on me to with my win10 64bit latest build

![screenshot_1](https://user-images.githubusercontent.com/10282500/47959104-80363400-e00e-11e8-85b9-f14d35152ba4.png)
