### ISSUE TITLE
Add an optional shortcut for muting recording device

### ISSUE THREAD

**Issue by Integritus** [Belphemur/SoundSwitch#299]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

**Comment by lgoose** [comment]
This would be truly amazing, currently when I have to mute I switch profile to one that has nothing mapped as input, but's a clunky work around, being able to mute sounds much better. Better yet if we could have a *push-to-talk* feature as well

**Comment by Belphemur** [comment]
I missed the issue.

This is done in v5.8.1
