### ISSUE TITLE
SOUNDWSITCH WON'T WORK ON ANY ROCKSTAR GAMES'S GAMES (LIKE GTA V, L.A. NOIRE,...)

### ISSUE THREAD

**Issue by Cut3310** [Belphemur/SoundSwitch#304]
As said in the title,
Soundswitch doesn't switch the audio between speakers and headset in any Rockstar Games's games. Please fix this, it would be very very useful.

**Comment by Belphemur** [comment]
Hello,

It's a known issue with a lot of games.
The way the audio work in Windows let the application decide if it want 
or not to listen to change in default device. This is not mandatory, and 
most game don't bother implementing it for multiple good reasons.

Unfortunately, I cannot do anything about it.
If SoundSwitch tells you it switched the audio, but the audio doesn't 
switch and the Windows Interface tells you it switched ... it means the 
application you're currently using (GTA, etc ...) is not supporting 
dynamic change of audio device.
