### ISSUE TITLE
I can not install or update SoundSwitch.

### ISSUE THREAD

**Issue by Brko28** [Belphemur/SoundSwitch#307]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

I can not install SoundSwitch by requiring the installation of Visual C ++ 2017 64-bit redistributable, and I have already installed VC ++.

**Comment by Belphemur** [comment]
Hello,

Which version of Windows are you using ?
Can you do a screenshot of the winver application ?

 > Press the Windows logo  key + R, type winver in the Open box, and 
then select OK to find out which version of Windows your device is running.

**Comment by DavidCorral94** [comment]
I have the same issues. The only way to fix it, for me, was to uninstall SoundSwitch, install Visual C++ https://support.microsoft.com/es-es/help/2977003/the-latest-supported-visual-c-downloads and then install SoundSwitch again.

Hope it can help you @Brko28!
