### ISSUE TITLE
High CPU usage with 4.10.6899.14921 when coming back from hibernation/sleep

### ISSUE THREAD

**Issue by sorrydaijin** [Belphemur/SoundSwitch#309]
I have been getting high (30%+) CPU usage with the latest version. Never had issues with previous versions AFAIK.

I am switching between onboard HD audio device (headphones) and NVIDIA HD audio over DP (monitor).

[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

**Comment by Belphemur** [comment]
Hello, 

Can you give me more detail to what was happening before you got the cpu spike? 

Was it at launch or when interacting with the app? 

Is it doing it all the time? 

________________________________

**Comment by zflash** [comment]
Same here. Soundswitch is consuming 25% (1 full core) of cpu. Have to kill it and restart it to behave normal again. NOt sure what triggers it, but after a couple of sound outputs, it's back.

**Comment by Belphemur** [comment]
Can you give me your [version of Windows using winver](https://kb.netgear.com/20246/Using-Winver-command-to-find-the-Windows-version) ?

Also which version of .NET is installed ?
(
   In a PowerShell run: 
 ```powershell
Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\' | Get-ItemPropertyValue -Name Release
```
)

**Comment by sorrydaijin** [comment]
Windows 10 Version 1803 (OS Build 17134.345)

.NET 461808

Hope that helps

**Comment by zflash** [comment]
Just saw that it showed a popup of the current default device and the cpu usage went up. I did no manual action regarding soundswitch whatsoever.

**Comment by Belphemur** [comment]
I have a hard time reproducing the issue.


The only moment I get it is when the computer is back from sleep.


Thr switching still works but no more notifications and I get the spike.


It's not easy to investigate.

________________________________

**Comment by WhyHarro** [comment]
I've noticed this issue happens everytime my computer comes out of sleep, Maybe that will help you track it down.

**Comment by sorrydaijin** [comment]
I often hibernate the PC so that may be the trigger.

**Comment by Belphemur** [comment]
Okay 3 report linking the issue to hibernation.

I'm going to edit the issue. This is helpful :+1:

**Comment by sorrydaijin** [comment]
One thing I would like to add is that this was definitely introduced in
4.10.
I have downgraded to 4.9 for now, and am not seeing any spikes in CPU usage.

**Comment by Belphemur** [comment]
Should be resolved in v4.11 👍

**Comment by sorrydaijin** [comment]
Awesome. Thanks for your work.

**Comment by sorrydaijin** [comment]
Something like this may have come back. I have been noticing crazy spikes in CPU from soundswitch lately. On v 4.12 atm.

**Comment by Belphemur** [comment]
@sorrydaijin Will be resolved in next version.

I found a better way to fix this to avoid #323

**Comment by digitaldias** [comment]
Still there, I immediately thought that you're abusing my cpu to mine crypto. It's running at least 16 of my 32 cores in high CPU when I come out of hibernation.

**Comment by Belphemur** [comment]
Can you test with the latest beta 5.2.0 ?

Might help with this.
Nope, there isn't any miner. It must be one part of the app that have difficulty coming back from hibernation.
