### ISSUE TITLE
Soundswitch won't start. No crash report.

### ISSUE THREAD

**Issue by burnyourfire** [Belphemur/SoundSwitch#31]
Can get Soundswitch to run. There is no error / crash message. Recent version (3.5.1), Windows 10 Pro x64, All dependencies installed (.NET Framework 4.6 Advanced Series, Visual C++ 2015 Redistributable), Certificate installed as recommended.

Don't know if it's any help but this is the app crash report (Report.wer):

Version=1
EventType=APPCRASH
EventTime=130879201839293729
ReportType=2
Consent=1
UploadTime=130879201839508939
ReportIdentifier=0bc3cd30-65e4-11e5-8d75-10bf48804b9f
IntegratorReportIdentifier=943775f8-ca38-4d25-9b93-5df991acaf83
NsAppName=SoundSwitch.exe
Response.BucketId=ba5e667630403900f4e90312c107f4a8
Response.BucketTable=4
Response.LegacyBucketId=120323425146
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=SoundSwitch.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=3.5.1.26132
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=55fbf5f8
Sig[3].Name=Fehlermodulname
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=10.0.10240.16384
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=559f38c3
Sig[6].Name=Ausnahmecode
Sig[6].Value=e06d7363
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=000000000002a1c8
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=10.0.10240.2.0.0.256.48
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=ad07
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=ad07192b91c4e5a5ac3605a31c644834
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=dd03
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=dd037a0b8c9da053fb9632f928376ad4
UI[2]=C:\Program Files\SoundSwitch\SoundSwitch.exe
LoadedModule[0]=C:\Program Files\SoundSwitch\SoundSwitch.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\system32\KERNEL32.dll
LoadedModule[4]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\system32\apphelp.dll
LoadedModule[6]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[7]=C:\Windows\system32\msvcrt.dll
LoadedModule[8]=C:\Windows\system32\sechost.dll
LoadedModule[9]=C:\Windows\system32\RPCRT4.dll
LoadedModule[10]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[11]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[12]=C:\Windows\system32\combase.dll
LoadedModule[13]=C:\Windows\system32\GDI32.dll
LoadedModule[14]=C:\Windows\system32\USER32.dll
LoadedModule[15]=C:\Windows\system32\IMM32.DLL
LoadedModule[16]=C:\Windows\system32\MSCTF.dll
LoadedModule[17]=C:\Windows\system32\kernel.appcore.dll
LoadedModule[18]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[19]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[20]=C:\Windows\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[21]=C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\dfd75630ade67ae60abbed1c6429af70\mscorlib.ni.dll
LoadedModule[22]=C:\Windows\system32\ole32.dll
LoadedModule[23]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[24]=C:\Windows\system32\uxtheme.dll
LoadedModule[25]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[26]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[27]=C:\Windows\SYSTEM32\cryptsp.dll
LoadedModule[28]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[29]=C:\Windows\system32\rsaenh.dll
LoadedModule[30]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[31]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System\516605b5a2073e367e76685de69c11e1\System.ni.dll
LoadedModule[32]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Drawing\f3507c083d2470c04f90943801e4d93d\System.Drawing.ni.dll
LoadedModule[33]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\b3049e723a732fde2034cf4bac3caeaa\System.Windows.Forms.ni.dll
LoadedModule[34]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Core\d4bc4eff7f89337ee51386f26c4b19cd\System.Core.ni.dll
LoadedModule[35]=C:\Program Files\SoundSwitch\Audio.EndPoint.Controller.Wrapper.dll
LoadedModule[36]=C:\Program Files\SoundSwitch\AudioEndPointLibrary.dll
LoadedModule[37]=C:\Windows\SYSTEM32\VCRUNTIME140.dll
LoadedModule[38]=C:\Windows\SYSTEM32\ucrtbase.dll
LoadedModule[39]=C:\Windows\SYSTEM32\MSVCP140.dll
LoadedModule[40]=C:\Windows\system32\clbcatq.dll
LoadedModule[41]=C:\Windows\System32\MMDevApi.dll
LoadedModule[42]=C:\Windows\System32\DEVOBJ.dll
LoadedModule[43]=C:\Windows\System32\PROPSYS.dll
LoadedModule[44]=C:\Windows\system32\cfgmgr32.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=SoundSwitch
AppPath=C:\Program Files\SoundSwitch\SoundSwitch.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=47AD8834364C2A3ECFBC34849928B22A

**Comment by Belphemur** [comment]
Can you download this: https://aaflalo.me/AudioTester.zip
Unzip it, run the AudioTester.exe 

If it crash, screenshot the message, if it works you should see the different actives soundcards.

This little app is using the same library than SoundSwitch, only this one is using it at a lower level and should help me to troubleshot the issue.

**Comment by burnyourfire** [comment]
Thanks for you fast reply.
AudioTester.exe crashes giving multiple errors.

![crash01](https://cloud.githubusercontent.com/assets/14873025/10139520/8a6b66e4-6603-11e5-9fec-291c4ca6836f.JPG)
![crash02](https://cloud.githubusercontent.com/assets/14873025/10139522/8a7452cc-6603-11e5-9fb7-52e3cbd17929.JPG)
![crash03](https://cloud.githubusercontent.com/assets/14873025/10139521/8a710360-6603-11e5-8bf3-aab22d261754.JPG)


Looks like Visual C++ Runtime errors, however the following packages are installed:

![vcruntimes](https://cloud.githubusercontent.com/assets/14873025/10139741/aab256b4-6604-11e5-8437-a60d89978683.JPG)

**Comment by Belphemur** [comment]
ah my bad, compiled it with the debug libs.

Can you try with this one: https://aaflalo.me/AudioEndTester.zip

**Comment by burnyourfire** [comment]
Not working either, different crash message though.

![audioendtester_crash](https://cloud.githubusercontent.com/assets/14873025/10157171/dcb243d0-6687-11e5-9314-d680bf9ea1d8.JPG)

**Comment by burnyourfire** [comment]
Ok, so for me 3.4.2 is the latest working version. 3.5.0 and 3.5.1 are not working. Maybe this info helps.

**Comment by Belphemur** [comment]
Yes it does help !

I think I need to rework the underlying library to avoid this kind of error. Thanks for the information.

**Comment by everlof** [comment]
I can verify that it's the same for me.. Tried with lastest but got no interface when started the program. As indicated by @burnyourfire I tried with 3.4.2, and it worked!

**Comment by Belphemur** [comment]
I'm sorry I have a lot of work lately. I have some idea of what is causing this issue and should be able to correct this (worst case, put the same behavior as in the 3.4.2).

**Comment by Hlsgs** [comment]
hello.

i can confirm this and yes, 3.4.2 does work.
i'm on W8 x64 with VIA VT2021 codec.

thanks for updating this, btw!

**Comment by FireEmerald** [comment]
Running on Win7 64bit Version 3.5.1.26132 - got same "error". The process is running, but nothing appears. Version 3.4.2.27416 is working as intended.

**Comment by Belphemur** [comment]
Thank you for all these bug report, clearly it's not linked to a specific version of Windows.

I tagged for now all version of 3.5.X as pre-release. I'll release soon a new version that should correct this issue.

**Comment by Belphemur** [comment]
If this issue comes back, please reopen it.
The new version should fixes the problem you all encountered.

Since I couldn't reproduce it, I hope "my shot in the black" worked.

**Comment by burnyourfire** [comment]
Unfortunately it's not working for me. Thanks for all your effort though!
I uninstalled v3.4.2, then rebooted, installed the certificate and finally v3.5.2.
It immediately crashes and let's me create a log file (see attached txt files).
[SoundSwitch_01.txt](https://github.com/Belphemur/SoundSwitch/files/31708/SoundSwitch_01.txt)
[SoundSwitch_02.txt](https://github.com/Belphemur/SoundSwitch/files/31709/SoundSwitch_02.txt)
[SoundSwitch_03.txt](https://github.com/Belphemur/SoundSwitch/files/31710/SoundSwitch_03.txt)
[SoundSwitch.txt](https://github.com/Belphemur/SoundSwitch/files/31711/SoundSwitch.txt)

**Comment by Hlsgs** [comment]
same here. back to 3.4.2.

**Comment by Belphemur** [comment]
In a way it's good. With this I'm now sure what's the issue.

**Comment by Hlsgs** [comment]
still not working. here are the log files
[SoundSwitch_03.txt](https://github.com/Belphemur/SoundSwitch/files/33803/SoundSwitch_03.txt)
[SoundSwitch_02.txt](https://github.com/Belphemur/SoundSwitch/files/33804/SoundSwitch_02.txt)
[SoundSwitch_01.txt](https://github.com/Belphemur/SoundSwitch/files/33805/SoundSwitch_01.txt)
[SoundSwitch.txt](https://github.com/Belphemur/SoundSwitch/files/33806/SoundSwitch.txt)
[SoundSwitch(A).txt](https://github.com/Belphemur/SoundSwitch/files/33807/SoundSwitch.A.txt)

**Comment by Hlsgs** [comment]
all good now. thank you, sir!
