### ISSUE TITLE
Unable to donate via PayPal

### ISSUE THREAD

**Issue by InoSiX** [Belphemur/SoundSwitch#312]
This {{{{may}}}} not be a problem on your end, but I was trying to donate and PayPal keeps generating an unknown error. It simply says "If you continue to encounter problems, please contact customer service." coupled with a yellow !. 

I tried several times. Both the button link and the banner link. May not be your issue, could be PayPal. Thought I would share none the less.

**Comment by Belphemur** [comment]
That's weird.

I have 2 other way to donate if that one doesn't work.
You have the form here: https://www.aaflalo.me/donate/

And if that doesn't work either, you can use this:
https://paypal.me/AAflalo
