### ISSUE TITLE
Characters in french are not displayed correctly in the installer

### ISSUE THREAD

**Issue by cyberium** [Belphemur/SoundSwitch#313]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

Just to let you know
https://i.imgur.com/SBKUC5v.png

encoding problem probably

**Comment by kenijo** [comment]
@Belphemur: I am not familiar with InnoSetup but if this is anything like NSIS, make the installer files use UTF-8 encoding with BOM. Also you may need to make sure you use the Unicode version of InnoSetup.
