### ISSUE TITLE
4.11.69 Bug with hotkeys

### ISSUE THREAD

**Issue by luxferro** [Belphemur/SoundSwitch#314]
There's some wonky things going on with hot keys. In the past when using SoundSwitch, I normally configured the hot key to `ALT + CTRL + ` `. The problem is the ``` key then no longer works for any other program in windows - even notepad. It also happens do be the default key to switch action bars in Assassin's Creed Odyssey - which was how I found that something was wrong. 

So then I went to change it to a different hotkey, but any time that SoundSwitch is running it still prevents me from using the ` key - even if the hotkey function is disabled in the settings.

**Comment by luxferro** [comment]
Yeah, it was setup as a key combo  (CTLR+ALT+`), but it blocks the use of the individual key when SoundSwitch is running. It doesn't block the tilda key which is SHIFT+` though.

I had been using your program for a while, but recently redid my windows and didn't have the older versions saved, so I download the latest from your site, and didn't realize there was an issue until I went to play a game that uses ` to switch hotbars by default.

This weekend I'll try to uninstall and do an fresh install of Soundswitch to see if that fixes anything. Or see if I can find one of the older versions for a comparison - I probably have it on my NAS somewhere.

**Comment by Brochtune** [comment]
I am having the same issue as well. I had to down grade to v4.6 to make the hot keys work again. i tried v4.11 and v4.10 in which both had the hot key issue where it would not switch between the two devices I had selected. I am using ALT + CONTROL+INSERT with v4.6 and that works. Does not work with v4.11 or 4.10.

**Comment by NeckBeardPrince** [comment]
Same issue here Control + Alt + F11 has suddenly stopped working.

**Comment by VeNoMouS** [comment]
yea my hot keys no longer work, mic hot key does, not speak though

**Comment by VeNoMouS** [comment]
@Belphemur still an issue for me even with new update.

**Comment by NeckBeardPrince** [comment]
Same here hotkeys still do not work..

**Comment by VeNoMouS** [comment]
@NeckBeardPrince if you click on soundswitch in your systray, how many devices are listed? I only have one refer #323 i think it could be the device cycle issue if theres only 1 device listed...
