### ISSUE TITLE
Visual C++ Redistributable for Visual Studio 2017 issues with  other program

### ISSUE THREAD

**Issue by Londonsmee** [Belphemur/SoundSwitch#315]
Hi Had to uninstall Visual C++ Redistributable for Visual Studio 2017 with total war warhammer to get it working. Have you got a version using 2015 version

**Comment by Belphemur** [comment]
That's surprising. 

You can have multiple version of VS Redistributable installed without impacting the different app. 

I have the 2015 and 2017 installed and I can play all the game that requires the 2015 without problem. 

You have to see the VS Redist as different application. 

________________________________

**Comment by Londonsmee** [comment]
Its not SS causing issues. Just WHTW doesnt seem to like it on my system couldn't even launch it. But taking it off means cant run SS. which is a shame it's one of my favorite little programs. :(

**Comment by Belphemur** [comment]
What happens when you have the 2017 installed alongside the 2015? 

Like I say, it shouldn't cause any issues since they are different application. 

________________________________
