### ISSUE TITLE
Ingame Switching

### ISSUE THREAD

**Issue by Gokku93** [Belphemur/SoundSwitch#316]
Is there any option to get the audio switch ingame? Or just impossible in win10?

**Comment by FireEmerald** [comment]
That's not an issue with Windows 10. Many games do not recognize it if you switch the sound output device **after** the game was started - they just use the device which was set as default when the game was launched.

Try to manually change the **default output device** after the game was started and check if it works:
![2019-01-17 14_57_42-window](https://user-images.githubusercontent.com/1107939/51323492-a80f3280-1a68-11e9-8214-ddf0d9275400.png)

**Comment by Gokku93** [comment]
Nope, it doesnt work... I have tried with 2 games and no. But danke for your help :)

**Comment by FireEmerald** [comment]
In this case it is in fact a "issue" of the game(s) itself.
