### ISSUE TITLE
Soundswitch does not open itself at boot.

### ISSUE THREAD

**Issue by thelewiss1** [Belphemur/SoundSwitch#317]
Using version 4.11.6912.394455

I have the Start automatically with windows option enabled, but soundswitch doesn't start.
I can't even put a shortcut in the Startup folder, it won't start.

Thanks

**Comment by Belphemur** [comment]
It could be blocked by system wide policy.

Is it your computer or a workstation ?

You'll have to see with the administrator of your system.
