### ISSUE TITLE
Failure to install Visual C++ Redistributable during first installation.

### ISSUE THREAD

**Issue by r2n2** [Belphemur/SoundSwitch#320]
[Setup Log 2019-02-04 #001.txt](https://github.com/Belphemur/SoundSwitch/files/2829038/Setup.Log.2019-02-04.001.txt)
[Setup Log 2019-02-04 #002.txt](https://github.com/Belphemur/SoundSwitch/files/2829014/Setup.Log.2019-02-04.002.txt)

Did not upload SS directory contents as this is not about SS directly.  Rather SoundSwitch_v4.11.6912.39455_Release_Installer failed trying to install Visual C++ 2017 64-Bit Redistributable.  It failed twice.  After the first failure I rebooted my system as recommended by the SS installer.  Logs attached.

**Workaround:** I went to Microsoft and downloaded https://aka.ms/vs/15/release/vc_redist.x64.exe.  I manually installed it.  NOTE: the '15' in the path suggests 2015; however, I double checked and this is what MS put under the 2017 distribution.  Once the system rebooted, because Microsoft, I was able to install and start SS.

Now I'm off to test its use it to fix the issue I'm having with nuclear wast... er, switching audio I/O devices on the fly.

**Comment by r2n2** [comment]
FYI - My system info: 
[System Info.txt](https://github.com/Belphemur/SoundSwitch/files/2829087/Issue_320_System.Info.txt)

**Comment by Belphemur** [comment]
Shouldn't be an issue in the latest version.

VC is not needed anymore
