### ISSUE TITLE
Not switching to HDMI Audio Device

### ISSUE THREAD

**Issue by xZangetsuxX** [Belphemur/SoundSwitch#322]
Hello i recently got a TV and i connected my TV with my PC.
unfortunately i cant switch to HDMI Audio can someone help pls ?

**Comment by Belphemur** [comment]
Hello,

Did you reconfigure SoundSwitch to add the TV to the list of switchable 
devices ?

**Comment by xZangetsuxX** [comment]
Yes ofc i added the TV

**Comment by Belphemur** [comment]
What happens when you do it manually from the Windows menu ?

Because if with that it doesn't work either, I can't really help (for now).

**Comment by xZangetsuxX** [comment]
it works manually... but not with keybind :(

**Comment by Belphemur** [comment]
Can you try with a different key binding ?

I have the feeling the default one is now taken by another application. see #314
