### ISSUE TITLE
SoundSwitch does not refresh itself when connecting new device to computer

### ISSUE THREAD

**Issue by mbc843** [Belphemur/SoundSwitch#323]
Hi! I have problem with SoundSwitch (v. 4.11.6912.39455) when i'm connecting a new device to the computer. It looks like SoundSwitch can't handle all of the connecting/disconnecting events on the fly.

So what i did was:

Connected my bose headphones to computer as this would be the first time. Boses (as many other bt headphones) will create two new playback devices "Stereo"/"Hands-free" to the computer. SoundSwitch will recognize these both devices but one of the devices will be on "Disconnected" state:
![sw1_bose_connect](https://user-images.githubusercontent.com/47883776/53235008-81609f00-3699-11e9-84b6-b387e18631b4.PNG)

![settings_bose_connect](https://user-images.githubusercontent.com/47883776/53235102-b7058800-3699-11e9-9a92-698dfa10c469.PNG)

Then i added both of these bose sound devices to the "selected" list, closed the settings page and clicked the trace icon -> now i could change between the devices although "hands-free" was on "disconnected" mode:
![image](https://user-images.githubusercontent.com/47883776/53235334-3a26de00-369a-11e9-99ea-f70ac9351bb2.png)

After that i disconnected (turned off) my headphones but the trace icon shows "Bose hands-free" still as a selectable device:
![image](https://user-images.githubusercontent.com/47883776/53235681-19ab5380-369b-11e9-8b69-e69543488c32.png)

I switched the headphones on and connected them to my computer, clicked the trace icon and now i had only "Bose stereo" as selectable:
![image](https://user-images.githubusercontent.com/47883776/53235897-9b02e600-369b-11e9-8808-679fb6d52aab.png)

Then i restarted SoundSwitch, clicked trace icon and all of my selected devices was there as they should be:
![image](https://user-images.githubusercontent.com/47883776/53236059-0d73c600-369c-11e9-81bc-c995ff99cda1.png)

This can also be repeated by using only usb-headphones. I think that this was still working on last fall but i don't remember what version of SoundSwitch that was. Is there something that could be fixed?

Thanks.

**Comment by VeNoMouS** [comment]
at a guess i would say problem was introduced at this commit...  https://github.com/Belphemur/SoundSwitch/commit/8fcbd63ede403e9ca0d1cde830d7bf17a6d6b7fa

mayyyybeee

**Comment by mbc843** [comment]
Yes that might be true. I had time to test different versions on weekend and i would say that this was working on build v4.9. On that version SoundSwitch automatically detects changes on sound devices.

**Comment by Belphemur** [comment]
I'll have to reproduce the issue, this is clearly a caching problem.

**Comment by Belphemur** [comment]
Should be resolved with v4.12

**Comment by VeNoMouS** [comment]
this is not resolved in 4.12

![image](https://user-images.githubusercontent.com/597545/53445625-d889b980-3a75-11e9-9303-93504ff065d6.png)

only shows one device... logitech g930's should also be in the list...

**Comment by mbc843** [comment]
Nice, this is working now at least for me! Thanks!
