### ISSUE TITLE
Hotkeys do not work even after 4.12

### ISSUE THREAD

**Issue by NeckBeardPrince** [Belphemur/SoundSwitch#324]
#314 This issue still remains after 4.12

**Comment by VeNoMouS** [comment]
Second that.

**Comment by Belphemur** [comment]
Here is what we're going to do.

1. Close SoundSwitch
1. Re-download the latest version
1. Choose to delete existing configuration
1. Reconfigure SoundSwitch
    * Try changing the hot keys

If it still doesn't work, I'll need:

A zip with the folder `%appdata%/SoundSwitch` (just type that in the explorer and zip the content, you can attach it to your comment on GitHub).

Couple of screenshots:
1. Windows Sound Menu
1. SoundSwitch Setting menu (with all the playback devices)
1. When you left click on the systray icon

**Comment by VeNoMouS** [comment]
Ok @Belphemur i'll give it a try

**Comment by VeNoMouS** [comment]
@Belphemur i noticed this from the logs..

from when i tried to change the bind... and back again and switch device..
```
{"@t":"2019-02-26T21:00:04.3612176Z","@mt":"Unregister previous hotkeys {hotkeys}","hotkeys":"Alt+Control+F8: True","ThreadId":1,"EnvironmentUserName":"firefly\\venom"}
{"@t":"2019-02-26T21:00:04.3622176Z","@mt":"Unregistering Hotkeys: {hotkeys}","hotkeys":"Alt+Control+F8: True","ThreadId":8,"EnvironmentUserName":"firefly\\venom"}
{"@t":"2019-02-26T21:00:04.3632173Z","@mt":"Unregistered previous hotkeys {hotkeys}","hotkeys":"Alt+Control+F8: True","ThreadId":1,"EnvironmentUserName":"firefly\\venom"}
{"@t":"2019-02-26T21:00:04.3632173Z","@mt":"Registering Hotkeys: {hotkeys}","hotkeys":"Alt+Control+F11: True","ThreadId":8,"EnvironmentUserName":"firefly\\venom"}
{"@t":"2019-02-26T21:00:04.3632173Z","@mt":"New Hotkeys registered {hotkeys}","hotkeys":"Alt+Control+F11: True","ThreadId":1,"EnvironmentUserName":"firefly\\venom"}
{"@t":"2019-02-26T21:00:04.3632173Z","@mt":"Saving configuration ","@l":"Debug","ThreadId":1,"EnvironmentUserName":"firefly\\venom"}
{"@t":"2019-02-26T21:00:39.3322486Z","@mt":"No devices available","@l":"Error","ThreadId":8,"EnvironmentUserName":"firefly\\venom"}
{"@t":"2019-02-26T21:00:41.5142355Z","@mt":"No devices available","@l":"Error","ThreadId":8,"EnvironmentUserName":"firefly\\venom"}
```

**Comment by VeNoMouS** [comment]
@Belphemur blowing away config on reinstall with `remove existing settings` *WORKED*... can confirm both devices now appear on systray when clicked...  and binding works.

**Comment by Belphemur** [comment]
Yep that what I thought, you might have had a corrupted configuration 
and restarting from a clean state was the way to go.

**Comment by Belphemur** [comment]
@NeckBeardPrince Since it worked for @VeNoMouS, can you also try reinstalling SoundSwitch ?

If I don't hear anything in the following days, I'll consider the issue closed.

**Comment by NeckBeardPrince** [comment]
@Belphemur  Boom baby!
