### ISSUE TITLE
[Feature] Switch device on single click on tray icon

### ISSUE THREAD

**Issue by K900** [Belphemur/SoundSwitch#325]
I only have two outputs on my PC: my headphones and my speakers, both connected at all times. That makes the single click menu on the tray icon largely useless for me. An option to cycle devices on a single click instead would be very welcome :)

**Comment by Belphemur** [comment]
Hello,

As per the section **Usage** of the Readme, you can double click on the systray icon to switch the playback device.

I've no plan to make it a single click.
