### ISSUE TITLE
Soundswitch crash at start when no internet

### ISSUE THREAD

**Issue by nvypwr** [Belphemur/SoundSwitch#326]
First of all I'd like to apologize if I somewhat violate the format, I am not familiar with GitHub.

I'd like to report an issue that has been present ever since I had started using SoundSwitch. I always use shortcut keys to switch between Headset and Speakers, but sometimes SoundSwitch does not respond right after logging in. I can't literally pinpoint the cause since it randomly happens. When I right click on SoundSwitch on taskbar, it literally stops responding, and forces me to end the task through Task Manager. After a forced restart of it SoundSwitch works just fine.

The issue is exactly the same with: https://github.com/Belphemur/SoundSwitch/issues/176

My system is Windows 7 (x64) and I'm using SoundSwitch version 4.11.6912.39455
Log File: [SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/2919386/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Hello, 

Can you try firs the latest version? (4.12)

A lot of change has been made that could resolve your crash. 

________________________________

**Comment by nvypwr** [comment]
Hi, I followed your advice and installed it right away a few days ago and unfortunately just now the problem surged again.

**Comment by Belphemur** [comment]
Hello,

Can you zip the content of the folder %appdata%/SoundSwitch and attach 
it to a comment here ?

It will contains the logs of the app and will help me understand what is 
happening.

Also, does it happens randomly or after a return from sleep ?

**Comment by nvypwr** [comment]
Hey there.
The contents of the requested folder is here:
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/2927838/SoundSwitch.zip)

As for when it happens, after booting. I haven't tested the issue for sleep. I didn't wake my PC from sleep in today's incident.

**Comment by Belphemur** [comment]
I might have a workaround for you.

Disable the auto-update. It seems SoundSwitch crash at start because it's trying to check for update, and well ... it can't.

**Comment by nvypwr** [comment]
Truly bizzare. Interestingly the computer is directly connected to the router with RJ45 cable...

I also just remembered something rather odd. Until I installed the latest version my settings for SoundSwitch was "Notify me when updates are available". And until you warned me updating to the latest version I had not even received any update notifications, not even by manually prompting it. Maybe is this somewhat related with SoundSwitch not being able to connect? Even so I'm still dumbfounded by the fact that it never actually checked for updates... And the main issue was still happening by the way.

I'll monitor the behaviour of the SoundSwitch and post updates. I'll also test whether if the issue is also triggered by Sleep and Wake Up cycle.

Thanks in advance.

**Comment by Belphemur** [comment]
Well your log has a connection error into it. And the only moment 
SoundSwitch try to connect to internet, is to check update.

Also it would explain the random crash, since it check every 12 hours 
and at start.

To be exact, it complains that it can't start a TLS/SSL connection with 
the server. Do you have any type of proxy or filtering that would stop 
this from hapening ?

**Comment by nvypwr** [comment]
I just booted the computer with "Never Check for Updates" settings from last night and again, SoundSwitch crashed.

As for the question my ISP is notorious for filtering so I have manual DNS settings for both IPv4 and IPv6. I have just checked my network settings and for some reason IPv6 has "No Network Access". Could this have any relation with the issue at hand?

**Comment by Belphemur** [comment]
That's unexpected. 

Can you send the logs again? 

Changing the dns shouldn't have any impact on the connection or that would be for your whole OS (windows) . 

About Ipv6 it's your OS that decide if it uses it or not. 

________________________________

**Comment by nvypwr** [comment]
Here it is. 

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/2931470/SoundSwitch.zip)

**Comment by nvypwr** [comment]
Hello again. I've been monitoring SoundSwitch's behaviour for the past few days and there had been no issues as of late for some reason. Although I still don't know the cause of the problem I had... One thing I can report is that we have recently changed our router. Not sure if this had any influence with the problem. I'll continue checking the behaviour for any problems.

**Comment by Belphemur** [comment]
Glad to hear !

Well I'll close it for now. If the issue appear again, don't hesitate to reopen it.

**Comment by nvypwr** [comment]
I'm sorry to inform you that the issue surged again.
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/2991220/SoundSwitch.zip)
