### ISSUE TITLE
Installer crashing

### ISSUE THREAD

**Issue by LaBeNo** [Belphemur/SoundSwitch#327]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
Newly downloaded installer (v4.12.6997.37167_Release_Installer) exits immediately. Nothing seems to be installed, no error message.

**Comment by Belphemur** [comment]
Hello, 

Next to the installer you have a log file with the same name. Can you attach it to a comment on GitHub? 

If you don't have it, can you re-download the installer? 

________________________________
