### ISSUE TITLE
Allow renaming devices

### ISSUE THREAD

**Issue by kenijo** [Belphemur/SoundSwitch#329]
My laptop is connected to a docking station and a headset. This means I have a pretty long list of devices with similar names:
* Headset Earphones (Platronics C325-M)
* Speaker/HP (Realtek High Definition Audio)
* Headphones (Thinkpad Dock USB Audio)
* Internal AUX Jack (High Definition Audio Device)
* Speakers (High Definition Audio Device)

It would be nice to have the ability to assign them names that are easier to read and spot when left clicking on the SoundSwitch systray icon and maybe also reorder them.
It would be easier to read this:
* Skype Headphones
* Bose Headphones
* Laptop Speakers
* Nice Speakers

What do you think?

**Comment by Belphemur** [comment]
Hello,

This is outside the scope of the application.
You can rename the devices in the Playback Menu of Windows.

**Comment by kenijo** [comment]
Thanks, I didn't know that! Can we hide the device description though?

**Comment by Belphemur** [comment]
Not really, it's what's Windows API is giving me.
