### ISSUE TITLE
[Bug] No Logitech G533 after updating soundswitch to 4.13

### ISSUE THREAD

**Issue by Clatoo** [Belphemur/SoundSwitch#331]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

**Comment by Clatoo** [comment]
Was like that in previous version wich I don't know the version number.  Should read "after changing G533 receiver USB port". Sorry for the wrong title.

**Comment by Belphemur** [comment]
Hello,


Can you reinstall the app and choose to remove all data?


You'll have to reconfigure your list of device after that.


I think you might have a corrupted configuration.


________________________________
