### ISSUE TITLE
Feature Request: Delay Launch for SoundSwitch

### ISSUE THREAD

**Issue by nvypwr** [Belphemur/SoundSwitch#332]
I'm sorry to inform you that the issue surged again.
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/2991220/SoundSwitch.zip)

_Originally posted by @nvypwr in https://github.com/Belphemur/SoundSwitch/issues/326#issuecomment-475142286_

However this time I have a potential culprit about the issue. While it may sound unrelated I have noticed Soundswitch runs **before** than the initialization of the network card. Sometimes the timing is just right, sometimes it just crashes.
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/2999197/SoundSwitch.zip)

---------------------------------------------------------------------------------------------------------------------------------

Today I have decided to test out a way to delay SoundSwitch's launch with a third party software. Apparently delaying SoundSwitch by approximately 5 seconds does not result in the problem I have been having. Since I couldn't find a way to initialize my network card faster upon booting I'd like to change the topic into a feature request. Said feature being able to manually adjust initialization delay of SoundSwitch if possible.

**Comment by FireEmerald** [comment]
As this will most likely not get implemented, here's a simple workaround for anyone else who would like to start any application delayed:

1. Press `[WIN]+[R]`, enter `shell:startup` and press OK, a folder should open.
2. Create a file called `delay.cmd` with the following content and you're done:
``` batch
@echo off
REM Delay Startup Script
REM Requires Windows Vista or later!

timeout 5 > nul
start /d "%ProgramFiles%\SoundSwitch" SoundSwitch.exe
```
