### ISSUE TITLE
Request: custom volume per device

### ISSUE THREAD

**Issue by SubSonix** [Belphemur/SoundSwitch#333]
Just hoping that this is something that might be possible?

Basically I use 30% volume for my desktop speakers and 50% for my headphones.

Would love if you could make it so that when switching devices, it switches volume level too :)

Thanks for the wonderful program btw :D

*EDIT* Also, a mute icon would be great too :)

**Comment by tonyrulez** [comment]
This works for me by defaul,  natively on Windows 10, even without the SoundSwitch app. I have the speakers set to 64% and the headphone set to 25%. Whenever I switch output (be it SoundSwitch or the Windows-way), the volume stays at the set level.

**Comment by FireEmerald** [comment]
As @tonyrulez already explained, this does work out of the box in Windows 10.

I don't know if it also works on Windows 7 the same, but if your are on Windows 7 and it does not work, i would suggest to update to 10. Windows 7 only get's security updates until January 2020 (EOL).
