### ISSUE TITLE
Don't launch the application after a silent install

### ISSUE THREAD

**Issue by ducksys** [Belphemur/SoundSwitch#336]
Please modify the installer script and add "skipifsilent" to the run section for
"{app}\SoundSwitch.exe"

**Comment by Belphemur** [comment]
I can't do this.

If I do it, when auto updating, SoundSwitch won't restart. It relies on the fact the installer restart the application.

**Comment by FireEmerald** [comment]
Should the installer really start the application by default?

There's normally a checkbox at the end of the installation process called "Start <AppName> after installation".

**Comment by Belphemur** [comment]
The checkbox is opt-out. 

It's usual for the app to be ran by the installer at the end. 

What it's asked now, is to not launch the app when the installer is launched with silent mode. 

This mode is currently only used when autoupdate or automatic install from system configurator. 

________________________________
