### ISSUE TITLE
Missing second playback device with same name

### ISSUE THREAD

**Issue by ttk** [Belphemur/SoundSwitch#338]
I have a dual monitor setup, and each monitor is identical and supports HDMI/DisplayPort for audio.  In my windows device list, it assigns each monitor the name: "LG HDR 4K".  In the SoundSwitch setting screen, it only lists one of these playback devices instead of both.  See the screenshot:

![image](https://user-images.githubusercontent.com/1742711/57251338-2dfebb80-700f-11e9-852b-ff7573e47771.png)

If I change the name of the playback devices to:
`LG HDR 4K - Center`
`LG HDR 4K - Left`

Then SoundSwitch uniquely detects each of them, and it works as expected.  I feel that SoundSwitch should be able to handle multiple playback devices with the same name without any special workaround by the user.

**Comment by Belphemur** [comment]
Fixed in v4.15.1 :)
