### ISSUE TITLE
Microphone level is reset to 0 after switching

### ISSUE THREAD

**Issue by stonko1994** [Belphemur/SoundSwitch#339]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

## Description
Usually I have the level of the microphone set at 80%.

## Problem
Everytime I switch the output device via the shortcut (not sure if this also happens without shortcut) the microphone level is reset to 0.

## Bug

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6216959/57552524-73531e00-736c-11e9-9ee2-7684c81fe9f1.gif)

[SoundSwitch.zip (Logs)](https://github.com/Belphemur/SoundSwitch/files/3167908/SoundSwitch.zip)

_Let me know if you need more information_

**Comment by Belphemur** [comment]
This look more like some problem with Another program that is setting it ...

SoundSwitch doesn't interact with the volume.

**Comment by stonko1994** [comment]
Alright, I will continue to investigate. (Closing for now)
