### ISSUE TITLE
Config needed error

### ISSUE THREAD

**Issue by randompherret** [Belphemur/SoundSwitch#34]
Windows 10 64x
Fresh install

When pressing the Hotkey I get an error that configuration is needed. However if I click the icon and switch it the audio does switch.

Contents of the SoundSwitchConfiguration.json are:

{"SelectedPlaybackDeviceList":["Speakers (High Definition Audio Device)","Speakers (Plantronics Savi 7xx)"],"SelectedRecordingDeviceList":[],"LastPlaybackActive":"Speakers (Plantronics Savi 7xx)","FirstRun":false,"PlaybackHotKeys":{"Keys":122,"Modifier":3},"RecordingHotKeys":{"Keys":172,"Modifier":0},"ChangeCommunications":false,"UpdateCheckInterval":43200}

**Comment by Belphemur** [comment]
Hello,

Can you try to set the hotkeys to another set of keys and see if that does work?

It's possible you selected a shortcut already registered by another application.

-----Message d'origine-----
De : "Derek Teague" <notifications@github.com>
Envoyé : ‎26-‎11-‎15 00:25
À : "Belphemur/SoundSwitch" <SoundSwitch@noreply.github.com>
Objet : [SoundSwitch] Config needed error (#34)

Windows 10 64x
Fresh install
When pressing the Hotkey I get an error that configuration is needed. However if I click the icon and switch it the audio does switch.
Contents of the SoundSwitchConfiguration.json are:
{"SelectedPlaybackDeviceList":["Speakers (High Definition Audio Device)","Speakers (Plantronics Savi 7xx)"],"SelectedRecordingDeviceList":[],"LastPlaybackActive":"Speakers (Plantronics Savi 7xx)","FirstRun":false,"PlaybackHotKeys":{"Keys":122,"Modifier":3},"RecordingHotKeys":{"Keys":172,"Modifier":0},"ChangeCommunications":false,"UpdateCheckInterval":43200}

**Comment by randompherret** [comment]
Switching it back to "ctrl+alt+f11" does make it work again. I am using an unusual key, but the key did work in windows 7.

The key I was trying to use is "BrowserHome". Chaning it to "ctrl+BrowserHome" makes it work as well so for now I guess that will work for me.

Thanks.
