### ISSUE TITLE
Allow multiple hotkeys for same action

### ISSUE THREAD

**Issue by tristanwilson111** [Belphemur/SoundSwitch#341]
**User Story**
On my laptop (Lenovo Legion y740), I have two Macro keys (M1 & M2, which are mapped to F13 and F14). I use it as a desktop, comined with my Razer Blackwidow keyboard as my main keyboard.

Holding Shift+F1 results in Shift+F1 hotkey, and I haven't found a way to emulate F13 successfully.

Clicking my "M1" key uses F13 in your program, but my Razer Blackwidow software doesn't allow F13 to be used (Clicking my M1 key outputs blank hotkey in Razer Synapse)

Lenovo suggests using "Magic Y Key" software from the Microsoft store to switch M1 to a different hotkey, but (of course), this software is unavailable in Canada.

**Possible Solution**
A way to resolve this would be allowing two different hotkeys; A complicated keypress for my Razer keyboard, and F13 for my M1 key. I can see other reasons other people may also want to use multiple hotkeys.

**Comment by FireEmerald** [comment]
I don't know if we really need such a feature as your use case is a bit _fuzzy_.

You could register something like `[CTRL]+[Shift]+[F11]` and it would work on all your devices.
