### ISSUE TITLE
Audio out of only one source

### ISSUE THREAD

**Issue by chubbyloves** [Belphemur/SoundSwitch#342]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
SoundSwitch no only switches between devices. I also cannot manually switch between outputs anymore. Sound only plays out of my headphones. I have tried uninstalling and reinstalling drivers and restarts. Nothing seems to be able to get sound out of my speaker bar anymore. I verified it still worked with my laptop, so it is just the pc. This issue occurred after I removed SoundSwitch and even when it is uninstalled this issue persists. I am willing to try just about anything to get my speaker back.

**Comment by Belphemur** [comment]
Hello,
What Windows are you using ?

Did you check what was the current windows settings ?

**Comment by chubbyloves** [comment]
I checked everything, fixed it by reinstalling Windows.
