### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by KucherenkoZZZ** [Belphemur/SoundSwitch#344]
Dont know if its just me.. SoundSwitch doesn't work in Chrome browser for me anymore, i tried a different version of chrome, different versions of SoundSwitch but nothing help when you press the hotkey it creates minor delay like it should be but then nothing happens, the sound still comes from headphones. Btw works good in Canary browser

**Comment by FireEmerald** [comment]
Instead of switching the playback device using SoundSwitch, could you test if the problem doesn't occur if you use the windows menu instead?

**Comment by KucherenkoZZZ** [comment]
@FireEmerald You are right, even with a Windows menu not working..
