### ISSUE TITLE
Icon in start menu is small when medium icon size is selected

### ISSUE THREAD

**Issue by stephen147** [Belphemur/SoundSwitch#345]
See screenshot of my menu, as you can see the icon should be bigger when medium size is selected.

![sc](https://i.imgur.com/WccOTjI.png)

**Comment by Belphemur** [comment]
Hello,

Unfortunately I have no control on this.

I did pack into the icon the 256x256 version.

You can see it when using the search.

![image](https://user-images.githubusercontent.com/197810/59869732-087d0580-9362-11e9-837c-8a5f9ac7bc59.png)

**Comment by stephen147** [comment]
OK. Maybe it's reserved for the app store programs.

Thanks.

**Comment by stephen147** [comment]
Ps. I've contacted MS about this issue. Quite a few are all small even some icons from Microsoft.
