### ISSUE TITLE
[Feature Request] Switch output by a shortcut without SoundSwitch running in tray

### ISSUE THREAD

**Issue by i486** [Belphemur/SoundSwitch#346]
I have been using dedicated sound card for many years with some 3rd party FP/SPKR output switcher utility that just need to run once from desktop. 

You double click on that EXE > output is changed to REAR SPEAKER, no tray, no GUI, nothing.
You double click again on that EXE > output is changed to FRONT PANEL and so on.

Is it possible to implement that feature in SoundSwitch?

It could be like this
1. Install SoundSwitch
2. Setting > Select devices to cycle through
3. "Create Shortcut" button right beside "Hotkeys". Press Create Shortcut. Shortcut is created on Desktop.
4. Double click on the shortcut to cycle through. SoundSwitch switches output without showing GUI and terminates.

Thanks!

**Comment by caesay** [comment]
The original DefSound application is a command line utility which can do this

**Comment by caesay** [comment]
You can also use http://www.nirsoft.net/utils/nircmd.html
