### ISSUE TITLE
Hotkey not working

### ISSUE THREAD

**Issue by choskey** [Belphemur/SoundSwitch#347]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
Since recent SoundSwitch update hotkey (Ctl-Alt-F1) is no longer working.  I have restarted computer and I have restarted SoundSwitch and hotkey still doesn't work.  
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/3315586/SoundSwitch.zip)

**Comment by KucherenkoZZZ** [comment]
I have the same problem, i used a "Pause" one-key hotkey and now its not working, did you find a solution?

**Comment by choskey** [comment]
No solution

**Comment by FireEmerald** [comment]
First of all try to uninstall Sound Switch. Then make sure the configuration files are also deleted, they are located at `%AppData%\SoundSwitch`. Reinstall the application and try any **unused** hotkey combination.

**Comment by choskey** [comment]
That solved it!  Thank you!

**Comment by devhl-labs** [comment]
Simply closing Sound Switch, removing the sound switch config, and starting sound switch again was enough to fix this for me.
