### ISSUE TITLE
Default Communication Device support

### ISSUE THREAD

**Issue by ziemniok99** [Belphemur/SoundSwitch#348]
**User Story**
I have Razer Nari Ultimate and in this headphones whith wheel on it to regulate sound from chat (Default communication devive) and from Game (Default device). And a speakers so actually I have 3 devicec registerster on my system, but when I am using Headphones I should have:
Default Comunnication Device: Razer Nari Ultimate - Chat
Default Device: Razer Nari Ultimate - Game
When using speaker I should have:
Default Comunnication Device: Speaker
Default Device: Speaker

**Posibble Solution**
Make something like groups select 1 or 2 devices on group. 1 is default device, 2 is default communication device.

**Comment by RoBiK75** [comment]
I have the same issue.

**Comment by supleed2** [comment]
+1 I'd like to suggest the idea of "presets" that are user made? An example of how I'd set it up:
A)
Default Playback: USB Headset Game
Default Communication Playback: USB Headset Chat
Default (and Communication) Mic: USB Headset

B)
Default (and Communication) Playback: Speaker
Default (and Communication) Mic: Separate USB Mic

**Comment by Bluscream** [comment]
I would love to have the same thing, please @Belphemur

**Comment by DanteSech** [comment]
I need this feature, I have been using this application for a year and I love it, but I just bought a wireless headset, a SteelSeries Arctis 7 but I still use my old Arctis 5 when I charge the other headset, the problem is that every time I want to use discord I must go to Windows configuration to change the default communication device. I would like there to be an option to link a communication device with a playback device.

**Comment by Belphemur** [comment]
I think I'll add this to the profile feature.
You'll be able to choose a communication device into the interface.

Also, about Discord, you can already use the profile feature to change the default device of Discord and have the right one selected.

**Comment by supleed2** [comment]
Is it possible to make the profiles selectable manually, like an option to switch out the current menu for profile menu?
I'd rather switch profile manually than try to tie it to every app since I use multiple devices on Discord but it depends on what else I'm doing at the same time.

**Comment by Belphemur** [comment]
Yes, you don't need to set an app. 
You can simply set the hotkey you want. 

I really need to rework that ui 

Sent from Nine
________________________________
