### ISSUE TITLE
Unable to download installer - SSL Issues

### ISSUE THREAD

**Issue by TyNavarre** [Belphemur/SoundSwitch#349]
When trying to download the latest install from https://soundswitch.aaflalo.me/ two of the proxy services we use are blocking the connection because it thinks that the site is using a Proxy or Anonymizer.

Are you guys using some kind of SSL rewriting or other kind of proxy service that would be messing with the SSL chain? If so that would make the site unreachable in many corporate environments.

**Comment by Belphemur** [comment]
Hello,

Not at all, I'm using github release, as you can see from the link.
GitHub is using AWS S3 to store the release, the whole redirection that happens is related to their system.

I don't think they do any SSL rewriting, just good old redirect 302.

**Comment by TyNavarre** [comment]
No big deal, thanks for checking it out! Corporate firewalls/proxies are always more sensitive on this stuff.
