### ISSUE TITLE
[Feature request] option to hide tray icon

### ISSUE THREAD

**Issue by henriklb** [Belphemur/SoundSwitch#352]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
I'd love an option to hide soundswitch tray icon

**Comment by Belphemur** [comment]
Since the access to the settings menu come from the tray icon, I'm not keen into making it removable. 

Currently you can hide it in the Windows' settings. 

________________________________
