### ISSUE TITLE
Soundswitch shortcut doesn't work anymore

### ISSUE THREAD

**Issue by dayzlun** [Belphemur/SoundSwitch#354]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
It worked for me for more than 6 months with no problem, but from a week ago, it doesn't work anymore. I tried to reinstall and delete appdata/soundswitch folder, still doesn't work.

My shortcut key to switch between output device was 'pause', but now whenever i register a key it adds a '0' in front like : '0 + Pause'. but Again when I hit on 0 + Pause nothing happens either.

[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/3560013/SoundSwitch.zip)

**Comment by JeffreySouza** [comment]
I have the same issue

**Comment by f03n1x** [comment]
Same issue, it's been completely fine, but after a windows update (not sure if this is related or not) I was not able to use shortcuts, I actually had trouble getting it to pop up at all to begin with so I decided to install the latest version.

**Comment by marvelousmax** [comment]
I, too, always used the pause button and since updating it no longer works. However, for me it simply doesn't change anything in the shortcut field at all. It will accept some shortcuts, but ignores the column of buttons including 'delete' 'page down' and 'scroll lock'. The default shortcut works, but I'd love to have it bound to a single button again.

**Comment by korodic** [comment]
Came here to report the same symptoms, but its only for playback swapping. My recording devices still switch when pressing the hotkey.

**Comment by Belphemur** [comment]
I apologize to all of you for this issue. 

I haven't had the time to work on SoundSwitch lately. I'll try to make some time this week-end. 
________________________________
