### ISSUE TITLE
Cycle throu selected  not working

### ISSUE THREAD

**Issue by jahodaradek** [Belphemur/SoundSwitch#357]
Cycle through selected deviced dont work. Cycle throu al ldevices works.

**Comment by Minlack** [comment]
I'm having the same issue :(

**Comment by Belphemur** [comment]
Hello, 

Can you stop SoundSwitch, then with the explorer go to 

%appdata%/SoundSwitch 
And delete all the files?

Now relaunch SoundSwitch and you'll just have to select the devices you want to use.

With the previous version the data got corrupted. 

________________________________

**Comment by ManosTsir** [comment]
I have the same problem since the last update. Did what you said but nothing changed.

Any other ideas?

**Comment by Belphemur** [comment]
What happens when you left click on the icon? 

Can you send me the content of the %appdata%/SoundSwitch folder as a zip? 

________________________________

**Comment by ManosTsir** [comment]
When I left click the icon it only shows me one of the two inputs that I have selected. But if I open settings they both show selected.

Here is the folder: https://we.tl/t-eyMDUbb9ov

**Comment by casperinmd** [comment]
> Cycle through selected deviced dont work. Cycle throu al ldevices works.
Same issue myself. I thought it was a Windows update though as I did not initially update SoundSwitch. I just did SoundSwitch to the latest but no help. Setting to cycle through all works.

I have attached my %appdata%/SoundSwitch folder as well.

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/3838789/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Can you try with the v4.15.1? 

________________________________

**Comment by ManosTsir** [comment]
Done! Fixed! Thanks man! :D

**Comment by jahodaradek** [comment]
Yeah can confirm, updating and deleting old settings works.
