### ISSUE TITLE
Missing Audio Device

### ISSUE THREAD

**Issue by Overload86** [Belphemur/SoundSwitch#358]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
![image](https://user-images.githubusercontent.com/25252217/68674658-90a0b900-0556-11ea-867c-c2bcd2b92979.png)
![image](https://user-images.githubusercontent.com/25252217/68674689-a7471000-0556-11ea-8fce-90e5d1be2a99.png)
My TX-NR709 is not considered "connected" anymore and I have no clue why. Worked fine before I updated today, unfortunately I don't know which version I was on before, but downgrading to 4.12 did not fix it at least.
Currently on latest and deleted the %appdata%\soundswitch folder to no avail.

**Comment by Belphemur** [comment]
Hello, 

TV are not as your usual audio device...

The only I found to fix this is to go into Windows device manager and Uninstall the TV. Then ask it to scan for devices. 

________________________________

**Comment by Overload86** [comment]
First of all, it's not a TV, it's a 5.1 Surround receiver, that is plugged in through HDMI. And secondly: It has worked before, I am using SoundSwitch for years now.

**Comment by Belphemur** [comment]
Win + X  > Device Manager > Audio inputs and outputs > Right click on device > Uninstall device

In the same App : Action > Scan for hardware changes.

It's a common issue with HDMI in general.

**Comment by Overload86** [comment]
Did that, didn't do anything. Still shows up as disconnected in SoundSwitch (by the way, choosing the output directly in windows works perfectly fine). If I make SoundSwitch switch all devices instead of only checked, it works as well. Maybe you could make it switch all checked devices, regardless if it thinks they are disconnected?

**Comment by Overload86** [comment]
![image](https://user-images.githubusercontent.com/25252217/68681239-60134c00-0563-11ea-87d5-f246752c3cf6.png)
![image](https://user-images.githubusercontent.com/25252217/68681266-69041d80-0563-11ea-867c-57efcfd07c65.png)
Just as proof ^^

**Comment by Gothico74** [comment]
Same for me.
And also it's nVidia High Definition Sound on Dell Monitor (DisplayPort if it matters)
I can add my Monitor by hand but this Program won't switch to it.
I deleted the appdata but no avail.

**Comment by Gothico74** [comment]
Log is full of errors

[https://pastebin.com/iPxxCX4t](url)

**Comment by Overload86** [comment]
Just as a side note, I just tried to completely uninstall SoundSwitch, reinstalled latest. Same problem
uninstalled again and went back to 4.10. Same problem. Uninstalled again and tried a different program (audioswitcher). Works. But I really liked your program more, because I can cycle inputs with one button, where the other is not maintained since 2018 and needs one hotkey per device.

**Comment by SiriusVI87** [comment]
I have the exact same problem. Everything worked until today. Now suddenly my Samsung Smart TV (connected via HDMI) is listed as disconnected. Reverting to an earlier version of the software has not helped.

**Comment by dizzyblyat** [comment]
Bump. Seems that HDMI devices appear to be disconnected in the software since the last patch.
