### ISSUE TITLE
Shortcut Not Working

### ISSUE THREAD

**Issue by Coggi** [Belphemur/SoundSwitch#359]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/3837220/SoundSwitch.zip)
Hi,
my soundswitch stopped working, the shortcut seems to not register anymore.
Whenever I launch soundswitch or try to remove/add the shortcut a notification come up and throws an error.

I attach the logs and config folder, also this is happening with the new build too

Thank you!

**Comment by Belphemur** [comment]
Hello,

From the log, it seems another app has that HotKey already registered.

I would advice trying another combination, I know Intel GPU Application is using it.

**Comment by Coggi** [comment]
I did install Intel GPU app, but i've since removed it and the shorcut can't be set.
However I did try another like alt + ctrl + f10 or ctrl + f2 it seems to register (doesn't give the error) but then it does nothing :/

Also idk why but one of my output it's not seen as connected even if it is and it's working :O
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/3837712/SoundSwitch.zip)
new log attached

thank you

**Comment by Belphemur** [comment]
Can you try with the v4.15.1?



________________________________

**Comment by Coggi** [comment]
Thanks!

Now everything's working fine!
Only the default shortcut is not working but I guess that's some issue with
the Intel GPU software not unregistering their shortcut when you uninstall
their product :/

Again, thank you very much!
