### ISSUE TITLE
Working device showing as "Disconnected" after latest update

### ISSUE THREAD

**Issue by asherbasher** [Belphemur/SoundSwitch#360]
![QnMKcqQsZZ](https://user-images.githubusercontent.com/10160470/68710935-7683cc80-0590-11ea-9e82-fe238e720b13.png)

In the attached image you can see my "Headphones" device is connected and working but SoundSwitch no longer recognises it as connected for some reason. Only just started happening and I've been using SoundSwitch for years.

**Comment by asherbasher** [comment]
Just downgraded to the previous version (4.14.0.31865) and it's actually the same there.

The difference is, with this previous version I am still able to switch between the two devices with my shortcut, whereas on the latest version it doesn't work, and my device doesn't appear on the drop down menu when right clicking the SoundSwitch icon in the system tray.

**Comment by Walls3k** [comment]
Same issue here, but with my speakers instead of my headset.

**Comment by asherbasher** [comment]
> Same issue here, but with my speakers instead of my headset.

I rolled back to the previous version (https://github.com/Belphemur/SoundSwitch/releases/download/v4.14.0/SoundSwitch_v4.14.0.31865_Release_Installer.exe) and it allows me to switch between them again (even though it still shows one as disconnected).

**Comment by Walls3k** [comment]
Just did the same. I observed the same as you, the older version works but it still shows it as disconnected. I wonder how long this bug has been floating around? Hrm.

**Comment by Belphemur** [comment]
Can you try with the v4.15.1?


________________________________

**Comment by asherbasher** [comment]
> Can you try with the v4.15.1?

It's working as usual. 👍

**Comment by Walls3k** [comment]
Yep, everything seems to be working normally again! Thanks for the quick update! :)
