### ISSUE TITLE
Speakers registering as disconnected in SoundSwitch since update 4.15.0.40592

### ISSUE THREAD

**Issue by Walls3k** [Belphemur/SoundSwitch#361]
Since today's update (4.15.0.40592) SoundSwitch has not been letting me switch to my speakers as an output. I did a little investigation of my own, and it appears that soundswitch is registering my speakers as "disconnected" in the playback tab, now. They're clearly not, and I can switch to them manually and playback is fine. 

I use both a wireless Logitech headset mic and my onboard sound, and use soundswitch to cycle between them as needed. 

This error started with today's update.

[soundswitch directory.zip](https://github.com/Belphemur/SoundSwitch/files/3838291/soundswitch.directory.zip)

**Comment by simbesh** [comment]
Also experiencing this exact issue

**Comment by Belphemur** [comment]
Can you try with the v4.15.1? 



________________________________

**Comment by simbesh** [comment]
@Belphemur Had to reconfigure my selected devices, and its working 😍

**Comment by Walls3k** [comment]
Working now, thanks :)
