### ISSUE TITLE
Possible Windows/Nvidia update causing persistent 4.10 and 4.15 issues.

### ISSUE THREAD

**Issue by SimplisticBeing** [Belphemur/SoundSwitch#363]
I have been using SoundSwitch for over a year now. I have updated when possible up to 4.10. I haven't had any issues up until these last few days after updating to 4.15. SoundSwitch now reports one of my outputs as disconnected, which is not and is capable of being used. Sadly this has rendered SoundSwitch pointless. I only have 2 devices to switch between and it no longer understands a connection to my TV/Avermedia passthrough/Nvidia outputs.

I decided to update to 4.15 after having no issues in updates before. This is the update where the issue arose. After switching back to 4.10 the issue persists. SoundSwitch refuses to recognize a working input as Connected, thus I am unable to use it with SoundSwitch.

I believe this may be related to a recent Windows Update or Nvidia Driver update as I have recently had major updates to both of these from Windows 1903 to 1909 and from Nvidia Driver 436.30 to 441.20.

Considering the simplicity of the program I am unsure what else to try. I have reverted Windows, reverted Nvidia drivers as well as SoundSwitch installs from scratch. I am at a loss but am sure something has changed in that the stable 4.10 no longer works as well.

Update 1.) Changing "Cycle through" in Settings to All Devices does allow selection of my TV and works as intended. But now I have to scroll through 1 extra output. Not a major issue, but definitely not what I've been doing for over a year. Thanks in advance for the help.
![!Connected but Not](https://user-images.githubusercontent.com/57699886/68738823-50bcee80-05b5-11ea-8d9d-0b4b0886f408.PNG)

Update 2.) I decided to go back to 4.10 until a fix is found. SoundSwitch still shows it as Disconnected, but I am able to use it properly. I removed all settings after uninstall and during a reinstall I had settings wiped again. This seems to have fixed my issue in 4.10 where some 4.15 settings may somehow cause issue when reverting without deleting settings during uninstall AND during re-install. Sound Switch is working properly on 4.10 after doing these steps.

**Comment by Belphemur** [comment]
Hello, 

Can you try with the latest version v4.15.1? 

Also when installing it choose to delete SoundSwitch data. 

You should be good then :) 
________________________________

**Comment by SimplisticBeing** [comment]
Thanks for the quick reply. Output Device is read as connected and works as
intended. Thanks bunches of oats.
