### ISSUE TITLE
Cannot Switch after the latest update

### ISSUE THREAD

**Issue by 666diabolus** [Belphemur/SoundSwitch#364]
After I upgraded SoundSwitch to the latest version, I can't  use the CTRL+ALT+F11 or Double Click to make a switch, is it just me or just another bug ?

**Comment by Belphemur** [comment]
Hello, 

Be sure you have the 4.15.1, go into settings and deselect everything. Select now the devices you need. 

________________________________

**Comment by fx02** [comment]
I fixed it by deinstalling and cleaning settings, then everything worked fine.
