### ISSUE TITLE
SoundSwitch crashes when switching to "Customized Sound Notification"

### ISSUE THREAD

**Issue by Overload86** [Belphemur/SoundSwitch#365]
Like the title says. Also when choosing "Banner" there is a button with an ellipsis symbol, which also crashes the application, when you click it. (Probably only supposed to appear on custom sound setting and possibly related to each other?)

**Comment by Belphemur** [comment]
When SoundSwitch crash it generate a zip file with all the data.

Can you attach it to the issue ?

**Comment by Belphemur** [comment]
I found the issue.

Should be fixed in v4.16
