### ISSUE TITLE
Would you like a translated readme in German?

### ISSUE THREAD

**Issue by Overload86** [Belphemur/SoundSwitch#366]
Don't know how else I would get in touch with you... I have taken the time to translate the whole readme into German, I did not translate the legal text at the bottom, left it as is and prefaced it with a warning that the legal text and the license are still valid and if not understood should refrain from using the software or making copies of it.

You can use (or don't) this document however you want, I don't need or want credit for the translation, just thought maybe it helps a few people. You would however have to reference in the code somewhere, that it should open "readme-de.html" when clicking on help, when the language is set to german or whatever. xD
[Readme-de.zip](https://github.com/Belphemur/SoundSwitch/files/3849946/Readme-de.zip)

**Comment by FireEmerald** [comment]
I read your translation and it's looking good to me so far. Some parts could need some improvements because they sound a little bit "bumpy" in german, but that's fine for now.

I didn't thought about translating the README until yet.

**Comment by Belphemur** [comment]
@FireEmerald if it's good for you, @Overload86 you can make an MR to add the Readme-de.md to the repository. I'll update the build script to generate the HTML file ;)
