### ISSUE TITLE
User can choose how the SoundSwitch Icon changes

### ISSUE THREAD

**Issue by xb0n3z** [Belphemur/SoundSwitch#368]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
Fresh install, deleted directories prior.
I always turn off notifications and rely on the taskbar icons to see what devices are selected.

I can switch sound devices with CTRL-ALT-F11 (task bar icon changes)
I can switch recording devices with CTRL-ALT-F7 (task bar icon DOES NOT change).

I can tell it switches recording devices if I turn on notifications such as banner.  But I preferred that the icon changed for whatever devices you were toggling to.

**Comment by Belphemur** [comment]
Hello,

I've changed the code for this in the latest version to fix issue #340 .
I didn't think that anybody was relying only on the recording part.

I'll add an option to choose to which type of device the icon should change.

**Comment by xb0n3z** [comment]
You're the best, thank you!  Comes in handy when streaming going from external mic to headset while using headset only for audio.

**Comment by Belphemur** [comment]
I've coded the whole feature. I'm just waiting for some translation and issue #369 to be done to release :)

**Comment by Belphemur** [comment]
You can download the latest version v4.16 to use the new feature ;)

**Comment by xb0n3z** [comment]
Thank you, really great work!  However, your gonna hate me ! :)   So the way the app seemed to work before was, if I pressed F11 it would change the speakers and also change the icon.  If I pressed F7 it would change the recording and also change the icon.   The icon would chnage for both and just display last changed icon for whatever was changed, playback or recording. 

Is there a way you can add the option for change icon for BOTH?  I have VR, Speakers, Headset, USB audio for studio recording which I'm always changing one or the other.  

Of course banners work great but I for whatever reason prefer to have banners off and reference the system icons.

Thank you again for your generosity and talent to the project!

**Comment by Belphemur** [comment]
@xb0n3z Done in v4.16.1 :)

Just need to update.
