### ISSUE TITLE
checking "Run as Admin" in kompatability mode under Win10 stops autostart on bootup

### ISSUE THREAD

**Issue by oDiDio** [Belphemur/SoundSwitch#370]
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/3877552/SoundSwitch.zip)

I (for a reason forgotten) set the checkmark "Runs as Admin" in the compatability tab for SoundSwitch. I noticed that it is not autostarting anymore. After some small testing it seems that running it as Admin keeps it from starting automatically. 
Checked registry and entry was there, also tried inserting it manually into the autostart folder. Both didnt work as long as it was running as admin.

**Comment by Belphemur** [comment]
Hello,

You don't need to run it as admin, I would even advise against it.
What is the reason behind this ?

**Comment by oDiDio** [comment]
As statet I dont know anymore. I was setting up a new PC and installing/redoing all my settings. Maybe something got mixed up.

Just wanted to let you know that there is a problem when run as admin, which seemed counterintuitive to me.

**Comment by Belphemur** [comment]
It's the way windows works with admin permission. 

We're adding in the registry for the current user to start SoundSwitch at boot time. 

The problem when you set the executable to be run as admin, Windows will ask you every time you run the program if you want to let it run with elevated right. 

I guess at boot time, windows refuse it for you then SoundSwitch don't run. 

Don't run SoundSwitch as admin.

________________________________
