### ISSUE TITLE
Support install through Chocolatey package manager

### ISSUE THREAD

**Issue by Xeevis** [Belphemur/SoundSwitch#372]
Hello, I'm using [Chocolatey Windows Package Manager](https://chocolatey.org/) to manage all of my installed software. SoundSwitch is the only one which I need to install/update manually outside this environment. Would be it possible to add support ? Thanks!

**Comment by FireEmerald** [comment]
Thanks for your idea. First of all keep in mind, that SoundSwitch does update itself completely without any user interaction if you enable it in the settings 😉

I don't know if this would be any problem for chocolatey.

**Comment by brogers5** [comment]
Coincidentally, I had created recently created [a community package request](https://github.com/chocolatey-community/chocolatey-package-requests/issues/733) for SoundSwitch not long ago.

The package itself doesn't necessarily require collaborator involvement, although it would be nice to see the package be officially maintained.

**Comment by brogers5** [comment]
For anyone who isn't following the community package request: @teknowledgist has stepped up and  [created a package](https://chocolatey.org/packages/soundswitch), which is currently under review.

Assuming an automatically updated package (albeit unofficial) will suffice, I'd say we're clear to close this out once it's approved.

If a collaborator wishes to be involved in package maintenance (now or later), feel free to [contact the Chocolatey admin team](https://chocolatey.org/docs/package-triage-process#i-want-to-take-overhelp-with-package-maintenance-for-my-software) and they'd be happy to work with you to make it happen.

**Comment by teknowledgist** [comment]
If @Belphemur would like to be a maintainer or co-maintainer, I am happy to have them contact me directly and I will set it up and help them get started.  The public repository is improved with more packages maintained by their application's creators.  Simple suggestions or corrections are also welcome.

I am open to other maintainers too if they can bring something to the table.

**Comment by Belphemur** [comment]
@teknowledgist Great work !

I'm sorry, but I don't have the time to maintain and support another way to get SoundSwitch.

**Comment by brogers5** [comment]
Package has been approved and is now ready to use!
