### ISSUE TITLE
Access violation error when updating

### ISSUE THREAD

**Issue by Achus619** [Belphemur/SoundSwitch#375]
I'm getting an access violation error when trying to update the application. It's been happening for the last 2/3 updates maybe, sadly I haven't kept track. After the error the installation process goes on for a while and then crashes reporting that there's been an error.
The apps works fine otherwise, it's just that I can't update it.

![Screenshot_1](https://user-images.githubusercontent.com/20907887/69495882-d04a9780-0eaa-11ea-9add-80bae000d6d7.png)

![Screenshot_2](https://user-images.githubusercontent.com/20907887/69495883-d2acf180-0eaa-11ea-826d-9474f50122b7.png)

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/3883651/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Hello,

Interesting, seems the installer isn't able to stop SoundSwitch.

Can you stop it manually before updating ?

**Comment by Achus619** [comment]
Thank you, that worked! Manually stopped soundswitch after the installer wizard started and the installation went through flawlessly.
