### ISSUE TITLE
Installer for 14.6.2.3656 fails

### ISSUE THREAD

**Issue by fredgreco** [Belphemur/SoundSwitch#382]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
When trying to install, I get an error:

"Access violation at address 6C0D2D8E in module 'atcuf32.dll'. Read of address 000000C4."

**Comment by fredgreco** [comment]
Appears I was able to install AFTER manually exiting out of SoundSwitch.

**Comment by Belphemur** [comment]
Unfortunately I'm not able to fix this for now. 

It's a known rare issue with the installer. I've never been able to reproduce it.
