### ISSUE TITLE
Unable to set custom sound notification

### ISSUE THREAD

**Issue by Pablo-Diablo** [Belphemur/SoundSwitch#386]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
When selecting a desired .wav file either nothing happens or you get a notification that the sound file could not be found.

**Comment by Belphemur** [comment]
Should be fixed in latest version.

**Comment by Pablo-Diablo** [comment]
4.16.3.39205 bug still persists
