### ISSUE TITLE
Latest version won't install

### ISSUE THREAD

**Issue by sajmonides** [Belphemur/SoundSwitch#388]
I got a notification that there was a new version available, but after downloading it, it won't install. I manually uninstalled the software, and tried re-downloading the newest version from the website but when I try to run SoundSwitch_v4.16.1.34861_Release_Installer.exe, nothing happens at all. I have no issue with any other programs. I tried restarting the PC, still happens.

**Comment by Belphemur** [comment]
Should be fixed with the latest version.
