### ISSUE TITLE
Add Korean language

### ISSUE THREAD

**Issue by Belphemur** [Belphemur/SoundSwitch#391]
Thanks to @HwaroK

We have Korean in the app.

**Comment by HwaroK** [comment]
Thanks.
If you see the wrong translation after the update
I will leave feedback.

**Comment by HwaroK** [comment]
SoundSwitch/Localization/Factory/Lang/Langs.cs

public string Label => "韓國語";
Can you replace ‘韓國語’ with ‘한국어’?

Koreans prefer Korean to Chinese.
It may sound strange,
Please.

**Comment by Belphemur** [comment]
Hello, 

Ho darn... Took the wrong one from Wikipedia. 

Sorry for the mistake, I'll correct it before realising it. 

Sent from Nine
________________________________
