### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#392]
We dropped it a couple of months/years (?) ago - i don't know anymore - but i'm looking forward to get it back implemented.

I will create a pull-request ~in the next few weeks.~

_________________
**Update 25.02.2020:** Unfortunately i don't have any free time for it... i will keep this issue open as note

**Comment by Belphemur** [comment]
I dropped it because it was a bother to maintain the test with the fact that CI machine didn't have audio device.

Also, when I was using CLR/C++ for the audio switching, I kept encountering weird bugs.

Now that SoundSwitch is fully C#, it might be easier.

**Comment by FireEmerald** [comment]
Yeah, these problems could occur, but i will give it one more try.
Due to the fact that we don't have any unit tests left, the CI will be build only for now.

**Comment by Belphemur** [comment]
Kind of done with Github action.

We should add test for the project in the future.
