### ISSUE TITLE
Updater doesn't support Emojis

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#394]
Priority Ultra High /joke

![2019-12-25 12_48_45-Window](https://user-images.githubusercontent.com/1107939/71444877-1e0a2800-2715-11ea-8908-0bb647b0d095.png)

**Comment by Belphemur** [comment]
I tried ...

Without having to embedded a real browser (chromium, firefox, etc ...) I couldn't find a way to get the default WebBrowser control to display emojis ...

I'll close this for now :)

**Comment by FireEmerald** [comment]
I think it's fine to don't use them there

**Comment by Belphemur** [comment]
Same, it was a fun ticket to check though :D

Updated the lib that do the conversion between markdwon and html to have support for more feature (not really needed, but since I was working on that component).
