### ISSUE TITLE
SoundSwitchAggregateException / error message

### ISSUE THREAD

**Issue by SmoothR81** [Belphemur/SoundSwitch#397]
Hi, 

if I add 2 of my sound devices and add f.e. Ctrl Alt and F11 I always get the above mentioned message, I can't solve this issue

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/4009684/SoundSwitch.zip)

[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[soundswitch20191230_009.log](https://github.com/Belphemur/SoundSwitch/files/4009674/soundswitch20191230_009.log)

[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

**Comment by Belphemur** [comment]
Hello, 

First time I see this problem. 
SoundSwitch isn't able to get the current default device. 

Which version of SoundSwitch are you using? 

Also what do you see in the windows control panel? 

Sent from Nine
________________________________

**Comment by AmoR-Ra** [comment]
Здравствуйте, замечена такая ошибка при запуске с windows 10,
файл с изображением прикрепляю, обновление не помогает.
![2020-01-27 11_10_47-SoundSwitch crashed](https://user-images.githubusercontent.com/60341509/73162197-f03e4780-40f5-11ea-9549-ac5ef146d52a.png)

**Comment by Belphemur** [comment]
It's fixed in v5.0.1

**Comment by Belphemur** [comment]
See #401
