### ISSUE TITLE
Error when installing just for me

### ISSUE THREAD

**Issue by JoanVicens** [Belphemur/SoundSwitch#398]
Hello, I'm having problems trying to install SoundSwitch if "Install for me only" option is selected on the Select install menu. If I try to install for all users I don't have any problem.

I'm using Microsoft Windows Version 1903 (OS Build 18362.592)

![image](https://user-images.githubusercontent.com/38570230/72670169-afca3400-3a3a-11ea-8598-6b5aba90e815.png)

PS: It's my firts Issue so hopefully I did it correctly

**Comment by Belphemur** [comment]
Hello, 

This is a known issue that has been fixed in the latest Beta version. By default, the installer doesn't select the right folder when you install just for yourself. 

For now, you'd have to select a folder your user control to install SoundSwitch in it. 
________________________________
