### ISSUE TITLE
What folder should I backup?

### ISSUE THREAD

**Issue by stephen147** [Belphemur/SoundSwitch#399]
Just this or are there others?

C:\Users\username\AppData\Roaming\SoundSwitch

Also is there a way possible to do a portable install which I could then backup that one location?

This thread from 2017 asks this question, I wonder if this has been developed any further?
https://github.com/Belphemur/SoundSwitch/issues/208

**Comment by Belphemur** [comment]
Hello,

That's the only folder used by SoundSwitch.

________________________________

**Comment by stephen147** [comment]
Thanks for the reply.

Regards the portable install, has this since been added?

**Comment by Belphemur** [comment]
Not a full portable one, more like, possibility to install it only for your user.

Only in the beta for now.

I'm not planning to make a zip for it.

**Comment by stephen147** [comment]
Okay, I understand. Thanks.
