### ISSUE TITLE
Forced mode

### ISSUE THREAD

**Issue by Bluscream** [Belphemur/SoundSwitch#400]
Sometimes programs force setting the devices to something that i don't want. Thats why i want to use soundswitch to act as a way to always "enforce" my setup.

So while the "force this setup" toggle is active either:
- Listen for "default device changed" event and automatically re-set it to the devices selected via SS
or if there is no event
- Check every 1 or 2 seconds which devices are set as default and if something changed, reset it to SS config

**Comment by Belphemur** [comment]
Hello,

Seeing your use case, you might want to try the latest Beta with the profile feature.

You'll be able to force a specific device for a specific program. (made to work with Windows 10, works okay in Windows 7). Every time the program is launched or maximised, the audio device is switched to the one you setup. 

Sent from Nine
________________________________

**Comment by Bluscream** [comment]
No!
