### ISSUE TITLE
Crash when switching with v5.0.0

### ISSUE THREAD

**Issue by ItsBradderz** [Belphemur/SoundSwitch#401]
Getting an AggregateException error from Soundswitch when trying to swap audio output using my keyboard shortcut, %appdata% compressed and attatched below, thanks!
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/4110973/SoundSwitch.zip)

**Comment by ngrahamdg** [comment]
Same here, seemed to start today after updating to v5.0. However, I reverted to v4.17 but had the same issue. Attaching one of the logs in case it help. 
[soundswitch20200124_004.log](https://github.com/Belphemur/SoundSwitch/files/4111479/soundswitch20200124_004.log)

**Comment by rogergh** [comment]
I had the same problem after updating to v5.0. By uninstalling v5.0 and reinstalling with 4.16.1.16453, it worked like it should again.

**Comment by Belphemur** [comment]
Thanks for the logs.

I've a fix coming for this issue.

**Comment by Belphemur** [comment]
Can you try with the 5.0.1 ?

**Comment by rogergh** [comment]
Works now with 5.0.1

**Comment by ItsBradderz** [comment]
> Can you try with the 5.0.1 ?

Works perfectly now, props for such a quick turnaround, many thanks! ++++
