### ISSUE TITLE
SoundSwitch_v5.0.1.14646_Release

### ISSUE THREAD

**Issue by AmoR-Ra** [Belphemur/SoundSwitch#402]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/4123901/SoundSwitch.zip)

 %AppData%\SoundSwitch directory and upload it.)
Не запускается, поправьте пожалуйста.
It does not start, please correct.

**Comment by Belphemur** [comment]
Hello,

It seems your installation of SoundSwitch has some issue, reinstall SoundSwitch.

**Comment by AmoR-Ra** [comment]
Переустанавливал несколько раз, удалял все данные о этой программе в системе, SoundSwitch_v4.16.1.34861_Release_Installer работает без проблем, последняя же версия не работает совсем, я ее скачивал заново, это не помогло, ошибка постоянно одна и та же, при обновлении с версии v4.16.1.34861 на v5 происходит тоже самое, ошибка которую я вам отправил, потому пока не обновляю.

**Comment by Belphemur** [comment]
I've tested the uninstallation and reinstallation.

I'm not able to reproduce your issue.

Do you have .Net Framework 4.7.2 installed ?
https://dotnet.microsoft.com/download/dotnet-framework/net472

**Comment by AmoR-Ra** [comment]
После установки Net Framework 4.7.2 проблема исчезла, я не знаю почему он не обновился автоматически как раньше, и то что он у меня устарел я узнал только благодаря этой проблеме, программа обновилась и работает без ошибки.

**Comment by Belphemur** [comment]
I admit, it shouldn't happen.

I'm glad installing 4.7.2 did fix your issue.
