### ISSUE TITLE
Hotkey gets various characters in addition to the key I actually want

### ISSUE THREAD

**Issue by Spokehedz** [Belphemur/SoundSwitch#405]
Pretty simple. Press 'end' and I get '0+end' for a hotkey. Other keys get other weird characters.

While making this comment, it started switching again. It still has the weird characters in the hotkey area. I'm putting this here so that when it happens again I will have some starting point.

I cleared the '%AppData%\SoundSwitch' folder but that didn't help, but when I was 'testing' to see what various characters would appear, it suddenly started working.

**Comment by Belphemur** [comment]
Hello,

Can you try with the latest version ?
I'm unable to reproduce your issue with SoundSwitch 5.0.1.
