### ISSUE TITLE
Looking for community chat/forum/FAQ for SoundSwitch

### ISSUE THREAD

**Issue by TonyGravagno** [Belphemur/SoundSwitch#406]
---
Discord Server: https://discord.gg/gUCw3Ue
---

New user - I just installed 5.0.1 for the first time with the installer. I will probably load source soon. As I get started with this, I'm not sure what is expected of me as a user. I have a lot of noob questions and was hoping to find a gitter chat, IRC, forum, or a FAQ in the wiki. And, right out of the box, the app keeps crashing when trying to hotkey to a profile. I don't want to report "issues" yet, because I'm not sure I'm doing what's expected to setup. I'll be happy to report specific issues over time, for code or docs, once I have a better understanding.

To get to that better understanding... what is the recommended place for simple Q&A? Just create an Issue here and keep it open until I run out of questions? :)  Would it help if I start a FAQ page for the Wiki and start with my own noob questions? If a gitter room is created will anyone use it?

Thanks for the app, for FOSSing it, and thanks for answers here.

**Comment by FireEmerald** [comment]
We don't have a gitter chat, IRC or a forum, so it should be fine to post your questions here.

Most questions should be answered by reading our [README](https://github.com/Belphemur/SoundSwitch). If you are looking for more information take a look at our [Wiki](https://github.com/Belphemur/SoundSwitch/wiki) it's kind of a FAQ.

> And, right out of the box, the app keeps crashing when trying to hotkey to a profile.

This definitely shouldn't happen 🙈 Could you compress and upload your `%AppData%\SoundSwitch` directory?

**Comment by TonyGravagno** [comment]
After playing with the app a while my noob questions are all/mostly answered. The crash issue was resolved with a reboot. As a developer I understand that we need to be able to clearly define a problem, and hopefully a reproducible case, so unless I have a specific issue I won't pursue that further.

**Comment by TonyGravagno** [comment]
When I boot my system the default mic is usually the laptop builtin "Realtek(R) Audio". So right on boot the mic is active and the speaker amplifies ambient sound.
1. Can we set a "boot profile" of sorts to default playback/record devices, other than the last ones which were set as default?
1. The keyboard has function keys for disabling audio and mic. Is code for these functions in SS? I can certainly use those keys to turn off sound after the system boots, but it would be ideal to have a code interface to control this functionality. I'm thinking of a profile where some app that requires silence might mute the devices.
1. Is it a bug or feature that all Internal Aux devices are visible in the lists? I don't know if there is any way for us to access/use some of these devices. And a couple of them have identical descriptions. I'm wondering if this is revealing something about our ability to use devices/drivers that we don't know about, or maybe if the software should be filtering out specific kinds of hardware.

Thanks.
![image](https://user-images.githubusercontent.com/499473/75593365-f3e92500-5a39-11ea-860e-185e5095ab1d.png)

**Comment by Belphemur** [comment]
I've decided to add a Telegram Group for support/questions/etc ...

https://t.me/joinchat/RB4ichzjxhf78V4kY1aKEg

**Comment by agamerj** [comment]
Hi, I would suggest to make Discord instead of Telegram as in discord within the same server you can have both thing. Plus, it has much better features compared to Telegram.

Discord is 100% Private and Safe too.

**Comment by FireEmerald** [comment]
I would also prefer Discord as it is more present in other projects then telegram. But it all depends on your personal preferences. @Belphemur ?

**Comment by agamerj** [comment]
Just in case @Belphemur If you need help with setting up Discord, I can help you with that as I have a very good experience with it and cost of everything is Nil / Zero.

**Comment by Belphemur** [comment]
@agamerj Let's go with Discord.

it does make sense since most of the users are gamer also :)
