### ISSUE TITLE
My hot-key stopped working after the last patch

### ISSUE THREAD

**Issue by Firk1n** [Belphemur/SoundSwitch#408]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

I've been using pause-break as the switch hot-key for the past few years. Ever since the last update it no longer works. Other keys seem to work just fine, but I'm having trouble getting used to a new setting. Any chance it will be supported again in the future?

**Comment by Belphemur** [comment]
Hello,

No change has been made related to the hotkeys. If SoundSwitch isn't able to bind to the Pause Key, it must mean another application is using it.

I'm able to use the pause key with the latest version.

**Comment by esegerson** [comment]
I am experiencing the same problem, and it's been about a week since the hotkey has worked.  Nothing has changed on my system as far as hotkey bindings go.  I tried changing the hotkey but the new binding does not work either.  SoundSwitch is useless now.  I found this great program about three weeks ago and it was perfect for toggling between my computer speakers and my new headset.

**Comment by Zaldrick** [comment]
Hi,
I've the same issue. I was using soundswitch since a while with FxSoundEnhanced.
I just did the last update and now soundswitch doesn't switch between my two devices when i'm pressing my hotkey, it try to switch but nothing happend. It occured right after the update.

**Comment by Belphemur** [comment]
What you can do is reinstall soundswitch and choose to delete the configuration to have a clean state. 

Your settings must have gotten corrupted in a way or in another. 

Sent from Nine
________________________________

**Comment by XTopherVersion2** [comment]
After a reinstall of Windows 10, I'm having unusual problems as well.

I can no longer set my previous default hotkey combination of shift + `, it simply refuses to add the ` key after pressing shift. Note that I can add the ` key independently. A reinstall and removal of settings failed to fix this.

Any ideas?

**Comment by Belphemur** [comment]
@XTopherVersion2 @Firk1n @Zaldrick @esegerson Can you try with the lastest version v5.0.2 ?

I've changed the way I'm setting the hotkeys, should help.

**Comment by Firk1n** [comment]
> @XTopherVersion2 @Firk1n @Zaldrick @esegerson Can you try with the latest version v5.0.2 ?
> 
> I've changed the way I'm setting the hotkeys, should help.

Still the same for me. Funny enough though, after reading XTopherVersion2's reply I tried using shift+pause instead just pause - and it actually worked with no problem. Not sure what's that about.

**Comment by Belphemur** [comment]
It would mean another program is using the Pause as global hotkey.

In that case, I can't do anything about it.

**Comment by XTopherVersion2** [comment]
Strangely enough, it worked for me! I updated and was able to immediately set my preferred hotkey combination.

Hrm, per @Belphemur I wonder if some other program was using my tilde key, and that's why I wasn't able to set it initially? Either way, very excited it's working now.

**Comment by Firk1n** [comment]
I tried to check using Windows Hotkey Explorer, and no application is
accessing pause/break according to it (screenshot added).
Any other idea? I can't figure out what software can possibly use it. I've
tried closing all apps in the background and it still persists.

**Comment by esegerson** [comment]
I installed 5.0.2, replacing the settings, and it's working again.  Thank you!  This is a great little utility!

**Comment by Zaldrick** [comment]
Still the same for me. I guess FxSoundEnhanced doesn't like the last update of SoundSwitch. I'll stay in 4.9.6733.39597 it's okay :)
