### ISSUE TITLE
Crash and Restart when using Windows Remote Desktop. Problem when new device is connected.

### ISSUE THREAD

**Issue by lysin** [Belphemur/SoundSwitch#41]
When initiating a remote desktop session to my pc running SoundSwitch , it crashs and automatically restarts.

Edit: This only seems to happen when I have the option to don't play any sound or play sounds on the remote device.

**Comment by Belphemur** [comment]
It might be connected to the issue #40 

Did you try with the latest version of SoundSwitch (3.6.2) ?

**Comment by lysin** [comment]
Yes, this is using the latest version.

**Comment by Belphemur** [comment]
Are you using the remote desktop of Windows or any other remote controlling program ?

What's your version of Windows (Win + X -> CMD as Admin -> winver).

**Comment by lysin** [comment]
I have Windows updated and the version is 1511 build 10586.29.

This happens when using the official Microsoft Remote Desktop application.

**Comment by Belphemur** [comment]
I'll have to give it a try to see if I can reproduce the issue.
I'll add a way to log the restart in the application log also. It should help me to troubleshoot this issue.

**Comment by lysin** [comment]
Ok, if you need anything else from me let me know. 

Amazingly useful app you have here! Cheers

**Comment by lysin** [comment]
Actually, I think the problem lies with the addition of a playback device when SS is running.

It happens when I start RDP (because of the virtual remote playback device) and when I plug in my Wireless Headset.

**Comment by Belphemur** [comment]
That what I was thinking. I thought I squashed this bug with the issue #40 
I'll give it a further look to this.

**Comment by aalvarado** [comment]
crashing when connecting or disconnecting a device:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	SoundSwitch.exe
  Application Version:	3.6.2.37350
  Application Timestamp:	566b7c1c
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.19018
  Fault Module Timestamp:	560a0094
  Exception Code:	e06d7363
  Exception Offset:	000000000000b3dd
  OS Version:	6.1.7601.2.1.0.256.49
  Locale ID:	1033
  Additional Information 1:	eaa4
  Additional Information 2:	eaa4e9a36255664f1a307d61106dd87c
  Additional Information 3:	c68a
  Additional Information 4:	c68a18627740a9b3bb4d1f0fe0081d6a
```
Win7
soundswitch v: 3.6.2.37350

Full appcrash dump: https://gist.github.com/aalvarado/c03fbcb655e2816785ac

**Comment by lysin** [comment]
Sorry, but it's still crashing using Windows Remote Desktop... Cheers

**Comment by Belphemur** [comment]
This bug is harder to squash than expected. 

I rewrote most of the part dealing with the Audio Device to improve the
performance and reduce that kind of issues .... 

I forgot to ask, does it crash on the Host or on the Target of the
remote control ? 

Antoine Aflalo 

Le 2015-12-22 10:41, lysin a écrit : 

> Sorry, but it's still crashing using Windows Remote Desktop... Cheers 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/Belphemur/SoundSwitch/issues/41#issuecomment-166650430

**Comment by Belphemur** [comment]
I finally got to the bottom of this issue. It will be corrected in the next release.
