### ISSUE TITLE
5.0.1 crashing on first run

### ISSUE THREAD

**Issue by nathan323** [Belphemur/SoundSwitch#413]
Have rebooted. Tried upgrading from 4.17.1 and keeping settings, then tried clean install.

Compressed AppData folder:
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/4401896/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Hello,

It looks like you don't have .NET 4.7.2 installed.

https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-web-installer

Install it and it should work.
I have to double check the installer, it should have detected this.

**Comment by nathan323** [comment]
Ok thanks. In the Readme, you state that  .NET 4.7 is needed, which I checked and was installed. Now that I have 4.7.2, all working.
