### ISSUE TITLE
[Enhancement] Set Default Devices on Startup

### ISSUE THREAD

**Issue by Arkhaeon** [Belphemur/SoundSwitch#414]
Hey Belphemur, thanks for this great project.
Just had an enhancement idea based on a feature from the old sirWest's AudioSwitch.
Could you please add the ability set the default playback/recording default/default communication devices on startup?

**Comment by Belphemur** [comment]
Hello,

For now SoundSwitch relies on Windows for this.

Windows always remember what device was the last one set a default and will change the device accordingly (if plugged before starting).
