### ISSUE TITLE
Make the updater detect if installed as User or Admin

### ISSUE THREAD

**Issue by Belphemur** [Belphemur/SoundSwitch#416]
It seems this problem still exists (just updated :P) for autoupdating C;\ProgramFiles installations which brings a question to my mind: what's the problem with setting `requestedExecutionLevel` to `requireAdministrator` in the app's manifest or at least replacing `Skip this file (not recommended)` button in OP (since it's not an option in a real world) button with `Run as Administrator` which just re-executes the downloaded installer? Or even better, make a check for permissions to the app's installed location **before** executing the downloaded installer and bring a dialog to run as Administrator if it is required. Those users who want to install the app into elevated locations will have no problem granting them to the installer and those who don't want to compromise their security will seamlessly install it into their user's folder as usual.

It will also be cool to add the same permissions check to the installer itself for first-time installations so new users won't have to cease the whole process after encountering the error in OP just to run the installer as Administrator from context menu again.

_Originally posted by @snakecase in https://github.com/Belphemur/SoundSwitch/issues/404#issuecomment-609423976_

**Comment by snakecase** [comment]
Just updated and it went very smooth and as expected so thank you on that. I have a last suggestion regarding the update process: I guess it's redundant to warn users that installation folder of their choice already exists, especially during an auto-update. It looks like a feature from early 2000s which almost nobody uses today so my suggestion is to disable that check so updating requires even less prescious clicks.

Anyway thank you for listening and making your users' lives a little more frictionless!

**Comment by Belphemur** [comment]
@snakecase If you want to not have to do anything, you can enable the auto-update instead of notify :)

The installer will then run in silent mode.

**Comment by snakecase** [comment]
Does it show up the updater window with changelog?

**Comment by Belphemur** [comment]
Nope that it won't. 

I could add a checkbox to the updater windows asking to run the installer silently. 

If you're interested, you can open another issue for it. 

Sent from Nine
________________________________
