### ISSUE TITLE
Win10 not launching

### ISSUE THREAD

**Issue by ngod88** [Belphemur/SoundSwitch#417]
[SoundSwitch1.zip](https://github.com/Belphemur/SoundSwitch/files/4439939/SoundSwitch1.zip)
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

Anyone else having issues not launching SoundSwitch from Win10? I was able to launch from Win7 with no issues. I deleted the AppData folder, uninstalled, reinstalled a few times.

**Comment by ngod88** [comment]
Hey Belphmur, 

Click on it, does it nothing. I even force quit / end task and reopen. 

The hotkey works, it just the GUI never launches. Ever. I have to re-write or delete my appdata config folder and rebuild it every single time to open the GUI.

**Comment by Belphemur** [comment]
Can you use [Screen to Gif](https://www.screentogif.com/) to make a simple gif showing me what you're doing ?

Do you see SoundSwitch Icon ? Are you right-clicking on it ?
The gif will help me understand what's hapenning.
