### ISSUE TITLE
Default Communication Device changing when it shouldn't.

### ISSUE THREAD

**Issue by MrDrumline** [Belphemur/SoundSwitch#418]
I have headphones that I would like to always stay as my default communications device, but even with "Switch Default Communication Device" disabled in the settings, SoundSwitch changes my communication device anyways. Toggling the setting on or off changes nothing, the default comms device always changes. I'm running on the latest update.

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/4448724/SoundSwitch.zip)

[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

**Comment by MrDrumline** [comment]
Issue seems to be fixed by manually setting the comms device separate from the default, and then changing the default at will. Windows limitation, maybe?

**Comment by Belphemur** [comment]
Hello,

I'm not able to reproduce your issue in the 5.0.2.
If the option to switch communication device is disabled, it doesn't get switched.
