### ISSUE TITLE
[Feature Request] All Connected Devices

### ISSUE THREAD

**Issue by franciscarriere** [Belphemur/SoundSwitch#419]
I often unplug and replug a USB headset on my computer and it seems to regenerate a new device ID everytime. This requires me to go back into soundswitch every time and enable it for it to be switchable.

Can we have a toggle able setting where all connected devices are enabled? Or instead of a whitelist system, a blacklist system? Where all devices connected are used for SoundSwitch except for those blacklisted?

Thanks!

**Comment by Belphemur** [comment]
Hello,

This feature already exists, albeit not very clear in the settings' menu:

![image](https://user-images.githubusercontent.com/197810/79048374-b1933600-7bea-11ea-88b1-187495407b82.png)

You want to select cycling through: All audio devices
