### ISSUE TITLE
Hotkey for cycling through devices in reverse order

### ISSUE THREAD

**Issue by dwincort** [Belphemur/SoundSwitch#420]
Hi,

I have a bunch of audio devices, and I use the hot key for switching among them.  Sometimes, I cycle through too quickly and miss the one I want.  Just like alt-tab has alt-shift-tab (on Windows), it would be great if I could set a hot key for cycling through the audio devices in reverse order.

Thanks!

**Comment by Belphemur** [comment]
Hello,

As a workaround, you could use the profile feature.

If you switch a lot between 2 groups of devices, you could set up 2 profiles with different hotkeys.

This way you would easily switch between one or the other without the need to cycle through everything.
