### ISSUE TITLE
Can't use Windows Key as part of the HotKey

### ISSUE THREAD

**Issue by Sukinidachi** [Belphemur/SoundSwitch#421]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)
I'm not sure what's been changed in the newest update but my hotkey used to be (LWin + Shift + A) and I am not longer able to use that combo.

Now that I'm testing out new hotkeys, seems I can't really use more than two keys?
P.s if anyone has any suggestions for a hotkey that currently works that I can use using one hand, that would be great.

**Comment by Belphemur** [comment]
Hello,

Thanks for the bug report, in the previous version I've changed how the Hotkey input works ...

The Windows Key isn't recognized correctly anymore, as a workaround, you can use another key until I fix the issue.
