### ISSUE TITLE
Listen to device default device isn't switched

### ISSUE THREAD

**Issue by Phoenix616** [Belphemur/SoundSwitch#424]
When switching the default playback device to a different one the audio of recording devices that are set to forward to the default playback device are not switched to the new audio device and continue playing on the old one.

**Comment by Belphemur** [comment]
Hello,

For now, SoundSwitch doesn't support "listen to device".
Currently, I've no way to know that it's in use.

**Comment by Phoenix616** [comment]
Ok. Not sure why that would justify an issue close though, seems like a feature/bug that should be looked into in the future, maybe someone even stumbles upon it who knows a solution.

**Comment by Belphemur** [comment]
@Phoenix616 It's also because it's a duplicate of:
https://github.com/Belphemur/SoundSwitch/issues/234

If I'm able to implement it, I'll fix that too.
