### ISSUE TITLE
Sporadically hangs

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#43]
The SoundSwitch application randomly doesn't respond anymore after the system was started.
In the settings section i enabled the Autostart option so the tool starts on every windows start.

I'm using Version **3.6.5.13463** on Win7 64bit.
![2015-12-24 16_27_55-](https://cloud.githubusercontent.com/assets/1107939/11996079/c5951b6e-aa5c-11e5-8738-20c7558c43fd.png)

**Comment by Belphemur** [comment]
Does it happen right away ? Or when you're connecting another device ?

**Comment by FireEmerald** [comment]
It happens immediately after login into windows. I normally doesn't dis-/connect any sound device.

**Comment by Belphemur** [comment]
The logs files are located here:
%appdata%/SoundSwitch/Logs

Please zip this folder and send it to me using my contact form: https://www.aaflalo.me/contact/ (choose send log as category). Or directly put the zip file into the comment.

Can you try this version of SoundSwitch before sending the logs ?
[SoundSwitch_v3.6.5.30162_Installer.zip](https://github.com/Belphemur/SoundSwitch/files/72276/SoundSwitch_v3.6.5.30162_Installer.zip)

**Comment by FireEmerald** [comment]
I sent you the logs - will install v3.6.5.30162 tomorrow and check if the error occures again.

**Comment by Belphemur** [comment]
Can you tell me if it still happen with the last version ? (3.7.0)

**Comment by FireEmerald** [comment]
I installed the version 3.7.0, it will take a couple of days until i can tell you if the error doesn't occur any more.

**Comment by FireEmerald** [comment]
Got the problem again with 3.8.4.28266.

https://mega.nz/#!FUc1nKAL!H_HXBsUip2kZ3Nx4xc_72pC3KYZpb7IT4R_eWavoU8w
(SoundSwitch_3_8_4_28266.zip)

**Comment by Belphemur** [comment]
It seems to be linked with the hotkeys. I'll see what I can do for this.

**Comment by Belphemur** [comment]
Can you take the time to see it with the last Beta version ?
It should be resolved.

(btw you can add zip file directly in Github by drag-dropping them into the comment section).

**Comment by FireEmerald** [comment]
Installed v3.9.1.14658 - it will take some time to confirm the fix.
About adding a zip file directly to a comment - github tells me always this, if i try to add a .zip file ro a comment:
![ph57o61](https://cloud.githubusercontent.com/assets/1107939/12218376/b41ecdc6-b71d-11e5-88c5-c16275b03f4a.png) ...

**Comment by Belphemur** [comment]
Are you using 7zip or Winrar to create your zip ?
You're sure the program in question is creating a zip file with zip compression algorithme ?

**Comment by FireEmerald** [comment]
I'm using WinRAR - and it sould create a .zip file if i tell the program to create such a file.
![2016-01-10 00_18_10-archive name and parameters](https://cloud.githubusercontent.com/assets/1107939/12218935/b9de6944-b72f-11e5-8f88-e5045b9c5203.png)

**Comment by FireEmerald** [comment]
@Belphemur Seems like this issue is indeed fixed. Did got any hang since using v3.9.1.14658.
