### ISSUE TITLE
Two same outputs devices fighting

### ISSUE THREAD

**Issue by gufpewga** [Belphemur/SoundSwitch#436]
Hi, I'm having issue with output list. I have two same LCD monitors and they are sometimes showing both, sometime only one of two and I never know which one is which until I test it... Cound you please add some identification if you see two same models? 
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/4603313/SoundSwitch.zip)

**Comment by Belphemur** [comment]
You can rename devices in the windows panel.

Right click on SoundSwitch systray > Playback Devices.

Choose the device you want to rename and do right click on it > properties.

![image](https://user-images.githubusercontent.com/197810/81509162-b7a63080-92d6-11ea-95ee-492fd281890b.png)

SoundSwitch use the name set there.

**Comment by gufpewga** [comment]
Ou I never tryed that, thanks. I hope it is going to work now.
