### ISSUE TITLE
cra<sh

### ISSUE THREAD

**Issue by Bluscream** [Belphemur/SoundSwitch#438]
[SoundSwitch-crashlog-12_5_2020.zip](https://github.com/Belphemur/SoundSwitch/files/4616754/SoundSwitch-crashlog-12_5_2020.zip)
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

**Comment by Belphemur** [comment]
Hello,

Thanks for the bug report.
It's a weird issue, I think I have a semi-fix for it.
