### ISSUE TITLE
Keybind not working, crashing when trying to edit keybind.

### ISSUE THREAD

**Issue by SeriousJulian** [Belphemur/SoundSwitch#443]
[SoundSwitch-crashlog-14_5_2020.zip](https://github.com/Belphemur/SoundSwitch/files/4629841/SoundSwitch-crashlog-14_5_2020.zip)

**Comment by Belphemur** [comment]
I've rewritten completely the keybinding, I'll release a Beta with it.

**Comment by Belphemur** [comment]
And that rewrite doesn't work as expected.
Rolled back to the old cold with a possible fix.

**Comment by Belphemur** [comment]
Can you try with the beta version :https://github.com/Belphemur/SoundSwitch/releases/tag/v5.1.0
