### ISSUE TITLE
Recognize re-connected devices as the same as before

### ISSUE THREAD

**Issue by scezumin** [Belphemur/SoundSwitch#444]
Hello,

First of all, thank you for sharing this project.  Being able to toggle through my many devices with simple keystrokes is a godsend.  However, as I noticed yesterday when I unplugged a USB hub with my wireless headphones attached, and reattached it to a different port, SoundSwitch seems to recognize every combination of port and device that Windows 10 has ever seen.  Is this intentional?  Is there a way to cull the list?  Is that something that I can do in Windows, outside the scope of SoundSwitch?

Thanks for reading,
Jeremy

**Comment by FireEmerald** [comment]
I realized the same even if you re-connect the device to the same port. Furthermore the sound playback stopped after some seconds and broke completely until i re-connected my USB headset. I would generally say that it's a bad idea to unplug and re-plugin your devices.

**Comment by p3yot3** [comment]
+1 for this. Devices refuse to play audio/video again until the "new" device is added to the list & app is restarted, which is a pain tbh. Great work so far though - thanks!

**Comment by scezumin** [comment]
> I realized the same even if you re-connect the device to the same port. Furthermore the sound playback stopped after some seconds and broke completely until i re-connected my USB headset. I would generally say that it's a bad idea to unplug and re-plugin your devices, because SoundSwitch needs some improvements here.

Yeah, now that I know, I'll definitely try to do it as infrequently as possible as a workaround.  I just think that's going to be a pretty standard user experience for anyone with a laptop and a USB output or input device.

**Comment by Belphemur** [comment]
Unfortunately that's a limitation of Windows.
Every time you use a different port, Windows assign a different ID (and even a different name like 2-headset).

Since SoundSwitch rely on the ID of the device to recognize it.

An improvement was made on how to list the device in the settings menu to have the active and selected one on the top and all the disconnected (even selected) on the bottom.

I agree the disconnected list is annoying and Windows is really making it worse than before:
![image](https://user-images.githubusercontent.com/197810/82123806-4ef10500-9769-11ea-83d7-73700cce1cf9.png)

I'm thinking of adding a way to not show the disconnected devices.

**Comment by p3yot3** [comment]
If I revert back to using the older Win7AudioSwitcher (running it in compatibility mode on Windoze 10) I no longer get a long list of disconnected devices - it remembers the device, so I'm not sure it is a limitation of Windoze, unless the compatibility mode changes something?

**Comment by scezumin** [comment]
I think that having an option to not cycle through disconnected devices perhaps collapsing the "Disconnected" section of the menu would do the trick.

**Comment by Belphemur** [comment]
Good news, I've realized SoundSwitch was also listing way too many type of device.

I've changed to only list what Windows consider Unplugged and Active

**Comment by scezumin** [comment]
Cool, sounds good!  Thank you!

**Comment by Belphemur** [comment]
Can you try with the beta version ?
https://github.com/Belphemur/SoundSwitch/releases/tag/v5.1.0
