### ISSUE TITLE
app crash new beta 5.1.0

### ISSUE THREAD

**Issue by cybermcm** [Belphemur/SoundSwitch#446]
[//]: # (Please provide us your logs/configuration folder if you are reporting a crash.)
[//]: # (Compress the whole %AppData%\SoundSwitch directory and upload it.)

Tried the new beta (clean settings), app starts but if I right click the icon I can't get any further (hourglass)...
Reverted back to 5.0.4 -> working
attached both logs
[SoundSwitch_working_5.0.4.zip](https://github.com/Belphemur/SoundSwitch/files/4639717/SoundSwitch_working_5.0.4.zip)
[SoundSwitch_not_working_5.1.0.zip](https://github.com/Belphemur/SoundSwitch/files/4639718/SoundSwitch_not_working_5.1.0.zip)

**Comment by FireEmerald** [comment]
I can confirm the bug. The application hangs after start, doing nothing.
![2020-05-17 10_35_18-](https://user-images.githubusercontent.com/1107939/82139692-1fee9800-982a-11ea-8127-b1d3673884b2.png)

**Comment by Belphemur** [comment]
A fix is coming for this.


Thanks for the report.


Sent from Nine
________________________________

**Comment by Belphemur** [comment]
You can try with the 5.1.1 : https://github.com/Belphemur/SoundSwitch/releases/tag/v5.1.1

Still a beta version.

**Comment by cybermcm** [comment]
Did a quick test (fresh settings), works fine, thanks for the quick fix!
