### ISSUE TITLE
Recognize installation directory

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#449]
Installed stable 5.0.4 for everyone (not only for the current user) in `D:\Apps\SoundSwitch`.

Using the latest beta release (5.1.1) the suggested installation directory is `C:\Users\username\AppData\Local\Programs\SoundSwitch`.

The suggested dir should be where SoundSwitch is at the moment (`D:\Programme\SoundSwitch`).

**Comment by Belphemur** [comment]
Caused by #416

I realized too late the installer is already able to see how is SoundSwitch installed, I shouldn't try to override that.

**Comment by Belphemur** [comment]
@FireEmerald Could you also try the latest beta for me ?

It's a big change that uses .NET Core instead of .NET Framework.

**Comment by FireEmerald** [comment]
@Belphemur Updated to the latest beta build 5.2.0.33004 and the installer recognized the path on it's own correct.
