### ISSUE TITLE
Version 3.6.5.13463 does not recognize playback devices, version 3.6.2.37344 does.

### ISSUE THREAD

**Issue by Hoanui** [Belphemur/SoundSwitch#45]
Whenever I try to switch playback devices on version 3.6.5, it gives me an error message which indicates configuration is needed and that no devices are available.

I'm on Windows 10 Pro build 10586, the controller for the playback devices is High Definition Audio Device by Microsoft. I don't know what other information I should include in this post.

**Comment by Belphemur** [comment]
Did you configure the devices you wanted to switch to in the settings menu? 

On 26 December 2015 07:08:48 GMT-05:00, Hoanui <notifications@github.com> wrote:
>Whenever I try to switch playback devices on version 365, it gives me
>an error message which indicates configuration is needed and that no
>devices are available
>
>I'm on Windows 10 Pro build 10586, the controller for the playback
>devices is High Definition Audio Device by Microsoft I don't know what
>other information I should include in this post
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/45

-- 
Best Regards, 
Antoine Aflalo

**Comment by Hoanui** [comment]
Yeah, the settings ported properly from version 3.6.2, everything's there, but Soundswitch still displays the error message.

**Comment by Belphemur** [comment]
Close SoundSwitch.  Go to %appdata%\SoundSwitch and delete it's content.  Relaunch the app and reconfigure it. 

On 26 December 2015 09:11:55 GMT-05:00, Hoanui <notifications@github.com> wrote:
>Yeah, the settings ported properly from version 3.6.2, everything's
>there, but Soundswitch still displays the error message.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Belphemur/SoundSwitch/issues/45#issuecomment-167327241

-- 
Best Regards, 
Antoine Aflalo

**Comment by Hoanui** [comment]
Same error message.

**Comment by Belphemur** [comment]
Can you try this version ?
Keep in mind this is not a stable one.

[SoundSwitch_v3.6.5.18369_Installer.zip](https://github.com/Belphemur/SoundSwitch/files/72465/SoundSwitch_v3.6.5.18369_Installer.zip)

If the problem persists, can you zip the content of %appdata%\SoundSwitch and send it to me using my contact form : https://www.aaflalo.me/contact/

**Comment by Hoanui** [comment]
It's the appdata/roaming/soundswitch folder, right?

**Comment by Belphemur** [comment]
Just copy/paste this:
 %appdata%\SoundSwitch  in the explorer address bar ;)
It will lead you directly to the right folder.

Btw, you can try this version instead:
[SoundSwitch_v3.6.6.21331_Installer.zip](https://github.com/Belphemur/SoundSwitch/files/72479/SoundSwitch_v3.6.6.21331_Installer.zip)

**Comment by Hoanui** [comment]
Version 21331 works. And it now registers recording devices that all the previous versions didn't. Thank you very much for your attention.

**Comment by Belphemur** [comment]
Great news !

It would seems for an unknown reason Windows decided to not set the devices as default device for some role (like Multimedia). I was expecting it to always set it right.
