### ISSUE TITLE
SoundSwitch doesn't remember when HotKey is disabled

### ISSUE THREAD

**Issue by cybermcm** [Belphemur/SoundSwitch#451]
**Describe the bug**
starting with clean settings, disable hotkey for recording (disable checkbox). Restarting Soundswitch -> Soundswitch complains that recording hotkey can't be registered, so disabling this hotkey won't survive a program restart.

**Version**
SoundSwitch v5.1.1.32475

**To Reproduce**
see description

**Expected behavior**
disabling of hotkey should survive restart of programm

**Screenshots**
n.a.

**Additional context**
was working with older versions, log attached
[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/4654809/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Thanks for the bug report.

Yep definitely a bug introduced with the latest beta.
I'll fix it asap.

**Comment by Belphemur** [comment]
Can you test with the latest Beta 5.2.0 ?

Should be fixed.

**Comment by cybermcm** [comment]
works again, thx for the fast fix!
