### ISSUE TITLE
SoundSwitch crashes on startup:  Can't get information about running process for Profile Feature

### ISSUE THREAD

**Issue by HugoKamps** [Belphemur/SoundSwitch#455]
When starting up my laptop I got the error that SoundSwitch crashed. Seems to be a Null reference in the configuration section.

[SoundSwitch-crashlog-25_5_2020.zip](https://github.com/Belphemur/SoundSwitch/files/4678125/SoundSwitch-crashlog-25_5_2020.zip)

**Comment by Belphemur** [comment]
Thanks for the report.

It's more complex than that, but easy to fix.

**Comment by Belphemur** [comment]
Will be fixed in the next release.
