### ISSUE TITLE
Better error message when launching second instance of SoundSwitch

### ISSUE THREAD

**Issue by theAkito** [Belphemur/SoundSwitch#456]
**Is your feature request related to a problem? Please describe.**
I installed SoundSwitch on a new Windows. I wanted to start SoundSwitch and it kept crashing. I found the notification "Impossible to register Hotkey"...
After that only I noticed, that the reason for that is that SoundSwitch was already running, but I didn't notice it.

It would be helpful, if the error message would be more clear. It should say, that there is already an instance running.

**Describe the solution you'd like**
Check for open SoundSwitch processes or create a `SoundSwitch.lock` file on every startup.

**Additional context**
This would improve UX.

**Comment by Belphemur** [comment]
Actually there is already a system in place to stop that from happening.

It's normally not possible to have 2 instances of SoundSwitch running.

I've improved that system in the last Beta.
Can you try with it ?
