### ISSUE TITLE
SoundSwitch crash at boot: Instance not initialized

### ISSUE THREAD

**Issue by cdrandin** [Belphemur/SoundSwitch#464]
**What were you doing when it crashed ?**
I just booted my computer and SoundSwitch immediately crashed. I have it set to boot on start.

**To Reproduce**
1. Turn on PC
2. Wait
3. Crash

**ZIP**
[SoundSwitch-crashlog-6_6_2020.zip](https://github.com/Belphemur/SoundSwitch/files/4740556/SoundSwitch-crashlog-6_6_2020.zip)

**Comment by Belphemur** [comment]
Hello,
Does this happen often ?

**Comment by cdrandin** [comment]
Almost always. I have even tried by reinstalling it. It will work for a bit but stops working eventually.

**Comment by Belphemur** [comment]
Can you test with this test version ?

Unzip it somewhere and launch SoundSwitch.exe.

If it works, I'll have a fix coming.

[SoundSwitch_Test.zip](https://github.com/Belphemur/SoundSwitch/files/4740992/SoundSwitch_Test.zip)

**Comment by cdrandin** [comment]
I have rebooted a couple of times and so far it seems to be working. Hopefully, this is the fix. I will keep you posted if any other issues persist. Thanks.
