### ISSUE TITLE
Banner + acoustic signal when switching output device

### ISSUE THREAD

**Issue by h0lley** [Belphemur/SoundSwitch#471]
In a previous version of SoundSwitch, the indicator when switching the output device was (or could be set to) a banner with an icon of the device switched to, accompanied by an acoustic signal.

Since a recent update - not exactly sure which one it was, I think it was perhaps one or two months ago - the banner is no longer accompanied by an acoustic signal and there appears to be no option in the settings to enable this again.

It appears that now, you can only have either the banner OR an acoustic signal.
My preference is still to have both while not having to use Windows Notifications.

**Comment by Serenitor** [comment]
yup, my bad.
the past, there was a default sound effect I believe.
I didn't realize you could add a custom sound effect to the banner.

thank you.
