### ISSUE TITLE
False positive in Malwarebytes

### ISSUE THREAD

**Issue by Tetriando** [Belphemur/SoundSwitch#473]
**Describe the bug**
After updating today to the latest Soundswitch version and trying to run it there was false positive detection in my Malwarebytes

**Version**
SoundSwitch v5.4.0

**To Reproduce**
1. Run latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/1027662/84378194-0dc30800-abe4-11ea-8efd-03652955575e.png)

**Comment by Belphemur** [comment]
Thanks for the report. I've reported the false positive to malware byte.

If you have a way to do the same in the app, please do that might speedup the process.

**Comment by MrFriendism** [comment]
Hi, I don't use MalwareBytes, But I have submitted them the tweet on Twitter about this false alarm.

I use ESET and KasperSky, But none of them find any sort of malware/issue with it.
