### ISSUE TITLE
Installer Offers To Install Older Desktop Runtime

### ISSUE THREAD

**Issue by Skibicki** [Belphemur/SoundSwitch#474]
**Describe the bug**
I tried updating to 5.4.0.
The SoundSwitch installer tries to install Windows Desktop Runtime 3.1.4 when 3.1.5 is installed.

**Version**
SoundSwitch v5.4.0

**To Reproduce**
Use the updater or manually download and install SoundSwitch

**Expected behavior**
Soundswitch should not offer to install dependencies when a newer minor version is already installed.

**Comment by Belphemur** [comment]
It's a known issue.

I'm gonna work on a fix that will released with the next version.
