### ISSUE TITLE
Better support for MultiScreen: Banner displayed on active screen

### ISSUE THREAD

**Issue by allmoney** [Belphemur/SoundSwitch#475]
**Describe the bug**
Alert when switch between audio devices on main display. But I have 2nd display in 2nd room and I can't see this alert. Is any what to show alert message on both displays or where is mouse?

**Version**
SoundSwitch v5.4.0 and earlier

**Comment by Belphemur** [comment]
Hello,
I've implemented this way:

The banner detect where the cursor is, and will display the form on the screen where the cursor is.
