### ISSUE TITLE
Crash at startup when soundswitch is installed on multiple users on Windows 10

### ISSUE THREAD

**Issue by Tichau** [Belphemur/SoundSwitch#476]
**What were you doing when it crashed ?**
Crash at startup when soundswitch is installed on multiple users on Windows 10.
Windows preload some applications for each users when starting. If soundswitch is installed on multiple users with "Start automatically with Windows" option checked, it crash at startup.

**To Reproduce**
1. Have two admin users on Windows 10
2. Install soundswitch on both users and set the "Start automatically with Windows" option to true
3. Restart your computer and log in to the other user (compared to last run).
4. See crash

**ZIP**
[SoundSwitch-crashlog-15_6_2020.zip](https://github.com/Belphemur/SoundSwitch/files/4782140/SoundSwitch-crashlog-15_6_2020.zip)

**Comment by Belphemur** [comment]
Hello,

Please update to v5.4.0. It has been fixed in the latest version.

**Comment by Tichau** [comment]
Thanks, sorry for the duplicates
