### ISSUE TITLE
Reconnected devices and profiles

### ISSUE THREAD

**Issue by dalai4git** [Belphemur/SoundSwitch#482]
**Is your feature request related to a problem? Please describe.**
After a reconnection of a device that leads to a change in its name (see also #444), the old profile is no longer valid. The alternative would be to delete the profile and create a new one (or edit the profile when #431 gets implemented), but that is not always convenient.

**Describe the solution you'd like**
Be able to specify the profile devices using a substring, glob pattern or regex, e.g. "\*Logitech\*"

**Comment by Belphemur** [comment]
Hello,

I'm thinking of changing the logic of matching device name. Like cleaning up the "added number" etc ... for a better matching.
