### ISSUE TITLE
ui window position when starting from task bar..

### ISSUE THREAD

**Issue by liamauve** [Belphemur/SoundSwitch#484]
hi, this is a minor quality of life request: if you right click the system's volume icon in the task bar, and select mixer, the mixer window would pop out at lower right, right where I right clicked and my cursor is. but opening from soundwsitch, (like playback devices; mixer; settings, etc) most are popped out at top left. again, this is a very minor request. I just need to extend the life of my mouse's teflon feet, i paid top dollar for them.  ok jk

**Describe alternatives you've considered**

so could we have all the UI open at bottom right? or center? thanks for reading. stay safe~~

**Comment by Belphemur** [comment]
Hello,

Unfortunately,  it doesn't seem I have a control on this.

It's supposed to show where the mouse pointer is and the display (left/right) is automatically calculated by the menu. I can't easily override this.
