### ISSUE TITLE
SoundSwitch crash when switching profile with a device that isn't active at time

### ISSUE THREAD

**Issue by skst** [Belphemur/SoundSwitch#485]
[SoundSwitch-crashlog-23_7_2020.zip](https://github.com/Belphemur/SoundSwitch/files/4969530/SoundSwitch-crashlog-23_7_2020.zip)

**What were you doing when it crashed ?**
I pressed a hotkey combination to set a profile. The profile did not switch. (No banner, etc.) SoundSwitch output a crash log instead.

_Note, this seems to have started happening after the Windows 10 2004 feature update._

**To Reproduce**
1. Press hotkey to select a profile.
2. Crash log saved. (but SoundSwitch continues to run).
3. Double-click the SoundSwitch icon in the notification area.
4. SoundSwitch switches to the new profile and displays the banner.

**ZIP**
Drag & Drop the file

**Comment by Belphemur** [comment]
This was fixed in the v5.4.0

You're using an old version v5.3.1

**Comment by skst** [comment]
Cool. SoundSwitch still says it's up-to-date though, so next time, I'll check myself instead. ;-)

![image](https://user-images.githubusercontent.com/74487/88484974-46bb0000-cf38-11ea-9e14-d531d5e480fd.png)

**Comment by Belphemur** [comment]
I've just tested now.

Is it possible you've either disable the update feature or simply blocking github API ?

**Comment by skst** [comment]
Ah ha! Yes, the update feature is disabled. Of course, since SoundSwitch said "No update available," I took it at its word and didn't remember that I must have disabled it months ago (unless that was the default). May I suggest changing the "No update available" text to something that indicates updates are not, in fact, being checked or perhaps remove the menu entry altogether if it's not checking for updates.

**Comment by Belphemur** [comment]
Can you open an enhancement issue for that ? :)

That's a great idea.

**Comment by skst** [comment]
Done. 🙂 #487
