### ISSUE TITLE
Installer cannot detect correctly version of .NET Core runtime when installed with the SDK

### ISSUE THREAD

**Issue by skst** [Belphemur/SoundSwitch#486]
**Describe the bug**
SoundSwitch requires an older version of .NET Core and .NET Core will not install older patch versions when a newer version is present.

**Version**
SoundSwitch 5.4.0.34051

**To Reproduce**
1. Install .NET Core 3.1.6 or later.
2. Download SoundSwitch 5.4.0.34051 installer and run.
3. The SoundSwitch installer says it has to install .NET Core 3.1.4. Proceed with the install.
4. Install of .NET Core 3.1.4 fails: "Error 0x80070666: Cannot install a product when a newer version is installed."

**Expected behavior**
SoundSwitch should not depend on specific .NET Core patches (e.g., 3.1.4)--only on minor versions (e.g., 3.1). In addition, it would be nice if the user is allowed to skip the installation of .NET Core and still install SoundSwitch in the event that they know better than the installer.

**Screenshots**
![image](https://user-images.githubusercontent.com/74487/88485154-80403b00-cf39-11ea-8b5e-1ffda55bdf22.png)
![image](https://user-images.githubusercontent.com/74487/88485157-8209fe80-cf39-11ea-9294-803fad9c6b3e.png)

**Comment by Belphemur** [comment]
Known issue.

To be fixed in a following version.

For now, I can give you this "apha" build that has the installer fix.


[SoundSwitch_v5.4.1.27032_Beta_Installer.exe.zip](https://github.com/Belphemur/SoundSwitch/files/4978223/SoundSwitch_v5.4.1.27032_Beta_Installer.exe.zip)

**Comment by skst** [comment]
_This is a duplicate of #474, but since it's closed, I'm commenting here._

The beta installer `SoundSwitch_v5.4.1.27032_Beta_Installer.exe` you provided in #486 still attempts to install .NET Core 3.1.4 even though 3.1.6 is already installed (and it fails).

![image](https://user-images.githubusercontent.com/74487/88491420-3884d800-cf68-11ea-80ba-fecc62b43e17.png)

![image](https://user-images.githubusercontent.com/74487/88491425-476b8a80-cf68-11ea-905b-dd96aee74ba3.png)

**Comment by Belphemur** [comment]
@skst Let me guess, you're a C# developer and you have the SDK installed ?

I need to work on the detection of the runtime when SDK is installed.

**Comment by Belphemur** [comment]
If it's the case, can you do a screenshot of your registry at this place ?

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions`

It's supposed to look like this:
![image](https://user-images.githubusercontent.com/197810/88501281-0475db00-cf99-11ea-98c3-d09ee93a4d9c.png)

**Comment by Belphemur** [comment]
Actually, I had a mistake in my Pascal logic ... God I hate that language.

Can you check with this version ? It should be good now.

[SoundSwitch_v5.4.1.24_beta_Installer.exe.zip](https://github.com/Belphemur/SoundSwitch/files/4979896/SoundSwitch_v5.4.1.24_beta_Installer.exe.zip)

**Comment by skst** [comment]
> @skst Let me guess, you're a C# developer and you have the SDK installed ?

😁 What gave it away?

> Actually, I had a mistake in my Pascal logic ... God I hate that language.

Pascal? Ouch. 😬 I didn't enjoy my tenure with that language either.

Anyway... Other than this blank wizard page, it installed fine. Thanks!

![image](https://user-images.githubusercontent.com/74487/88579703-1cd50c80-d010-11ea-8a1a-46a629f4e91f.png)

**Comment by Belphemur** [comment]
@skst Just to keep you in the loop, profile UI doesn't work on this build ^^'

I'm reworking completely the UI to add a system of triggers etc ...
