### ISSUE TITLE
Wrong error message when adding a profile without triggers

### ISSUE THREAD

**Issue by basmith7** [Belphemur/SoundSwitch#488]
**Describe the bug**
Trying to add a new profile says a profile needs a name, but it has a name in the name field. 

**Version**
SoundSwitch v5.5.0.42512

**To Reproduce**
1. Settings > Profiles Tab > Add
2. Type a profile name. 
3. Select playback/recording/communication devices (or don't)
4. Click Save

**Expected behavior**
It saves the new profile, using the name in the name field. 

**Screenshots**
https://i.imgur.com/1UIusGv.png

**Additional context**
Thanks for everything. SoundSwitch is awesome.

**Comment by Belphemur** [comment]
Ho darn, wrong error message.

But you do have an error.

You need to add a trigger to a profile else you can't create it.
