### ISSUE TITLE
When Steam Big Picture is closed, returned the audio default devices as they were before switching

### ISSUE THREAD

**Issue by gitrys** [Belphemur/SoundSwitch#490]
**Is your feature request related to a problem? Please describe.**
If i start a game over Steam Big Picture the audio of the game isn't played (the audio of the Steam Big Picture overlay is played flawlessly on the specified device).

**Describe the solution you'd like**
I can bypass this problem if i check "also switch default device". Here it would be great if there was an option like: "after the trigger isn't active anymore select a specific device" or "activate the previously selected default device".

**Describe alternatives you've considered**
no idea

**Additional context**
[some ideas](https://user-images.githubusercontent.com/54995488/89111866-1bb23e00-d45b-11ea-9f2a-bf698adbbe1c.png)

**Comment by Belphemur** [comment]
Here is the way I've implemented it:

When Steam Big Picture is closed, returned the audio default devices as they were before switching.
