### ISSUE TITLE
Robust enhancement of profile selection, toggling, rotation and no-hotkey profiles.

### ISSUE THREAD

**Issue by 4girl1der** [Belphemur/SoundSwitch#492]
I would like to propose the following which would make this program really robust. 
This addresses issue #420, #409 & #491 plus adds the one feature I would like see no-hotkey profiles with selection from taskbar icon..  

To properly support this workflow would be:
1.  Under the settings Menu: # This works with profiles that have the available trigger of "Fast Rotation"
       1. [x] Add the "ProfileRotateNext" and "ProfileRotatePrevious" hotkey assignments to this area.
       1. [ ] Add a option box to have "Double-click" taskbar icon to rotate profiles instead of output devices. 

1.  Add the following "Available Triggers"
       1. [x] "Fast Rotation"  # This makes those profiles available to the "HotKey" rotation hotkey set under settings as well as the double click the taskbar icon option.
       1. [x] "Taskbar Selection"  # This makes those profiles show up in the list with the devices when you click the taskbar icon. Then a person can manually click the profile wanted to change both devices. Also lets people create profiles who don't want hotkeys.

If I new how to code better, I would help. :)

**Comment by Belphemur** [comment]
Hello,

I like most of the ideas presented here. I'll see what I can do.

**Comment by 4girl1der** [comment]
@Belphemur , Thank you, that is something I can donate too. :)

**Comment by Belphemur** [comment]
I haven't forgot about this.

I'm gonna implement it little by little. Right now, I'll add the profile to the menu when they have the "Taskbar Selection".

**Comment by Belphemur** [comment]
Taskbar Selection is done.

You test it in the dev build:
https://nc.aaflalo.me/s/8DKytYCTAbrn6yz

**Comment by Belphemur** [comment]
With version v6.1.0, you'll be able to switch between using the same hotkey.

At this point, I've implemented most of the feature that was requested, I'm closing this issue :)
## Explanation
https://github.com/Belphemur/SoundSwitch/discussions/738
