### ISSUE TITLE
No scroll bar on Add Profile window when size smaller than the content. 

### ISSUE THREAD

**Issue by littlegreenrock** [Belphemur/SoundSwitch#496]
**Describe the bug**
go to: Settings / Profile / Add
resize this window by dragging the corner.  
Result: no scroll bars to access the entirety of the frame. 

Problem: when operating on a 1280 x 800, or similarly small screen res., the user is unable to see all of this menu. 

This issue will never be seen until a low resolution is used.   It does not seem to affect other windows of the app. 

**Version**
SoundSwitch v5.5.2

[Three screen shots for clarity](https://imgur.com/a/SusBobh)

**Comment by FireEmerald** [comment]
I will take a look at it if @Belphemur hasn't fixed it already 😄
