### ISSUE TITLE
Show dependency between 'Also switch default device' and 'Communication' in profile dialog

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#498]
**Describe the bug**
If the user selects _"Also switch default device"_ in profile **without** a device selected in _"Communication"_ none error is shown.

**Version**
SoundSwitch v5.5.2

**Expected behavior**
A error message should be shown, as the Default device can't be switched without a actual selected one.
The dropdown should be only enabled if the checkbox is checked.

**Screenshots**
![2020-08-27 08_47_28-Add Profile](https://user-images.githubusercontent.com/1107939/91405351-32716800-e842-11ea-870d-7c0a4ec8035d.png)

**Additional Context**
Seems like this configuration does not lead to a crash but the user may wonder why his configuration does not work.

**Comment by Belphemur** [comment]
That configuration works. 

If you select nothing, the global device will be used for everything. 

Setting the communication device is only useful if you want a different one than the global one. 

Sent from Nine
________________________________

**Comment by FireEmerald** [comment]
The "global device" means the device selected in "Playback"?

**Comment by Belphemur** [comment]
Yep. 

Sent from Nine
________________________________

**Comment by FireEmerald** [comment]
I assume you mean with "global device" = "Playback".

I got your point but I think it would be a waaay better to say if the user wants to switch the default device he must define it. The current solution is to much "magic" in the background. At the moment you assume that the user knows what you know: _If there's nothing selected in Communication the Playback device is used._

In addition, the dropdown field can still be edited, although the corresponding checkbox is not active - that's horrible. The dropdown field does not have any effect if the checkbox is not checked.

**Comment by Belphemur** [comment]
I'm not assuming anything, this is the way Windows works. 

If you don't manually set a device as communication, it uses the default playback device. I reproduce the same feature. 

For this one, I'm not going to change the way it works as this is already an advanced feature where you're supposed to know what it does already since you used in Windows. 

Sent from Nine
________________________________
