### ISSUE TITLE
Profiles without change default device may wont work

### ISSUE THREAD

**Issue by FireEmerald** [Belphemur/SoundSwitch#500]
**Describe the bug**
If a profile is configured without the checkbox _"Also switch default device"_ **checked**, the profile does not work as expected.

**Version**
SoundSwitch v5.5.2

**To Reproduce**
1. Sound is on Headphones
2. Create a profile for a media player as shown below
3. Do not check "Also switch default device"
4. Save
5. Start chrome and play a youtube video
6. Start the media player directly via a file
7. Profile is triggered
![2020-08-27 09_22_10-Big Buck Bunny-720p mp4](https://user-images.githubusercontent.com/1107939/91410197-d6f5a900-e846-11ea-8705-4c6643e980b3.png)
8. Main device remains the same
![2020-08-27 09_30_23-Einstellungen](https://user-images.githubusercontent.com/1107939/91410994-03f68b80-e848-11ea-8fa6-2dad52b0a221.png)
9. Output device of the process is configured
![2020-08-27 09_29_22-Einstellungen](https://user-images.githubusercontent.com/1107939/91410883-da3d6480-e847-11ea-9c7c-f22f2398cd52.png)
⚠ This does not always work, i tested it several times and quite often it looked like:
![2020-08-27 14_52_43-Einstellungen](https://user-images.githubusercontent.com/1107939/91444416-ff949780-e874-11ea-8fa3-9b364f535037.png)

**Expected behavior**
Music of the media player is redirected to selected device ("Integrated Speakers"). But it is not - in both cases of (9.).

❓ Perhaps we should by default check the checkbox and if the user tries to uncheck it, we could show a messagebox with a warning to confirm, that unchecking the option may lead to a non-working profile.

**Screenshots**
![2020-08-27 09_18_33-Add Profile](https://user-images.githubusercontent.com/1107939/91409982-81210100-e846-11ea-89cb-d8fe7c5ce921.png)

**Additional**
- Big Buck Bunny: https://cloud.blender.org/p/big-buck-bunny/564c6fd8c379cf0d22a81f83 (play, right click > save video)
- "Standard" (de) = "Default" (en)

**Comment by Belphemur** [comment]
That's the first application that I see that doesn't play nice. Spotify, Firefox, mpv, ... not a problem.

This is only related to MPC-HC. Can't do anything about it.
