### ISSUE TITLE
Is there any chance of supporting changing of the "default format" control panel option? 

### ISSUE THREAD

**Issue by rondnelson99** [Belphemur/SoundSwitch#501]
On my sound card I use Dolby Digital Live to get 5.1 audio through SPIDF. However, when I'm not playing a surround sound-enabled game I like to just use 2-channel LPCM to avoid the quality loss that DD Live causes.

 I can do this in sound device properties -> advanced -> Default format, and swap between 16-bit 48000hz and Dolby Digital. However, doing this every single time is a pain. I would love if there was a way to automate this, and I'd imagine others would too, even if Dolby Digital Live is becoming increasingly obscure.

**Comment by Belphemur** [comment]
Hello,

Thanks for your request, but this is outside the scope of the application.

**Comment by rondnelson99** [comment]
Understandable. I thought that might be the case. Thanks anyways, and Im sure this program is very helpful for many others.
