### ISSUE TITLE
Backspace key not working while Soundwitch is running

### ISSUE THREAD

**Issue by RostokMcSponge** [Belphemur/SoundSwitch#503]
**Describe the bug**
Backspace key not working while Soundwitch is running

**Version**
SoundSwitch v5.5.2

**To Reproduce**
1) Run Soundswitch
2) Type in any app, browser etc
3) Hit backspace

**Expected behavior**
Backspace key to function normally and delete char to left of cursor.

**Screenshots**
N/A

**Additional context**
Closing Soundswitch re-enables the backspace key.
All other keys including Delete key work.
Toggling Hotkey feature makes no difference.
Previous installed version worked fine.
Installed latest Windows updates around the same time (Feature update 2004, KB4569745, KB4561600)

**Comment by Belphemur** [comment]
Resolved in discord.

Needed to reinstall SoundSwitch.
