### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by JSWorkspace1** [Belphemur/SoundSwitch#508]
[SoundSwitch-crashlog-17_9_2020.zip](https://github.com/Belphemur/SoundSwitch/files/5240472/SoundSwitch-crashlog-17_9_2020.zip)

**What were you doing when it crashed ?**
soundwitch was set to start on Windows start. 
Crash accrued on System start.

System: win10;   soundwitch version 5.5.3
but the crash also happened with the previous version.

**Comment by JSWorkspace1** [comment]
Also the Crash Logger had some Problems.  But probably unrelated 
![cant save Report](https://user-images.githubusercontent.com/23420842/93497953-6a377100-f911-11ea-8ceb-79d1f36cf3c0.png)

**Comment by Belphemur** [comment]
Hello,
It seems you have 2 installation of SoundSwitch running together ... (like one installed as User and the other for the whole system).

Can you uinstall SoundSwitch ? Then check that c:\Program Files\SoundSwitch and also C:\Users\Antoine\AppData\Local\Programs\SoundSwitch are deleted.

Then reinstall SoundSwitch (you don't need to remove your settings).

**Comment by JSWorkspace1** [comment]
hmm weird I thought I tried a clean uninstallation before and found no leftover files but it  seems to be resolved for now. Maybe the Visual Studio build I had played with had registered itself for autoStart :/     thank you anyway 👍  great program
