### ISSUE TITLE
Computer screen will not sleep when Sound Switch running

### ISSUE THREAD

**Issue by jakkaj** [Belphemur/SoundSwitch#509]
**Describe the bug**
I was having trouble figuring out why my screen would never sleep. Even if I force it to sleep using a PowerShell command it would immediately turn back on again. 

Upon closing SoundSwitch I found that the screen would sleep correctly.  

**Version**
SoundSwitch v5.5.3

**To Reproduce**
With Sound Switch running, enter the following PowerShell command:

```(Add-Type -MemberDefinition "[DllImport(""user32.dll"")]`npublic static extern int SendMessage(int hWnd, int hMsg, int wParam, int lParam);" -Name "Win32SendMessage" -Namespace Win32Functions -PassThru)::SendMessage(0xffff, 0x0112, 0xF170, 2)```

**Expected behavior**
The PC screen sleeps after timeout or when forced.

**Comment by Belphemur** [comment]
Thanks for the report and the command.

I'm not able to reproduce. Was the current sound device the screen when it went to sleep ?
