### ISSUE TITLE
Add recent version to winget-pkgs?

### ISSUE THREAD

**Issue by r7kamura** [Belphemur/SoundSwitch#512]
**Is your feature request related to a problem? Please describe.**

I tried to install SoundSwitch via `winget install SoundSwitch`, but I was stuck with a .NET-related problem.

![image](https://user-images.githubusercontent.com/111689/95061338-6e97c280-0736-11eb-97ed-453ddb1e8721.png)

**Describe the solution you'd like**

It would be nice if some new version will be added to microsoft/winget-pkgs, like https://github.com/microsoft/winget-pkgs/pull/1359. (...or should I send a pull request to winget-pkgs instead?)

**Additional context**

Thank you for the great product! I really like SoundSwitch ❤️

**Comment by Belphemur** [comment]
Since winget-pkgs only works in User mode, I can't have the installer actually work completely if .NET Core isn't installed already ...

I might need to change the config to not be run as user.

**Comment by Belphemur** [comment]
Done

https://github.com/microsoft/winget-pkgs/pull/4683

Waiting for approval

**Comment by r7kamura** [comment]
I installed it successfully via `winget`. Thanks so much!

**Comment by FireEmerald** [comment]
We now got three ways to install SoundSwitch or did i forget one? @Belphemur 

- `choco install soundswitch` https://chocolatey.org/packages/soundswitch
- `winget install SoundSwitch` https://github.com/microsoft/winget-pkgs/tree/master/manifests/AntoineAflalo/SoundSwitch
- `manual` https://github.com/Belphemur/SoundSwitch/releases

**Comment by Belphemur** [comment]
@FireEmerald That is true.
Actually, for the manual I'd rather have the people use https://soundswitch.aaflalo.me (no need to wonder what to download when you're not used to GitHub).


I realize I should ping @teknologist because the config of choco is wrong, it says the dependency requires dotnet framework, now it requires dotnet core.
