### ISSUE TITLE
App crashes when update is declined

### ISSUE THREAD

**Issue by Xianth** [Belphemur/SoundSwitch#516]
**Describe the bug**
When i decline to upgrade app to newest version - app crashes and shows endless tabs with error.

**Version**
SoundSwitch v5.5.2.29612

**To Reproduce**
1. Go to task bar
2. Click on sound switch icon
3. decline the popup with request to update

**Expected behavior**
update window is closed without app crash
**Screenshots**

**Additional context**

**Comment by Belphemur** [comment]
Can you give me a screenshot or the content of %appdata%/SoundSwitch ?

Without this, I won't be able to understand what's happening.
