### ISSUE TITLE
Selecting only certain devices gets overwritten when opening the app

### ISSUE THREAD

**Issue by alexraileanu** [Belphemur/SoundSwitch#520]
**Describe the bug**
If I have 3 devices and I deselect one of them, when I close and re-open the app, all 3 devices are selected again.

**Version**
SoundSwitch v5.5.4.33783

**To Reproduce**
1. Go to Playback
2. Deselect one of the selected devices
3. Close the window
4. Re-open from tray

**Expected behavior**
I expect only the devices that I selected to be checked, however all of them are checked.

**Screenshots**

**Additional context**
I believe this is a relatively recent bug as it was not happening before.

Edit: it looks like this happens only when I don't re-open the GUI again. If I leave it closed, then the expected behavior happens and it only cycles thru the ones I have selected.

**Comment by Belphemur** [comment]
Can you add a screenshot of the setting page with the devices ?

I wonder if it's because they have the "same name". It is also possible there is something wrong in the config.

Can you zip the content of %appdata%/SoundSwitch and also attach it ?

**Comment by alexraileanu** [comment]
they have indeed the same name. isn't there some unique id internally that can be used rather than their names?

screenshot: https://i.imgur.com/kmI6hpn.png
%appdata% contents:https://github.com/Belphemur/SoundSwitch/files/5554426/SoundSwitch.zip

**Comment by Belphemur** [comment]
Windows usually appends a number after the name, the problem, it does the same when it's the same device plugged in a different USB port.

I've decided to clean the name. Which mean, if they have the same name, it will match all.

In your case, both device have exactly the same name.

You can rename the device in the Window playback settings to different one, SoundSwitch will pickup on it and you'll be able to deselect the device you don't want without problem.

**Comment by alexraileanu** [comment]
I tried renaming the devices but the problem still exists: https://i.imgur.com/uxB4wyb.png. image from my playback settings to see the renamed devices: https://i.imgur.com/54LtTiF.png

**Comment by Belphemur** [comment]
Can you send me again the %appdata%/SoundSwitch ?

This should have worked.

**Comment by alexraileanu** [comment]
i see in the soundswitch config json that each device has an id that looks like a UUID, is it not better to use this to check which have been selected? 

[SoundSwitch.zip](https://github.com/Belphemur/SoundSwitch/files/5566132/SoundSwitch.zip)

**Comment by Belphemur** [comment]
Yes and no. As said the UUID is also depending on which port you plug the device, it's generated by Windows and can't be trusted as unique identifier of the device, but unique identifier of the plugged soundcard. (USB make all this very complex ...).

For now:
* Stop SoundSwitch
* Replace the config file by the one attached to this message
* That should do the trick


[SoundSwitchConfiguration.json.zip](https://github.com/Belphemur/SoundSwitch/files/5568417/SoundSwitchConfiguration.json.zip)

**Comment by Belphemur** [comment]
I've also fixed some code path to be sure you won't need to edit manually the config.

**Comment by alexraileanu** [comment]
this (and the new version) seems to do the trick. thanks!
