### ISSUE TITLE
Open the update installer's Github issue links in the default browser

### ISSUE THREAD

**Issue by sfkpmr** [Belphemur/SoundSwitch#525]
**Describe the solution you'd like**
When clicking the issue link of what was fixed in the latest update, it is opened in the update installer itself. It would be easier to handle in the default browser.

**Additional context**
It's both harder to read in the installer window, and there's no back button to go back to update details.

**Comment by Belphemur** [comment]
I think I've fixed this in a previous release.

I'm closing this for now. If it's not fixed don't hesitate to reopen it.
