### ISSUE TITLE
Keep configuration when updating

### ISSUE THREAD

**Issue by PereViader** [Belphemur/SoundSwitch#526]
**Is your feature request related to a problem? Please describe.**
Every time sound switch updates, the configuration is lost and it needs to be reconfigured.

**Describe the solution you'd like**
It would be great if sound switch only lost the configuration when the configuration actually got invalid from the previous version.
And even better if there was a way to programmatically update configurations to keep it valid even after an update.

**Describe alternatives you've considered**
A possible solution to this is to never update but I think this is not a good solution as then we don't have access to the latests feature updates.

**Comment by Belphemur** [comment]
It's already the case, SoundSwitch never reset the config unless asked.

I think I understand what's happening in your case:

You must have asked SoundSwitch installer to remove your config at one point.

The update keeps the settings of the installer and apply them again, hence deleting your config at each update.

Manually install SoundSwitch from the latest version and be sure you don't have the "remove config" checked.

**Comment by PereViader** [comment]
Thank you for the recomendation!

User feedback: If this is the actual behaviour it is a bit confusing. From an outside prespective it sounds like it should only remove the configuration once when installing and not each time.

**Comment by Belphemur** [comment]
@PereViader Agreed, this isn't the wanted behavior.

Issue created for fixing it: https://github.com/Belphemur/SoundSwitch/issues/538
