### ISSUE TITLE
Unable to Switch Speakers

### ISSUE THREAD

**Issue by compupix** [Belphemur/SoundSwitch#529]
Yesterday this was working just fine...
Yesterday, turning on the Bluetooth speaker would activate it and turn off the desktop speakers.  Today, turning the Bluetooth speaker on or off has no effect on which speakers are used. The desktop speakers are always used regardless of Bluetooth speaker on / off setting and regardless of what is selected using the SoundSwitch speaker switch.

Windows 10.0.19042
SoundSwitch 5.6.1.38743

Sound:
![sound](https://user-images.githubusercontent.com/38867927/101862174-9cc6c380-3b26-11eb-8f1c-8bd6fa1b2205.PNG)

Device Manager:
![device manager](https://user-images.githubusercontent.com/38867927/101862244-c4b62700-3b26-11eb-8197-8412a5e1d1cf.PNG)

The Bluetooth speaker shows up as SoundTorch:
![blue](https://user-images.githubusercontent.com/38867927/101862424-2e363580-3b27-11eb-828a-72475cb7fb07.PNG)

Sound with Bluetooth speaker on:
![sound with blue on](https://user-images.githubusercontent.com/38867927/101862571-80775680-3b27-11eb-8222-764323c3ce2b.PNG)

Sound: Recording
![recording](https://user-images.githubusercontent.com/38867927/101862715-c2a09800-3b27-11eb-8aea-8099f816c300.PNG)

SoundSwitch Settings with the Bluetooth speaker off:
![settings blue off](https://user-images.githubusercontent.com/38867927/101863102-2e830080-3b28-11eb-945b-acb3851a91d5.PNG)

SoundSwitch Settings with Bluetooth speaker on:
![settings blue on](https://user-images.githubusercontent.com/38867927/101863494-67bb7080-3b28-11eb-946b-484a0ba9d840.PNG)

Double clicking on the SoundSwitch tray icon puts up a banner indicating that the playback device IS changing between: Speakers (Realtek (r) audio) and Bluetooth speaker (Soundtorch hand-free AG audio.) But, the sound continues to come from the desktop speakers.

Single click SoundSwitch Menu:
![menu](https://user-images.githubusercontent.com/38867927/101864632-1eb7ec00-3b29-11eb-8405-875cecd0a4c3.PNG)

Alternate Single click SoundSwitch Menu:
![alt menu](https://user-images.githubusercontent.com/38867927/101864726-53c43e80-3b29-11eb-8569-671b43219793.PNG)
The sound is still coming out of the desktop speakers.

Thanks!

**Comment by compupix** [comment]
Windows just updated my system. I made no other changes. 
The switching between the Bluetooth speaker and the desktop speakers is working as desired. 
I made no other changes.
I wish I could save the current configuration!
I know it will break again some time in the future.
For now, it works.

**Comment by Belphemur** [comment]
Sorry to come so late.

Bluetooth is always a weird beast for sound in Windows (and any OS in general)...

Happy to hear it works for now.
