### ISSUE TITLE
Add translation for Traditional Chinese (zh_Hant)

### ISSUE THREAD

**Issue by AlexisKerib** [Belphemur/SoundSwitch#531]
I added traditional chinese (zh_Hant) to weblate

**Comment by Belphemur** [comment]
Thanks for your work, I'll add support for it in SoundSwitch

**Comment by AlexisKerib** [comment]
New option "正體字/繁體字"(ChineseTraditional/zh_Hant/CHT) is not work correctly
The display is the same as "汉语"(ChineseSimplified/zh_Hans/CHS)

And I suggest changing label string "正體字/繁體字" to "中文 (正體)" and "汉语" to "中文 (简体)" here
https://github.com/Belphemur/SoundSwitch/blob/56cc4f157f15c8bae9c6b138251db231733e6090/SoundSwitch/Localization/Factory/Lang/Langs.cs#L91
https://github.com/Belphemur/SoundSwitch/blob/1d5f762867e528190d678259513e345893f69d3d/SoundSwitch/Localization/Factory/Lang/Langs.cs#L103
