### ISSUE TITLE
Updater window open pages inside itself

### ISSUE THREAD

**Issue by alexantr** [Belphemur/SoundSwitch#536]
**Describe the bug**
Updater window shows changelog page and if I click on any link new page opens inside this window and it looks broken

**Version**
SoundSwitch v5.6.1 and v5.7.0 maybe

**To Reproduce**
1. Wait until new version will be released
2. Click on link in changelog in updater window
3. See broken page

**Expected behavior**
Pages must open in default browser in new tab.

**Comment by Belphemur** [comment]
It's a known issue, I need to rework the "browser" since I only use it to display the markdown.
