### ISSUE TITLE
New option "正體字/繁體字" is not work correctly

### ISSUE THREAD

**Issue by AlexisKerib** [Belphemur/SoundSwitch#537]
**Describe the bug**
New option "正體字/繁體字"(ChineseTraditional/zh_Hant/CHT) is not work correctly
The display is the same as "汉语"(ChineseSimplified/zh_Hans/CHS)

**Version**
SoundSwitch v5.7.0

**Additional context**
And I suggest changing label string "正體字/繁體字" to "中文 (正體)" and "汉语" to "中文 (简体)" here
https://github.com/Belphemur/SoundSwitch/blob/56cc4f157f15c8bae9c6b138251db231733e6090/SoundSwitch/Localization/Factory/Lang/Langs.cs#L91
https://github.com/Belphemur/SoundSwitch/blob/1d5f762867e528190d678259513e345893f69d3d/SoundSwitch/Localization/Factory/Lang/Langs.cs#L103

**Comment by Belphemur** [comment]
Thanks for opening an issue for it.

I need to dig deeper in the Localization and Chinese language, it doesn't seem to work like the other ones.
