### ISSUE TITLE
Windows Notification option displays Banner (not Windows Notification)

### ISSUE THREAD

**Issue by skst** [Belphemur/SoundSwitch#539]
**Describe the bug**
When the **Notification** setting is set to _Windows Notification_, and the user presses a profile's hotkey combination for the _current_ profile, SoundSwitch displays a banner (not a Windows Notification).

When the **Notification** setting is set to _Windows Notification_, and the user presses a profile's hotkey combination for a _different_ profile, SoundSwitch displays a banner **and** a Windows Notification.

**Version**
SoundSwitch v5.7.0

**To Reproduce**
1. Set **Notification** setting to _Windows Notification_.
2. Press the hotkey combination for the current profile.
3. Note that a banner is displayed and no Windows Notification is displayed.
4. Press the hotkey combination for a different profile.
5. Note that a banner is displayed and a Windows Notification is displayed.

**Expected behavior**
When **Notification** setting to _Windows Notification_, I expect only a Windows Notification to appear when I press the hotkey combination for a profile.

**Screenshots**
![2021-01-13](https://user-images.githubusercontent.com/74487/104521822-459f8d00-55c3-11eb-89ff-72fbad91cfb4.png)
![Screenshot 2021-01-13 170903](https://user-images.githubusercontent.com/74487/104521828-489a7d80-55c3-11eb-8574-d0f0fb49d816.png)

**Additional context**
Before setting the **Notification** setting to _Windows Notification_, it was set to _Banner_.

**Comment by Belphemur** [comment]
Thanks for the report.

It's a known issue, for now the Profile notification bypass the setting an only uses banner because the amount of information given might be longer than the longer than what Windows accepts for its notification.

Also, it wouldn't make much sense with the other available notification.
