### ISSUE TITLE
Soundswitch 3.7.0.23142 crashed when I tried to update it through the update button.

### ISSUE THREAD

**Issue by Hoanui** [Belphemur/SoundSwitch#54]
Here is the crashlog.

[SoundSwitch-crashlog-30_12_2015.zip](https://github.com/Belphemur/SoundSwitch/files/74831/SoundSwitch-crashlog-30_12_2015.zip)

**Comment by Belphemur** [comment]
I found the bug. Thanks for the Crashlog.
I removed the previous version.

Unfortunately because of the bug you'll have to download manually the new version.

**Comment by Hoanui** [comment]
Yeah, I already did.

**Comment by Belphemur** [comment]
Sorry for the inconvenience, please download manually the last version (3.8.1).  https://github.com/Belphemur/SoundSwitch/releases/tag/v3.8.1
