### ISSUE TITLE
Unable to add single monitor sound source

### ISSUE THREAD

**Issue by sfkpmr** [Belphemur/SoundSwitch#542]
**Describe the bug**
I have a USB headset and two monitors with speakers (using DP), and can't add just one of the monitors to SoundSwitch.

**Version**
SoundSwitch v5.7.1 and 5.6.1.38743.

**To Reproduce**
1. Go to settings and add USB headset and one monitor.
2. CTRL + ALT + F11 to switch sound source and notice there's more than two.
3. Go back to settings, now both monitors are added.

**Expected behavior**
Go to settings, add one monitor, and now you can switch between USB headset and one monitor.

**Screenshots**
First time going to settings.
![sound1](https://user-images.githubusercontent.com/10453979/104856586-cf2cc300-5913-11eb-9ad3-a84b9245f1e9.PNG)

After adding one monitor and noticing the problem.
![sound2](https://user-images.githubusercontent.com/10453979/104856587-d358e080-5913-11eb-8720-d4e9dc5cd488.PNG)

**Additional context**
This has worked in the past. I noticed it now with the latest version, so I think it worked with 5.6.1, but when I reinstalled it and cleared settings, it didn't. I'm now running v5.5.3.26916 and have it working properly.

**Comment by Belphemur** [comment]
Hello,

It's a known issue when you have two devices with the exact same name.

## Troubleshooting

1. Unselect the device
2. Use SoundSwitch to go to playback devices
3. Select the device you want and rename it (like screen right, screen left).
![image](https://user-images.githubusercontent.com/197810/104856855-c1ab1500-58e2-11eb-918b-a0e7622d29a3.png)


That'll fix it :)

This was put in place to help in the case of USB devices, unfortunately causes issue for multi screen setup using the exact same model.

**Comment by sfkpmr** [comment]
> Hello,
> 
> It's a known issue when you have two devices with the exact same name.
> 
> ## Troubleshooting
> 1. Unselect the device
> 2. Use SoundSwitch to go to playback devices
> 3. Select the device you want and rename it (like screen right, screen left).
>    ![image](https://user-images.githubusercontent.com/197810/104856855-c1ab1500-58e2-11eb-918b-a0e7622d29a3.png)
> 
> That'll fix it :)
> 
> This was put in place to help in the case of USB devices, unfortunately causes issue for multi screen setup using the exact same model.

Thank you and keep up the good work! 👍
