### ISSUE TITLE
Webclient exception when SoundSwitch tries to update multiple times

### ISSUE THREAD

**Issue by sfkpmr** [Belphemur/SoundSwitch#543]
**Describe the bug**
If you click the SoundSwitch icon in the notification area multiple times with an available update, you get this error:

![sound3](https://user-images.githubusercontent.com/10453979/104856899-47e04f00-5915-11eb-8ffe-f14dd37a7ad1.PNG)

![crash2](https://user-images.githubusercontent.com/10453979/104857066-52e7af00-5916-11eb-80a6-959660299417.PNG)

**Version**
SoundSwitch v5.6.1

**To Reproduce**
1. Click SoundSwitch in the notification area.
2. Click again.
3. Click again.
4. After a couple of times, maybe depending on download speed, you get the error.

**Expected behavior**
The update shouldn't be affected by multiple icon clicks. Seems to launch multiple updates/downloads?

**Comment by Belphemur** [comment]
Good catch, I should block launching more than once the Update form, it hasn't been design for that.
