### ISSUE TITLE
SoundSwitch 5.7.1 will not start after installation.

### ISSUE THREAD

**Issue by basrieter** [Belphemur/SoundSwitch#545]
**Describe the bug**
I just upgraded from 5.7.0 to 5.7.1 and after the upgrade SoundSwitch will not start. Reverting back to 5.7.0 solves the issue.

**Version**
SoundSwitch v5.7.1

**To Reproduce**
1. Install
2. Try to run

**Expected behavior**
It should start SoundSwitch.

**Screenshots**
n.a.

**Additional context**
n.a.

**Comment by Belphemur** [comment]
Yeah I just realized it can happen.

On it. I'll re-release the v5.7.1

**Comment by basrieter** [comment]
Would it not be better to call it v5.7.1.1?

**Comment by bhamans** [comment]
Same issue here after a fresh and first install of 5.7.1 the problem does not occur with 5.7.0.

**Comment by Belphemur** [comment]
I'll simply ignore 5.7.1, and only release 5.7.2

**Comment by Belphemur** [comment]
Should be good with v5.7.2

**Comment by basrieter** [comment]
Yes, it's working again. Thank you so much!
