### ISSUE TITLE
Add an easy way for the user to get a ZIP with his config and logs

### ISSUE THREAD

**Issue by Belphemur** [Belphemur/SoundSwitch#546]
To make support easier, I should add a basic menu entry to generate the dump and have the user be able to give it to me directly.

Akin to what happens when SoundSwitch crashes.

**Comment by FireEmerald** [comment]
In addition it could be also an idea to submit any unhandled exceptions from clients automatically to a service which allows tracking of error behavior. The only problem here is to find a good service for free 😅 I don't know one right out of the box, but googling may show some good results. I know that at least for android there are several free solutions out there.

**Comment by Belphemur** [comment]
I thought of checking some telemetry/crash services, a lot of them have free tier (like new relic). The problem lies in the need for a privacy policy and communicate the feature correctly to the users.

I'll have to be sure we support GDPR, let the user opt-in/opt-out etc... 
For now, having a simple entry in the menu for getting all the logs seems the best case.

The popup only shows if the exception is unhandled and make the application crash.
