### ISSUE TITLE
Add methods of switch only communication device.

### ISSUE THREAD

**Issue by VapidLinus** [Belphemur/SoundSwitch#549]
**Is your feature request related to a problem? Please describe.**
I am unable to use SoundSwitch's 1) keyboard shortcuts or 2) [quick switch menu](https://i.imgur.com/VeZ6eoc.png) to switch the _communication device_ exclusively.

**Describe the solution you'd like**
I have two suggestions that I would appreciate. Either would solve my issues, but ideally both would be preferable.

1) Add a seperate keyboard shortcut that only switches the _communication device_. Currently it is possible to disable the "Switch Default Communication Device" toggle, which lets me control the _playback device_ seperatel. With the toggle on, you can control both together. But there is currently no way to only switch the _communication device_.

2) Add an option that right-clicking something in the [quick switch menu](https://i.imgur.com/VeZ6eoc.png) sets the _communcation device_.

Of course these features could be refined and better integrated with the current options that SoundSwitch offers for adjusting the default devices.

**Describe alternatives you've considered**
So the solution to my actual problem could be solved in a better way than my above suggestions, but I expect it would be a less common feature.

I have 2 playback devices that I care about. I have my headphones, and I have my speakers. The perfect solution for me is that when I use SoundSwitch to switch to my speakers, both the _playback_ and _communication_ device would be set to my speakers, like so:
![image](https://user-images.githubusercontent.com/4418470/107117575-86fe2200-687b-11eb-88a9-bef713c7f443.png)

And then when I use SoundSwitch to switch to my headphones, the _playback_ device would indeed be my main headphones device, but the _communication_ device would be set to a seperate device, like so:
![image](https://user-images.githubusercontent.com/4418470/107117601-b0b74900-687b-11eb-9981-2cca946c3dee.png)

**Comment by dkurylo** [comment]
Need a separate hot key and taskbar context menu entry to switch between communication devices as well.

**Comment by lgoose** [comment]
you can save two profiles, only swapping the default comms device btw them and assign a separate shortcut to each

**Comment by Belphemur** [comment]
As this is possible with profile, I'll close this issue :)
