### ISSUE TITLE
Crash when using Windows Notification after SoundSwitch restart and switch device

### ISSUE THREAD

**Issue by StephenCavender** [Belphemur/SoundSwitch#55]
After updating to v3.8.1.19304 soundswitch crashes when I switch playback devices. It successfully switches playback devices but reports a crash and closes. It produced this zip of a crashlog.

[SoundSwitch-crashlog-30_12_2015.zip](https://github.com/Belphemur/SoundSwitch/files/75053/SoundSwitch-crashlog-30_12_2015.zip)

**Comment by devildant** [comment]
hello,
I have exactly same problem.
(Windows 10)

**Comment by Belphemur** [comment]
Until I come with the fix, you can use this workaround:

0. Go into Settings
0. change the notification type to anything then back to windows notification

**Comment by devildant** [comment]
hello,

thanks, it's work for one instance.
when i restart or when soundswith is restart the problem respawn.

**Comment by Belphemur** [comment]
Yes that's why it's a workaround.
I'm releasing 3.8.2 right now to fix the issue.

**Comment by devildant** [comment]
Nice, thanks a lot
