### ISSUE TITLE
Program not responding after PC starts

### ISSUE THREAD

**Issue by alexantr** [Belphemur/SoundSwitch#550]
Every time I shut down PC and turn it on after some hours SoundSwitch starts but not responding if I click on tray icon. Global hotkeys don't work too. No matter what output device was selected before shut down. SoundSwitch works normally if I restart PC.

Log: [soundswitch20210221.log](https://github.com/Belphemur/SoundSwitch/files/6017431/soundswitch20210221.log) (start at 10:44:26)

**Comment by djemar** [comment]
Same for me, killing the process and restarting it fixes it, too.

**Comment by alexantr** [comment]
This problem happens too often, almost every day. I disabled startup from settings and created task in Task Scheduler. It runs SS at log on with delay 1 minute.
