### ISSUE TITLE
No "Save" button on Profiles - Add.

### ISSUE THREAD

**Issue by falvarezr** [Belphemur/SoundSwitch#551]
**Describe the bug**
Can't save a profile there is no save button.

**Version**
SoundSwitch v5.7.2

**To Reproduce**
1. Go to 'Profiles'
2. Click on 'Add'

**Expected behavior**
A button to save the profile.

**Screenshots**
[![Soundswitchbug.png](https://i.postimg.cc/xCJ3NhWH/Soundswitchbug.png)](https://postimg.cc/fts962WT)

**Additional context**

**Comment by Belphemur** [comment]
Hello,

I have the feeling you're using a very small resolution or a very high scaling level.
This is how the UI is supposed to look like:
![image](https://user-images.githubusercontent.com/197810/108633806-4e964080-7444-11eb-81a9-4d9aad7adabe.png)


If it's not the case, can you try to close SoundSwitch, install this version of .NET and restart SoundSwitch ?

https://download.visualstudio.microsoft.com/download/pr/a8dcbda1-8720-453c-9ec6-5a9d90935643/28754321a8b966f1ce837e6f59035b48/windowsdesktop-runtime-5.0.3-win-x86.exe

**Comment by falvarezr** [comment]
True, using 150% text scaling makes the button go out the window, even maximizing the window won't snap the button in place or add a scrollbar, 100% text sixe shows the button. Thanks for the help, and the program.
