### ISSUE TITLE
unresponsive context menu and crash afterwards.

### ISSUE THREAD

**Issue by azeunkn0wn** [Belphemur/SoundSwitch#553]
It becomes unresponsive after right clicking the soundswitch icon in notification area, then it crashes.
Can't believe this still hasn't been fixed yet. This is the reason why I stopped using it for a while.
Is this uncommon issue?

Event viewer reports:

Source: 
.NET runtime
Details:
Application: SoundSwitch.exe
CoreCLR Version: 5.0.321.7212
.NET Version: 5.0.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC38C4004F (00007FFC38A70000) with exit code c0000005.

Source: 
Application Error
Details:
Faulting application name: SoundSwitch.exe, version: 5.7.2.29590, time stamp: 0x5fbf100e
Faulting module name: coreclr.dll, version: 5.0.321.7212, time stamp: 0x600b9847
Exception code: 0xc0000005
Fault offset: 0x00000000001d004f
Faulting process id: 0x42c
Faulting application start time: 0x01d70d8702d11cec
Faulting application path: C:\Program Files\SoundSwitch\SoundSwitch.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.3\coreclr.dll
Report Id: 503df8a9-2f0d-4762-9052-14c71a7991e6
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Belphemur** [comment]
Sorry for coming so late.

When this happens, can you attach the logs present in: %appdata%/SoundSwitch/logs ?
