### ISSUE TITLE
Can not register or use hotkey that includes middle mouse button

### ISSUE THREAD

**Issue by dkurylo** [Belphemur/SoundSwitch#554]
I wanted to create a hotkey for switching audio and assign it a Win + Ctrl + MButton value.
When I press the combination, it is displayed in the text field and is highlighted green, but when I release the keys, they are not remembered. Seems like it wants to have a keyboard letter or functional key pressed as well.
I tried entering the 4th key to register the combination (Ctrl + Win + MButton + D for example) and by unpressing the presed buttons in certain order was able to accomplish the fact that input reads green "Control + Win + MButton", but this combination still does not work, neither Ctrl + Win + MButton + D works.
I tried to enter Ctrl + Win + MButton but released keyboard buttons before releasing mouse button. It starts reading Ctrl + C for some reason, but the intended combination starts working. It also starts working for plain Ctrl + C (the standard copy to buffer functionality does not work anymore unless I clear the hot key assignment). When I remove this combination from the program and try Ctrl + Win + MButton (to check maybe it indeed works as Ctrl + C), it does not copy the text, so I have no idea how it links this key combination to Ctrl + C and why it starts working.
I checked what key is assigned to MButton in the mouse driver, and it's a standard middle button without any fancy stuff.

Also I tried to use other combination that includes MButton, for example, Alt + Win + MButton, it registers the combination without such problems as above and highlights it green, but does not trigger the switch when the combination is pressed.

Control + MButton does not register as well. As soon as I release the keys the combination is removed from the text input.

**Version**
SoundSwitch v5.7.2.29590
Windows 7 x64 Pro
Logitech MX518

**To Reproduce**
1. Go to settings
2. Click on text input to set up the hot key
3. Try to register a combination that uses keyboard modifiers (Ctrl, Alt) and middle mouse button mouse middle button
4. The combination is cleared when the buttons are released, or if not cleared, it does not work

**Expected behavior**
I expect the combination that includes the middle mouse button to be registered and triggered successfully (e.g. Ctrl + MButton, Ctrl + Win + MButton, Win + Alt + MButton)

**Comment by Belphemur** [comment]
Hello,

Unfortunately SoundSwitch doesn't support using the mouse button as part of the hotkeys.
I have no plan to add support to it for now.

Only when the box stays green, the hotkey is accepted. I should maybe make it more obvious.
