### ISSUE TITLE
App crash randomly

### ISSUE THREAD

**Issue by tomo92s** [Belphemur/SoundSwitch#557]
I'm sending my 3 crash logs from 12th march to 14th march
[soundswitch20210313.log](https://github.com/Belphemur/SoundSwitch/files/6137176/soundswitch20210313.log)
[soundswitch20210314.log](https://github.com/Belphemur/SoundSwitch/files/6137177/soundswitch20210314.log)
[soundswitch20210312.log](https://github.com/Belphemur/SoundSwitch/files/6137178/soundswitch20210312.log)

**Comment by Belphemur** [comment]
Can you try to update .NET to 5.0.4: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.4-windows-x64-installer

And see if it fixes for you ?
