### ISSUE TITLE
Switch all Applications to a device without changing default device

### ISSUE THREAD

**Issue by Gordin** [Belphemur/SoundSwitch#558]
**Is your feature request related to a problem? Please describe.**
I'm currently using the NVIDIA Broadcast App for Meetings/Streaming (it does AI noise cancellation for sound inputs AND outputs). Broadcast creates a virtual Sound Output and input, and you set those in your OBS/Discord/whatever. The actual output/input devices can then be configured in the NVIDIA Broadcast App. My problem is that NVIDIA Broadcast uses the output volume of the selected output device as volume and the volume setting for the Broadcast device doesn't do anything. So when I switch my devices to NVIDIA Broadcast with SoundSwitch, I can't control my volume with the Media keys anymore, because those control the Broadcast device now, which doesn't do anything. I can set all my apps to output to NVIDIA Broadcast manually and keep the default device as my speakers, but I would like to do this one button press.

**Describe the solution you'd like**
What I want is to be able to switch between the following profiles:
1. Output directly to speakers
2. Output directly to headset
3. Output to NVIDIA Broadcast, but Media keys control speaker volume
4. Output to NVIDIA Broadcast, but Media keys control headset volume

This could be achieved if SoundSwitch could switch all running applications (or just selected ones) to one output (NVIDIA Broadcast), while setting the default device to something different (My Speakers or my headset).

**Describe alternatives you've considered**
Another solution for me would be to set NVIDIA Broadcast as input/output device and then somehow make the media keys control the volume of a different device, but I don't know if that's possible.
Also, maybe there is some solution with virtual devices that I can't think of. Or if there is a program that can intercept hardware output devices and route the sound to NVIDIA Broadcast, that could work too.

**Comment by Belphemur** [comment]
Technically using a profile you should be able to decide which application is using which device. And it will be (by default) only for that application.

Other than that, I don't think it's easily doable.
