### ISSUE TITLE
Notification settings reset when Soundswitch closes when choosing "No Notification" (3.8.2.25464)

### ISSUE THREAD

**Issue by Hoanui** [Belphemur/SoundSwitch#56]
Title says everything.

**Comment by Belphemur** [comment]
Really weird bug, it seems to happen only when I set it to No Notification.

**Comment by Belphemur** [comment]
Okay the workaround for the moment is 

0. Close SoundSwitch
0. Open %appdata%\SoundSwitch in the explorer
0. Using Notepad or any other editor open: SoundSwitchConfiguration.json
0. Remove *"DisplayNotifications":false*
0. restart SoundSwitch

**Comment by Hoanui** [comment]
Thank you for your attention.

**Comment by Hoanui** [comment]
Update: It also reset after I shutdown and restarted my PC.

**Comment by Belphemur** [comment]
The time that I correct this, I advise you to use the Sound Notification. It's the less intrusive.
