### ISSUE TITLE
Suggestion: Include the .NET runtime in the application code

### ISSUE THREAD

**Issue by WesselKroos** [Belphemur/SoundSwitch#563]
**Is your feature request related to a problem? Please describe.**
While I've updated SoundSwitch through the years sometimes a new .NET runtime version is installed in the installation/update process. As an user I don't know which runtime versions can be uninstalled since multiple applications might still use it but in practise that seems to be a rare situation. The result is that multiple runtime versions are unused but still installed on an users pc, because we don't want to break other applications. These runtimes seems to take ~200MB of disk storage per runtime version.

**Describe the solution you'd like**
Include the .NET runtime in the application code, so that older versions are automatically removed from the pc.
How to by Microsoft: https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained

**Describe alternatives you've considered**
Removing all older .NET runtime versions after each update of SoundSwitch, but I rather not remove them because it might break other applications.

**Additional context**
![image](https://user-images.githubusercontent.com/31220528/113458914-3d156080-9414-11eb-99a0-8ca73d2fc981.png)

**Comment by Belphemur** [comment]
Hello @WesselKroos,

I tested the self-container feature, but it makes the installer go from ~4 Mb to ~25 Mb.
Which mean, the user will have to download that much at each update. 

You know what, let's give it a try. I've updated the latest release v5.8.0 to use a self-contained version of the app for Windows x64.

You can redownload & reinstall SoundSwitch and give it a try :)

https://github.com/Belphemur/SoundSwitch/releases/download/v5.8.0/SoundSwitch_v5.8.0.35064_Release_Installer.exe
