### ISSUE TITLE
Unable to register Keybinding closes sound switch when opening it 

### ISSUE THREAD

**Issue by PereViader** [Belphemur/SoundSwitch#578]
**Describe the bug**
When sound switch is opened, it states that the keybinding can not be registered on a windows 10 notification and the application closes on its own

**Version**
SoundSwitch v5.8.1

**To Reproduce**
1. I *think* Control Alt M was beeing used by sound switch
2. Open Sound switch

**Expected behavior**
Maybe:
- Sound switch opens and lets you change the keybinding
- Sound switch shows a prompt telling the user that the keybinding cannot be used and that removes that keybinding after pressing OK.
- Sound switch tells the user something very bad happened and the configuration file located at `%AppData%/Roaming/SoundSwitch/SoundSwitchConfiguration.json` should be reset. This could be a good default option for working around and letting the user keep their sound switch installation functional when there is not a more concrete fix.

**Additional context**
Log after sound switch closed:
[soundswitch20210405.log](https://github.com/Belphemur/SoundSwitch/files/6260328/soundswitch20210405.log)

**Comment by Belphemur** [comment]
Hello,

With 5.8.1, I've added a new feature: Mute microphone, it uses CTRL+ALT+M.
Normally, SoundSwitch doesn't stop when the shortcut is used, you're supposed to be able to change it.

1. Launch SoundSwitch
2. Open the settings by right clicking on the systray icon
3. Go to Recording
4. Either disable the Mute microphone (uncheck the checkbox) or change the hotkey.

**Comment by PereViader** [comment]
Hello,

After manually deleting the configuration file at `%AppData%/Roaming/SoundSwitch/SoundSwitchConfiguration.json` I can properly see that and disable it.

If I didn't delete the file, sound switch would not stop closing itself down before I could disable the shortcut.

Thanks!

**Comment by Belphemur** [comment]
It seems your configuration must have gotten corrupted in the process.
I see nothing in the log to explain why it can happen, and without the config itself, it's hard to diagnose.
