### ISSUE TITLE
Explanation of SoundSwitch folder structure

### ISSUE THREAD

**Issue by Alpha-UMi** [Belphemur/SoundSwitch#582]
I noticed that after an update, there is an impressive difference in number of files installed in the program folder. For example, the previous version was about 30 files or so, the latest release (5.8.1 at the time of writing this post) is over 200 files, mainly .net or visual studio files, I presume. In the past, there was a similar difference from one release to the other one. I would like to know why such a huge difference...
@Belphemur thanks in advance!

**Comment by Belphemur** [comment]
Hello,

It's pretty simple. Before SoundSwitch would rely on .NET 5.0 to be installed on the user machine to run.

This caused multiple issue where you couldn't install SoundSwitch without admin privileges + the need from my side to be sure the user is always up to date on the framework.

When issue #563 came, I thought it was time to change the way I package the software.

Now SoundSwitch doesn't need any runtime to be installed, it packages the part it needs to run.

No more need for admin right and no more double update.

The only downside is the size of the installer. From 3 Mb to 25 Mb.

**Comment by Alpha-UMi** [comment]
OK, now I understand. Thank you for explaining to me.

My compliments for your application. Very useful!
