### ISSUE TITLE
Crashes after update has been installed ( Win 7)

### ISSUE THREAD

**Issue by SilasNiewierra** [Belphemur/SoundSwitch#586]
**What were you doing when it crashed ?**
I was trying to update SoundSwitch. After the update I tried to start SoundSwitch and it crashed.

**To Reproduce**
1. Install the latest update

**ZIP**
Drag & Drop the file
[SoundSwitch-crashlog-11_4_2021.zip](https://github.com/Belphemur/SoundSwitch/files/6291183/SoundSwitch-crashlog-11_4_2021.zip)

**Comment by rabelux** [comment]
Same here, also Win 7 user.
[SoundSwitch-crashlog-11_4_2021.zip](https://github.com/Belphemur/SoundSwitch/files/6291583/SoundSwitch-crashlog-11_4_2021.zip)
