### ISSUE TITLE
Add Turkish language

### ISSUE THREAD

**Issue by kbasaran** [Belphemur/SoundSwitch#588]
I would like to translate to Turkish. I am a native speaker and I work in the audio industry.

**Comment by Belphemur** [comment]
Hello,
To do so, connect with your GitHub account to Weblate: https://hosted.weblate.org/projects/soundswitch/

I've added the language to all the components :)
When you've done your translation, just add a comment here, and I'll add the language to the application.

**Comment by kbasaran** [comment]
I completed the translations only today. I see they have been merged when the work wasn't fully finished. Will the latest status at Weblate be merged on following release?

**Comment by Belphemur** [comment]
Yes, every 24h Weblate push the new translation and they will automatically be included in the next release.
