### ISSUE TITLE
Can't see Profiles after update

### ISSUE THREAD

**Issue by UrknallBigBang** [Belphemur/SoundSwitch#589]
After update to SoundSwitch v5.8.2.39980 and then clean install you can't see profiles - the field is empty on screen.

I have tried to delete the settings and make a new Profile but nothing is shown.

SoundSwitch v5.8.2.39980

![Profile](https://user-images.githubusercontent.com/69319033/114298975-3c866500-9ab9-11eb-987b-62b0ef6f2363.png)

**Comment by UrknallBigBang** [comment]
Switching between profiles works and everything works except display profiles

**Comment by Belphemur** [comment]
Hello,

Can you download this zip file: https://nc.aaflalo.me/s/8DKytYCTAbrn6yz

1. Stop SoundSwitch
2. Unzip the archive
3. Run SoundSwitch.exe
4. Does it fixes your issue ?
