### ISSUE TITLE
Mute Input dialog outputs ArgumentException

### ISSUE THREAD

**Issue by fishbiscuit13** [Belphemur/SoundSwitch#596]
**Describe the bug**
Muting the input device creates a message balloon reading:
 "SoundSwitch: ArgumentException
Balloon tip text must have a non-empty value."

**Version**
SoundSwitch v5.8.3.19187

**Comment by Belphemur** [comment]
Thanks for the bug report.

For the moment, can you switch to Banner as notification method, I need to fix this in a later release.
