### ISSUE TITLE
Ability to switch default communications device as well.

### ISSUE THREAD

**Issue by john681611** [Belphemur/SoundSwitch#60]
If I'm using a program like TS3 no sounds are coming though my speakers when default is set to speakers because the default communications isn't switching as well. Can a option be set so default communications changes as well?  Would mean I don't miss any important people.

**Comment by Belphemur** [comment]
This feature is presents in SoundSwitch since version 3.3 I think.

In the settings menu you have a checkbox to set also the switched device as communication device.
