### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by LeBaux** [Belphemur/SoundSwitch#61]
Hi, it would be awesome it I could do the switch with command line, probably one argument would be enough.

```
C:\Program Files\Soundswitch\soundswitch.exe -switchnow
```

...or something like that. It would help me a lot, I can imagine that there are more people using keyboard launchers like me.
Thanks for reply!

**Comment by Belphemur** [comment]
Hello Pierre,

I have difficulty to understand the use case here. Why launching the app 
with a command argument when you can simply use the HotKeys you set in 
the Settings ?
Usually SoundSwitch will run at windows start (when asked in the 
configuration).

**Comment by LeBaux** [comment]
Hi, thanks for such a fast response. Let me clarify. I use [slickrun](https://www.bayden.com/SlickRun/) to launch everything in my computer, and with command line arguments, I do not need to click on anything (most people probably know [executor](http://executor.dk/), or [launchy](http://www.launchy.net/), they do the same thing). Sure you have a hotkey, but I am not really using hotkeys at all. Even when it comes to screenshots, most people use hotkeys, but with [ShareX command line](https://github.com/ShareX/ShareX/wiki/Command-line-arguments) I can do 10 different types of capture with commands. Another example, when I want to connect to my FTP, via [filezilla command line](https://wiki.filezilla-project.org/Command-line_arguments_(Client)), [I use this command](http://i.imgur.com/5B4lN93.png) and I am immediately connected to desired ftp account. All these actions are mostly about eliminating clicking around in GUI. There a is fairly big group of people like me, who use "command launchers", this would be a nice addition.

**Comment by Belphemur** [comment]
The issue is the way SoundSwitch works. It's meant to be kept in the background, monitoring audio device changes/status and hotkeys press.

If you want I could instead provide you a little program that at every launch will switch the audio device to the next available. No configuration, just launch, and it'll switch. (I'm using something similar to test the underlying library I created for SoundSwitch).

**Comment by LeBaux** [comment]
No need to, I don't want to bother you. I found a way around this - I use a script to simulate a hotkey combo. I would like to thank you for continuous support and development of this little nifty tool. It removes that small frustration of crawling under the table to connect/disconnect the headphones after every game of Counter Strike. You should probably have some donate button, I am not really on rich side, but I always try to at least buy a beer for developers like you. Or if you find yourself in Prague, I can buy you one in person. Cheers!

**Comment by Belphemur** [comment]
Great that you find a way to bend it to your needs :)

I'll think about a donation button, for now I prefer to avoid, I won't feel "obliged" to work on this or that because somebody "donated" for it :)

**Comment by CGollhardt** [comment]
@Belphemur My usecase would be a Microsoft Keyboard Favorite Key. I can only lunch a programm in Microsoft Mouse and Keyboard Center. I can not set the favorite key in Sound Switch.

![Microsoft Keyboard](https://imgur.com/aCvXFt0)

**Comment by teeedubb** [comment]
> 
> 
> The issue is the way SoundSwitch works. It's meant to be kept in the background, monitoring audio device changes/status and hotkeys press.
> 
> If you want I could instead provide you a little program that at every launch will switch the audio device to the next available. No configuration, just launch, and it'll switch. (I'm using something similar to test the underlying library I created for SoundSwitch).

Hi,

Any chance you could share this program? I would like to have a icon in my taskbar that switches audio outputs. I tried using AudioEndpointController but that doesnt configure the default microphone like SoundSwitch does.

Thanks

**Comment by jennyd20** [comment]
I also just got a Microsoft Keyboard and I'm trying to customize the favorite keys (like @CGollhardt over a year ago).  A script or a .exe argument would work beautifully (I'm not having any luck trying to hack the keyboard itself to trigger the hotkey combination, unfortunately).

**Comment by CGollhardt** [comment]
Would you accept a pull request?

**Comment by EdSpurrier** [comment]
Well what about as a hack it can listen to an apps (I think Title) and when that is in the foreground it will activate.
So you could potentially make a batch file that opens and closes and has a window title that soundswitch is listening for?
I to use Macro keys to switch between monitor setups, audio devices, hardware and software apps to manage multiple projects and developments
