### ISSUE TITLE
Would be useful: keep the tray popup menu open until it loses focus

### ISSUE THREAD

**Issue by schittli** [Belphemur/SoundSwitch#620]
**Thank you very much for sharing your great work!**

**Is your feature request related to a problem? Please describe.**

There are users like me, who in this menu:
![image](https://user-images.githubusercontent.com/8282673/116806506-c1e7bd00-ab2d-11eb-885c-3d7c15d7cf69.png)

always switch both: the playback and recording device. 
That's why it's a bit annoying if the popup menu closes immediately after one has changed the 1st device: one must always open the popup menu twice to change the other device, too.

**Describe the solution you'd like**
It would be useful if the tray popup menu stays open until it loses focus.

**Describe alternatives you've considered**
Maybe, there are other / better close events than 'loosing the focus', e.g. clicking somewhere outside the menu, another application get's the focus, ...

**Additional context**
See above :-)

Thanks a lot, kind regards,
Thomas

**Comment by Belphemur** [comment]
Hello,

I can't easily change the behaviour of the ContextMenu as it is defined by Windows.

If you create profiles with the trigger "In app menu" you'll be able to switch directly to the profile you want from the that menu.

![image](https://user-images.githubusercontent.com/197810/116816278-48e96500-ab2f-11eb-9fc6-850ac0cc03eb.png)

**Comment by schittli** [comment]
**Thank you very much!,** 
yes, that's an almost perfect solution, I'll write a small suggestion :-)
