### ISSUE TITLE
Garbled code during program update installation

### ISSUE THREAD

**Issue by smallprogram** [Belphemur/SoundSwitch#624]
**Describe the bug**
When the soundswitch prompts that there is a new update, after the update is downloaded, click Install, the installation interface pops up with garbled characters.
![image](https://user-images.githubusercontent.com/6050360/116897047-6ae60300-ac67-11eb-8655-e58d5679db9e.png)

**Version**
SoundSwitch v5.9.0.19580

**Comment by Belphemur** [comment]
Hello,

It's Chinese, it seems the installer detected it as your OS language.

I have no control on this part, usually when the installer starts it ask you for the language you want to use.

Sent from Nine
________________________________
From: zhusir ***@***.***>
Sent: Monday, May 3, 2021 11:30
To: Belphemur/SoundSwitch
Cc: Subscribed
Subject: [Belphemur/SoundSwitch] Garbled code during program update installation (#624)

Describe the bug
When the soundswitch prompts that there is a new update, after the update is downloaded, click Install, the installation interface pops up with garbled characters.
Version
SoundSwitch v5.9.0.19580
