### ISSUE TITLE
Device Switching Hotkey... displaying all existing devices would be useful

### ISSUE THREAD

**Issue by schittli** [Belphemur/SoundSwitch#625]
**Is your feature request related to a problem? Please describe.**

This idea comes from my observation that when I use the hotkey to change the playback / record devices, almost every time I go through all devices twice. The background is that I am never sure whether I have actually caught the right device if I just see this:

![image](https://user-images.githubusercontent.com/8282673/116925473-83e7b780-ac59-11eb-8f06-b7d6c766a10e.png)

I keep asking myself:
* Which devices did the system detect at all?
* What are the names of these devices again?

**Describe the solution you'd like**

Maybe I'm the only one who feels this way, but actually it would be very useful if when switching devices via HotKey (maybe configurable?), if the SoundSwitch Notification always shows all available devices and highlights the device that has now been activated. Something like this mockup:

![image](https://user-images.githubusercontent.com/8282673/116926302-826abf00-ac5a-11eb-9b34-1c15874a4c0c.png)

Thanks a lot, kind regards,
Thomas

**Comment by Belphemur** [comment]
Depending on how many devices a user can have that would make the notification quite big, moreover it wouldn't work with the other type...

For now, I don't plan to implement this, I think it would make the notification quite big. I'd rather figure out a nice stacking way.

**Comment by sfkpmr** [comment]
Yes, I only have two sound devices, and I like being able to just hit the hotkeys once and immediately switch.

**Comment by luopa** [comment]
This issue is pretty much in line with #527 

Windows' design of the "Languge Switching" dialogue (Hold Win-Key and repeatetly press Space) seems to solve this interaction challenge quite nicely.
