### ISSUE TITLE
v5.9.0, Tray ContextMenu: does it make sense to have the few user profiles in a submenu?

### ISSUE THREAD

**Issue by schittli** [Belphemur/SoundSwitch#628]
Good evening

**Is your feature request related to a problem? Please describe.**
It's a great usability improvement to have the User Profiles in the Tray ContextMenu, thank you very much!

But I guess that >95% of the users have only 2..4, maybe 5 user profiles, so there is probably no good reason to hide the profiles in a submenu: the ContextMenu would still be well arranged if they would be displayed in the main menu.

The submenu is a bit annoying, too: The user must navigate to the profile menu item with the mouse, open it with one click and then select the appropriate profile again with one additional click. 

With this concept, it is almost easier to select the playback and recording devices individually :-(

**Describe the solution you'd like**
I would find it **much** more useful if the user profiles were directly visible and selectable:

![image](https://user-images.githubusercontent.com/8282673/117358308-4764c780-aeb6-11eb-9026-27ece9b0c182.png)

I'm pretty sure that users would then only mostly work with the profiles and use the direct device selection only in case of emergency (or if they don't know the way to create profiles ;-))

Thanks a lot, kind regards,
Thomas

**Comment by Belphemur** [comment]
Hello,

True, I guess there wouldn't be that many profiles to warrant a submenu.

However I'll put them first then the speaker and microphone.

**Comment by schittli** [comment]
Hello @Belphemur 

**Thank you very much!**, 
I think it's very useful 😃
