### ISSUE TITLE
Provide ability to disable auto updater

### ISSUE THREAD

**Issue by khanc** [Belphemur/SoundSwitch#63]
Annoyingly this seems to popup and play a sound every several hours that version 3.8.4 is available. A way to disable this update check *without any change to the notifications when the sound is actually switched* would be very welcome.

**Comment by Belphemur** [comment]
I have no control on the sound. This is the decision of the people that reimplemented the basic balloon tips into the Windows 10 shitty notification system.

I won't put a way to disable the updater, but I can add a way to make it stealth. Like chrome or Firefox, it'll download the updates automatically and install them also.

Btw the updater check every 12h and at every launch of the application.

-----Message d'origine-----
De : "khanc" <notifications@github.com>
Envoyé : ‎10-‎01-‎16 13:16
À : "Belphemur/SoundSwitch" <SoundSwitch@noreply.github.com>
Objet : [SoundSwitch] Provide ability to disable auto updater (#63)

Annoyingly this seems to popup and play a sound every several hours that version 384 is available A way to disable this update check without any change to the notifications when the sound is actually switched would be very welcome

**Comment by Technetium1** [comment]
Stealthy updates would be a great thing to implement!
