### ISSUE TITLE
Tray icon not working

### ISSUE THREAD

**Issue by Dominiquini** [Belphemur/SoundSwitch#635]
**Describe the bug**
The tray icon does not respond to mouse clicks, either with the right or left button.
The problem is intermittent. Sometimes I have to click about 5 times until the menu appears!

**Version**
SoundSwitch v5.9.3

**To Reproduce**
1. Start SoundSwitch
2. Click on tray icon (left or right)
3. Nothing hapens (sometimes the PC emit some sound)
4. Keep clicking ... At some point the menu opens!

**Expected behavior**
The correct menu should open on the first click! 

**Screenshots**
---

**Additional context**
The old version (5.9.0) works correctly!

Log: [soundswitch20210508.log](https://github.com/Belphemur/SoundSwitch/files/6446762/soundswitch20210508.log)

**Comment by Belphemur** [comment]
Can you try this build ?
https://nc.aaflalo.me/s/8DKytYCTAbrn6yz

- Stop SoundSwitch if running
- Unzip the archive in a folder (on where SoundSwitch is installed)
- Run SoundSwitch.exe

**Comment by Dominiquini** [comment]
This version seems to be working fine, but it indicates to be 5.8.3 and tries to update as soon as I start the application! 

Thanks.
