### ISSUE TITLE
After Uninstalling unable to use volume control on Windows 10 after switching source output

### ISSUE THREAD

**Issue by Giagiu90** [Belphemur/SoundSwitch#636]
Hi, after uninstalling the software, I'm unable to use volume controls for my keyboard when I switch the audio output.

I've my stereo system attached trough 3.5 audio jack and my Wireless Headset with a usb dongle,

I've been using SoundSwitch to rapidly change audio output from keyboard and it was very good. When I use the hotkey to switch audio outputs, the volume shortcuts on my keyboard "follows" the selected devices, and also on the taskbar I visualize the correct icons (I mean the sound icons).

I've uninstalled the software to make cleaning on my OS, but now after the uninstallation, the behaviour of the volume controls are not following the selected device, even on the taskbar is stuck on one device.

Also i've noticed that when SoundSwitch is installed, I'm unable to change device output from selection into the builtin Windows 10 system.

version used.

SoundSwitch v5.9.2
tried also latest SoundSwitch v5.9.3 but same issue applies

Could you please help me?

Thanks
Gianluca

**Comment by Belphemur** [comment]
Hello,

You need to reset the Windows Application Sound Settings:
![reset-windows-sound-settings](https://user-images.githubusercontent.com/197810/117584305-31375100-b0da-11eb-91c5-fd31ab0f0576.gif)
That should fix your problem.

**Comment by Giagiu90** [comment]
Hi! Your suggestion worked! Thanks a lot.

But why this behaviour? I'd like to keep using SoundSwitch, but also able to change default audio from Windows.

Thanks for all your efforts.

Gianluca

**Comment by Belphemur** [comment]
It's because of the default feature: Also switch foreground application.

I'll disable it for now user, it's an advanced feature that can cause issues like this one.

**Comment by Giagiu90** [comment]
Thank you very much again for the help resolving the issue and also for the technical explanation, indeed as you said is better to keep it disabled by default for the next installations, it will be better for "standard users" :-)

My best regards.

Gianluca

**Comment by Hamza141** [comment]
This is broken for me in the latest version and the fix above isn't working
![image](https://user-images.githubusercontent.com/14940503/224235181-57daa777-ba99-44ad-9574-8a810b5d6332.png)
