### ISSUE TITLE
Add a "stealth" component to the Auto-Update

### ISSUE THREAD

**Issue by Belphemur** [Belphemur/SoundSwitch#64]
The auto update should be able to run in the background, don't display notification and update the program using the silent parameter for the installer.

See #63

**Comment by FireEmerald** [comment]
If you're implementing such an option it would be good if you also add these options:
- Auto Update Check Interval option
- Check for updates every: Daily/Weekly/Monthly

I would move these new options and the selected one on this screenshot to a new region (1):
![2016-01-31 12_54_01-settings beta](https://cloud.githubusercontent.com/assets/1107939/12701979/2d22709e-c81a-11e5-9b5f-48819834463a.png)

Only an example how it could look like ;)

**Comment by Belphemur** [comment]
:+1: Good idea, moving the settings into another tab should make the interface cleaner.

I think I'll just keep the Hotkeys in the same UI but more the rest.
