### ISSUE TITLE
Instead of _Update check disabled_, provide a menu command to check for an update

### ISSUE THREAD

**Issue by skst** [Belphemur/SoundSwitch#642]
**Is your feature request related to a problem? Please describe.**
This came about because I discovered #641. I set **Update Settings** to _Never check for updates_ to avoid the blinking tray icon. However, I found there was no way to trigger an install of an update when one is released.

**Describe the solution you'd like**
Instead of the context menu command changing to _Update check disabled_, it would be very helpful to provide a menu command to check for an update and, if there is one, to offer to install it.

**Describe alternatives you've considered**
I tried changing **Update Settings** back to _Notify me_, but SoundSwitch did not check for an update. (See #641.) I could not find any way to make SoundSwitch check for an update.

**Additional context**

**Comment by Belphemur** [comment]
More information about this here: https://github.com/Belphemur/SoundSwitch/discussions/658
