### ISSUE TITLE
Profile trigger for when devices are changed by Windows

### ISSUE THREAD

**Issue by mdcollins05** [Belphemur/SoundSwitch#648]
**Is your feature request related to a problem? Please describe.**
Windows has a "feature" where it will change the audio input and output devices when you plug in a device. I've got my devices set as I need but there's no way to disable the feature.

**Describe the solution you'd like**
I've started using SoundSwitch to make it easier to change from a hotkey but if there were a feature to automatically apply a profile when Windows decides to change inputs, it would be awesome.

**Describe alternatives you've considered**
I've not found a tool to make this better or disable the feature. SoundSwitch makes this way more tolerable, so I appreciate it!

**Comment by donatopace** [comment]
I have same problem with Bluetooth devices.

**Describe the solution you'd like**
 to automatically apply a profile that restore my default prefered devices when Windows decides to change inputs-outputs.

**Comment by tjanke42** [comment]
I have what is likely a related problem.   I use headphones for audio.    I have an LG large screen TV plugged in to my video card as a secondary screen.  

When I wake the system from hibernation, windows displays a message saying the default output device has been switched from the headphones to the LG's speakers, and the SoundSwitch icon changes to a monitor/tv.  NOTE that the output itself doesn't change, just the icon.  The sound still comes from my headphones, and window's Sound Settings still shows the headphones as the default output device.  
  
Still, if I want SoundSwitch to accurately show which output device the audio is actually going to, I have to switch output devices to something else and then switch back to headphones.  It's a pain.

**Comment by codemann8** [comment]
@mdcollins05 @donatopace @tjanke42
I too have been very annoyed by Windows 10's "feature", so I forked this project and added a new trigger to add to your Profiles. This will ensure you will always be on the device of your choosing. [here](https://github.com/codemann8/SoundSwitch)
Altho, you will be required to compile the app yourself.

**Comment by xcasxcursex** [comment]
Epic, thanks so much. That's been driving everyone insane for years.
