### ISSUE TITLE
Connect to bluetooth headphones and then switch

### ISSUE THREAD

**Issue by Tratcher** [Belphemur/SoundSwitch#65]
My PC has normal speakers as well as a pair of bluetooth headphones. Normally these work fine with SoundSwitch. However, if I power off the headphones and then power them back on they will not automatically reconnect to the PC, meaning I can't use SoundSwitch to switch over to them. I have to open the system playback devices menu, select the headphones, hit Connect, and then use SoundSwitch to switch to them.

Is this a process SoundSwitch could help streamline? Perhaps with a key combo to connect to the headphones and then switch over to them?

**Comment by Belphemur** [comment]
Unfortunately this is outside the scope of SoundSwitch. This is directly linked to the bluetooth manager of windows and not the sound manager. Usually each connectable device remember the last device to which it has been connected and reconnect to it automatically (I have that with my bluetooth speakers).

On windows 10 they made is a little bit easier to connect to the bluetooth device: http://windows.microsoft.com/en-ca/windows-10/getstarted-connect-to-bluetooth-devices
Usually if the device was the last default device, windows will reswitch to it automatically upon connection.

**Comment by Tratcher** [comment]
Thanks, I hadn't known about that Win10 feature yet. It is good about switching the default when connected. I think most of my trouble comes from using the same headphones with both my phone and my PC, so it's not sure which device it should auto-connect to.

Now if only more of my games honored the change of default audio output without restarting them...
