### ISSUE TITLE
Banner notifications may not be displayed

### ISSUE THREAD

**Issue by kreis117** [Belphemur/SoundSwitch#653]
**Describe the bug**
If you press the hotkey to switch the input or output device immediately after pressing the hotkey to mute the input device, the banner notification will not be displayed.

**Version**
SoundSwitch v5.9.4.42272

**To Reproduce**
1. On the settings screen, set "Notification" to "Banner" and "Tooltip on Hover" to "For both Devices".
2. Press the "Toggle mute" hotkey.
3. Immediately after that, press the hotkey to switch the input device or output device.
4. While the "Toggle mute" banner notification is displayed, the banner notification when switching between the input device and the output device is not displayed.

**Expected behavior**
I think the banner notification will always be overwritten.

**Screenshots**
None.

**Additional context**
None.

**Comment by Belphemur** [comment]
Now with the quick menu, I don't this matter much anymore.
