### ISSUE TITLE
Make new instance of SoundSwitch close the previous one

### ISSUE THREAD

**Issue by Life4YourGames** [Belphemur/SoundSwitch#66]
Just installed SoundSwitch Beta, works as a charm :+1: 

But I also discovered some possible cosmetic enhancements:
![image](https://cloud.githubusercontent.com/assets/8037924/12373890/7d72a5d2-bc8a-11e5-8a89-2b6410f942b9.png)

This is what happens, when I start the latest release (3.9.1.14658) (via the shortcut added to the desktop by the installer) and SoundSwitch is already running.
This window closes after a few seconds and the running instance is still working fine.

Since this seems to be more a cosmetic insufficiency than a real problem I don't include logs by now, tell me, if you need them.

Maybe you could just call the existing SoundSwitch-Instance to open itself, when the user clicks the shortcut. (For example using IPC)

Also: Is selecting "Sound Switch Beta X.X.X" from the context-menu of the tray icon supposed to do nothing ?

**Comment by Belphemur** [comment]
I should display a little warning that SoundSwitch is already open and then close gracefully.

Easy to add :)

**Comment by Life4YourGames** [comment]
Sounds good to me, but incomplete for lazy users ;)
