### ISSUE TITLE
SoundSwitch for 32 bit

### ISSUE THREAD

**Issue by Partha132** [Belphemur/SoundSwitch#665]
SoundSwitch for 32 bit
SoundSwitch is'nt available for Windows x86 based systems

5.10.0
SoundSwitch v5.10.0

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85022552/120071158-92d05700-c0ab-11eb-9bf1-b55afc77b20f.png)

**Additional context**

**Comment by Belphemur** [comment]
I won't support x86, this is a deprecated architecture.
