### ISSUE TITLE
Popups on wrong monitor.

### ISSUE THREAD

**Issue by pitman-87** [Belphemur/SoundSwitch#67]
My right monitor is my main. Whenever i click on the icon, a popup appears on the second monitor (that is iff most of the time). Not a crucial bug, just kinda annoying.

Keep up the good work!

See: http://puu.sh/mIALh/9c99a20e66.jpg

**Comment by Belphemur** [comment]
Well the default behaviour of the menu is to spawn where the cursor is ... 

Since you're cursor is on the second monitor when you click the icon, it's displayed there.

**Comment by pitman-87** [comment]
No it wasn't. How can the curser be on the second monitor, when I need to click the icon in the taskbar on my first monitor? :)

**Comment by Belphemur** [comment]
I didn't forget this issue but I can't find any information on how to resolve it ...

Does it also happen when you use the right click instead of the left click ?

**Comment by pitman-87** [comment]
It's both.

But to be fair:

Monitorprofile Switcher: https://sourceforge.net/projects/monitorswitcher/
Borderless Gaming: https://github.com/Codeusa/Borderless-Gaming
and puush: http://puush.me/

are sharing the same issue. 
So it could be more an issue with having a multiple monitor setup and a taskbar between the borders. 
Or it could be an issue with whatever API, framework you and the others are using.

Anyway, pressing Alt+Ctrl+F11 is working for me fine so far :)

**Comment by Belphemur** [comment]
Okay if it's both, and other project have the same issue, it's linked directly to Windows and surely C#.
I'm closing this issue as wontfix since I can't do anything on my side.
