### ISSUE TITLE
Required Registry Access not available (Mute not working)

### ISSUE THREAD

**Issue by Laeae** [Belphemur/SoundSwitch#672]
All of a sudden, SoundSwitch does no longer work for muting the mic. When I try to access the settings, a popup says 

_"It seems SoundSwitch has crashed. 
Required registry access is not allowed. 
Would you like to share more information with the developers?"_

Actually it has not crashed, but settings won't come up. 

Is this a known issue? 

Thanks,
Laeae

**Comment by Belphemur** [comment]
Hello,

Can you attach the content of %appdata%/SoundSwitch ?

That will help me understand better what is happening.
