### ISSUE TITLE
Suggestion: Invoke command line to directly choose a source

### ISSUE THREAD

**Issue by seascape** [Belphemur/SoundSwitch#69]
Great app, thanks for keeping it going.

Right now it seems that the only way to switch sources is to toggle between them in order. I think it would be useful to be able to tell the app to switch to a specific source immediately. This would be useful in AutoHotKey scripts, among other applications.

One obvious way would be to allow this via command line: soundswitch.exe /source [number of source in list] or soundswitch.exe /source [full source name or enough starting characters to uniquely identify one source]. 

You could also allow the mapping of additional key shortcuts, each tied directly to a single source.

**Comment by Belphemur** [comment]
Please see #61 

For this kind of feature you have other programs available: https://github.com/Belphemur/AudioEndPointController

**Comment by CGollhardt** [comment]
@Belphemur My usecase would be a Microsoft Keyboard Favorite Key. I can only lunch a programm in Microsoft Mouse and Keyboard Center. I can not set the favorite key in Sound Switch.

![Microsoft Keyboard](https://imgur.com/aCvXFt0)
