### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by 1353604736** [Belphemur/SoundSwitch#700]
One or two pictures appear during installation 。
![搜狗截图20210725102156](https://user-images.githubusercontent.com/12869582/126885555-3abd3bf0-cc13-44f6-b3f3-8a6472a96496.png)
![搜狗截图20210725102301](https://user-images.githubusercontent.com/12869582/126885558-2bcd3a46-ee91-4a89-826f-6c3485595947.png)

![搜狗截图20210725105146](https://user-images.githubusercontent.com/12869582/126886079-115aef21-d20c-4986-8f45-7cca27ba35f7.png)

After uninstalling, click the installer and three pictures will pop up 。

**Comment by Belphemur** [comment]
It looks like your user don't have proper permission to its own registry.

Can you try to install it for all user with Admin access ?
