### ISSUE TITLE
Can't switch devices with newest update

### ISSUE THREAD

**Issue by SubSonix** [Belphemur/SoundSwitch#701]
**Describe the bug**
Cannot switch between headphones and speakers as of new update.

**Version**
SoundSwitch v5.11.0.38495

![image](https://user-images.githubusercontent.com/3277416/126897860-e0b01571-96b0-44ee-8c70-4615e67ef093.png)

I assume it's related to 0dd1ef2 but I don't know how to rename my device.

**Comment by Belphemur** [comment]
Hello,

No problem, I've added a FAQ item for this : https://github.com/Belphemur/SoundSwitch/discussions/702

**Comment by SubSonix** [comment]
Ah, so it needs to be fixed with an update?

**Comment by Belphemur** [comment]
@SubSonix Yep ... I isolated the bug, update coming.
