### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by mrplumber** [Belphemur/SoundSwitch#706]
**What were you doing when it crashed ?**
Single left mouse button click on the SoundSwitch tray icon produced an error (screenshot attached):
SoundSwitch crashed...
An item with the same key has already been added. Key: Digital Audio (S/PDIF) (High Definition Audio Device)

**To Reproduce**
1. Click on SoundSwitch tray icon
2. See error

**ZIP**
[SoundSwitch_crashed.zip](https://github.com/Belphemur/SoundSwitch/files/6879562/SoundSwitch_crashed.zip)

**Comment by chanskat** [comment]
I have the same issue. I have two monitors with the same "DELL U2717D (NVIDIA High Definition Audio)" listed as speakers. Tried to uninstall (they reinstalled on reboot), then disable. SS still crashes.

**Comment by chanskat** [comment]
As above, single left click on SS in tray and the same error box pops up, though with my devices.

**Comment by Belphemur** [comment]
Can you try with this build: https://nc.aaflalo.me/s/8DKytYCTAbrn6yz

And tell me if it fixes it or not ?

* Stop SoundSwitch
* Download the Zip
* Unzip it anywhere
* Open SoundSwitch from inside the folder

**Comment by mrplumber** [comment]
@Belphemur, your provided beta version solves the problem - no error, works as expected. Thank you.

**Comment by chanskat** [comment]
Antoine,

Yes, it works for me too. Thanks.

Regards,

Charles
