### ISSUE TITLE
Empty Icon defined for an AudioDevice

### ISSUE THREAD

**Issue by n1c0l4** [Belphemur/SoundSwitch#71]
1) the First issue was the duplicated hotkey for intelHDgraphic (ctrl+alt+f11), i have disabled the hotkey in HDgraphic control panel then the issue is not come anymore

2)for the second issue at the same way I'm not able to run the software, but this time I can't understand the problem.

[SoundSwitch-crashlog-21_2_2016.zip](https://github.com/Belphemur/SoundSwitch/files/139540/SoundSwitch-crashlog-21_2_2016.zip)
LOG attached
i'm running win10 64bit

**Comment by Belphemur** [comment]
Hello @n1c0l4 

Could you open the windows sound settings and do a screenshot of the playback devices and recording devices?

It seems one of your AudioDevice has an empty icon set which SoundSwitch can't deal with.

**Comment by n1c0l4** [comment]
![cattura](https://cloud.githubusercontent.com/assets/16437967/13205032/19911a6a-d8de-11e5-8dcf-8de86235504c.PNG)
![cattura2](https://cloud.githubusercontent.com/assets/16437967/13205033/19954cde-d8de-11e5-941b-c8c1f2089018.PNG)
Italian, I'm sorry, but it doesn't seem to need translation

**Comment by Belphemur** [comment]
I think I found the problem, but I'm not sure at 100%. Especially after seeing the screenshot that doesn't contain any weird audio device.

I pushed a fix, and will release another beta version. Try it and tell me it resolves your problem.

**Comment by n1c0l4** [comment]
Now It's working fne
