### ISSUE TITLE
SoundSwitch keeps cycling the recording device

### ISSUE THREAD

**Issue by Razukin** [Belphemur/SoundSwitch#717]
**Describe the bug**
I only have one recording device selected, but I keep seeing notifications on the top-left of the screen about the recording device being switched.

**Version**
SoundSwitch 5.11.2.39643

**To Reproduce**
1. Have two external microphones (in my case, a Blue Yeti and a webcam with a microphone)
2. Start SoundSwitch.
3. The behavior occurs intermittently.

**Expected behavior**
When I have only one microphone (the Yeti) selected, only that one should remain selected regardless. The recording device should probably also not be changed when none are selected.

**Screenshots**

**Additional context**
...I think I fixed this by re-enabling the hotkey to switch the recording device. The issue seems to occur when there are two microphones AND it is disabled.

I'm logging this for information, but I'll close it since it's solved for me now.

**Comment by Razukin** [comment]
Seems to still be happening.

**Comment by Belphemur** [comment]
Can you check with v6.0.0 if it does still happen ?

Especially with the new quick menu.

**Comment by Razukin** [comment]
Sorry for not updating this. It turned out to be my motherboard/USB port. I moved the webcam to another USB port, and it stopped disconnecting/reconnecting all the time. That fixed the issue. It's not SoundSwitch. SoundSwitch works great!
