### ISSUE TITLE
At windows startup, hotkeys don't work

### ISSUE THREAD

**Issue by itzlibo** [Belphemur/SoundSwitch#72]
Hi, great app, but, at windows startup, hotkeys don't work, app register it but I can't use it , hotkeys are check. After reboot, I have to uncheck and check the hotkey case to make it work.
Why ?

**Comment by Belphemur** [comment]
Hi,

Try to set the Hotkeys to another set of keys.

It's possible you have another application that is started before SoundSwitch and use the same hotkeys.

**Comment by itzlibo** [comment]
Same, I have to uncheck and check the case each reboot.

**Comment by itzlibo** [comment]
That's now working, thanks Belphemur.
