### ISSUE TITLE
Artifact near taskbar on double-clicking SoundSwitch icon (Windows 7)

### ISSUE THREAD

**Issue by mossmoss** [Belphemur/SoundSwitch#735]
I noticed this on my system and am not sure if it's unique to me. 

If I double-click the SoundSwitch taskbar icon, I see a grey rectangle artifact around the taskbar for a little while. 

It seems double-clicking the taskbar icon cycles and activates the next profile?

![artifact](https://user-images.githubusercontent.com/3586595/131671765-2da28812-b2f6-41f0-bd43-aa7dc2daf216.png)

**Comment by Belphemur** [comment]
Hello,

That's because of the quick menu that is displayed where the cursor is.
I should make it display at the top of the cursor when at the end of the screen.

**Comment by jwfx** [comment]
Actually this is not the regular left click menu.

It is the banner that is incorrectly drawn there.

Screenshot after after making the taskbar bigger and double-clicking the tray icon:
![image](https://user-images.githubusercontent.com/39484381/135746556-19852329-6d05-47ca-87b1-385a101f02ac.png)

This seems to be an issue of recent versions, I did not encounter it on 5.9.

**Comment by Belphemur** [comment]
It's not the banner per say.
It's the quick menu, you can disable it in the settings.

I need to figure out a way to move the menu when it couldn't be visible. It's not that easy.

Sent from Nine
________________________________
