### ISSUE TITLE
Unable to installl dependencies, but Sound Switch would stil install. Crash at start

### ISSUE THREAD

**Issue by pricelessbrewing** [Belphemur/SoundSwitch#74]
So when I tried to install, there was an error with a requisite microsoft package. Not sure which one the issue was with, as I should have both installed already. Soundswitch installer said to reboot and try again, so I did. Installer skipped checking the dependencies, and installed soundswitch. Soundswitch crashes on start. Uninstalled all 3. Tried to reinstall the dependencies, and vc_redist_2016_14.0.23026 is giving an error of 0x80240017. 

Are there any old versions that are build using 2012 vc? Otherwise I'll be looking for another application to do this. 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	SoundSwitch.exe
  Application Version:	3.9.5.24632
  Application Timestamp:	56cb5641
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7600.16850
  Fault Module Timestamp:	4e211da1
  Exception Code:	e0434352
  Exception Offset:	000000000000a88d

**Comment by Belphemur** [comment]
The installer should have downloaded the right version of the VC_Redist.
You need the 2015 for your architecture.

**Comment by pricelessbrewing** [comment]
I know, I downloaded them manually but it looks like vc 2015 doesn't want to install. Might be because I never updated my W7 updates, looks like 2015 requires SP1. 

Just wanted you to know about it, so you can check and fix any issues with the installer.

**Comment by Belphemur** [comment]
This problem is clearly linked to your setup, not to the program.

And yes, from VC 2015, the minimum version is Windows 7 SP1. The only thing I can do is make the installer check for Windows 7 SP1.
