### ISSUE TITLE
ClamWin reports Win.Virus.Expiro-9892715-0 in createdump.exe

### ISSUE THREAD

**Issue by melihozbek** [Belphemur/SoundSwitch#759]
**Describe the bug**
Clam Win reports Win.Virus.Expiro-9892715-0 in createdump.exe. I assume this is a false positive, but are there any steps we could take to resolve it?

**Version**
SoundSwitch v5.81.42

**Comment by Belphemur** [comment]
Hello,

Each version of SoundSwitch is passed through Virus Total.

Also, I don't recognize that build version. v5 only reached v5.11.x, I never released a 5.81.42.

Did you download SoundSwitch from another source than the official website or GitHub ?

**Comment by melihozbek** [comment]
Thanks. Sorry, I meant to say version 5.8.1.42, I downloaded it from here.

Virus Total gives me complete peace of mind. Also ClamWin reports it as a false positive, when I double checked, and I know it's not necessarily as reputable as Virus Total. So all good, I think we can close out the issue then. Thanks again.

**Comment by Belphemur** [comment]
Also, quick question, is there a reason you're still on 5.8 and not on 6.1 ?

**Comment by melihozbek** [comment]
I didn't know about the 6.1 release! I'll update asap.
