### ISSUE TITLE
Providing 'help' for first time users at the time of installation

### ISSUE THREAD

**Issue by Philip-Sutton** [Belphemur/SoundSwitch#78]
Hi Antoine,  Could you add, in the installer, a checkbox to open the readme at the end of the installation. 

(By the way, the readme has a .md suffix.  What programs read that?  I changed the suffix to .txt temporarily so that I could see if I could read it (which I could).  I've since changed the suffix back to .md

Could you also add a link on the 'right-click' window that causes the readme to open, so that people can access the info later if they need to, without having to figure out to go to the program folder and then figure out how to open the readme fille.

Thanks.

Philip

**Comment by Belphemur** [comment]
.md mean markdown, it's "enhanced" text format, you have more information on the [GitHub Help page](https://guides.github.com/features/mastering-markdown/).

**Comment by Philip-Sutton** [comment]
Antoine,  My guess is that you will have to change the readme file from a .md to a .txt suffix so that users computers know what to do with the file when they try to access it.  My computer (using Windows 10) didn't know how to open the .md files that are in the SoundSwitch install folder. (I had to change them to .txt)  If you need formatting on the readme file (best avoided?) I guess you could create an .rtf file.  I think the standard for readme files is plain text to have minimum problems for first time users accessing the file.

Philip

**Comment by Belphemur** [comment]
Good point about the .md, as a GitHub user and developer I tend to forget .md is not a known file type.

I added in the build process a html generator for the .md file, this HTML file will be included in the Installer.
