### ISSUE TITLE
Issue with switching devices on Win11

### ISSUE THREAD

**Issue by artgru** [Belphemur/SoundSwitch#785]
**Describe the bug**
After update to Win11 SoundSwitch is not able to switch devices properly.
The green check mark remains with the same device and does not switch between other devices.
Soundswitch switches the devices though but if a green mark is set up for the device A, I can switch between B,C,D but I never can come back to A as according to the software it is selected...

**Version**
SoundSwitch v6.1.0.19729 (clean install)

**To Reproduce**
1. Select all devices you want to swtich between
2. Notice which one is currently selected (in my case it is always the same device regardles of the current device set as default)
3. Try to switch between the devices, you should notice the green mark does not follow the selection
4. You can't select the device back to the first, marked with the green check mark

**Expected behavior**
Before the update everything run smoothly, Soundswitch should switch devices and green mark should follow the selection

**Screenshots**
initial state - headphones selected and playing

![obraz](https://user-images.githubusercontent.com/37419387/136545250-ac717227-dca6-42f3-afea-155bdab4485b.png)

switched device to OPT, sound source is switched but green mark does not follow

![obraz](https://user-images.githubusercontent.com/37419387/136545353-c7deb00d-d603-45d3-9f1b-f107c0f913b8.png)

**Comment by Belphemur** [comment]
Hello,

Can you try with 6.1.1 (just released today) and see if that fixes it ?

**Comment by artgru** [comment]
I've overwritten all the files but the issue remains the same :(
