### ISSUE TITLE
Option to set different communication devices for input and output

### ISSUE THREAD

**Issue by TauTauBenn** [Belphemur/SoundSwitch#793]
I'm using an Astro A40 Gaming Headset which has two output devices (game and voice) and also two input devices (game and voice). With Soundswitch i can set the standard communication device for playback but not for recording.

Would be nice if i could also set this option when creating a profile.

**Comment by xcasxcursex** [comment]
Likewise, I can't do this: 
![image](https://user-images.githubusercontent.com/58130821/149243682-b39c2687-a32a-4e41-8244-7ce535417f96.png)

**Comment by RixzZ** [comment]
I'm just missing this option too :(

The app is great otherwise.

**Comment by xcasxcursex** [comment]
Thanks!!
