### ISSUE TITLE
Windows 11: SoundSwitch shutting down without error window upon using hotkey to change Output Device 

### ISSUE THREAD

**Issue by Blake-V-Walker** [Belphemur/SoundSwitch#799]
**What were you doing when it crashed ?**
Using my hotkey to switch between output devices.

**To Reproduce**
1. Be on Windows 11 21H2 OS Build 22000.258
2. Use your preset Hotkey Button 
4. SoundSwitch Crashes with no error message, just shuts down and disappears from the taskbar. 
[soundswitch20211024.log](https://github.com/Belphemur/SoundSwitch/files/7403658/soundswitch20211024.log)

**ZIP**
(Logs) 
[soundswitch20211023.zip](https://github.com/Belphemur/SoundSwitch/files/7403660/soundswitch20211023.zip)

**Comment by kreis117** [comment]
I am experiencing the same crash in my environment(Windows11 211H2 OS Build 22000.282).
The crash occurs not only when switching the playback device (hotkey, double-clicking the task icon), but also when switching the recording device.
[soundswitch20211024.log](https://github.com/Belphemur/SoundSwitch/files/7403893/soundswitch20211024.log)
