### ISSUE TITLE
Request: Cycle through connected devices by double clicking on the system tray icon

### ISSUE THREAD

**Issue by Neurotron** [Belphemur/SoundSwitch#80]
As a user I would like to be able to quickly switch between my two devices (my headphones and my speakers) by double clicking on the SoundSwitch system tray icon. 

I have the SoundSwitch icon always in view as I frequently switch between my devices. A double click would mean faster switches then going through the menu. 

Keep up the good work!

**Comment by Technetium1** [comment]
I agree. This would still work alongside the single click to bring up the menu hopefully.

**Comment by Belphemur** [comment]
I made this work quite easily. Only quirk, the normal menu will always show when double clicking on the icon (in fact, it shows breafely between the 2 clicks).
