### ISSUE TITLE
Keep getting notification of new version for each new version of SoundSwitch instead of the latest

### ISSUE THREAD

**Issue by vertigo220** [Belphemur/SoundSwitch#806]
**Is your feature request related to a problem? Please describe.**
Windows notifications for updates seem to occur randomly, possibly multiple times a day, and there's a separate one for each new version, which is very annoying, e.g. if the installed version is three versions behind, there will be three separate pop-ups (I'm currently on 6.1.2.0 and it keeps notifying me about 6.2.0, 6.2.1, and 6.2.2 in separate notifications one right after another).

**Describe the solution you'd like**
Only one notification when out of date, indicating the latest version, and a setting to only notify once per specified period (e.g. per day/week/launch/version)

**Describe alternatives you've considered**
Only auto-update, but that's not always desired

**Additional context**
N/A

**Comment by vertigo220** [comment]
I'm not asking for a way to postpone the update, nor am I taking issue with the amount of updates. My issue, and the point of this issue, is that when SoundSwitch checks if the latest version is installed, when it finds there's a newer version and notifies about that, it does a separate notification for each new version, so currently I get three notifications one right after another at least once a day. Even checking and notifying once a day is a bit much, but the real problem is that it's notifying for each new version that's been released since the installed version instead of just once for the latest version.

**Comment by Belphemur** [comment]
That's not supposed to happen, I'm going to double check and recategorize this as bug.

**Comment by Belphemur** [comment]
I've confirmed the issue.

**Comment by Belphemur** [comment]
Fixed, but technically, this will only be fixed in 2 version.
Next version has the fix, and you'll the result of that when the following version comes up.

**Comment by vertigo220** [comment]
Sounds good, thanks!
