### ISSUE TITLE
SoundSwitch crashes when logging in to a second user in Win10

### ISSUE THREAD

**Issue by Nifta** [Belphemur/SoundSwitch#82]
If I have Soundswitch running on an account and then, for example, my wife logs in on the same laptop without having logged me out, then Soundswitch crashes during her login.

This happens 100% on our laptop.

It writes out a crash dump. 
[SoundSwitch-crashlog-27_3_2016.zip](https://github.com/Belphemur/SoundSwitch/files/191097/SoundSwitch-crashlog-27_3_2016.zip)

This looks the relevant bit?

TracerX: Log file opened at 27/03/2016 22:00:37.  FullFilePolicy = Wrap, Use_00 = False, MaxGrowth = 1 MB, AppendIfSmallerThan = 0 1, initial size = 3.
22:00:37.818 Warn <null> SoundSwitch+ Application already started

**Comment by Nifta** [comment]
Oops, sorry, this looks similar to issue 81

**Comment by Belphemur** [comment]
I close the isue as duplicated of #81 

Thank for the report :)
