### ISSUE TITLE
Updater crash with Full updater and progress bar

### ISSUE THREAD

**Issue by pitastrudl** [Belphemur/SoundSwitch#83]
[SoundSwitch-crashlog-30_3_2016.zip](https://github.com/Belphemur/SoundSwitch/files/195871/SoundSwitch-crashlog-30_3_2016.zip)

tried to update, got crash, win7 64bit

**Comment by pitastrudl** [comment]
updated to latest version from website, still the same. sometimes when i change outputs it disableds the windows audio service for some reason

**Comment by Belphemur** [comment]
For the first bug, it seems to be linked to the progress bar of the updater.

For the second, keep in mind the way SoundSwitch switch device is a hack. I do have the same issue sometimes and still haven't been able to track it down.

**Comment by Belphemur** [comment]
For what I read it's because you're in "classic windows theme". If you enable the "normal" theme it should work without problems.

I keep the bug open in case I find another way to resolve this?

**Comment by pitastrudl** [comment]
new versions work good :)
