### ISSUE TITLE
Changing mic and playback combo at once

### ISSUE THREAD

**Issue by yazan1107** [Belphemur/SoundSwitch#831]
**Is your feature request related to a problem? Please describe.**
i hate that i need to change every device sepreatly, i prefer to have some combs to switch between for example:
playback A with Mic B
or Play B with Mic C

**Describe the solution you'd like**
switching mic and playback simulatensoly and not seperately(something like profiles)
**Describe alternatives you've considered**
switching seperately which is frustrating!
**Additional context**

**Comment by Belphemur** [comment]
Hello,

You should try set a profile for those :)

https://github.com/Belphemur/SoundSwitch/discussions/738

Will show you how to do that.
