### ISSUE TITLE
Soundswitch will not launch

### ISSUE THREAD

**Issue by dilwei3374** [Belphemur/SoundSwitch#836]
**Describe the bug**

The first time I download soundswitch, the software opens normally. However if I close the software and try to reopen the software at a later date to change settings or check for updates, it will no longer open. The software WILL still work if I select my binded key, and automatically update. But I cannot open the software itself.

**Version**
SoundSwitch v3.2.6
Windows 10 Pro Version 21H1

**To Reproduce**
1. Download latest version of Soundswitch
2. Install and change to preferred user settings
3. Close out of software
4. Double click desktop shortcut to try to reopen, for me it won't reopen.

**Expected behavior**
I was hoping if I need to change settings I can double click on the soundswitch desktop shortcut to open the software.

**Comment by Belphemur** [comment]
Hello,

The way SoundSwitch works is in the background. The first time you open the software, SoundSwitch will show you the settings menu.

After that to access SoundSwitch you need to go in the tray icon.

![TrayIcon](https://user-images.githubusercontent.com/197810/146657898-efedc248-0ffa-4d5f-abd1-48356115b8d5.gif)
