### ISSUE TITLE
SoundSwitch 3.9.6 Cannot install visual c++ redist

### ISSUE THREAD

**Issue by djgreg** [Belphemur/SoundSwitch#84]
The installer tells me to install  Visual C++ 2015 64-Bit Redistributable However it is already installed, but it wont detect it The installation cannot continue I Have tried earlier versions to no avail

**Comment by Belphemur** [comment]
Hello,

Can you give me the exact version reported by Program and Features (in the control panel) of your VC Redist ?

I'll work a better fix that should resolve this once and for all.

1 avril 2016 21:00 "djgreg"  a écrit:
	The installer tells me to install Visual C++ 2015 64-Bit Redistributable However it is already installed, but it wont detect it The installation cannot continue I Have tried earlier versions to no avail

**Comment by djgreg** [comment]
10.0.40219

**Comment by diegose** [comment]
This happens for me too. I have 14.0.23918 installed. Downloading the vc redist from Microsoft doesn't work either (and, oddly enough, the downloaded version is 14.0.23026)

**Comment by Belphemur** [comment]
I recompiled the installer with the fix.
The last Stable version should work with any version of VC Redist 2015
@diegose  Can you confirm it ?

**Comment by diegose** [comment]
It works now. Thanks man, I love this app!

**Comment by Stasysprime** [comment]
I currently can not install 3.10.0 for the same reason as the original poster. I currently have c++ redist 64 bit 14.0.23026 installed. I get "Error opening http://download.microsoft.com/download/C/E/5/CE514EAE-78A8-4381-86E8-29108D78DBD4/VC_redist.x64.exe. The server returned status code 404."
