### ISSUE TITLE
Add an easy way to find and download the installer.

### ISSUE THREAD

**Issue by gene-pavlovsky** [Belphemur/SoundSwitch#85]
Hey, maybe I'm stupid, but how the heck do I install it? Where's the installer.exe?
You have a bunch of info in your readme, it lists dependencies, but there's nothing about **download** and **install**, please add this info!

**Comment by maxmarchuk** [comment]
You will need to go to his website to get the installer: https://www.aaflalo.me/downloads/

**Comment by djgreg** [comment]
Releases button on github

**Comment by FireEmerald** [comment]
It's hard to say, but you are stupid, if you are unable to find this section on the github project site:
- https://github.com/Belphemur/SoundSwitch/releases

**Comment by Belphemur** [comment]
I do receive some emails about the location of the installer.

@FireEmerald there is a lot of user of SoundSwitch that aren't familiar with GitHub and compared to CodePlex where the button is huge and unmissable, here it's just a little link.

I'm going to add a direct link to my website in the read me and project description.

**Comment by gene-pavlovsky** [comment]
@FireEmerald Even though I'm familiar with github, and checked the `releases`, I didn't see any links to an installer download in there.

**Comment by Belphemur** [comment]
@gene-pavlovsky you need to scroll down the changelog of the release, then you have the "assets" where you can find the installer :)

**Comment by gene-pavlovsky** [comment]
Ok, I see it now. I didn't scroll that far down, I stopped scrolling when I saw some previous version (3.9.5, 3.9.4. etc) listed in ChangeLog. I figured the download links would be at least above any mention of 3.9.5. Anyway thanks for adding the download link.
