### ISSUE TITLE
The downloaded installation file is garbled when opened 。

### ISSUE THREAD

**Issue by 1353604736** [Belphemur/SoundSwitch#852]
![2021-12-19 11-9-12](https://user-images.githubusercontent.com/12869582/146662302-bfb35310-b510-4c56-9bb3-ec1dcaa44f60.png)

WIN10-64-21H2
![2021-12-19 11-10-33](https://user-images.githubusercontent.com/12869582/146662341-af36a262-dca1-4886-bf8f-bb2e1f0ac946.png)

**Comment by Belphemur** [comment]
Hello,
I'm not able to reproduce this, can you re-download the latest release ?

**Comment by kreis117** [comment]
This is the case for the language at the bottom of the Language Settings pull-down menu when the installer is launched.
The installer I am using is "SoundSwitch_v6.2.4.0_Release_Installer.exe".
![image](https://user-images.githubusercontent.com/74777259/160224273-d37fd154-844b-4980-88cf-3b0cea7b9f9d.png)

**Comment by Belphemur** [comment]
I've updated InnoSetup, this hopefully will fixe it.

**Comment by kreis117** [comment]
Not fixed in SoundSwitch_v6.3.0.0_Release_Installer.exe.
![image](https://user-images.githubusercontent.com/74777259/175800027-5719f6b7-ec20-4e16-a33f-11d9f267b0b0.png)
