### ISSUE TITLE
Taskbar preview of selected playback device

### ISSUE THREAD

**Issue by Cadiuro** [Belphemur/SoundSwitch#86]
It would be very handy to have an indication on the taskbar as to which playback device is selected. The Windows-notification is useful, but only appears when first switching the device. (They also stack when quickly switching between devices, which can cause confusion).

This indication could be a color of the SoundSwitch-icon, a custom icon,... which can be set up per device.

**Comment by Belphemur** [comment]
I understand the idea. However, there is already a similar feature when you left click on the icon.

It shows you a menu with the differents selected devices and a "V" next to the active one.

**Comment by JustOff** [comment]
Is a pity that this request was marked as wontfix. The ability to visually, without any mouse actions, identify which device is active at the moment would be very useful.
