### ISSUE TITLE
Playback devices constantly go in the Disconnected section

### ISSUE THREAD

**Issue by Magnus75** [Belphemur/SoundSwitch#87]
So, I have a multilayered problem with SoundSwitch 3.

Firstly, every playback device that is in a certain period is not used goes (after I restart or shutdown the PC) in section Playback>Disconnected, but over and over again. After some time, list of (practically the same, repeated) disconnected device is huge. I note that "not used" means exactly that (not excluded, disconnected or unplugged).

Secondly, some devices which is always connected with PC (viz sound source) and selected in SoundSwitch, simply change status in Disconnected after I restart or shutdown the PC.

I use Windows 7 [x64] and have latest nVidia graphics drivers. Sound Switch is also regularly updated.

Thanks in advance!

**Comment by Belphemur** [comment]
Note to self: Add a cycling active device option to resolve the issue.

**Comment by Magnus75** [comment]
Is there a possibility for deletion (or resetting) list of disconnected devices from Settings > Playback? I try with (un)installing process, but list is obviously memorised somewhere.

**Comment by Belphemur** [comment]
The list is directly fed by the windows API.
I ask Windows the list of all the Sound Device and their state.

I'm polishing the feature that will let you cycle through all the active device. With this, you won't have to select which device you want and will be able to switch with any connected one.

**Comment by Belphemur** [comment]
Can you test the last beta version (just put it online now).

Go into settings and put: Cycle through -> All audio devices

**Comment by Magnus75** [comment]
I installed the beta version & choose Cycle through -> All audio devices. I will test & follow app in the coming days.

**Comment by Magnus75** [comment]
Situation is somewhat better than before, by the fact that all sources of sound, and even those who are not currently in operation (but are connected to the PC) are constantly checked in Playback>Selected section.

Now everything works correctly. However, it is obvious that I have a problem with the graphic card, which attached devices treated in a very strange way.

In any case, a new feature that is implemented is helpful for me.

Thanks again!
