### ISSUE TITLE
portable zip

### ISSUE THREAD

**Issue by pozhiloy-enotik** [Belphemur/SoundSwitch#875]
https://portableapps.com/about/what_is_a_portable_app

**Comment by Belphemur** [comment]
The installer can work in portable mode (user mode)

**Comment by pozhiloy-enotik** [comment]
@Belphemur 
> The installer can work in portable mode (user mode)

This is not a portable app. I specially left a link for you

**Comment by marvinlehmann** [comment]
This issue should be reopened as the config path is hard coded to AppData? Therefore it isn't really portable.
https://github.com/Belphemur/SoundSwitch/blob/0efb8547961eded9b77d6e44f2ec5af9025d46be/SoundSwitch/Framework/ApplicationPath.cs#L23-L32
https://github.com/Belphemur/SoundSwitch/blob/0efb8547961eded9b77d6e44f2ec5af9025d46be/SoundSwitch/Framework/Configuration/ConfigurationManager.cs#L39-L47

**Comment by pozhiloy-enotik** [comment]
@Belphemur
