### ISSUE TITLE
Show active device on hover Systray Icon

### ISSUE THREAD

**Issue by JustOff** [Belphemur/SoundSwitch#88]
Could you please add the name of current active device to tray tooltip?
Also, there may be a setting to choose what devices to show: playback, recording or both.

**Comment by Belphemur** [comment]
@JustOff That's a great idea !

I didn't think of the hover on the systray.

**Comment by JustOff** [comment]
Thank you for the assistance, but I didn't mean to create additional tooltip, only replace default one, which shows "SoundSwitch" by default. I'm so sorry, but solution that you have provided in the last beta is completely unusable ;-(

**Comment by Belphemur** [comment]
@JustOff Ah that one, the default tooltip of the Icon.

Well that's not hard to change :)

**Comment by JustOff** [comment]
Thank you very much!
