### ISSUE TITLE
Won't Install ?

### ISSUE THREAD

**Issue by Emplehod** [Belphemur/SoundSwitch#89]
I have a brand-new reformatted SSD with Windows 7 64-bit Ultimate. I was using Soundswitch for a long time previously, great program.

I had a brain glitch and "upgraded" to Windows 10 for a couple of months but then reformatted and now I'm back to 7. Downloaded this new version and it won't install.

> This program does not support the version of Windows your computer is running.

**Comment by Belphemur** [comment]
Hello @Emplehod,

Do you have the SP1 of Windows 7 ?
If my memory is right I blocked for before SP1.

Can you check this ?

**Comment by Emplehod** [comment]
I think you're correct. It did not list a service pack version in the systems info but after a few reboots, it is now in the updates.

Installing SP1 now and I'm sure it will work again.

Thanks and a great utility.

**Comment by Belphemur** [comment]
Great ! I'm closing the issue for now. If the problem persists don't hesitate to reopen it.
