### ISSUE TITLE
Silently crashes when switching playback devices.

### ISSUE THREAD

**Issue by kreis117** [Belphemur/SoundSwitch#892]
**What were you doing when it crashed ?**
The prescribed playback device was changed by pressing a hot key.
I have changed the icons and names of the sound devices and that may be the cause.
The banner notification sound when switching devices is also changed from the settings.

**To Reproduce**
It does not occur in the definite.
However, it occurs almost daily.
1. press the hotkey ([Alt+Control+F9] in my environment) that changes the prescribed playback device
2. silently SoundSwitch crashes

**ZIP**
This is the log immediately after SoundSwitch crashes.
[soundswitch20220326.log](https://github.com/Belphemur/SoundSwitch/files/8354655/soundswitch20220326.log)

**Comment by kreis117** [comment]
I don't know if this is relevant, but I will post my setup.
![image](https://user-images.githubusercontent.com/74777259/160224704-5f3e8510-6ba9-4a55-bfeb-1416c220976c.png)

**Comment by Belphemur** [comment]
Might be fixed in the newest version.
