### ISSUE TITLE
Issue with banner notification of both playback and recording devices when switching playback device with a hotkey (and vice versa).

### ISSUE THREAD

**Issue by kreis117** [Belphemur/SoundSwitch#893]
**Describe the bug**
Issue with banner notification of both playback and recording devices when switching playback device with a hotkey (and vice versa).

**Version**
SoundSwitch v6.2.4.0

**To Reproduce**
1. Open the settings screen
2. With the settings screen active, use hot keys to switch playback devices (or recording devices)
3. A banner notification for the recording device will appear for a moment, then the banner notification for the playback device will appear.

**Expected behavior**
Only switched devices will be banner notified.

**Screenshots**
https://user-images.githubusercontent.com/74777259/160225183-7f6da146-efeb-43f8-894b-c49a6f32f60e.mp4

**Additional context**

**Comment by Belphemur** [comment]
If both are show, that would mean for Windows both got switched...

This is kind of weird, do you have any other application that interact with audio device ?

**Comment by kreis117** [comment]
I don't think I have any other application that interact with audio device.
As noted above, it only seems to happen when the settings window is open.
It also seems to occur with notification methods other than banners.

**Comment by felipecrs** [comment]
Glad I'm not the only one. See:

https://user-images.githubusercontent.com/29582865/209367131-c2167496-799d-47c1-9674-6da154b05982.mp4

I was only pressing the Playback switch shortcut (not Recording switch shortcut), yet, you can see that it shows up the Recording device almost always.

I'm happy to provide any data that may be useful.

**Comment by felipecrs** [comment]
BTW the issue persists even after closing Nvidia Broadcast, PowerToys, and Logitech G Hub.

**Comment by Belphemur** [comment]
@felipecrs Are you on Win11 ?

I have the feeling they changed something in the API and give all device when one is changed instead of just the one that changed.

**Comment by felipecrs** [comment]
Yes, Windows 11 22H2.

**Comment by Belphemur** [comment]
Will be fixed in a new version.

In the meantime, can you try a test version for me ?
https://f000.backblazeb2.com/file/SoundSwitch/nightly/SoundSwitch-6.5.39925.1238.zip

This should fix that issue.

Download the zip, stop SoundSwitch, go where SoundSwitch is installed, replace all the file with the content of the Zip and restart SoundSwitch

**Comment by felipecrs** [comment]
On it.

**Comment by felipecrs** [comment]
Awesome, it works just fine!

![image](https://user-images.githubusercontent.com/29582865/214402782-3f0e97a8-92dc-4734-b1f5-30b483073ec4.png)
