### ISSUE TITLE
multiple notifications when switching devices

### ISSUE THREAD

**Issue by zilchoid** [Belphemur/SoundSwitch#900]
When I cycle through playback devices I get the notification type I selected (Banner, Windows notification, ...) plus another unwanted notification at the cursor position. Is there any way to disable the second notification?

SoundSwitch v6.2.4
Windows 10 LTSC 21H2

![ssnoti](https://user-images.githubusercontent.com/58773062/161906703-3e61b6c0-73c4-4114-b2fb-69fa92d14c9a.png)

**Comment by acrang** [comment]
I am having the same issue. I looked through the settings but was unable to find any way to disable the second notification.
