### ISSUE TITLE
Add option to automatically select new audio devices to be displayed in systray menu

### ISSUE THREAD

**Issue by sillikk** [Belphemur/SoundSwitch#924]
**Is your feature request related to a problem? Please describe.**
My home cinema is recognized as a new device each time I switch my display between my computer screen and the home cinema, and the new audio device is not displayed by default in SoundSwitch.

**Describe the solution you'd like**
I would like any new audio device plugged into the PC to appear in the SoundSwitch app. An option to enable or disable this behavior would allow people to keep current behavior if they don't want that to happen.

**Describe alternatives you've considered**
The current alternative is to use a hotkey to cycle through all devices instead of just the active ones, but it is not as easy as being able to select the new device when clicking on the systray icon.

**Additional context**

**Comment by Belphemur** [comment]
Hello,

Does the device keep changing name every time you plug it ?
Because normally SoundSwitch relies on the name of the device to avoid having to reconfigure it.

If it doesn't work, you could delete the config and retry. (`%appdata%/SoundSwitch/`)

**Comment by sillikk** [comment]
It does not change name. I will try to delete the config and will let you know.
However I still think it would make sense to opt-in by default any new device you plug in.
