### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by joelamos** [Belphemur/SoundSwitch#96]
Would it be possible to add command line support so that this can be used be developers?

**Comment by Belphemur** [comment]
Hello @joelamos,

I won't add any command line support to SoundSwitch.
If you're looking for a command line version there is: https://github.com/Belphemur/AudioEndPointController

And if you're interested in providing the SoundSwitch feature in your app, there is the underlying library that I coded for SoundSwitch in C++/C#:
 https://github.com/Belphemur/AudioEndPointLibrary

**Comment by joelamos** [comment]
Thanks for all your work and for pointing me in the right direction!

**Comment by Aq32** [comment]
Sorry to revive a closed thread but is there an equivalent for audio input too?
