### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by familypc123** [Belphemur/SoundSwitch#966]
**Is your feature request related to a problem? Please describe.**
Yes language barrier
**Describe the solution you'd like**
Translate the application to hebrew
**Describe alternatives you've considered**
did not find
**Additional context**

**Comment by Belphemur** [comment]
We already have Hebrew translation for the program. 

If you want to contribute, I invite you to use Weblate: https://hosted.weblate.org/projects/soundswitch/

**Comment by familypc123** [comment]
> We already have Hebrew translation for the program.
> 
> If you want to contribute, I invite you to use Weblate: https://hosted.weblate.org/projects/soundswitch/

how can i add this translation to the program?

**Comment by Belphemur** [comment]
To change the language of the app:
Right Click on the SoundSwitch Tray Icon > Settings > Settings Tab > Language
