### ISSUE TITLE
Webroot warning

### ISSUE THREAD

**Issue by inpariswithyou** [Belphemur/SoundSwitch#97]
SoundSwitch triggers a Webroot alert for:

Malware Group: Pua.Downloadmanager

This is new today.

What's wrong?

**Comment by Belphemur** [comment]
Hello @inpariswithyou 

It's a false positive. Which anti-virus are you using ?

Proof: https://www.virustotal.com/en/url/daf890f9d5225ce52cf11bd7457db5c9e25fca252f9fe561bce8942387ade559/analysis/1463430059/

And 
https://www.virustotal.com/en/file/9a2eb3f5dab8b7fe591c6da7f664fa09d8acfbd3a4f358ca4d84627626ae19aa/analysis/1463386836/

**Comment by inpariswithyou** [comment]
Oh, I'm sure it's a false-positive, I just don't know how to get around it.

Webroot Secure Anywhere.

**Comment by Belphemur** [comment]
It seems your antivirus does have a way to report a threat as false positive: 
https://community.webroot.com/t5/Webroot-SecureAnywhere-Antivirus/Possible-false-positives/td-p/13104
