### ISSUE TITLE
Add rounded corner for Windows 11

### ISSUE THREAD

**Issue by RiajuLRidoY** [Belphemur/SoundSwitch#971]
**Please make corner rounded for Windows 11**

**Comment by xcasxcursex** [comment]
Is it intentional that the rounded corners appear on Windows 10 also?

**Comment by Belphemur** [comment]
@xcasxcursex Yep that was on purpose, I liked the look it gave to the banner, so this way it doesn't rely on the new Windows 11 API but work for any version of Windows (even win 7).

**Comment by xcasxcursex** [comment]
OK thanks. It kinda clashes with win10 since it uses sharp corners everywhere, but no big deal.
