### ISSUE TITLE
Toggle selected not updating after option unchecked

### ISSUE THREAD

**Issue by iguy1569** [Belphemur/SoundSwitch#978]
**Describe the bug**
When using the playback toggle hotkey for selected items it appears as though it is not saving changes made to selected/non-selected playback devices. List of selected options appears correct.

**Version**
SoundSwitch v6.4.1

**To Reproduce**
1. Go to 'playback devices
2. Click on 'specific selected playback devices, (i.e. x/y amount)
3. proceed to use the hot-swap toggle for playback devices
4. Will still allow non-selected items in toggle

**Expected behavior**
Items listed as selected should be the only items showing when toggling through options. Currently still uses all.
Used to work properly back on v6.3.x. Ensured add new-device toggle is off.

**Screenshots**

![Screenshot 2022-08-05 101159](https://user-images.githubusercontent.com/5656397/183118143-e37116c4-5c9f-49dc-b839-96fe7060d8dd.png)

![Screenshot 2022-08-05 101259](https://user-images.githubusercontent.com/5656397/183118290-16837894-28ba-499c-a5e3-24b8afb2e8f3.png)

![Screenshot 2022-08-05 101347](https://user-images.githubusercontent.com/5656397/183118428-53186742-117c-43e4-9450-f808a8716f96.png)

**Comment by Belphemur** [comment]
I'll have to investigate this. I might have an idea what caused the bug.

**Comment by Belphemur** [comment]
@iguy1569 Could test this beta build to tell me if it fixes it for you ?

https://f000.backblazeb2.com/file/SoundSwitch/nightly/SoundSwitch-6.4.28197.951.zip

* Stop SoundSwitch
* Replace the file where you installed it by the content of the zip file
* Relaunch SoundSwitch and see if it happens again after selecting + deselecting the device.
