### ISSUE TITLE
SoundSwitch install not working, VCRedist detect and download problem v3.10 Stable

### ISSUE THREAD

**Issue by An4x15** [Belphemur/SoundSwitch#98]
I had to reinstall my Windows 10 Pro x64 , Vc_redist.x64 (14.0.23
026) is installed on the system.Every time when i trying to install latest stable SoundSwitch.This error occurs: http://prntscr.com/b69aqb (I guess that path not valid anymore), and also SS cant detect this VC version.

**Comment by ddulic** [comment]
Having the exact same problem. Redist is installed. Still prompting a download :/
![c red](https://cloud.githubusercontent.com/assets/10076428/15424897/606a64ae-1e85-11e6-823d-0f0df5e8081f.JPG)

**Comment by Belphemur** [comment]
note to self: see #84 

Mmmh I thought I resolved this issue once and for all ... thanks for the report about the link and the detection problem.

**Comment by Otakugen** [comment]
Hi. I've done some test today. What result was this : 
- the dl link for VC_redist is dead as shown in An4x15 post, and it is different from the one that appears on the .iss file which is the good one.
- i"ve success to install soundswitch by changing the build number with regedit. The build downloaded from microsoft was 23026, but in the function to verify, the test is build_number >= 23506, that's where the detection problem is.

Hope it will help.

**Comment by Belphemur** [comment]
Hey @otakugen,

It doesn't help, it resolve the issue completely !
I just have to do some change in the install script recompile it with 
the new link and it should fly :)

Thanks !

**Comment by DJDragonWagon** [comment]
Hey I am still experiencing this problem - did you already apply your fix?

**Comment by Eyadish** [comment]
Wishing for a fix to be applied in the next few days. Cannot install Soundswitch currently and it's driving me crazy.

**Comment by Belphemur** [comment]
This bug lead me to another one that took longer than expect to fix.

I'll release later today a fixed version.
